package java

// errors.go — emits:
//   errors/ApiErrorResponse.java, errors/ApiException.java — base types
//   errors/{Action}Exception.java — per-action typed exception (e.g. GetAccountException)
//   errors/{convenience}.java — 7 convenience subclasses (NotFoundException, etc.)
//   errors/{Module}Errors.java — per-module error factory class
//   controllers/GlobalExceptionHandler.java — framework error handler
//
// All error classes live in the errors/ package, NOT in models/.
// Matches the folder structure of the TypeScript/Node frontend emitter.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	jstrategy "github.com/Adhamzineldin/Veld/internal/emitter/backend/java/strategy"
)

const javaPackageErrors = "maayn.veld.generated.errors"

// emitAllErrors generates the full errors/ directory in one shot.
// Called once from Emit() — replaces the old per-module approach.
func (e *JavaEmitter) emitAllErrors(strat jstrategy.FrameworkStrategy, a ast.AST, outDir string) error {
	errorsDir := pkgToDir(outDir, javaPackageErrors)
	if err := os.MkdirAll(errorsDir, 0755); err != nil {
		return err
	}

	// ── Clean up stale error files from models/ (old code put them there) ──
	modelsDir := pkgToDir(outDir, javaPackageModels)
	staleFiles := []string{
		"ApiException.java",
		"ApiErrorResponse.java",
		"NotFoundException.java",
		"BadRequestException.java",
		"UnauthorizedException.java",
		"ForbiddenException.java",
		"ConflictException.java",
		"ValidationException.java",
		"InternalException.java",
	}
	for _, f := range staleFiles {
		_ = os.Remove(filepath.Join(modelsDir, f))
	}
	// Also clean old models/errors/ sub-package if it existed
	_ = os.RemoveAll(filepath.Join(modelsDir, "errors"))

	// ApiErrorResponse.java
	if err := emitJavaApiErrorResponse(errorsDir); err != nil {
		return err
	}

	// ApiException.java — base class with helpers
	if err := emitJavaApiException(errorsDir); err != nil {
		return err
	}

	// 7 convenience exception subclasses
	if err := emitJavaConvenienceExceptions(errorsDir); err != nil {
		return err
	}

	// Per-action typed exceptions (e.g., GetAccountException, LoginException)
	for _, mod := range a.Modules {
		if err := emitJavaActionExceptions(mod, errorsDir); err != nil {
			return fmt.Errorf("action exceptions %s: %w", mod.Name, err)
		}
	}

	// Per-module error factory class ({Module}Errors.java)
	for _, mod := range a.Modules {
		if err := emitJavaModuleErrorFactories(mod, errorsDir); err != nil {
			return fmt.Errorf("module errors %s: %w", mod.Name, err)
		}
	}

	// GlobalExceptionHandler — framework-specific
	src := strat.GlobalExceptionHandlerSource(javaPackageControllers, javaPackageErrors)
	if src != "" {
		ctrlDir := pkgToDir(outDir, javaPackageControllers)
		if err := os.WriteFile(filepath.Join(ctrlDir, "GlobalExceptionHandler.java"), []byte(src), 0644); err != nil {
			return err
		}
	}

	return nil
}

func emitJavaApiErrorResponse(dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageErrors))
	sb.WriteString("/** Standard API error response body. */\n")
	sb.WriteString("public record ApiErrorResponse(\n")
	sb.WriteString("    String error,\n")
	sb.WriteString("    String code,\n")
	sb.WriteString("    int status\n")
	sb.WriteString(") {}\n")
	return os.WriteFile(filepath.Join(dir, "ApiErrorResponse.java"), []byte(sb.String()), 0644)
}

func emitJavaApiException(dir string) error {
	var ae strings.Builder
	ae.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	ae.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageErrors))
	ae.WriteString("import java.time.Instant;\n\n")
	ae.WriteString("/**\n")
	ae.WriteString(" * Typed API exception with a machine-readable code and HTTP status.\n")
	ae.WriteString(" * Every Veld-generated error factory returns ApiException or a subclass.\n")
	ae.WriteString(" *\n")
	ae.WriteString(" * <pre>{@code\n")
	ae.WriteString(" * throw new ApiException(\"GET_USER_NOT_FOUND\", 404, \"user not found\");\n")
	ae.WriteString(" * }</pre>\n")
	ae.WriteString(" */\n")
	ae.WriteString("public class ApiException extends RuntimeException {\n")
	ae.WriteString("    private final String code;\n")
	ae.WriteString("    private final int status;\n")
	ae.WriteString("    private final String timestamp;\n\n")
	ae.WriteString("    public ApiException(String code, int status, String message) {\n")
	ae.WriteString("        super(message);\n")
	ae.WriteString("        this.code = code;\n")
	ae.WriteString("        this.status = status;\n")
	ae.WriteString("        this.timestamp = Instant.now().toString();\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    public String getCode() { return code; }\n")
	ae.WriteString("    public int getStatus() { return status; }\n")
	ae.WriteString("    public String getTimestamp() { return timestamp; }\n\n")
	ae.WriteString("    /** Check if this exception matches a specific error code. */\n")
	ae.WriteString("    public boolean isErrorCode(String errorCode) {\n")
	ae.WriteString("        return this.code.equals(errorCode);\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    /** Check if this exception has a specific HTTP status. */\n")
	ae.WriteString("    public boolean isHttpStatus(int httpStatus) {\n")
	ae.WriteString("        return this.status == httpStatus;\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    /** Convert to a JSON-safe ApiErrorResponse. */\n")
	ae.WriteString("    public ApiErrorResponse toErrorResponse() {\n")
	ae.WriteString("        return new ApiErrorResponse(getMessage(), code, status);\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    /** Check if a throwable is an ApiException. */\n")
	ae.WriteString("    public static boolean isApiException(Throwable t) {\n")
	ae.WriteString("        return t instanceof ApiException;\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    /** Convert any throwable to an ApiErrorResponse. */\n")
	ae.WriteString("    public static ApiErrorResponse toErrorResponse(Throwable t) {\n")
	ae.WriteString("        if (t instanceof ApiException ae) {\n")
	ae.WriteString("            return ae.toErrorResponse();\n")
	ae.WriteString("        }\n")
	ae.WriteString("        return new ApiErrorResponse(t.getMessage(), \"INTERNAL_ERROR\", 500);\n")
	ae.WriteString("    }\n")
	ae.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, "ApiException.java"), []byte(ae.String()), 0644)
}

func emitJavaConvenienceExceptions(dir string) error {
	type errDef struct {
		name, msg, codeConst string
		status               int
	}
	defs := []errDef{
		{"NotFoundException", "Not Found", "NOT_FOUND", 404},
		{"BadRequestException", "Bad Request", "BAD_REQUEST", 400},
		{"UnauthorizedException", "Unauthorized", "UNAUTHORIZED", 401},
		{"ForbiddenException", "Forbidden", "FORBIDDEN", 403},
		{"ConflictException", "Conflict", "CONFLICT", 409},
		{"ValidationException", "Validation Failed", "VALIDATION_FAILED", 422},
		{"InternalException", "Internal Server Error", "INTERNAL_SERVER_ERROR", 500},
	}
	for _, d := range defs {
		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageErrors))
		sb.WriteString(fmt.Sprintf("/** %d %s — throw from service implementations for quick status responses. */\n", d.status, d.msg))
		sb.WriteString(fmt.Sprintf("public class %s extends ApiException {\n", d.name))
		sb.WriteString(fmt.Sprintf("    public %s() { this(\"%s\"); }\n", d.name, d.msg))
		sb.WriteString(fmt.Sprintf("    public %s(String message) { this(message, \"%s\"); }\n", d.name, d.codeConst))
		sb.WriteString(fmt.Sprintf("    public %s(String message, String code) { super(code, %d, message); }\n", d.name, d.status))
		sb.WriteString("}\n")
		if err := os.WriteFile(filepath.Join(dir, d.name+".java"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	return nil
}

// emitJavaActionExceptions writes per-action typed exception classes like
// GetAccountException, LoginException, etc. These are what interfaces reference
// in `throws` clauses, allowing developers to implement the pattern:
//
//	public AccountItem getAccount(String id) throws GetAccountException { ... }
func emitJavaActionExceptions(mod ast.Module, dir string) error {
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		className := capitalize(act.Name) + "Exception"

		// Build the union of valid error codes for this action
		var codes []string
		for _, errName := range act.Errors {
			codes = append(codes, emitter.ErrorCode(act.Name, errName))
		}

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageErrors))
		sb.WriteString(fmt.Sprintf("/**\n"))
		sb.WriteString(fmt.Sprintf(" * Typed exception for the %s action.\n", act.Name))
		sb.WriteString(fmt.Sprintf(" * Valid error codes: %s\n", strings.Join(codes, ", ")))
		sb.WriteString(fmt.Sprintf(" *\n"))
		sb.WriteString(fmt.Sprintf(" * <p>Throw this from your service implementation:</p>\n"))
		sb.WriteString(fmt.Sprintf(" * <pre>{@code\n"))
		if len(act.Errors) > 0 {
			sb.WriteString(fmt.Sprintf(" * throw %sErrors.%s();\n",
				capitalize(emitter.ToCamelCase(act.Name)),
				emitter.ToCamelCase(act.Name)+act.Errors[0]))
		}
		sb.WriteString(fmt.Sprintf(" * }</pre>\n"))
		sb.WriteString(fmt.Sprintf(" */\n"))
		sb.WriteString(fmt.Sprintf("public class %s extends ApiException {\n", className))
		sb.WriteString(fmt.Sprintf("    public %s(String code, int status, String message) {\n", className))
		sb.WriteString("        super(code, status, message);\n")
		sb.WriteString("    }\n\n")
		sb.WriteString(fmt.Sprintf("    public %s(String code, int status) {\n", className))
		sb.WriteString(fmt.Sprintf("        this(code, status, code);\n"))
		sb.WriteString("    }\n")

		// Static factory methods per error
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			factoryName := emitter.ToCamelCase(errName)
			sb.WriteString(fmt.Sprintf("\n    /** Create a %s error (%d). */\n", errName, status))
			sb.WriteString(fmt.Sprintf("    public static %s %s(String message) {\n", className, factoryName))
			sb.WriteString(fmt.Sprintf("        return new %s(\"%s\", %d, message != null ? message : \"%s\");\n", className, code, status, errName))
			sb.WriteString("    }\n")
			sb.WriteString(fmt.Sprintf("\n    public static %s %s() { return %s(null); }\n", className, factoryName, factoryName))
		}

		sb.WriteString("}\n")
		if err := os.WriteFile(filepath.Join(dir, className+".java"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	return nil
}

// emitJavaModuleErrorFactories writes errors/{Module}Errors.java with aggregate factories.
func emitJavaModuleErrorFactories(mod ast.Module, dir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	className := mod.Name + "Errors"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageErrors))
	sb.WriteString(fmt.Sprintf("/** Aggregate error factories for the %s module. */\n", mod.Name))
	sb.WriteString(fmt.Sprintf("public final class %s {\n", className))
	sb.WriteString(fmt.Sprintf("    private %s() {}\n\n", className))

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		exceptionClass := capitalize(act.Name) + "Exception"
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			methodName := emitter.ToCamelCase(act.Name) + errName
			sb.WriteString(fmt.Sprintf("    public static %s %s(String message) {\n", exceptionClass, methodName))
			sb.WriteString(fmt.Sprintf("        return new %s(\"%s\", %d, message != null ? message : \"%s\");\n", exceptionClass, code, status, errName))
			sb.WriteString("    }\n\n")
			sb.WriteString(fmt.Sprintf("    public static %s %s() { return %s(null); }\n\n", exceptionClass, methodName, methodName))
		}
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, className+".java"), []byte(sb.String()), 0644)
}

// ── Legacy no-ops kept for backward compat ───────────────────────────────────

func (e *JavaEmitter) emitErrorHandler(_ jstrategy.FrameworkStrategy, _ string) error { return nil }
func (e *JavaEmitter) emitModuleErrors(_ ast.Module, _ string) error                  { return nil }
