package java

// errors.go — emits a GlobalExceptionHandler.java via the FrameworkStrategy,
// plus pure-Java ApiErrorResponse.java, ApiException.java, and per-module
// typed ApiError constant classes when actions define errors.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// emitErrorHandler writes ApiErrorResponse.java, ApiException.java (pure Java),
// and GlobalExceptionHandler.java (framework-specific via strategy).
func (e *JavaEmitter) emitErrorHandler(outDir string) error {
	modelsDir := filepath.Join(outDir, "models")

	// ApiErrorResponse — pure Java record, no framework dependency.
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))
	sb.WriteString("/** Standard API error response body. */\n")
	sb.WriteString("public record ApiErrorResponse(\n")
	sb.WriteString("    String error,\n")
	sb.WriteString("    String code\n")
	sb.WriteString(") {}\n")
	if err := os.WriteFile(filepath.Join(modelsDir, "ApiErrorResponse.java"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	// ApiException — pure Java runtime exception, no framework dependency.
	var ae strings.Builder
	ae.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	ae.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))
	ae.WriteString("/** Typed API exception with a machine-readable code and HTTP status. */\n")
	ae.WriteString("public class ApiException extends RuntimeException {\n")
	ae.WriteString("    private final String code;\n")
	ae.WriteString("    private final int status;\n\n")
	ae.WriteString("    public ApiException(String code, int status, String message) {\n")
	ae.WriteString("        super(message);\n")
	ae.WriteString("        this.code = code;\n")
	ae.WriteString("        this.status = status;\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    public String getCode() { return code; }\n")
	ae.WriteString("    public int getStatus() { return status; }\n")
	ae.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(modelsDir, "ApiException.java"), []byte(ae.String()), 0644); err != nil {
		return err
	}

	// GlobalExceptionHandler — entirely framework-specific, owned by the strategy.
	src := e.strategy.GlobalExceptionHandlerSource(javaPackageControllers, javaPackageModels)
	if src == "" {
		return nil
	}
	ctrlDir := filepath.Join(outDir, "controllers")
	return os.WriteFile(filepath.Join(ctrlDir, "GlobalExceptionHandler.java"), []byte(src), 0644)
}

// emitModuleErrors writes errors/{Module}Errors.java with typed error factory methods.
func (e *JavaEmitter) emitModuleErrors(mod ast.Module, outDir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	className := mod.Name + "Errors"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s.errors;\n\n", javaPackageModels))
	sb.WriteString(fmt.Sprintf("import %s.ApiException;\n\n", javaPackageModels))
	sb.WriteString(fmt.Sprintf("public final class %s {\n", className))
	sb.WriteString(fmt.Sprintf("    private %s() {}\n\n", className))

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			methodName := emitter.ToCamelCase(act.Name) + errName
			sb.WriteString(fmt.Sprintf("    public static ApiException %s(String message) {\n", methodName))
			sb.WriteString(fmt.Sprintf("        return new ApiException(\"%s\", %d, message != null ? message : \"%s\");\n", code, status, errName))
			sb.WriteString("    }\n\n")
			sb.WriteString(fmt.Sprintf("    public static ApiException %s() {\n", methodName))
			sb.WriteString(fmt.Sprintf("        return %s(null);\n", methodName))
			sb.WriteString("    }\n\n")
		}
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, className+".java"), []byte(sb.String()), 0644)
}
