package java

// errors.go — emits GlobalExceptionHandler + ApiErrorResponse + ApiException +
// 7 convenience exception subclasses + helper methods + per-module typed error factories.
// Matches the comprehensive approach used by the TypeScript/Node emitter.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	jstrategy "github.com/Adhamzineldin/Veld/internal/emitter/backend/java/strategy"
)

// emitErrorHandler writes ApiErrorResponse.java, ApiException.java (pure Java with helpers),
// 7 convenience subclasses, and GlobalExceptionHandler.java (framework-specific).
func (e *JavaEmitter) emitErrorHandler(strat jstrategy.FrameworkStrategy, outDir string) error {
	modelsDir := pkgToDir(outDir, javaPackageModels)

	// ApiErrorResponse — pure Java record, no framework dependency.
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))
	sb.WriteString("/** Standard API error response body. */\n")
	sb.WriteString("public record ApiErrorResponse(\n")
	sb.WriteString("    String error,\n")
	sb.WriteString("    String code,\n")
	sb.WriteString("    int status\n")
	sb.WriteString(") {}\n")
	if err := os.WriteFile(filepath.Join(modelsDir, "ApiErrorResponse.java"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	// ApiException — pure Java runtime exception with helpers.
	var ae strings.Builder
	ae.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	ae.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))
	ae.WriteString("import java.time.Instant;\n\n")
	ae.WriteString("/**\n")
	ae.WriteString(" * Typed API exception with a machine-readable code and HTTP status.\n")
	ae.WriteString(" * Every Veld-generated error factory returns ApiException.\n")
	ae.WriteString(" *\n")
	ae.WriteString(" * <pre>{@code\n")
	ae.WriteString(" * throw new ApiException(\"GET_USER_NOT_FOUND\", 404, \"user not found\");\n")
	ae.WriteString(" * }</pre>\n")
	ae.WriteString(" */\n")
	ae.WriteString("public class ApiException extends RuntimeException {\n")
	ae.WriteString("    private final String code;\n")
	ae.WriteString("    private final int status;\n")
	ae.WriteString("    private final String timestamp;\n\n")
	ae.WriteString("    public ApiException(String code, int status, String message) {\n")
	ae.WriteString("        super(message);\n")
	ae.WriteString("        this.code = code;\n")
	ae.WriteString("        this.status = status;\n")
	ae.WriteString("        this.timestamp = Instant.now().toString();\n")
	ae.WriteString("    }\n\n")
	ae.WriteString("    public String getCode() { return code; }\n")
	ae.WriteString("    public int getStatus() { return status; }\n")
	ae.WriteString("    public String getTimestamp() { return timestamp; }\n\n")

	// ── Helper methods
	ae.WriteString("    // ── Helper Methods ──────────────────────────────────────────\n\n")

	ae.WriteString("    /** Check if this exception matches a specific error code. */\n")
	ae.WriteString("    public boolean isErrorCode(String errorCode) {\n")
	ae.WriteString("        return this.code.equals(errorCode);\n")
	ae.WriteString("    }\n\n")

	ae.WriteString("    /** Check if this exception has a specific HTTP status. */\n")
	ae.WriteString("    public boolean isHttpStatus(int httpStatus) {\n")
	ae.WriteString("        return this.status == httpStatus;\n")
	ae.WriteString("    }\n\n")

	ae.WriteString("    /** Convert to a JSON-safe ApiErrorResponse. */\n")
	ae.WriteString("    public ApiErrorResponse toErrorResponse() {\n")
	ae.WriteString("        return new ApiErrorResponse(getMessage(), code, status);\n")
	ae.WriteString("    }\n\n")

	ae.WriteString("    // ── Static Helper Methods ───────────────────────────────────\n\n")

	ae.WriteString("    /** Check if a throwable is an ApiException. */\n")
	ae.WriteString("    public static boolean isApiException(Throwable t) {\n")
	ae.WriteString("        return t instanceof ApiException;\n")
	ae.WriteString("    }\n\n")

	ae.WriteString("    /** Check if a throwable is an ApiException with the given code. */\n")
	ae.WriteString("    public static boolean isErrorCode(Throwable t, String errorCode) {\n")
	ae.WriteString("        return t instanceof ApiException ae && ae.code.equals(errorCode);\n")
	ae.WriteString("    }\n\n")

	ae.WriteString("    /** Check if a throwable is an ApiException with the given HTTP status. */\n")
	ae.WriteString("    public static boolean isHttpStatus(Throwable t, int httpStatus) {\n")
	ae.WriteString("        return t instanceof ApiException ae && ae.status == httpStatus;\n")
	ae.WriteString("    }\n\n")

	ae.WriteString("    /**\n")
	ae.WriteString("     * Convert any throwable into a consistent ApiErrorResponse.\n")
	ae.WriteString("     * ApiException instances preserve their code and status;\n")
	ae.WriteString("     * other throwables become 500 Internal Server Error.\n")
	ae.WriteString("     */\n")
	ae.WriteString("    public static ApiErrorResponse toErrorResponse(Throwable t) {\n")
	ae.WriteString("        if (t instanceof ApiException ae) {\n")
	ae.WriteString("            return ae.toErrorResponse();\n")
	ae.WriteString("        }\n")
	ae.WriteString("        return new ApiErrorResponse(t.getMessage(), \"INTERNAL_ERROR\", 500);\n")
	ae.WriteString("    }\n")
	ae.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(modelsDir, "ApiException.java"), []byte(ae.String()), 0644); err != nil {
		return err
	}

	// ── 7 convenience exception subclasses ───────────────────────────────
	type errDef struct {
		name      string
		status    int
		msg       string
		codeConst string
	}
	defs := []errDef{
		{"NotFoundException", 404, "Not Found", "NOT_FOUND"},
		{"BadRequestException", 400, "Bad Request", "BAD_REQUEST"},
		{"UnauthorizedException", 401, "Unauthorized", "UNAUTHORIZED"},
		{"ForbiddenException", 403, "Forbidden", "FORBIDDEN"},
		{"ConflictException", 409, "Conflict", "CONFLICT"},
		{"ValidationException", 422, "Validation Failed", "VALIDATION_FAILED"},
		{"InternalException", 500, "Internal Server Error", "INTERNAL_SERVER_ERROR"},
	}

	for _, d := range defs {
		var cs strings.Builder
		cs.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		cs.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))
		cs.WriteString(fmt.Sprintf("/** %d %s — throw from service implementations for quick status responses. */\n", d.status, d.msg))
		cs.WriteString(fmt.Sprintf("public class %s extends ApiException {\n", d.name))
		cs.WriteString(fmt.Sprintf("    public %s() {\n", d.name))
		cs.WriteString(fmt.Sprintf("        this(\"%s\");\n", d.msg))
		cs.WriteString("    }\n\n")
		cs.WriteString(fmt.Sprintf("    public %s(String message) {\n", d.name))
		cs.WriteString(fmt.Sprintf("        this(message, \"%s\");\n", d.codeConst))
		cs.WriteString("    }\n\n")
		cs.WriteString(fmt.Sprintf("    public %s(String message, String code) {\n", d.name))
		cs.WriteString(fmt.Sprintf("        super(code, %d, message);\n", d.status))
		cs.WriteString("    }\n")
		cs.WriteString("}\n")
		if err := os.WriteFile(filepath.Join(modelsDir, d.name+".java"), []byte(cs.String()), 0644); err != nil {
			return err
		}
	}

	// GlobalExceptionHandler — entirely framework-specific, owned by the strategy.
	src := strat.GlobalExceptionHandlerSource(javaPackageControllers, javaPackageModels)
	if src == "" {
		return nil
	}
	ctrlDir := pkgToDir(outDir, javaPackageControllers)
	return os.WriteFile(filepath.Join(ctrlDir, "GlobalExceptionHandler.java"), []byte(src), 0644)
}

// emitModuleErrors writes errors/{Module}Errors.java with typed error factory methods.
func (e *JavaEmitter) emitModuleErrors(mod ast.Module, outDir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	dir := pkgToDir(outDir, javaPackageModels+".errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	className := mod.Name + "Errors"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s.errors;\n\n", javaPackageModels))
	sb.WriteString(fmt.Sprintf("import %s.ApiException;\n\n", javaPackageModels))
	sb.WriteString(fmt.Sprintf("public final class %s {\n", className))
	sb.WriteString(fmt.Sprintf("    private %s() {}\n\n", className))

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			methodName := emitter.ToCamelCase(act.Name) + errName
			sb.WriteString(fmt.Sprintf("    public static ApiException %s(String message) {\n", methodName))
			sb.WriteString(fmt.Sprintf("        return new ApiException(\"%s\", %d, message != null ? message : \"%s\");\n", code, status, errName))
			sb.WriteString("    }\n\n")
			sb.WriteString(fmt.Sprintf("    public static ApiException %s() {\n", methodName))
			sb.WriteString(fmt.Sprintf("        return %s(null);\n", methodName))
			sb.WriteString("    }\n\n")
		}
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, className+".java"), []byte(sb.String()), 0644)
}
