package java_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/backend/java"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

// javaPath returns the expected filesystem path for a generated Java file,
// matching Maven standard layout: src/main/java/maayn/veld/generated/<sub>/<file>
func javaPath(outDir, sub, file string) string {
	return filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", sub, file)
}

func TestJavaEmitterEmit(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "spring"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	// Models are now per-module: models/{group}/{Type}.java
	// Auth module uses LoginInput, User, and Role (via User.role field) → models/auth/
	expectedFiles := []string{
		filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", "models", "auth", "LoginInput.java"),
		filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", "models", "auth", "User.java"),
		filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", "models", "auth", "Role.java"),
		javaPath(outDir, "services", "IAuthService.java"),
		javaPath(outDir, "controllers", "AuthController.java"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
	// Spring no longer emits pom.xml — the user project owns it.
	if _, err := os.Stat(filepath.Join(outDir, "pom.xml")); !os.IsNotExist(err) {
		t.Error("Spring emitter must not generate pom.xml in outDir")
	}
}

func TestJavaEmitterDryRun(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, got %d entries", len(entries))
	}
}

func TestJavaEmitterModelContent(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "spring"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", "models", "auth", "User.java"))
	if err != nil {
		t.Fatalf("ReadFile User.java: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"package", "package maayn.veld.generated.models.auth;"},
		{"list import", "import java.util.List;"},
		{"class declaration", "public class User"},
		{"private field", "private String email;"},
		{"no-arg constructor", "public User() {}"},
		{"all-args constructor", "public User(UUID id, String email"},
		{"getter", "public String getEmail()"},
		{"setter", "public void setEmail(String email)"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("User.java missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestJavaEmitterEnumContent(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "spring"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", "models", "auth", "Role.java"))
	if err != nil {
		t.Fatalf("ReadFile Role.java: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"package", "package maayn.veld.generated.models.auth;"},
		{"JsonCreator import", "JsonCreator"},
		{"JsonValue import", "JsonValue"},
		{"enum declaration", "public enum Role {"},
		{"admin value", `ADMIN("admin")`},
		{"user value", `USER("user")`},
		{"getValue method", "@JsonValue"},
		{"fromValue method", "@JsonCreator"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("Role.java missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestJavaEmitterInterfaceContent(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "spring"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(javaPath(outDir, "services", "IAuthService.java"))
	if err != nil {
		t.Fatalf("ReadFile IAuthService.java: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"package", "package maayn.veld.generated.services;"},
		{"models import", "import maayn.veld.generated.models.auth.*;"},
		{"interface", "public interface IAuthService {"},
		{"login method", "User login(LoginInput input) throws Exception;"},
		{"me method", "User me() throws Exception;"},
		{"logout void", "void logout() throws Exception;"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("IAuthService.java missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestJavaEmitterControllerContent(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "spring"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(javaPath(outDir, "controllers", "AuthController.java"))
	if err != nil {
		t.Fatalf("ReadFile AuthController.java: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"package", "package maayn.veld.generated.controllers;"},
		{"rest controller", "@RestController"},
		{"request mapping prefix", `@RequestMapping("/api")`},
		{"class declaration", "public class AuthController {"},
		{"constructor injection", "public AuthController(IAuthService service)"},
		{"post mapping", `@PostMapping("/auth/login")`},
		{"get mapping", `@GetMapping("/auth/me")`},
		{"delete mapping", `@DeleteMapping("/auth/logout")`},
		{"request body", "@RequestBody"},
		{"post 201", "HttpStatus.CREATED"},
		{"delete no content", "ResponseEntity.noContent()"},
		{"api exception catch", "} catch (ApiException e) {"},
		{"generic catch", "} catch (Exception e) {"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("AuthController.java missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestJavaEmitterPathParams(t *testing.T) {
	e := java.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{BackendFramework: "spring"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(javaPath(outDir, "controllers", "ItemsController.java"))
	content := string(data)

	if !strings.Contains(content, `@PathVariable("id") String id`) {
		t.Errorf("controller should extract path param: got:\n%s", content)
	}
}

func TestJavaEmitterSummary(t *testing.T) {
	e := java.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}
	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	const srcRoot = "src/main/java/maayn/veld/generated/"
	for _, want := range []string{srcRoot + "models/", srcRoot + "services/", srcRoot + "controllers/", "./"} {
		if !dirs[want] {
			t.Errorf("Summary() missing dir %q", want)
		}
	}
}

func TestJavaEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("java"); err != nil {
		t.Errorf("java backend not registered: %v", err)
	}
}
