package java

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("java", New())
}

// JavaEmitter generates a typed Java Spring Boot backend from a Veld AST.
// Output layout:
//
//	outDir/
//	├── pom.xml
//	├── models/      — one .java file per model + one per enum
//	├── services/    — I{Module}Service.java per module
//	└── controllers/ — {Module}Controller.java per module
type JavaEmitter struct{}

func (*JavaEmitter) IsBackend() {}
func New() *JavaEmitter         { return &JavaEmitter{} }

// Summary returns a human-readable list of files that will be generated.
func (e *JavaEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine

	lines = append(lines, emitter.SummaryLine{Dir: "models/", Files: "<Model>.java, <Enum>.java"})

	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "I"+capitalize(m)+"Service.java")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "services/", Files: strings.Join(ifaceFiles, ", ")})
	}

	ctrlFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ctrlFiles = append(ctrlFiles, capitalize(m)+"Controller.java")
	}
	if len(ctrlFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "controllers/", Files: strings.Join(ctrlFiles, ", ")})
	}

	lines = append(lines, emitter.SummaryLine{Dir: "./", Files: "pom.xml"})
	return lines
}

// capitalize returns s with its first character uppercased.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// Emit writes all generated files to outDir.
func (e *JavaEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	if err := e.createDirs(outDir); err != nil {
		return err
	}
	if err := e.emitModels(a, outDir); err != nil {
		return fmt.Errorf("models: %w", err)
	}
	if err := e.emitErrorHandler(outDir); err != nil {
		return fmt.Errorf("error handler: %w", err)
	}
	for _, mod := range a.Modules {
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("service interface %s: %w", mod.Name, err)
		}
		if err := e.emitController(a, mod, outDir); err != nil {
			return fmt.Errorf("controller %s: %w", mod.Name, err)
		}
		if err := e.emitModuleErrors(mod, outDir); err != nil {
			return fmt.Errorf("errors %s: %w", mod.Name, err)
		}
	}
	if err := e.emitPom(outDir); err != nil {
		return fmt.Errorf("pom.xml: %w", err)
	}
	return nil
}

func (e *JavaEmitter) createDirs(outDir string) error {
	for _, sub := range []string{"models", "services", "controllers"} {
		if err := os.MkdirAll(filepath.Join(outDir, sub), 0755); err != nil {
			return err
		}
	}
	return nil
}

// emitPom writes a minimal Spring Boot pom.xml.
func (e *JavaEmitter) emitPom(outDir string) error {
	const pom = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED BY VELD — DO NOT EDIT -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.0</version>
    <relativePath/>
  </parent>

  <groupId>com.example</groupId>
  <artifactId>veld-generated</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>

  <properties>
    <java.version>17</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
`
	return os.WriteFile(filepath.Join(outDir, "pom.xml"), []byte(pom), 0644)
}
