package java

// middleware.go — emits per-module middleware interfaces.
// Servlet/framework imports are delegated to the FrameworkStrategy.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// emitModuleMiddleware writes middleware/I{Module}Middleware.java.
func (e *JavaEmitter) emitModuleMiddleware(mod ast.Module, outDir string) error {
	allMiddleware := emitter.CollectModuleMiddleware(mod)
	if len(allMiddleware) == 0 {
		return nil
	}

	dir := filepath.Join(outDir, "middleware")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	interfaceName := "I" + mod.Name + "Middleware"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s.middleware;\n\n", javaPackageModels))
	for _, imp := range e.strategy.MiddlewareImports() {
		sb.WriteString(fmt.Sprintf("import %s;\n", imp))
	}
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("/**\n * Middleware interface for the %s module.\n", mod.Name))
	sb.WriteString(" * Implement this interface and register it with the controller.\n */\n")
	sb.WriteString(fmt.Sprintf("public interface %s {\n\n", interfaceName))

	middlewareImports := e.strategy.MiddlewareImports()
	reqType := "Object"
	resType := "Object"
	if len(middlewareImports) >= 2 {
		// Extract simple class name from the last segment of the import path.
		parts := strings.Split(middlewareImports[0], ".")
		reqType = parts[len(parts)-1]
		parts = strings.Split(middlewareImports[1], ".")
		resType = parts[len(parts)-1]
	}

	for _, mw := range allMiddleware {
		methodName := emitter.ToCamelCase(mw)
		sb.WriteString(fmt.Sprintf("    /** %s middleware — return true to proceed, false to reject. */\n", mw))
		sb.WriteString(fmt.Sprintf("    boolean %s(%s request, %s response);\n\n", methodName, reqType, resType))
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, interfaceName+".java"), []byte(sb.String()), 0644)
}
