package java

// middleware.go — generates per-label middleware interfaces, framework interceptors,
// VeldWebMvcConfigurer (path-pattern wiring), and VeldAutoConfiguration (component scan).

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	jstrategy "github.com/Adhamzineldin/Veld/internal/emitter/backend/java/strategy"
)

const javaPackageMiddleware = "maayn.veld.generated.middleware"
const javaPackageBase = "maayn.veld.generated"

// emitMiddleware generates all middleware-related files for the whole AST (not per-module):
//
//  1. I{Label}Middleware.java   — interface the user implements (one per unique label)
//  2. {Label}Interceptor.java   — Spring HandlerInterceptor delegating to the interface
//  3. VeldWebMvcConfigurer.java — registers every interceptor to its exact path patterns
//  4. VeldAutoConfiguration.java + META-INF imports — component scan without touching user code
func (e *JavaEmitter) emitMiddleware(strat jstrategy.FrameworkStrategy, a ast.AST, outDir string) error {
	allLabels := emitter.CollectAllMiddleware(a.Modules)

	if len(allLabels) > 0 {
		mwDir := pkgToDir(outDir, javaPackageMiddleware)
		if err := os.MkdirAll(mwDir, 0755); err != nil {
			return err
		}

		mwImports := strat.MiddlewareImports()
		reqType, resType := "Object", "Object"
		if len(mwImports) >= 2 {
			parts := strings.Split(mwImports[0], ".")
			reqType = parts[len(parts)-1]
			parts = strings.Split(mwImports[1], ".")
			resType = parts[len(parts)-1]
		}

		// 1 + 2: per-label interface and interceptor
		for _, label := range allLabels {
			if err := emitMiddlewareInterface(label, reqType, resType, mwImports, mwDir); err != nil {
				return fmt.Errorf("middleware interface %s: %w", label, err)
			}
			if src := strat.InterceptorSource(label, javaPackageMiddleware); src != "" {
				if err := os.WriteFile(filepath.Join(mwDir, label+"Interceptor.java"), []byte(src), 0644); err != nil {
					return fmt.Errorf("interceptor %s: %w", label, err)
				}
			}
		}

		// 3: VeldWebMvcConfigurer — build path map first
		pathMap := buildMiddlewarePathMap(a.Modules)
		if src := strat.WebMvcConfigurerSource(pathMap, javaPackageControllers, javaPackageMiddleware); src != "" {
			ctrlDir := pkgToDir(outDir, javaPackageControllers)
			if err := os.WriteFile(filepath.Join(ctrlDir, "VeldWebMvcConfigurer.java"), []byte(src), 0644); err != nil {
				return fmt.Errorf("VeldWebMvcConfigurer: %w", err)
			}
		}
	}

	// 4: VeldAutoConfiguration (always emitted for Spring — fixes component-scan gap)
	return emitAutoConfig(strat, outDir)
}

// emitMiddlewareInterface writes I{Label}Middleware.java.
func emitMiddlewareInterface(label, reqType, resType string, imports []string, dir string) error {
	ifaceName := "I" + label + "Middleware"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageMiddleware))
	for _, imp := range imports {
		sb.WriteString(fmt.Sprintf("import %s;\n", imp))
	}
	if len(imports) > 0 {
		sb.WriteString("\n")
	}
	sb.WriteString(fmt.Sprintf("/**\n * Implement this interface and register it as a @Bean to activate %s middleware.\n */\n", label))
	sb.WriteString(fmt.Sprintf("public interface %s {\n", ifaceName))
	sb.WriteString("    /** Called before each matching request. Return true to proceed, false to reject. */\n")
	sb.WriteString(fmt.Sprintf("    boolean handle(%s request, %s response) throws Exception;\n", reqType, resType))
	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, ifaceName+".java"), []byte(sb.String()), 0644)
}

// buildMiddlewarePathMap returns label → []full-path for every action that declares middleware.
func buildMiddlewarePathMap(modules []ast.Module) map[string][]string {
	pathMap := map[string][]string{}
	seen := map[string]map[string]bool{}
	for _, mod := range modules {
		for _, act := range mod.Actions {
			fullPath := act.Path
			if mod.Prefix != "" {
				fullPath = mod.Prefix + act.Path
			}
			for _, mw := range act.Middleware {
				if seen[mw] == nil {
					seen[mw] = map[string]bool{}
				}
				if !seen[mw][fullPath] {
					seen[mw][fullPath] = true
					pathMap[mw] = append(pathMap[mw], fullPath)
				}
			}
		}
	}
	return pathMap
}

// emitAutoConfig writes VeldAutoConfiguration.java and the Spring Boot auto-config imports file.
// The imports file activates component scanning automatically when the resources directory
// is on the classpath (add generated/src/main/resources via build-helper add-resource goal
// or Gradle sourceSets.main.resources.srcDir — `veld setup` handles this).
func emitAutoConfig(strat jstrategy.FrameworkStrategy, outDir string) error {
	src := strat.AutoConfigSource(javaPackageBase)
	if src == "" {
		return nil
	}
	baseDir := pkgToDir(outDir, javaPackageBase)
	if err := os.MkdirAll(baseDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(baseDir, "VeldAutoConfiguration.java"), []byte(src), 0644); err != nil {
		return err
	}
	// Spring Boot 3+ auto-configuration imports file.
	metaDir := filepath.Join(outDir, "src", "main", "resources", "META-INF", "spring")
	if err := os.MkdirAll(metaDir, 0755); err != nil {
		return err
	}
	importsFile := filepath.Join(metaDir, "org.springframework.boot.autoconfigure.AutoConfiguration.imports")
	return os.WriteFile(importsFile, []byte(javaPackageBase+".VeldAutoConfiguration\n"), 0644)
}
