package java

// routes.go — emits controllers/{Module}Controller.java.
// All framework-specific annotations and response building are delegated
// to the FrameworkStrategy; this file only owns Java structure.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	jstrategy "github.com/Adhamzineldin/Veld/internal/emitter/backend/java/strategy"
)

const javaPackageControllers = "maayn.veld.generated.controllers"

func (e *JavaEmitter) emitController(strat jstrategy.FrameworkStrategy, a ast.AST, mod ast.Module, outDir string) error {
	dir := pkgToDir(outDir, javaPackageControllers)

	enumNames := make(map[string]bool, len(a.Enums))
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	modClass := capitalize(mod.Name)

	// Determine which extra imports the controller needs.
	needsList := false
	for _, act := range mod.Actions {
		rt := javaReturnType(act, enumNames)
		if strings.HasPrefix(rt, "List<") {
			needsList = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageControllers))
	sb.WriteString(fmt.Sprintf("import %s.*;\n", javaPackageModels))
	sb.WriteString(fmt.Sprintf("import %s.I%sService;\n", javaPackageServices, modClass))
	if needsList {
		sb.WriteString("import java.util.List;\n")
	}
	for _, imp := range strat.ControllerImports() {
		sb.WriteString(fmt.Sprintf("import %s;\n", imp))
	}
	sb.WriteString("\n")

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", mod.Description))
	}
	for _, ann := range strat.ControllerAnnotations(mod) {
		sb.WriteString(ann + "\n")
	}
	sb.WriteString(fmt.Sprintf("public class %sController {\n\n", modClass))
	sb.WriteString(fmt.Sprintf("    private final I%sService service;\n\n", modClass))
	sb.WriteString(fmt.Sprintf("    public %sController(I%sService service) {\n", modClass, modClass))
	sb.WriteString("        this.service = service;\n")
	sb.WriteString("    }\n")

	for _, act := range mod.Actions {
		if act.Method == "WS" {
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			emitType := act.Emit
			if emitType == "" {
				emitType = "String"
			}
			sb.WriteString(strat.WSControllerMethod(capitalize(act.Name), routePath, emitType, act.Stream))
		} else {
			e.writeHandler(strat, &sb, act, enumNames)
		}
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, modClass+"Controller.java"), []byte(sb.String()), 0644)
}

// writeHandler appends a single handler method to sb.
func (e *JavaEmitter) writeHandler(strat jstrategy.FrameworkStrategy, sb *strings.Builder, act ast.Action, enumNames map[string]bool) {
	pathParams := emitter.ExtractPathParams(act.Path)
	returnType := javaReturnType(act, enumNames)

	sb.WriteString("\n")
	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("    /** %s */\n", act.Description))
	}
	sb.WriteString(fmt.Sprintf("    %s\n", strat.RouteAnnotation(act.Method, act.Path)))

	methodName := javaCamelField(act.Name)
	var params []string
	for _, p := range pathParams {
		ann := strat.PathParamAnnotation(p)
		if ann != "" {
			params = append(params, fmt.Sprintf("%s String %s", ann, javaCamelField(p)))
		} else {
			params = append(params, fmt.Sprintf("String %s", javaCamelField(p)))
		}
	}
	if act.Input != "" {
		ann := strat.InputParamAnnotation()
		if ann != "" {
			params = append(params, fmt.Sprintf("%s %s body", ann, act.Input))
		} else {
			params = append(params, fmt.Sprintf("%s body", act.Input))
		}
	}
	if act.Query != "" {
		ann := strat.QueryParamAnnotation()
		if ann != "" {
			params = append(params, fmt.Sprintf("%s %s query", ann, strat.QueryParamType()))
		} else {
			params = append(params, fmt.Sprintf("%s query", strat.QueryParamType()))
		}
	}

	sb.WriteString(fmt.Sprintf("    public %s %s(%s) {\n", strat.ResponseWrapper(), methodName, strings.Join(params, ", ")))
	sb.WriteString("        try {\n")

	var callArgs []string
	for _, p := range pathParams {
		callArgs = append(callArgs, javaCamelField(p))
	}
	if act.Input != "" {
		callArgs = append(callArgs, "body")
	}
	if act.Query != "" {
		callArgs = append(callArgs, "query")
	}

	serviceCall := fmt.Sprintf("service.%s(%s)", methodName, strings.Join(callArgs, ", "))

	switch {
	case returnType == "void" && act.Method == "DELETE":
		sb.WriteString(fmt.Sprintf("            %s;\n", serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.NoContentResponse()))
	case returnType == "void" && act.Method == "POST":
		// POST with no output — call service, return 201 with no body
		sb.WriteString(fmt.Sprintf("            %s;\n", serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.CreatedResponse("null")))
	case returnType == "void":
		sb.WriteString(fmt.Sprintf("            %s;\n", serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.OkResponse("null")))
	case act.Method == "POST":
		sb.WriteString(fmt.Sprintf("            %s result = %s;\n", returnType, serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.CreatedResponse("result")))
	default:
		sb.WriteString(fmt.Sprintf("            %s result = %s;\n", returnType, serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.OkResponse("result")))
	}

	sb.WriteString("        } catch (Exception e) {\n")
	sb.WriteString(fmt.Sprintf("            %s\n", strat.ErrorResponse("e")))
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")
}
