package java

// sdk.go — service SDK generation for Java backend.
// Mirrors the normal generated backend structure exactly:
//
//	sdk/{service}/
//	  models/
//	    {module}/          ← one subfolder per module (matches backend types/ split)
//	      ModelA.java
//	      ModelB.java
//	  errors/
//	    SdkApiError.java           ← base typed exception (mirrors ApiException)
//	    {Module}Errors.java        ← one per module, nested per action (mirrors backend)
//	  {ServiceName}Client.java     ← typed HTTP client, throws SdkApiError

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
)

func (e *JavaEmitter) EmitServiceSdk(consumed []emitter.ConsumedServiceInfo, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun || len(consumed) == 0 {
		return nil
	}
	for _, c := range consumed {
		if err := emitJavaSdk(c, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", c.Name, err)
		}
	}
	return nil
}

func emitJavaSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	sdkDir := filepath.Join(outDir, "src", "main", "java", "maayn", "veld", "generated", "sdk", name)
	errorsDir := filepath.Join(sdkDir, "errors")
	if err := os.MkdirAll(errorsDir, 0755); err != nil {
		return err
	}
	// models/ subfolders are created per-module inside emitJavaSdkModels
	if err := emitJavaSdkModels(consumed, sdkDir, name); err != nil {
		return err
	}
	if err := emitJavaSdkApiError(errorsDir, name); err != nil {
		return err
	}
	if err := emitJavaSdkModuleErrors(consumed, errorsDir, name); err != nil {
		return err
	}
	return emitJavaSdkClient(consumed, sdkDir, name)
}

// ── Models — one subfolder per module ────────────────────────────────────────

// emitJavaSdkModels writes model and enum classes into models/{module}/ subfolders.
// Each model lands in the folder of the first module that uses it, matching the
// TypeScript frontend's per-module types split (types/users.ts, types/auth.ts, …).
func emitJavaSdkModels(consumed emitter.ConsumedServiceInfo, sdkDir, pkg string) error {
	a := consumed.AST
	modelGroups, enumGroups, modelOwner, _ := emitter.AssignModelsToModules(a)
	keys := emitter.SortedGroupKeys(modelGroups, enumGroups)

	// Write enums and model classes per group.
	for _, group := range keys {
		subDir := filepath.Join(sdkDir, "models", group)
		if err := os.MkdirAll(subDir, 0755); err != nil {
			return err
		}
		subPkg := fmt.Sprintf("maayn.veld.generated.sdk.%s.models.%s", pkg, group)

		for _, en := range enumGroups[group] {
			var sb strings.Builder
			sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
			sb.WriteString(fmt.Sprintf("package %s;\n\n", subPkg))
			sb.WriteString(fmt.Sprintf("public enum %s {\n", en.Name))
			for i, v := range en.Values {
				comma := ","
				if i == len(en.Values)-1 {
					comma = ";"
				}
				sb.WriteString(fmt.Sprintf("    %s(%q)%s\n", strings.ToUpper(v), v, comma))
			}
			sb.WriteString("\n    private final String value;\n")
			sb.WriteString(fmt.Sprintf("    %s(String value) { this.value = value; }\n", en.Name))
			sb.WriteString("    public String getValue() { return value; }\n}\n")
			if err := os.WriteFile(filepath.Join(subDir, en.Name+".java"), []byte(sb.String()), 0644); err != nil {
				return err
			}
		}

		for _, m := range modelGroups[group] {
			var sb strings.Builder
			sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
			sb.WriteString(fmt.Sprintf("package %s;\n\n", subPkg))

			// Detect which imports the model needs — uses the same adapter as normal backend.
			needsList, needsMap := false, false
			importSet := make(map[string]bool)
			for _, f := range m.Fields {
				if f.IsArray {
					needsList = true
				}
				if f.IsMap {
					needsMap = true
				}
				// Collect imports from the adapter for each field type.
				_, imports, _ := javaLang.MapType(f.Type)
				for _, imp := range imports {
					importSet[imp] = true
				}
				if f.IsMap {
					_, valImports, _ := javaLang.MapType(f.MapValueType)
					for _, imp := range valImports {
						importSet[imp] = true
					}
				}
			}
			if needsList {
				sb.WriteString("import java.util.List;\n")
			}
			if needsMap {
				sb.WriteString("import java.util.Map;\n")
			}
			for imp := range importSet {
				sb.WriteString(fmt.Sprintf("import %s;\n", imp))
			}
			sb.WriteString("import com.fasterxml.jackson.annotation.JsonIgnoreProperties;\n")

			// If this model extends another, import the parent's package
			if m.Extends != "" {
				parentMod := modelOwner[m.Extends]
				if parentMod != "" && parentMod != group {
					sb.WriteString(fmt.Sprintf("import maayn.veld.generated.sdk.%s.models.%s.%s;\n",
						pkg, parentMod, m.Extends))
				}
			}
			sb.WriteString("\n@JsonIgnoreProperties(ignoreUnknown = true)\n")
			extendsClause := ""
			if m.Extends != "" {
				extendsClause = " extends " + m.Extends
			}
			sb.WriteString(fmt.Sprintf("public class %s%s {\n", m.Name, extendsClause))
			for _, f := range m.Fields {
				jType := javaFieldType(f)
				sb.WriteString(fmt.Sprintf("    private %s %s;\n", jType, f.Name))
			}
			sb.WriteString("\n    protected " + m.Name + "() {}\n\n")
			// All-args constructor
			if len(m.Fields) > 0 {
				var ctorParams []string
				for _, f := range m.Fields {
					jType := javaFieldType(f)
					ctorParams = append(ctorParams, fmt.Sprintf("%s %s", jType, f.Name))
				}
				sb.WriteString(fmt.Sprintf("    public %s(%s) {\n", m.Name, strings.Join(ctorParams, ", ")))
				for _, f := range m.Fields {
					sb.WriteString(fmt.Sprintf("        this.%s = %s;\n", f.Name, f.Name))
				}
				sb.WriteString("    }\n\n")
			}
			for _, f := range m.Fields {
				jType := javaFieldType(f)
				getter := "get" + capitalize(f.Name)
				setter := "set" + capitalize(f.Name)
				sb.WriteString(fmt.Sprintf("    public %s %s() { return this.%s; }\n", jType, getter, f.Name))
				sb.WriteString(fmt.Sprintf("    public void %s(%s %s) { this.%s = %s; }\n", setter, jType, f.Name, f.Name, f.Name))
			}
			sb.WriteString("}\n")
			if err := os.WriteFile(filepath.Join(subDir, m.Name+".java"), []byte(sb.String()), 0644); err != nil {
				return err
			}
		}
	}
	return nil
}

// ── SdkApiError ──────────────────────────────────────────────────────────────

func emitJavaSdkApiError(errorsDir, pkg string) error {
	errorsPkg := fmt.Sprintf("maayn.veld.generated.sdk.%s.errors", pkg)
	var sb strings.Builder
	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", errorsPkg))
	sb.WriteString("/**\n")
	sb.WriteString(" * Typed exception thrown by the SDK client when a remote service returns an HTTP error.\n")
	sb.WriteString(" * Mirrors {@code ApiException} on the server — same check patterns:\n")
	sb.WriteString(" * <pre>{@code\n")
	sb.WriteString(" * try {\n")
	sb.WriteString(" *     iamClient.login(req);\n")
	sb.WriteString(" * } catch (SdkApiError e) {\n")
	sb.WriteString(" *     if (IamErrors.login.isUnauthorized(e)) { ... }\n")
	sb.WriteString(" *     if (IamErrors.Login.UNAUTHORIZED_CODE.equals(e.getCode())) { ... }\n")
	sb.WriteString(" *     if (e.isCode(\"LOGIN_UNAUTHORIZED\")) { ... }\n")
	sb.WriteString(" *     if (e.isStatus(401)) { ... }\n")
	sb.WriteString(" * }\n")
	sb.WriteString(" * }</pre>\n")
	sb.WriteString(" */\n")
	sb.WriteString("public class SdkApiError extends RuntimeException {\n")
	sb.WriteString("    private final String code;\n")
	sb.WriteString("    private final int status;\n\n")
	sb.WriteString("    public SdkApiError(String code, int status, String message) {\n")
	sb.WriteString("        super(message);\n")
	sb.WriteString("        this.code = code;\n")
	sb.WriteString("        this.status = status;\n")
	sb.WriteString("    }\n\n")
	sb.WriteString("    /** Machine-readable error code from the contract, e.g. \"LOGIN_UNAUTHORIZED\". */\n")
	sb.WriteString("    public String getCode() { return code; }\n\n")
	sb.WriteString("    /** HTTP status code, e.g. 401. */\n")
	sb.WriteString("    public int getStatus() { return status; }\n\n")
	sb.WriteString("    /** Returns true if this error's code matches. */\n")
	sb.WriteString("    public boolean isCode(String errorCode) { return this.code.equals(errorCode); }\n\n")
	sb.WriteString("    /** Returns true if this error's HTTP status matches. */\n")
	sb.WriteString("    public boolean isStatus(int httpStatus) { return this.status == httpStatus; }\n")
	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(errorsDir, "SdkApiError.java"), []byte(sb.String()), 0644)
}

// ── Per-module error namespaces ───────────────────────────────────────────────

// emitJavaSdkModuleErrors generates one errors/{Module}Errors.java per module,
// exactly mirroring the backend's {Module}Errors.java nested-static-class pattern.
// Matchers replace factory methods since the caller catches SdkApiError, not throws it.
func emitJavaSdkModuleErrors(consumed emitter.ConsumedServiceInfo, errorsDir, pkg string) error {
	a := consumed.AST
	errorsPkg := fmt.Sprintf("maayn.veld.generated.sdk.%s.errors", pkg)

	for _, mod := range a.Modules {
		if !emitter.HasErrors(mod) {
			continue
		}
		className := mod.Name + "Errors"

		// Build javadoc example
		exampleAction := ""
		exampleErr := ""
		for _, act := range mod.Actions {
			if len(act.Errors) > 0 {
				exampleAction = emitter.ToCamelCase(act.Name)
				exampleErr = "is" + capitalize(act.Errors[0])
				break
			}
		}

		var sb strings.Builder
		sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
		sb.WriteString(fmt.Sprintf("package %s;\n\n", errorsPkg))
		sb.WriteString("/**\n")
		sb.WriteString(fmt.Sprintf(" * Error constants and matchers for the %s module.\n", mod.Name))
		sb.WriteString(" * Mirrors the server-side {@code " + className + "} pattern.\n")
		if exampleAction != "" {
			sb.WriteString(" * <pre>{@code\n")
			sb.WriteString(" * } catch (SdkApiError e) {\n")
			sb.WriteString(fmt.Sprintf(" *     if (%s.%s.%s(e)) { ... }\n", className, exampleAction, exampleErr))
			sb.WriteString(" * }\n")
			sb.WriteString(" * }</pre>\n")
		}
		sb.WriteString(" */\n")
		sb.WriteString(fmt.Sprintf("public final class %s {\n", className))
		sb.WriteString(fmt.Sprintf("    private %s() {}\n\n", className))

		for _, act := range mod.Actions {
			if len(act.Errors) == 0 {
				continue
			}
			camelAction := emitter.ToCamelCase(act.Name)
			innerClass := capitalize(act.Name) + "Errors"

			// Static singleton — mirrors server: UsersErrors.getUser.notFound(...)
			sb.WriteString(fmt.Sprintf("    /** Error constants and matchers for the %s action. */\n", act.Name))
			sb.WriteString(fmt.Sprintf("    public static final %s %s = new %s();\n\n", innerClass, camelAction, innerClass))

			sb.WriteString(fmt.Sprintf("    /** Per-error constants and matchers for %s.\n", act.Name))
			sb.WriteString(fmt.Sprintf("     * Constants match server-side {@code %s.%s.*_CODE} exactly. */\n", className, camelAction))
			sb.WriteString(fmt.Sprintf("    public static final class %s {\n", innerClass))
			sb.WriteString(fmt.Sprintf("        private %s() {}\n\n", innerClass))

			for _, errName := range act.Errors {
				code := emitter.ErrorCode(act.Name, errName)
				status := emitter.ActionErrorStatus(act, errName)
				methodName := emitter.ToCamelCase(errName)
				constCode := screamingSnake(errName) + "_CODE"
				constStatus := screamingSnake(errName) + "_STATUS"
				isMethod := "is" + capitalize(errName)

				sb.WriteString(fmt.Sprintf("        /** Matches server-side %sErrors.%s.%s_CODE = \"%s\" */\n",
					strings.ToLower(mod.Name), camelAction, screamingSnake(errName), code))
				sb.WriteString(fmt.Sprintf("        public static final String %s = \"%s\";\n", constCode, code))
				sb.WriteString(fmt.Sprintf("        public static final int %s = %d;\n\n", constStatus, status))

				sb.WriteString(fmt.Sprintf("        /** Returns true if the SdkApiError is a %s error (%d). */\n", errName, status))
				sb.WriteString(fmt.Sprintf("        public static boolean %s(SdkApiError e) {\n", isMethod))
				sb.WriteString(fmt.Sprintf("            return %s.equals(e.getCode());\n", constCode))
				sb.WriteString("        }\n\n")

				sb.WriteString(fmt.Sprintf("        /** Returns true if this instance's error is %s. */\n", errName))
				sb.WriteString(fmt.Sprintf("        public boolean %s(SdkApiError e) { return %s(e); }\n\n", methodName, isMethod))
			}
			sb.WriteString("    }\n\n")
		}
		sb.WriteString("}\n")

		if err := os.WriteFile(filepath.Join(errorsDir, className+".java"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	return nil
}

// ── HTTP Client ───────────────────────────────────────────────────────────────

// emitJavaSdkClient writes the typed HTTP client with one public inner class per module,
// so callers navigate module-first exactly like the TypeScript SDK:
//
//	TS:   await iamClient.auth.login(req)
//	Java: iamClient.auth.login(req)
func emitJavaSdkClient(consumed emitter.ConsumedServiceInfo, sdkDir, pkg string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)
	errorsPkg := fmt.Sprintf("maayn.veld.generated.sdk.%s.errors", pkg)

	// Collect all module subpackages that have types used in actions
	usedModulePkgs := make(map[string]bool)
	_, _, modelOwner, _ := emitter.AssignModelsToModules(a)
	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			for _, typeName := range []string{act.Input, act.Output, act.Query} {
				if typeName != "" {
					if owner, ok := modelOwner[typeName]; ok {
						usedModulePkgs[owner] = true
					}
				}
			}
			// Error models referenced in the errors list
			for _, errName := range act.Errors {
				if errName != "" {
					if owner, ok := modelOwner[errName]; ok {
						usedModulePkgs[owner] = true
					}
				}
			}
		}
	}

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package maayn.veld.generated.sdk.%s;\n\n", pkg))
	sb.WriteString("import java.net.URI;\n")
	sb.WriteString("import java.net.http.HttpClient;\n")
	sb.WriteString("import java.net.http.HttpRequest;\n")
	sb.WriteString("import java.net.http.HttpResponse;\n")
	sb.WriteString("import java.util.Map;\n")
	sb.WriteString("import java.util.HashMap;\n")
	sb.WriteString("import com.fasterxml.jackson.databind.ObjectMapper;\n")
	sb.WriteString(fmt.Sprintf("import %s.SdkApiError;\n", errorsPkg))
	for modPkg := range usedModulePkgs {
		sb.WriteString(fmt.Sprintf("import maayn.veld.generated.sdk.%s.models.%s.*;\n", pkg, modPkg))
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("public class %s {\n", className))
	sb.WriteString("    private final String base;\n")
	sb.WriteString("    private final HttpClient http;\n")
	sb.WriteString("    private final Map<String, String> headers;\n")
	sb.WriteString("    private final ObjectMapper mapper = new ObjectMapper();\n\n")

	// Public module namespace fields — iamClient.auth.login(req)
	for _, mod := range a.Modules {
		modLower := emitter.ToCamelCase(mod.Name)
		innerClass := capitalize(mod.Name) + "Actions"
		sb.WriteString(fmt.Sprintf("    /** Actions for the %s module. Usage: client.%s.actionName(...) */\n", mod.Name, modLower))
		sb.WriteString(fmt.Sprintf("    public final %s %s = new %s();\n", innerClass, modLower, innerClass))
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("    public %s() { this(null, null); }\n\n", className))
	sb.WriteString(fmt.Sprintf("    public %s(String baseUrl, Map<String, String> headers) {\n", className))
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("        this.base = baseUrl != null ? baseUrl : System.getenv(\"%s\") != null ? System.getenv(\"%s\") : \"%s\";\n",
			envVar, envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("        String resolved = baseUrl != null ? baseUrl : System.getenv(\"%s\");\n", envVar))
		sb.WriteString(fmt.Sprintf("        if (resolved == null) throw new IllegalArgumentException(\"No base URL for %s — pass baseUrl or set %s\");\n",
			consumed.Name, envVar))
		sb.WriteString("        this.base = resolved;\n")
	}
	sb.WriteString("        this.http = HttpClient.newHttpClient();\n")
	sb.WriteString("        this.headers = headers != null ? headers : new HashMap<>();\n")
	sb.WriteString("    }\n\n")

	// Internal raw HTTP helper — throws SdkApiError with parsed code+message
	sb.WriteString("    String request(String method, String path, String body) throws Exception {\n")
	sb.WriteString("        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(this.base + path))\n")
	sb.WriteString("            .header(\"Content-Type\", \"application/json\");\n")
	sb.WriteString("        this.headers.forEach(builder::header);\n")
	sb.WriteString("        if (body != null) { builder.method(method, HttpRequest.BodyPublishers.ofString(body)); }\n")
	sb.WriteString("        else { builder.method(method, HttpRequest.BodyPublishers.noBody()); }\n")
	sb.WriteString("        HttpResponse<String> res = http.send(builder.build(), HttpResponse.BodyHandlers.ofString());\n")
	sb.WriteString("        if (res.statusCode() >= 400) {\n")
	sb.WriteString("            String errBody = res.body();\n")
	sb.WriteString("            String code = extractJsonString(errBody, \"code\");\n")
	sb.WriteString("            String msg  = extractJsonString(errBody, \"error\");\n")
	sb.WriteString("            if (code == null) code = \"UNKNOWN_ERROR\";\n")
	sb.WriteString("            if (msg  == null) msg  = errBody;\n")
	sb.WriteString("            throw new SdkApiError(code, res.statusCode(), msg);\n")
	sb.WriteString("        }\n")
	sb.WriteString("        return res.body();\n")
	sb.WriteString("    }\n\n")

	sb.WriteString("    ObjectMapper mapper() { return mapper; }\n\n")

	// Zero-dependency JSON string extractor (only used for error responses)
	sb.WriteString("    static String extractJsonString(String json, String key) {\n")
	sb.WriteString("        if (json == null) return null;\n")
	sb.WriteString("        String search = \"\\\"\" + key + \"\\\"\";\n")
	sb.WriteString("        int idx = json.indexOf(search);\n")
	sb.WriteString("        if (idx < 0) return null;\n")
	sb.WriteString("        int colon = json.indexOf(':', idx + search.length());\n")
	sb.WriteString("        if (colon < 0) return null;\n")
	sb.WriteString("        int start = json.indexOf('\"', colon + 1);\n")
	sb.WriteString("        if (start < 0) return null;\n")
	sb.WriteString("        int end = json.indexOf('\"', start + 1);\n")
	sb.WriteString("        if (end < 0) return null;\n")
	sb.WriteString("        return json.substring(start + 1, end);\n")
	sb.WriteString("    }\n\n")

	// One inner class per module
	for _, mod := range a.Modules {
		innerClass := capitalize(mod.Name) + "Actions"
		sb.WriteString(fmt.Sprintf("    /** Actions for the %s module. */\n", mod.Name))
		sb.WriteString(fmt.Sprintf("    public final class %s {\n", innerClass))
		sb.WriteString(fmt.Sprintf("        private %s() {}\n", innerClass))

		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				continue
			}
			sb.WriteString("\n")
			writeJavaSdkMethod(&sb, mod, act, "        ")
		}
		sb.WriteString("    }\n\n")
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(sdkDir, className+".java"), []byte(sb.String()), 0644)
}

func writeJavaSdkMethod(sb *strings.Builder, mod ast.Module, act ast.Action, indent string) {
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	methodName := emitter.ToCamelCase(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	retType := "void"
	if act.Output != "" {
		retType = act.Output
	}

	var params []string
	for _, p := range pathParams {
		params = append(params, "String "+p)
	}
	if act.Input != "" {
		params = append(params, act.Input+" input")
	}

	sb.WriteString(fmt.Sprintf("%s/** %s %s */\n", indent, method, routePath))
	sb.WriteString(fmt.Sprintf("%spublic %s %s(%s) throws Exception {\n", indent, retType, methodName, strings.Join(params, ", ")))

	urlExpr := javaSdkBuildUrl(routePath, pathParams)

	if act.Input != "" {
		sb.WriteString(fmt.Sprintf("%s    String body = mapper().writeValueAsString(input);\n", indent))
	}

	bodyArg := "null"
	if act.Input != "" {
		bodyArg = "body"
	}

	if act.Output != "" {
		sb.WriteString(fmt.Sprintf("%s    String raw = request(%q, %s, %s);\n", indent, method, urlExpr, bodyArg))
		sb.WriteString(fmt.Sprintf("%s    return mapper().readValue(raw, %s.class);\n", indent, act.Output))
	} else {
		sb.WriteString(fmt.Sprintf("%s    request(%q, %s, %s);\n", indent, method, urlExpr, bodyArg))
	}
	sb.WriteString(fmt.Sprintf("%s}\n", indent))
}

func javaSdkBuildUrl(routePath string, pathParams []string) string {
	if len(pathParams) == 0 {
		return fmt.Sprintf("%q", routePath)
	}
	expr := "\"" + routePath + "\""
	for _, p := range pathParams {
		expr = strings.Replace(expr, ":"+p, "\" + "+p+" + \"", 1)
	}
	return strings.ReplaceAll(expr, " + \"\"", "")
}
