package java

// types.go — emits models/*.java: one Java record per Veld model, one Java
// enum per Veld enum. All models are placed in a flat models/ package since
// Java organises by package rather than by module.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter/lang"
)

const javaPackageModels = "maayn.veld.generated.models"

// javaLang is the shared language adapter for pure Java type and naming conventions.
var javaLang = &lang.JavaAdapter{}

func (e *JavaEmitter) emitModels(a ast.AST, outDir string) error {
	dir := pkgToDir(outDir, javaPackageModels)

	for _, en := range a.Enums {
		if err := e.emitEnum(en, dir); err != nil {
			return fmt.Errorf("enum %s: %w", en.Name, err)
		}
	}
	for _, m := range a.Models {
		if err := e.emitRecord(m, a.Enums, dir); err != nil {
			return fmt.Errorf("model %s: %w", m.Name, err)
		}
	}
	return nil
}

// emitRecord writes a Java class for a Veld model with constructor + getters/setters.
func (e *JavaEmitter) emitRecord(m ast.Model, enums []ast.Enum, dir string) error {
	enumNames := make(map[string]bool, len(enums))
	for _, en := range enums {
		enumNames[en.Name] = true
	}

	needsList := false
	needsMap := false
	importSet := make(map[string]bool)
	for _, f := range m.Fields {
		if f.IsArray {
			needsList = true
		}
		if f.IsMap {
			needsMap = true
		}
		// Collect imports from the adapter for each field type.
		_, imports, _ := javaLang.MapType(f.Type)
		for _, imp := range imports {
			importSet[imp] = true
		}
		if f.IsMap {
			_, valImports, _ := javaLang.MapType(f.MapValueType)
			for _, imp := range valImports {
				importSet[imp] = true
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))

	if needsList {
		sb.WriteString("import java.util.List;\n")
	}
	if needsMap {
		sb.WriteString("import java.util.Map;\n")
	}
	for imp := range importSet {
		sb.WriteString(fmt.Sprintf("import %s;\n", imp))
	}
	sb.WriteString("import com.fasterxml.jackson.annotation.JsonIgnoreProperties;\n")
	sb.WriteString("\n")

	if m.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
	}

	sb.WriteString("@JsonIgnoreProperties(ignoreUnknown = true)\n")
	extendsClause := ""
	if m.Extends != "" {
		extendsClause = " extends " + m.Extends
	}
	sb.WriteString(fmt.Sprintf("public class %s%s {\n", m.Name, extendsClause))

	// Private fields
	for _, f := range m.Fields {
		javaType := javaFieldType(f)
		fieldName := javaCamelField(f.Name)
		if f.Default != "" {
			sb.WriteString(fmt.Sprintf("    private %s %s = %s;\n", javaType, fieldName, javaDefaultLiteral(f.Default, f.Type)))
		} else {
			sb.WriteString(fmt.Sprintf("    private %s %s;\n", javaType, fieldName))
		}
	}
	sb.WriteString("\n")

	// No-arg constructor (protected so Jackson can still deserialize, but IDE only shows the all-args ctor)
	sb.WriteString(fmt.Sprintf("    protected %s() {}\n\n", m.Name))

	// All-args constructor
	if len(m.Fields) > 0 {
		var ctorParams []string
		for _, f := range m.Fields {
			javaType := javaFieldType(f)
			fieldName := javaCamelField(f.Name)
			ctorParams = append(ctorParams, fmt.Sprintf("%s %s", javaType, fieldName))
		}
		sb.WriteString(fmt.Sprintf("    public %s(%s) {\n", m.Name, strings.Join(ctorParams, ", ")))
		for _, f := range m.Fields {
			fieldName := javaCamelField(f.Name)
			sb.WriteString(fmt.Sprintf("        this.%s = %s;\n", fieldName, fieldName))
		}
		sb.WriteString("    }\n\n")
	}

	// Getters and setters
	for _, f := range m.Fields {
		javaType := javaFieldType(f)
		fieldName := javaCamelField(f.Name)
		getter := "get" + capitalize(f.Name)
		setter := "set" + capitalize(f.Name)
		sb.WriteString(fmt.Sprintf("    public %s %s() { return this.%s; }\n", javaType, getter, fieldName))
		sb.WriteString(fmt.Sprintf("    public void %s(%s %s) { this.%s = %s; }\n", setter, javaType, fieldName, fieldName, fieldName))
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, m.Name+".java"), []byte(sb.String()), 0644)
}

// emitEnum writes a Java enum with @JsonValue/@JsonCreator for proper JSON serialisation.
func (e *JavaEmitter) emitEnum(en ast.Enum, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", javaPackageModels))
	sb.WriteString("import com.fasterxml.jackson.annotation.JsonCreator;\n")
	sb.WriteString("import com.fasterxml.jackson.annotation.JsonValue;\n\n")

	if en.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
	}
	sb.WriteString(fmt.Sprintf("public enum %s {\n", en.Name))

	for i, v := range en.Values {
		constName := strings.ToUpper(strings.ReplaceAll(v, "-", "_"))
		comma := ","
		if i == len(en.Values)-1 {
			comma = ";"
		}
		sb.WriteString(fmt.Sprintf("    %s(\"%s\")%s\n", constName, v, comma))
	}

	sb.WriteString("\n    private final String value;\n\n")
	sb.WriteString(fmt.Sprintf("    %s(String value) { this.value = value; }\n\n", en.Name))
	sb.WriteString("    @JsonValue\n")
	sb.WriteString("    public String getValue() { return value; }\n\n")
	sb.WriteString("    @JsonCreator\n")
	sb.WriteString(fmt.Sprintf("    public static %s fromValue(String value) {\n", en.Name))
	sb.WriteString("        for (" + en.Name + " e : values()) {\n")
	sb.WriteString("            if (e.value.equals(value)) return e;\n")
	sb.WriteString("        }\n")
	sb.WriteString(fmt.Sprintf("        throw new IllegalArgumentException(\"Unknown %s: \" + value);\n", en.Name))
	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, en.Name+".java"), []byte(sb.String()), 0644)
}

// javaFieldType maps an AST field to its Java type string via the language adapter.
func javaFieldType(f ast.Field) string {
	if f.IsMap {
		valType, _, _ := javaLang.MapType(f.MapValueType)
		return "Map<String, " + valType + ">"
	}
	base, _, _ := javaLang.MapType(f.Type)
	if f.IsArray {
		return "List<" + base + ">"
	}
	return base
}

// javaCamelField converts a field or parameter name to Java camelCase via the language adapter.
func javaCamelField(name string) string {
	return javaLang.NamingConvention(name, lang.NamingContextPrivate)
}

// javaDefaultLiteral converts a Veld default value to a Java literal.
func javaDefaultLiteral(val, veldType string) string {
	// Already a quoted string → Java string literal
	if strings.HasPrefix(val, "\"") {
		return val
	}
	// Booleans
	if val == "true" || val == "false" {
		return val
	}
	// Numeric — check for long suffix on int types
	if veldType == "int" {
		return val + "L" // Java long
	}
	if veldType == "float" {
		return val
	}
	if veldType == "decimal" {
		return fmt.Sprintf("new java.math.BigDecimal(\"%s\")", val)
	}
	// Enum value or identifier — emit as string
	return "\"" + val + "\""
}
