package node

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
)

// ExpressEmitter generates TypeScript types, service interfaces, and Express
// route files from a parsed AST.
type ExpressEmitter struct{}

// New returns an ExpressEmitter.
func New() *ExpressEmitter { return &ExpressEmitter{} }

// Emit writes all generated files into outDir.
func (e *ExpressEmitter) Emit(a ast.AST, outDir string) error {
	for _, mod := range a.Modules {
		if err := e.emitTypes(a, mod, outDir); err != nil {
			return fmt.Errorf("types for module %s: %w", mod.Name, err)
		}
		if err := e.emitInterface(mod, outDir); err != nil {
			return fmt.Errorf("interface for module %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(mod, outDir); err != nil {
			return fmt.Errorf("routes for module %s: %w", mod.Name, err)
		}
	}
	return nil
}

// emitTypes writes generated/types/{module}.ts with TypeScript interfaces for
// every model used by the given module.
func (e *ExpressEmitter) emitTypes(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Determine which model names this module actually uses.
	usedNames := make(map[string]bool)
	for _, act := range mod.Actions {
		if act.Input != "" {
			usedNames[act.Input] = true
		}
		if act.Output != "" {
			usedNames[act.Output] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")

	// Emit models in their original definition order.
	for _, m := range a.Models {
		if !usedNames[m.Name] {
			continue
		}
		sb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
		for _, f := range m.Fields {
			sb.WriteString(fmt.Sprintf("  %s: %s\n", f.Name, veldTypeToTS(f.Type)))
		}
		sb.WriteString("}\n")
	}

	return os.WriteFile(filepath.Join(dir, strings.ToLower(mod.Name)+".ts"), []byte(sb.String()), 0644)
}

// emitInterface writes generated/interfaces/I{Module}Service.ts.
func (e *ExpressEmitter) emitInterface(mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	usedTypes := collectUsedTypes(mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types/%s'\n", strings.Join(usedTypes, ", "), moduleLower))
	}
	sb.WriteString(fmt.Sprintf("\nexport interface I%sService {\n", mod.Name))
	for _, act := range mod.Actions {
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf("  %s(input: %s): Promise<%s>\n", act.Name, act.Input, act.Output))
		} else {
			sb.WriteString(fmt.Sprintf("  %s(userId: string): Promise<%s>\n", act.Name, act.Output))
		}
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("I%sService.ts", mod.Name)), []byte(sb.String()), 0644)
}

// emitRoutes writes generated/routes/{module}.routes.ts.
// The generated function accepts a router instance from the caller so the
// generated file has zero runtime dependencies — no express import at all.
func (e *ExpressEmitter) emitRoutes(mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	funcName := moduleLower + "Router"

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	// No framework import — router is passed in by the caller.
	sb.WriteString(fmt.Sprintf("import type { I%sService } from '../interfaces/I%sService'\n", mod.Name, mod.Name))
	sb.WriteString(fmt.Sprintf("\n// Pass any Express-compatible router (or app) and your service implementation.\n"))
	sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService): void {\n", funcName, mod.Name))

	for _, act := range mod.Actions {
		method := strings.ToLower(act.Method)
		sb.WriteString(fmt.Sprintf("\n  router.%s('%s', async (req: any, res: any) => {\n", method, act.Path))
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf("    const result = await service.%s(req.body)\n", act.Name))
		} else {
			sb.WriteString(fmt.Sprintf("    const result = await service.%s(req.user?.id)\n", act.Name))
		}
		sb.WriteString("    res.json(result)\n")
		sb.WriteString("  })\n")
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+".routes.ts"), []byte(sb.String()), 0644)
}

// collectUsedTypes returns the unique type names referenced as inputs or outputs
// in the module, with inputs listed before outputs and in action order.
func collectUsedTypes(mod ast.Module) []string {
	seen := make(map[string]bool)
	var inputs, outputs []string

	for _, act := range mod.Actions {
		if act.Input != "" && !seen[act.Input] {
			seen[act.Input] = true
			inputs = append(inputs, act.Input)
		}
	}
	for _, act := range mod.Actions {
		if act.Output != "" && !seen[act.Output] {
			seen[act.Output] = true
			outputs = append(outputs, act.Output)
		}
	}
	return append(inputs, outputs...)
}

// veldTypeToTS maps a Veld primitive type name to its TypeScript equivalent.
func veldTypeToTS(t string) string {
	switch t {
	case "int":
		return "number"
	case "bool":
		return "boolean"
	default:
		return t // "string" stays "string"
	}
}
