package strategy

import (
	"fmt"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// PlainStrategy generates framework-agnostic Java: service interfaces and model types only.
// No HTTP framework dependency — the developer wires the generated interfaces into
// their own servlet container, Jetty, Netty, or any framework of their choice.
type PlainStrategy struct{}

func (s *PlainStrategy) ControllerAnnotations(_ ast.Module) []string { return nil }

func (s *PlainStrategy) RouteAnnotation(method, path string) string {
	return fmt.Sprintf("// %s %s", strings.ToUpper(method), path)
}

func (s *PlainStrategy) InputParamAnnotation() string        { return "" }
func (s *PlainStrategy) QueryParamAnnotation() string        { return "" }
func (s *PlainStrategy) QueryParamType() string              { return "java.util.Map<String, String>" }
func (s *PlainStrategy) ResponseWrapper() string             { return "Object" }
func (s *PlainStrategy) PathParamAnnotation(_ string) string { return "" }

func (s *PlainStrategy) OkResponse(expr string) string {
	return fmt.Sprintf("return %s;", expr)
}

func (s *PlainStrategy) CreatedResponse(expr string) string {
	return fmt.Sprintf("return %s; // 201 Created", expr)
}

func (s *PlainStrategy) NoContentResponse() string {
	return "// 204 No Content"
}

func (s *PlainStrategy) ErrorResponse(errVar string) string {
	return fmt.Sprintf("throw new RuntimeException(%s.getMessage());", errVar)
}

func (s *PlainStrategy) ControllerImports() []string { return nil }
func (s *PlainStrategy) MiddlewareImports() []string { return nil }
func (s *PlainStrategy) ValidationImports() []string { return nil }

func (s *PlainStrategy) GlobalExceptionHandlerSource(_, _ string) string { return "" }
func (s *PlainStrategy) InterceptorSource(_, _ string) string            { return "" }
func (s *PlainStrategy) WebMvcConfigurerSource(_ map[string][]string, _, _ string) string {
	return ""
}
func (s *PlainStrategy) AutoConfigSource(_ string) string { return "" }

func (s *PlainStrategy) WSControllerMethod(actionName, routePath, emitType, streamType string) string {
	if emitType == "" {
		emitType = "String"
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n    // WebSocket: WS %s\n", routePath))
	sb.WriteString(fmt.Sprintf("    // Implement: service.on%sConnect(session, params)\n", actionName))
	sb.WriteString(fmt.Sprintf("    // Implement: service.on%sMessage(session, msg /* %s */)\n", actionName, emitType))
	if streamType != "" {
		sb.WriteString(fmt.Sprintf("    // Broadcast: service.on%sStream(session) -> %s\n", actionName, streamType))
	}
	sb.WriteString(fmt.Sprintf("    // Implement: service.on%sClose(session)\n", actionName))
	return sb.String()
}

func (s *PlainStrategy) BuildFile() (string, string) {
	return "build.gradle", plainBuildGradle
}

const plainBuildGradle = `// AUTO-GENERATED BY VELD — DO NOT EDIT
// Plain Java — no HTTP framework dependency.
// Wire the generated service interfaces into your own HTTP layer.
plugins {
    id 'java'
}

group = 'maayn.veld'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    // Add your preferred HTTP framework here, e.g.:
    // Spring Boot: implementation 'org.springframework.boot:spring-boot-starter-web:3.2.0'
    // Quarkus:     implementation 'io.quarkus:quarkus-resteasy-reactive:3.6.0'
    // Micronaut:   implementation 'io.micronaut:micronaut-http-server-netty:4.2.0'
}
`
