package strategy

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// rePathParam matches Veld-style :param segments and converts them to {param} for Spring.
var rePathParam = regexp.MustCompile(`:([a-zA-Z_][a-zA-Z0-9_]*)`)

func toSpringPath(path string) string {
	return rePathParam.ReplaceAllString(path, "{$1}")
}

// SpringStrategy implements FrameworkStrategy for Spring Boot 3.x / 4.x (Java 17+, Jakarta EE 10+).
type SpringStrategy struct{}

func (s *SpringStrategy) ControllerAnnotations(mod ast.Module) []string {
	annotations := []string{"@RestController"}
	if mod.Prefix != "" {
		annotations = append(annotations, fmt.Sprintf("@RequestMapping(%q)", mod.Prefix))
	}
	return annotations
}

func (s *SpringStrategy) RouteAnnotation(method, path string) string {
	springPath := toSpringPath(path) // convert :id → {id}
	// Spring Boot 3+ disabled trailing-slash matching. A path of "/" on a method
	// whose controller already has @RequestMapping("/prefix") would resolve to
	// "/prefix/" — which no longer matches "/prefix". Emit with no path argument
	// so the method maps to the prefix itself.
	bare := springPath == "" || springPath == "/"
	ann := func(name, p string) string {
		if bare {
			return "@" + name
		}
		return fmt.Sprintf("@%s(%q)", name, p)
	}
	switch strings.ToUpper(method) {
	case "GET":
		return ann("GetMapping", springPath)
	case "POST":
		return ann("PostMapping", springPath)
	case "PUT":
		return ann("PutMapping", springPath)
	case "DELETE":
		return ann("DeleteMapping", springPath)
	case "PATCH":
		return ann("PatchMapping", springPath)
	default:
		if bare {
			return fmt.Sprintf("@RequestMapping(method = RequestMethod.%s)", strings.ToUpper(method))
		}
		return fmt.Sprintf("@RequestMapping(method = RequestMethod.%s, value = %q)", strings.ToUpper(method), springPath)
	}
}

func (s *SpringStrategy) InputParamAnnotation() string { return "@RequestBody" }
func (s *SpringStrategy) QueryParamAnnotation() string { return "@ModelAttribute" }
func (s *SpringStrategy) QueryParamType() string       { return "" } // unused: type comes from act.Query
func (s *SpringStrategy) ResponseWrapper() string      { return "ResponseEntity<?>" }

func (s *SpringStrategy) PathParamAnnotation(name string) string {
	return fmt.Sprintf("@PathVariable(%q)", name)
}

func (s *SpringStrategy) OkResponse(expr string) string {
	return fmt.Sprintf("return ResponseEntity.ok(%s);", expr)
}

func (s *SpringStrategy) CreatedResponse(expr string) string {
	return fmt.Sprintf("return ResponseEntity.status(HttpStatus.CREATED).body(%s);", expr)
}

func (s *SpringStrategy) NoContentResponse() string {
	return "return ResponseEntity.noContent().build();"
}

func (s *SpringStrategy) ApiExceptionCatch(errVar string) string {
	return fmt.Sprintf(
		"return ResponseEntity.status(%s.getStatus()).body(%s.toErrorResponse());",
		errVar, errVar,
	)
}

func (s *SpringStrategy) ErrorResponse(errVar string) string {
	return fmt.Sprintf(
		"return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ApiException.toErrorResponse(%s));",
		errVar,
	)
}

func (s *SpringStrategy) ControllerImports() []string {
	return []string{
		"org.springframework.http.HttpStatus",
		"org.springframework.http.ResponseEntity",
		"org.springframework.web.bind.annotation.*",
		"java.util.Map",
	}
}

func (s *SpringStrategy) MiddlewareImports() []string {
	return []string{
		"jakarta.servlet.http.HttpServletRequest",
		"jakarta.servlet.http.HttpServletResponse",
	}
}

func (s *SpringStrategy) ValidationImports() []string {
	return []string{
		"jakarta.validation.ConstraintViolation",
		"jakarta.validation.Validation",
		"jakarta.validation.Validator",
		"jakarta.validation.ValidatorFactory",
		"java.util.List",
		"java.util.Set",
		"java.util.stream.Collectors",
	}
}

func (s *SpringStrategy) GlobalExceptionHandlerSource(ctrlPkg, errorsPkg string) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", ctrlPkg))
	sb.WriteString(fmt.Sprintf("import %s.ApiErrorResponse;\n", errorsPkg))
	sb.WriteString(fmt.Sprintf("import %s.ApiException;\n", errorsPkg))
	sb.WriteString("import org.springframework.http.HttpStatus;\n")
	sb.WriteString("import org.springframework.http.ResponseEntity;\n")
	sb.WriteString("import org.springframework.web.bind.annotation.ControllerAdvice;\n")
	sb.WriteString("import org.springframework.web.bind.annotation.ExceptionHandler;\n\n")
	sb.WriteString("@ControllerAdvice\n")
	sb.WriteString("public class GlobalExceptionHandler {\n\n")
	sb.WriteString("    @ExceptionHandler(ApiException.class)\n")
	sb.WriteString("    public ResponseEntity<ApiErrorResponse> handleApiException(ApiException ex) {\n")
	sb.WriteString("        return ResponseEntity.status(ex.getStatus())\n")
	sb.WriteString("            .body(ex.toErrorResponse());\n")
	sb.WriteString("    }\n\n")
	sb.WriteString("    @ExceptionHandler(Exception.class)\n")
	sb.WriteString("    public ResponseEntity<ApiErrorResponse> handleAll(Exception ex) {\n")
	sb.WriteString("        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)\n")
	sb.WriteString("            .body(ApiException.toErrorResponse(ex));\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")
	return sb.String()
}

func (s *SpringStrategy) InterceptorSource(label, middlewarePkg string) string {
	interceptorName := label + "Interceptor"
	ifaceName := "I" + label + "Middleware"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", middlewarePkg))
	sb.WriteString("import jakarta.servlet.http.HttpServletRequest;\n")
	sb.WriteString("import jakarta.servlet.http.HttpServletResponse;\n")
	sb.WriteString("import org.springframework.stereotype.Component;\n")
	sb.WriteString("import org.springframework.web.servlet.HandlerInterceptor;\n\n")
	sb.WriteString(fmt.Sprintf("/** Spring HandlerInterceptor delegating to {@link %s}.\n", ifaceName))
	sb.WriteString(" * Register a @Bean implementing " + ifaceName + " and this interceptor activates. */\n")
	sb.WriteString("@Component\n")
	sb.WriteString(fmt.Sprintf("public class %s implements HandlerInterceptor {\n\n", interceptorName))
	sb.WriteString(fmt.Sprintf("    private final %s middleware;\n\n", ifaceName))
	sb.WriteString(fmt.Sprintf("    public %s(%s middleware) {\n", interceptorName, ifaceName))
	sb.WriteString("        this.middleware = middleware;\n    }\n\n")
	sb.WriteString("    @Override\n")
	sb.WriteString("    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {\n")
	sb.WriteString("        return middleware.handle(request, response);\n    }\n}\n")
	return sb.String()
}

func (s *SpringStrategy) WebMvcConfigurerSource(pathMap map[string][]string, controllerPkg, middlewarePkg string) string {
	if len(pathMap) == 0 {
		return ""
	}
	labels := make([]string, 0, len(pathMap))
	for l := range pathMap {
		labels = append(labels, l)
	}
	sort.Strings(labels)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", controllerPkg))
	for _, label := range labels {
		sb.WriteString(fmt.Sprintf("import %s.%sInterceptor;\n", middlewarePkg, label))
	}
	sb.WriteString("import org.springframework.beans.factory.annotation.Autowired;\n")
	sb.WriteString("import org.springframework.context.annotation.Configuration;\n")
	sb.WriteString("import org.springframework.web.servlet.config.annotation.InterceptorRegistry;\n")
	sb.WriteString("import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;\n\n")
	sb.WriteString("@Configuration\npublic class VeldWebMvcConfigurer implements WebMvcConfigurer {\n\n")
	for _, label := range labels {
		field := strings.ToLower(label[:1]) + label[1:] + "Interceptor"
		sb.WriteString(fmt.Sprintf("    @Autowired\n    private %sInterceptor %s;\n\n", label, field))
	}
	sb.WriteString("    @Override\n    public void addInterceptors(InterceptorRegistry registry) {\n")
	for _, label := range labels {
		field := strings.ToLower(label[:1]) + label[1:] + "Interceptor"
		paths := pathMap[label]
		quoted := make([]string, len(paths))
		for i, p := range paths {
			quoted[i] = fmt.Sprintf("%q", p)
		}
		sb.WriteString(fmt.Sprintf("        registry.addInterceptor(%s)\n            .addPathPatterns(%s);\n", field, strings.Join(quoted, ", ")))
	}
	sb.WriteString("    }\n}\n")
	return sb.String()
}

func (s *SpringStrategy) AutoConfigSource(basePkg string) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("package %s;\n\n", basePkg))
	sb.WriteString("import org.springframework.context.annotation.ComponentScan;\n")
	sb.WriteString("import org.springframework.context.annotation.Configuration;\n\n")
	sb.WriteString("/**\n * Veld auto-configuration — scans all generated controllers and interceptors.\n")
	sb.WriteString(" * Activated via src/main/resources/META-INF/spring/\n")
	sb.WriteString(" *   org.springframework.boot.autoconfigure.AutoConfiguration.imports\n")
	sb.WriteString(" * If controllers are still not found, add to your main class:\n")
	sb.WriteString(" *   @Import(maayn.veld.generated.VeldAutoConfiguration.class)\n */\n")
	sb.WriteString("@Configuration\n")
	sb.WriteString(fmt.Sprintf("@ComponentScan(%q)\n", basePkg))
	sb.WriteString("public class VeldAutoConfiguration {}\n")
	return sb.String()
}

// BuildFile returns ("", "") — Spring projects own their pom.xml/build.gradle.
// Use `veld setup` to add build-helper-maven-plugin or a Gradle sourceSet pointing
// at generated/src/main/java instead.
func (s *SpringStrategy) BuildFile() (string, string) {
	return "", ""
}

func (s *SpringStrategy) WSControllerMethod(actionName, routePath, emitType, streamType string) string {
	if emitType == "" {
		emitType = "String"
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n    /** WebSocket handler for %s */\n", routePath))
	sb.WriteString(fmt.Sprintf("    @MessageMapping(%q)\n", routePath))
	if streamType != "" {
		sb.WriteString(fmt.Sprintf("    @SendTo(%q)\n", routePath+"/stream"))
	}
	sb.WriteString(fmt.Sprintf("    public void handle%s(@Payload %s msg, SimpMessageHeaderAccessor headerAccessor) {\n", actionName, emitType))
	sb.WriteString(fmt.Sprintf("        // implement: service.on%sMessage(headerAccessor.getSessionId(), msg);\n", actionName))
	sb.WriteString("    }\n")
	return sb.String()
}

const springPomXML = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED BY VELD — DO NOT EDIT -->
<!--
  This is a LIBRARY module, not a standalone Spring Boot application.
  Add it to your parent pom.xml <modules> list, then depend on it from your app:

  <dependency>
    <groupId>maayn.veld</groupId>
    <artifactId>veld-generated</artifactId>
    <version>0.1.0</version>
  </dependency>
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>maayn.veld</groupId>
  <artifactId>veld-generated</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>

  <properties>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <spring-boot.version>3.2.0</spring-boot.version>
  </properties>

  <!-- Import Spring Boot BOM — no <parent> needed -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
  </dependencies>
</project>
`
