// Package dockerfile generates Dockerfiles for each backend language.
package dockerfile

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("dockerfile", New())
}

// DockerfileEmitter generates a Dockerfile tailored to the detected backend.
type DockerfileEmitter struct{}

func New() *DockerfileEmitter         { return &DockerfileEmitter{} }
func (*DockerfileEmitter) IsBackend() {}

func (e *DockerfileEmitter) Summary(_ []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "./", Files: "Dockerfile, .dockerignore"},
	}
}

func (e *DockerfileEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	// Detect backend by checking for known files
	lang := detectBackend(outDir)

	dockerfile := generateDockerfile(lang)
	if err := os.WriteFile(filepath.Join(outDir, "Dockerfile"), []byte(dockerfile), 0644); err != nil {
		return err
	}

	dockerignore := generateDockerignore(lang)
	return os.WriteFile(filepath.Join(outDir, ".dockerignore"), []byte(dockerignore), 0644)
}

func detectBackend(outDir string) string {
	checks := []struct {
		file string
		lang string
	}{
		{"go.mod", "go"},
		{"Cargo.toml", "rust"},
		{"pom.xml", "java"},
		{"VeldGenerated.csproj", "csharp"},
		{"composer.json", "php"},
		{"package.json", "node"},
		{"requirements.txt", "python"},
	}
	for _, c := range checks {
		if _, err := os.Stat(filepath.Join(outDir, c.file)); err == nil {
			return c.lang
		}
	}
	// Check for Python by directory structure
	if _, err := os.Stat(filepath.Join(outDir, "schemas", "schemas.py")); err == nil {
		return "python"
	}
	return "node" // default
}

func generateDockerfile(lang string) string {
	switch lang {
	case "go":
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
# Multi-stage Go build
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 8080
CMD ["./server"]
`
	case "rust":
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
# Multi-stage Rust build
FROM rust:1.76-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release && rm -rf src
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/server .
EXPOSE 8080
CMD ["./server"]
`
	case "java":
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
# Multi-stage Java build
FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY . .
RUN mvn package -DskipTests -B

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
`
	case "csharp":
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
# Multi-stage .NET build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder
WORKDIR /app
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=builder /app/out .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
CMD ["dotnet", "VeldGenerated.dll"]
`
	case "php":
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
FROM php:8.2-fpm-alpine
RUN apk add --no-cache nginx
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
COPY composer.json .
RUN composer install --no-dev --no-scripts --no-autoloader
COPY . .
RUN composer dump-autoload --optimize
EXPOSE 8080
CMD ["php", "-S", "0.0.0.0:8080", "-t", "public"]
`
	case "python":
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt* ./
RUN pip install --no-cache-dir flask pydantic 2>/dev/null || true
RUN [ -f requirements.txt ] && pip install --no-cache-dir -r requirements.txt || true
COPY . .
EXPOSE 8080
ENV FLASK_APP=app.py
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"]
`
	default: // node
		return `# AUTO-GENERATED BY VELD — DO NOT EDIT
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .
EXPOSE 8080
CMD ["node", "index.js"]
`
	}
}

func generateDockerignore(lang string) string {
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(".git\n.gitignore\n*.md\n.env\n.env.*\n")

	switch lang {
	case "go":
		sb.WriteString("vendor/\n*.exe\n")
	case "rust":
		sb.WriteString("target/\n")
	case "java":
		sb.WriteString("target/\n.mvn/\n*.class\n")
	case "csharp":
		sb.WriteString("bin/\nobj/\n")
	case "php":
		sb.WriteString("vendor/\nstorage/\n")
	case "python":
		sb.WriteString("__pycache__/\n*.pyc\nvenv/\n.venv/\n")
	default:
		sb.WriteString("node_modules/\ndist/\n")
	}

	return sb.String()
}
