package swift

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterFrontend("swift", New())
}

// SwiftEmitter generates the frontend Swift SDK (generated/client/APIClient.swift).
type SwiftEmitter struct{}

func (*SwiftEmitter) IsFrontend() {}

// New returns a SwiftEmitter.
func New() *SwiftEmitter { return &SwiftEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *SwiftEmitter) Summary(modules []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "client/", Files: "APIClient.swift"},
	}
}

// Emit writes generated/client/APIClient.swift into outDir.
func (e *SwiftEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	dir := filepath.Join(outDir, "client")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Collect all used types across all modules (deduplicated).
	allTypes := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			allTypes[t] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\nimport Foundation\n\n")

	// VeldApiError
	sb.WriteString("struct VeldApiError: Error {\n    let status: Int\n    let body: String\n}\n\n")

	emitEnums(&sb, a, allTypes)
	emitStructs(&sb, a, allTypes)
	emitApiEnum(&sb, a, opts)

	return os.WriteFile(filepath.Join(dir, "APIClient.swift"), []byte(sb.String()), 0644)
}
