package swift_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/frontend/swift"
	_ "github.com/Adhamzineldin/Veld/internal/emitter/frontend/swift"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:        "Login",
						Description: "Log in with credentials",
						Method:      "POST",
						Path:        "/auth/login",
						Input:       "LoginInput",
						Output:      "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
				},
			},
		},
	}
}

func TestSwiftEmitterEmit(t *testing.T) {
	e := swift.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	path := filepath.Join(outDir, "client", "APIClient.swift")
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Errorf("expected file %s to exist", path)
	}
}

func TestSwiftEmitterDryRun(t *testing.T) {
	e := swift.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestSwiftEmitterContent(t *testing.T) {
	e := swift.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "client", "APIClient.swift"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"Foundation import", "import Foundation"},
		{"VeldApiError", "struct VeldApiError: Error"},
		{"User struct", "struct User: Codable {"},
		{"enum", "enum Role: String, Codable {"},
		{"VeldApi enum", "enum VeldApi {"},
		{"route doc comment", "/// POST /api/auth/login"},
		{"Auth namespace", "enum Auth {"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("APIClient.swift missing %s: want %q", c.desc, c.needle)
		}
	}
}

func TestSwiftEmitterPathParams(t *testing.T) {
	e := swift.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "client", "APIClient.swift"))
	content := string(data)

	if !strings.Contains(content, "id: String") {
		t.Error("path param should generate id: String parameter")
	}
}

func TestSwiftEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetFrontend("swift"); err != nil {
		t.Errorf("swift frontend not registered: %v", err)
	}
}

func TestSwiftEmitterRouteDocComments(t *testing.T) {
	e := swift.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "client", "APIClient.swift"))
	content := string(data)

	if !strings.Contains(content, "/// POST /api/auth/login") {
		t.Error("missing route doc comment for POST /api/auth/login")
	}
	if !strings.Contains(content, "/// GET /api/auth/me") {
		t.Error("missing route doc comment for GET /api/auth/me")
	}
}
