package swift

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterFrontend("swift", New())
}

// SwiftEmitter generates the frontend Swift SDK (generated/client/APIClient.swift).
type SwiftEmitter struct{}

func (*SwiftEmitter) IsFrontend() {}

// New returns a SwiftEmitter.
func New() *SwiftEmitter { return &SwiftEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *SwiftEmitter) Summary(modules []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "client/", Files: "APIClient.swift"},
	}
}

func veldTypeToSwift(t string) string {
	switch t {
	case "int":
		return "Int"
	case "float":
		return "Double"
	case "bool":
		return "Bool"
	case "string", "date", "datetime", "uuid":
		return "String"
	default:
		return t
	}
}

func swiftFieldType(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("[String: %s]", veldTypeToSwift(f.MapValueType))
	}
	base := veldTypeToSwift(f.Type)
	if f.IsArray {
		return fmt.Sprintf("[%s]", base)
	}
	return base
}

// Emit writes generated/client/APIClient.swift into outDir.
func (e *SwiftEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	dir := filepath.Join(outDir, "client")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	allTypes := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			allTypes[t] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\nimport Foundation\n\n")

	// VeldApiError
	sb.WriteString("struct VeldApiError: Error {\n    let status: Int\n    let body: String\n}\n\n")

	// Enums
	for _, en := range a.Enums {
		if !allTypes[en.Name] {
			continue
		}
		sb.WriteString(fmt.Sprintf("enum %s: String, Codable {\n", en.Name))
		for _, v := range en.Values {
			sb.WriteString(fmt.Sprintf("    case %s = \"%s\"\n", v, v))
		}
		sb.WriteString("}\n\n")
	}

	// Codable structs
	modelMap := make(map[string]ast.Model)
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}
	for _, m := range a.Models {
		if !allTypes[m.Name] {
			continue
		}
		allFields := collectAllFields(m, modelMap)
		sb.WriteString(fmt.Sprintf("struct %s: Codable {\n", m.Name))
		for _, f := range allFields {
			ft := swiftFieldType(f)
			if f.Optional {
				sb.WriteString(fmt.Sprintf("    var %s: %s?\n", f.Name, ft))
			} else {
				sb.WriteString(fmt.Sprintf("    var %s: %s\n", f.Name, ft))
			}
		}
		sb.WriteString("}\n\n")
	}

	// VeldApi enum (namespace)
	baseUrlDefault := ""
	if opts.BaseUrl != "" {
		baseUrlDefault = opts.BaseUrl
	}
	sb.WriteString(fmt.Sprintf("enum VeldApi {\n    static var baseURL = \"%s\"\n\n", baseUrlDefault))

	// Private helper
	sb.WriteString(`    private static func request(_ method: String, _ path: String, body: Data? = nil) async throws -> Data {
        guard let url = URL(string: "\(baseURL)\(path)") else {
            throw VeldApiError(status: 0, body: "Invalid URL")
        }
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = body
        let (data, response) = try await URLSession.shared.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse else {
            throw VeldApiError(status: 0, body: "Invalid response")
        }
        if httpResponse.statusCode >= 400 {
            throw VeldApiError(status: httpResponse.statusCode, body: String(data: data, encoding: .utf8) ?? "")
        }
        return data
    }

`)

	// Module enums
	for _, mod := range a.Modules {
		sb.WriteString(fmt.Sprintf("    enum %s {\n", mod.Name))
		for _, act := range mod.Actions {
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			method := strings.ToUpper(act.Method)
			pathParams := emitter.ExtractPathParams(routePath)

			desc := act.Description
			if desc != "" {
				desc = " — " + desc
			}
			if method == "WS" {
				sb.WriteString(fmt.Sprintf("        /// WS %s%s\n", routePath, desc))
			} else {
				sb.WriteString(fmt.Sprintf("        /// %s %s%s\n", method, routePath, desc))
			}

			// Return type
			outputType := "Void"
			if act.Output != "" {
				base := veldTypeToSwift(act.Output)
				if act.OutputArray {
					outputType = fmt.Sprintf("[%s]", base)
				} else {
					outputType = base
				}
			}

			// Params
			var sigParams []string
			for _, p := range pathParams {
				sigParams = append(sigParams, fmt.Sprintf("%s: String", p))
			}
			if act.Input != "" {
				sigParams = append(sigParams, fmt.Sprintf("input: %s", act.Input))
			}
			if act.Query != "" {
				sigParams = append(sigParams, fmt.Sprintf("query: %s? = nil", act.Query))
			}
			sig := strings.Join(sigParams, ", ")

			urlExpr := swiftStringInterpolation(routePath)

			sb.WriteString(fmt.Sprintf("        static func %s(%s) async throws -> %s {\n", lcFirst(act.Name), sig, outputType))

			if method == "WS" {
				sb.WriteString(fmt.Sprintf("            // WebSocket: connect to \\(baseURL)%s\n", urlExpr))
				sb.WriteString("            fatalError(\"WebSocket not yet supported\")\n")
			} else {
				bodyArg := "nil"
				if act.Input != "" {
					bodyArg = "try JSONEncoder().encode(input)"
				}

				sb.WriteString(fmt.Sprintf("            let data = try await request(\"%s\", \"%s\", body: %s)\n", method, urlExpr, bodyArg))

				if act.Output == "" {
					// void return — just discard data
				} else {
					sb.WriteString(fmt.Sprintf("            return try JSONDecoder().decode(%s.self, from: data)\n", outputType))
				}
			}

			sb.WriteString("        }\n\n")
		}
		sb.WriteString("    }\n\n")
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "APIClient.swift"), []byte(sb.String()), 0644)
}

func collectAllFields(m ast.Model, models map[string]ast.Model) []ast.Field {
	if m.Extends == "" {
		return m.Fields
	}
	parent, ok := models[m.Extends]
	if !ok {
		return m.Fields
	}
	parentFields := collectAllFields(parent, models)
	return append(parentFields, m.Fields...)
}

func swiftStringInterpolation(path string) string {
	return emitter.ToTemplateLiteral(path)
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
