package javascript

// errors.go — emits errors/_base.js, errors/{module}.errors.js, errors/index.js
// with base ApiError class, 7 convenience subclasses, type guards, and error handler.
// Plain JavaScript with JSDoc annotations. Matches the TS/Node emitter approach.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// emitAllErrors generates the full errors/ directory in one shot.
// Called once from Emit() — replaces the old per-module emitErrors call.
func (e *JSEmitter) emitAllErrors(a ast.AST, outDir string) error {
	hasAny := false
	for _, mod := range a.Modules {
		if emitter.HasErrors(mod) {
			hasAny = true
			break
		}
	}
	if !hasAny {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	if err := emitJSErrorsBase(dir); err != nil {
		return err
	}
	for _, mod := range a.Modules {
		if err := emitJSModuleErrors(mod, dir); err != nil {
			return fmt.Errorf("errors %s: %w", mod.Name, err)
		}
	}
	return emitJSErrorsBarrel(a, dir)
}

// emitJSErrorsBase writes errors/_base.js with the core ApiError class,
// 7 convenience subclasses, type guard helpers, toErrorResponse(), and
// an Express-compatible error handler middleware.
func emitJSErrorsBase(dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

	// ── Core ApiError class
	sb.WriteString("/**\n")
	sb.WriteString(" * Base typed API error. Every Veld-generated error extends this class.\n")
	sb.WriteString(" * @example throw new ApiError('GET_USER_NOT_FOUND', 404, 'user not found');\n")
	sb.WriteString(" */\n")
	sb.WriteString("class ApiError extends Error {\n")
	sb.WriteString("  /**\n")
	sb.WriteString("   * @param {string} code\n")
	sb.WriteString("   * @param {number} status\n")
	sb.WriteString("   * @param {string} [message]\n")
	sb.WriteString("   */\n")
	sb.WriteString("  constructor(code, status, message) {\n")
	sb.WriteString("    super(message ?? code);\n")
	sb.WriteString("    this.name = 'ApiError';\n")
	sb.WriteString("    /** @type {string} */\n")
	sb.WriteString("    this.code = code;\n")
	sb.WriteString("    /** @type {number} */\n")
	sb.WriteString("    this.status = status;\n")
	sb.WriteString("    /** @type {string} */\n")
	sb.WriteString("    this.timestamp = new Date().toISOString();\n")
	sb.WriteString("  }\n\n")
	sb.WriteString("  /** Serialise to a JSON-safe object. */\n")
	sb.WriteString("  toJSON() {\n")
	sb.WriteString("    return { error: this.message, code: this.code, status: this.status };\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	// ── Type guards
	sb.WriteString("// ── Type Guards ──────────────────────────────────────────────────────\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * Check if an error is an ApiError instance.\n")
	sb.WriteString(" * @param {unknown} err\n")
	sb.WriteString(" * @returns {boolean}\n")
	sb.WriteString(" */\n")
	sb.WriteString("function isApiError(err) {\n")
	sb.WriteString("  return err instanceof ApiError;\n")
	sb.WriteString("}\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * Check if an error matches a specific error code.\n")
	sb.WriteString(" * @param {unknown} err\n")
	sb.WriteString(" * @param {string} code\n")
	sb.WriteString(" * @returns {boolean}\n")
	sb.WriteString(" */\n")
	sb.WriteString("function isErrorCode(err, code) {\n")
	sb.WriteString("  return err instanceof ApiError && err.code === code;\n")
	sb.WriteString("}\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * Check if an error has a specific HTTP status code.\n")
	sb.WriteString(" * @param {unknown} err\n")
	sb.WriteString(" * @param {number} status\n")
	sb.WriteString(" * @returns {boolean}\n")
	sb.WriteString(" */\n")
	sb.WriteString("function isHttpStatus(err, status) {\n")
	sb.WriteString("  return err instanceof ApiError && err.status === status;\n")
	sb.WriteString("}\n\n")

	// ── Convenience error subclasses
	sb.WriteString("// ── Convenience Errors ───────────────────────────────────────────────\n\n")

	type errDef struct {
		name      string
		status    int
		msg       string
		codeConst string
	}
	defs := []errDef{
		{"NotFoundError", 404, "Not Found", "NOT_FOUND"},
		{"BadRequestError", 400, "Bad Request", "BAD_REQUEST"},
		{"UnauthorizedError", 401, "Unauthorized", "UNAUTHORIZED"},
		{"ForbiddenError", 403, "Forbidden", "FORBIDDEN"},
		{"ConflictError", 409, "Conflict", "CONFLICT"},
		{"ValidationError", 422, "Validation Failed", "VALIDATION_FAILED"},
		{"InternalError", 500, "Internal Server Error", "INTERNAL_SERVER_ERROR"},
	}

	for _, d := range defs {
		sb.WriteString(fmt.Sprintf("/** %d %s — throw from service implementations for quick status responses. */\n", d.status, d.msg))
		sb.WriteString(fmt.Sprintf("class %s extends ApiError {\n", d.name))
		sb.WriteString("  /**\n")
		sb.WriteString("   * @param {string} [message]\n")
		sb.WriteString("   * @param {string} [code]\n")
		sb.WriteString("   */\n")
		sb.WriteString(fmt.Sprintf("  constructor(message, code) {\n"))
		sb.WriteString(fmt.Sprintf("    super(code ?? '%s', %d, message ?? '%s');\n", d.codeConst, d.status, d.msg))
		sb.WriteString(fmt.Sprintf("    this.name = '%s';\n", d.name))
		sb.WriteString("  }\n")
		sb.WriteString("}\n\n")
	}

	// ── Error response helper
	sb.WriteString("// ── Error Response Helper ────────────────────────────────────────────\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * Convert any caught error into a consistent { error, code, status } object.\n")
	sb.WriteString(" * @param {unknown} err\n")
	sb.WriteString(" * @returns {{ error: string, code: string, status: number }}\n")
	sb.WriteString(" */\n")
	sb.WriteString("function toErrorResponse(err) {\n")
	sb.WriteString("  if (err instanceof ApiError) {\n")
	sb.WriteString("    return { error: err.message, code: err.code, status: err.status };\n")
	sb.WriteString("  }\n")
	sb.WriteString("  if (err instanceof Error) {\n")
	sb.WriteString("    return { error: err.message, code: 'INTERNAL_ERROR', status: 500 };\n")
	sb.WriteString("  }\n")
	sb.WriteString("  return { error: String(err), code: 'UNKNOWN_ERROR', status: 500 };\n")
	sb.WriteString("}\n\n")

	// ── Error handler middleware
	sb.WriteString("// ── Error Handler ────────────────────────────────────────────────────\n\n")

	sb.WriteString("/**\n")
	sb.WriteString(" * Express-style error-handling middleware.\n")
	sb.WriteString(" * Mount after all routes: `app.use(errorHandler)`\n")
	sb.WriteString(" *\n")
	sb.WriteString(" * @param {unknown} err\n")
	sb.WriteString(" * @param {*} _req\n")
	sb.WriteString(" * @param {*} res\n")
	sb.WriteString(" * @param {*} next\n")
	sb.WriteString(" */\n")
	sb.WriteString("function errorHandler(err, _req, res, next) {\n")
	sb.WriteString("  if (res.headersSent) { next(err); return; }\n")
	sb.WriteString("  const { error, code, status } = toErrorResponse(err);\n")
	sb.WriteString("  res.status(status).json({ error, code });\n")
	sb.WriteString("}\n\n")

	// ── CommonJS exports
	sb.WriteString("module.exports = {\n")
	sb.WriteString("  ApiError,\n")
	sb.WriteString("  isApiError,\n")
	sb.WriteString("  isErrorCode,\n")
	sb.WriteString("  isHttpStatus,\n")
	sb.WriteString("  toErrorResponse,\n")
	sb.WriteString("  errorHandler,\n")
	for _, d := range defs {
		sb.WriteString(fmt.Sprintf("  %s,\n", d.name))
	}
	sb.WriteString("};\n")

	return os.WriteFile(filepath.Join(dir, "_base.js"), []byte(sb.String()), 0644)
}

// emitJSModuleErrors writes errors/{moduleLower}.errors.js with per-action error factories.
func emitJSModuleErrors(mod ast.Module, dir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	moduleLower := strings.ToLower(mod.Name)
	var sb strings.Builder

	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("const { ApiError } = require('./_base');\n\n")

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}

		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf("/** Error factories for %s — each entry also exposes .code/.status for checks. */\n", act.Name))
		sb.WriteString(fmt.Sprintf("const %sErrors = {\n", camelAction))
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ActionErrorStatus(act, errName)
			camelErr := emitter.ToCamelCase(errName)
			sb.WriteString(fmt.Sprintf("  %s: Object.assign(\n", camelErr))
			sb.WriteString(fmt.Sprintf("    /** @param {string} [message] @returns {ApiError} */\n"))
			sb.WriteString(fmt.Sprintf("    (message) => new ApiError('%s', %d, message ?? '%s'),\n", code, status, errName))
			sb.WriteString(fmt.Sprintf("    { code: '%s', status: %d },\n", code, status))
			sb.WriteString("  ),\n")
		}
		sb.WriteString("};\n\n")
	}

	// Aggregate module errors namespace
	sb.WriteString(fmt.Sprintf("const %sErrors = {\n", moduleLower))
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sErrors,\n", camelAction, camelAction))
	}
	sb.WriteString("};\n\n")

	// CommonJS exports
	sb.WriteString("module.exports = { ApiError")
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf(", %sErrors", camelAction))
	}
	sb.WriteString(fmt.Sprintf(", %sErrors };\n", moduleLower))

	return os.WriteFile(filepath.Join(dir, moduleLower+".errors.js"), []byte(sb.String()), 0644)
}

// emitJSErrorsBarrel writes errors/index.js that re-exports everything.
func emitJSErrorsBarrel(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

	sb.WriteString("// Core error class, type guards, convenience errors, and handler\n")
	sb.WriteString("const _base = require('./_base');\n\n")

	// Per-module re-exports
	for _, mod := range a.Modules {
		if !emitter.HasErrors(mod) {
			continue
		}
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf("const %sModule = require('./%s.errors');\n", moduleLower, moduleLower))
	}
	sb.WriteString("\n")

	sb.WriteString("module.exports = {\n")
	sb.WriteString("  // Base\n")
	sb.WriteString("  ..._base,\n")
	for _, mod := range a.Modules {
		if !emitter.HasErrors(mod) {
			continue
		}
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf("  // %s module\n", mod.Name))
		sb.WriteString(fmt.Sprintf("  ...%sModule,\n", moduleLower))
	}
	sb.WriteString("};\n")

	return os.WriteFile(filepath.Join(dir, "index.js"), []byte(sb.String()), 0644)
}

// emitErrors is kept for backward compat — now a no-op since emitAllErrors handles everything.
func (e *JSEmitter) emitErrors(mod ast.Module, outDir string) error {
	return nil
}
