package javascript

// interfaces.go — emits interfaces/I{Module}Service.js with JSDoc-annotated
// callback typedefs for service method signatures.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *JSEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", mod.Description))
	}

	sb.WriteString("/**\n")
	sb.WriteString(fmt.Sprintf(" * @typedef {Object} I%sService\n", mod.Name))

	for _, act := range mod.Actions {
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		// Build param list for the callback type.
		var params []string
		for _, p := range pathParams {
			params = append(params, p+": string")
		}
		if act.Input != "" {
			params = append(params, "input: "+act.Input)
		}
		if act.Query != "" {
			params = append(params, "query: "+act.Query)
		}
		if act.Headers != "" {
			params = append(params, "headers: "+act.Headers)
		}

		outputType := formatOutputTypeJSDoc(act)
		camelName := emitter.ToCamelCase(act.Name)

		if act.Description != "" || act.Deprecated != "" {
			// Emit description inline before the @property.
			if act.Deprecated != "" {
				sb.WriteString(fmt.Sprintf(" * @property {function(%s): Promise<%s>} %s - @deprecated %s",
					strings.Join(params, ", "), outputType, camelName, act.Deprecated))
			} else {
				sb.WriteString(fmt.Sprintf(" * @property {function(%s): Promise<%s>} %s - %s",
					strings.Join(params, ", "), outputType, camelName, act.Description))
			}
		} else {
			sb.WriteString(fmt.Sprintf(" * @property {function(%s): Promise<%s>} %s",
				strings.Join(params, ", "), outputType, camelName))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(" */\n")

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("I%sService.js", mod.Name)), []byte(sb.String()), 0644)
}
