package javascript_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/backend/javascript"
	_ "github.com/Adhamzineldin/Veld/internal/emitter/backend/javascript"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

func TestJSEmitterEmit(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "index.js"),
		filepath.Join(outDir, "package.json"),
		filepath.Join(outDir, "types", "auth.js"),
		filepath.Join(outDir, "types", "index.js"),
		filepath.Join(outDir, "interfaces", "IAuthService.js"),
		filepath.Join(outDir, "routes", "auth.routes.js"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestJSEmitterDryRun(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestJSEmitterTypesContent(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "types", "auth.js"))
	if err != nil {
		t.Fatalf("ReadFile types/auth.js: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"User typedef", "@typedef {Object} User"},
		{"optional field", "[bio]"},
		{"array field", "string[]"},
		{"enum typedef", "@typedef {'admin' | 'user' | 'guest'} Role"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("types/auth.js missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}

	// Must NOT contain TypeScript syntax.
	tsChecks := []string{"export interface", "export type Role ="}
	for _, ts := range tsChecks {
		if strings.Contains(content, ts) {
			t.Errorf("types/auth.js should not contain TypeScript syntax %q", ts)
		}
	}
}

func TestJSEmitterInterfaceContent(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "interfaces", "IAuthService.js"))
	if err != nil {
		t.Fatalf("ReadFile IAuthService.js: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"interface typedef", "@typedef {Object} IAuthService"},
		{"login method", "login"},
		{"me method", "me"},
		{"logout method", "logout"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("IAuthService.js missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestJSEmitterRoutesContent(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "routes", "auth.routes.js"))
	if err != nil {
		t.Fatalf("ReadFile auth.routes.js: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"function declaration", "function authRouter("},
		{"post route", "router.post('/api/auth/login'"},
		{"get route", "router.get('/api/auth/me'"},
		{"delete route", "router.delete('/api/auth/logout'"},
		{"post 201 status", "res.status(201).json(result)"},
		{"delete 204 status", "res.status(204).end()"},
		{"try/catch", "} catch (err) {"},
		{"service call camelCase", "service.login("},
		{"module.exports", "module.exports"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("auth.routes.js missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}

	// Must NOT contain TypeScript syntax.
	if strings.Contains(content, ": any") {
		t.Error("auth.routes.js should not contain TypeScript type annotations")
	}
}

func TestJSEmitterPathParams(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
					{Name: "Delete", Method: "DELETE", Path: "/items/:id"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "routes", "items.routes.js"))
	content := string(data)

	if !strings.Contains(content, "req.params.id") {
		t.Error("path param :id should be extracted via req.params.id")
	}
}

func TestJSEmitterSummary(t *testing.T) {
	e := javascript.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}

	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	for _, want := range []string{"types/", "interfaces/", "routes/"} {
		if !dirs[want] {
			t.Errorf("Summary() missing entry for directory %q", want)
		}
	}
}

func TestJSEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("javascript"); err != nil {
		t.Errorf("javascript backend not registered: %v", err)
	}
}
