package javascript

// routes.go — emits routes/{module}.routes.js with try/catch and
// correct HTTP status codes (201 for POST, 204 for DELETE with no output).
// Plain JavaScript — no type annotations.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *JSEmitter) emitRoutes(a ast.AST, mod ast.Module, outDir string, opts emitter.EmitOptions) error {
	dir := filepath.Join(outDir, "routes")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	funcName := moduleLower + "Router"
	allMiddleware := emitter.CollectModuleMiddleware(mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")

	if emitter.HasErrors(mod) {
		sb.WriteString(fmt.Sprintf("const { ApiError } = require('../errors/%s.errors');\n", moduleLower))
	}

	// When validation is enabled, import the generated zero-dep validators.
	if opts.Validate {
		if imports := buildValidatorImports(mod); len(imports) > 0 {
			sb.WriteString(fmt.Sprintf("const { %s } = require('../_validators');\n", strings.Join(imports, ", ")))
		}
	}

	sb.WriteString("\n")

	// JSDoc for the function signature.
	sb.WriteString("/**\n")
	sb.WriteString(fmt.Sprintf(" * Registers %s module routes.\n", mod.Name))
	sb.WriteString(" * @param {*} router\n")
	sb.WriteString(fmt.Sprintf(" * @param {import('../interfaces/I%sService').I%sService} service\n", mod.Name, mod.Name))
	if len(allMiddleware) > 0 {
		sb.WriteString(" * @param {Object} middleware\n")
	}
	sb.WriteString(" */\n")

	if len(allMiddleware) > 0 {
		sb.WriteString(fmt.Sprintf("function %s(router, service, middleware) {\n", funcName))
	} else {
		sb.WriteString(fmt.Sprintf("function %s(router, service) {\n", funcName))
	}

	for _, act := range mod.Actions {
		writeJSRouteHandler(&sb, mod, act, opts)
	}

	sb.WriteString("}\n\n")
	sb.WriteString(fmt.Sprintf("module.exports = { %s };\n", funcName))

	if err := os.WriteFile(filepath.Join(dir, moduleLower+".routes.js"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	if len(allMiddleware) > 0 {
		return e.emitMiddlewareInterface(mod, allMiddleware, outDir)
	}
	return nil
}

// writeJSRouteHandler appends a single route registration + async handler to sb.
func writeJSRouteHandler(sb *strings.Builder, mod ast.Module, act ast.Action, opts emitter.EmitOptions) {
	method := strings.ToLower(act.Method)
	routePath := act.Path
	if mod.Prefix != "" {
		routePath = mod.Prefix + act.Path
	}
	camelName := emitter.ToCamelCase(act.Name)

	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("\n  // %s\n", act.Description))
	}

	// WebSocket actions: commented stub only.
	if act.Method == "WS" {
		sb.WriteString(fmt.Sprintf("\n  // WebSocket: %s\n", routePath))
		sb.WriteString("  // To handle this route, set up a WebSocket server (e.g. 'ws' package)\n")
		sb.WriteString(fmt.Sprintf("  // and call service.%s(ws", camelName))
		for _, p := range emitter.ExtractPathParams(routePath) {
			sb.WriteString(fmt.Sprintf(", %s", p))
		}
		sb.WriteString(") on connection.\n")
		return
	}

	mwArgs := ""
	for _, mw := range act.Middleware {
		mwArgs += fmt.Sprintf("middleware.%s, ", mw)
	}

	sb.WriteString(fmt.Sprintf("\n  router.%s('%s', %sasync (req, res) => {\n", method, routePath, mwArgs))
	sb.WriteString("    try {\n")

	// Build service call arguments.
	pathParams := emitter.ExtractPathParams(routePath)
	callArgs := make([]string, 0, len(pathParams)+2)
	for _, p := range pathParams {
		callArgs = append(callArgs, fmt.Sprintf("req.params.%s", p))
	}

	if act.Input != "" {
		if opts.Validate {
			sb.WriteString(fmt.Sprintf("      const body = parse%s(req.body);\n", act.Input))
			callArgs = append(callArgs, "body")
		} else {
			callArgs = append(callArgs, "req.body")
		}
	}

	if act.Query != "" {
		callArgs = append(callArgs, "req.query")
	}

	serviceCall := fmt.Sprintf("service.%s(%s)", camelName, strings.Join(callArgs, ", "))

	switch {
	case act.Method == "DELETE" && act.Output == "":
		sb.WriteString(fmt.Sprintf("      await %s;\n", serviceCall))
		sb.WriteString("      res.status(204).end();\n")

	case act.Method == "POST":
		sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
		if opts.Validate && act.Output != "" {
			writeJSOutputAssertion(sb, act)
		}
		sb.WriteString("      res.status(201).json(result);\n")

	default:
		sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
		if opts.Validate && act.Output != "" {
			writeJSOutputAssertion(sb, act)
		}
		sb.WriteString("      res.json(result);\n")
	}

	sb.WriteString("    } catch (err) {\n")
	sb.WriteString("      const status = err.status ?? err.statusCode ?? 500;\n")
	sb.WriteString("      const body = { error: err.message ?? 'Internal Server Error' };\n")
	sb.WriteString("      if (err.code) body.code = err.code;\n")
	sb.WriteString("      res.status(status).json(body);\n")
	sb.WriteString("    }\n")
	sb.WriteString("  });\n")
}

// writeJSOutputAssertion emits assertX(result) or assertXArray(result).
func writeJSOutputAssertion(sb *strings.Builder, act ast.Action) {
	if act.OutputArray {
		sb.WriteString(fmt.Sprintf("      assert%sArray(result);\n", act.Output))
	} else {
		sb.WriteString(fmt.Sprintf("      assert%s(result);\n", act.Output))
	}
}

// emitMiddlewareInterface writes interfaces/I{Module}Middleware.js.
func (e *JSEmitter) emitMiddlewareInterface(mod ast.Module, allMiddleware []string, outDir string) error {
	dir := filepath.Join(outDir, "middleware")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	interfaceName := "I" + mod.Name + "Middleware"
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("/**\n")
	sb.WriteString(fmt.Sprintf(" * Middleware interface for the %s module.\n", mod.Name))
	sb.WriteString(" * Implement this object and pass it to the route registrar.\n")
	sb.WriteString(fmt.Sprintf(" * @typedef {Object} %s\n", interfaceName))
	for _, mw := range allMiddleware {
		camelMw := emitter.ToCamelCase(mw)
		sb.WriteString(fmt.Sprintf(" * @property {function(*, *, function): void} %s - %s middleware handler\n", camelMw, mw))
	}
	sb.WriteString(" */\n\n")
	sb.WriteString(fmt.Sprintf("module.exports = {};\n"))

	return os.WriteFile(filepath.Join(dir, interfaceName+".js"), []byte(sb.String()), 0644)
}
