package javascript

// sdk.go — service SDK generation for plain JavaScript backend.
// Generates fetch-based HTTP client classes (.js, no TypeScript).

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
)

// EmitServiceSdk generates plain JS service SDK clients for each consumed service.
func (e *JSEmitter) EmitServiceSdk(consumed []emitter.ConsumedServiceInfo, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun || len(consumed) == 0 {
		return nil
	}
	for _, c := range consumed {
		if err := emitJsSdk(c, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", c.Name, err)
		}
	}
	return emitJsSdkBarrel(consumed, outDir)
}

func emitJsSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	dir := filepath.Join(outDir, "sdk", name)
	modelsDir := filepath.Join(dir, "models")
	if err := os.MkdirAll(modelsDir, 0755); err != nil {
		return err
	}
	if err := emitJsSdkModels(consumed, modelsDir); err != nil {
		return err
	}
	if err := emitJsSdkClient(consumed, dir); err != nil {
		return err
	}
	if err := emitJsSdkConstants(consumed, dir); err != nil {
		return err
	}
	return emitJsSdkIndex(consumed, dir)
}

func emitJsSdkModels(consumed emitter.ConsumedServiceInfo, modelsDir string) error {
	a := consumed.AST
	modelGroups, enumGroups, _, _ := emitter.AssignModelsToModules(a)
	keys := emitter.SortedGroupKeys(modelGroups, enumGroups)

	for _, group := range keys {
		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString(fmt.Sprintf("// Service SDK models for: %s (%s)\n\n", consumed.Name, group))

		for _, en := range enumGroups[group] {
			sb.WriteString(fmt.Sprintf("/** @typedef {%s} %s */\n\n",
				"'"+strings.Join(en.Values, "' | '")+"'", en.Name))
		}

		for _, m := range modelGroups[group] {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			sb.WriteString(fmt.Sprintf("class %s {\n", m.Name))
			// Constructor
			sb.WriteString("  constructor(data = {}) {\n")
			for _, f := range m.Fields {
				if f.Optional {
					sb.WriteString(fmt.Sprintf("    this.%s = data.%s ?? undefined;\n", f.Name, f.Name))
				} else {
					sb.WriteString(fmt.Sprintf("    this.%s = data.%s ?? %s;\n", f.Name, f.Name, jsDefault(f)))
				}
			}
			sb.WriteString("  }\n")
			// Getters and setters
			for _, f := range m.Fields {
				pascal := strings.ToUpper(f.Name[:1]) + f.Name[1:]
				sb.WriteString(fmt.Sprintf("\n  get%s() { return this.%s; }\n", pascal, f.Name))
				sb.WriteString(fmt.Sprintf("  set%s(value) { this.%s = value; }\n", pascal, f.Name))
			}
			// toJSON + fromJSON
			sb.WriteString("\n  toJSON() { return { ...this }; }\n")
			sb.WriteString(fmt.Sprintf("  static fromJSON(data) { return new %s(data); }\n", m.Name))
			sb.WriteString("}\n\n")
		}

		// Export all classes
		var classNames []string
		for _, m := range modelGroups[group] {
			classNames = append(classNames, m.Name)
		}
		if len(classNames) > 0 {
			sb.WriteString(fmt.Sprintf("module.exports = { %s };\n", strings.Join(classNames, ", ")))
		} else {
			sb.WriteString("module.exports = {};\n")
		}
		if err := os.WriteFile(filepath.Join(modelsDir, group+".js"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel index.js
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	barrel.WriteString(fmt.Sprintf("// Service SDK models barrel for: %s\n\n", consumed.Name))
	for _, group := range keys {
		barrel.WriteString(fmt.Sprintf("Object.assign(module.exports, require('./%s'));\n", group))
	}
	return os.WriteFile(filepath.Join(modelsDir, "index.js"), []byte(barrel.String()), 0644)
}

func jsSortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func jsDocType(f ast.Field) string {
	base := f.Type
	switch f.Type {
	case "string", "uuid", "date", "datetime", "decimal":
		base = "string"
	case "int", "float":
		base = "number"
	case "bool":
		base = "boolean"
	case "any", "json":
		base = "*"
	}
	if f.IsMap {
		val := f.MapValueType
		switch val {
		case "string", "uuid", "date", "datetime", "decimal":
			val = "string"
		case "int", "float":
			val = "number"
		case "bool":
			val = "boolean"
		}
		return fmt.Sprintf("Object.<string, %s>", val)
	}
	if f.IsArray {
		return base + "[]"
	}
	return base
}

func jsDefault(f ast.Field) string {
	if f.Default != "" {
		return jsConvertDefault(f.Default, f.Type)
	}
	if f.IsArray {
		return "[]"
	}
	if f.IsMap {
		return "{}"
	}
	switch f.Type {
	case "string", "date", "datetime", "uuid", "decimal":
		return "''"
	case "int", "float":
		return "0"
	case "bool":
		return "false"
	default:
		return "undefined"
	}
}

func emitJsSdkClient(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)

	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("class VeldApiError extends Error {\n  constructor(status, body) {\n    super(`HTTP ${status}: ${body}`);\n    this.name = 'VeldApiError';\n    this.status = status;\n    this.body = body;\n  }\n}\n\n")

	sb.WriteString(fmt.Sprintf("class %s {\n", className))
	sb.WriteString("  constructor(baseUrl, headers) {\n")
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("    this.base = baseUrl || process.env.%s || '%s';\n", envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("    const resolved = baseUrl || process.env.%s;\n", envVar))
		sb.WriteString(fmt.Sprintf("    if (!resolved) throw new Error('No base URL for %s — pass baseUrl or set %s');\n", consumed.Name, envVar))
		sb.WriteString("    this.base = resolved;\n")
	}
	sb.WriteString("    this.hdrs = headers || {};\n  }\n\n")

	sb.WriteString("  async _request(method, path, body) {\n")
	sb.WriteString("    const res = await fetch(this.base + path, {\n      method,\n      headers: { 'Content-Type': 'application/json', ...this.hdrs },\n")
	sb.WriteString("      body: body !== undefined ? JSON.stringify(body) : undefined,\n    });\n")
	sb.WriteString("    if (!res.ok) throw new VeldApiError(res.status, await res.text());\n")
	sb.WriteString("    if (res.status === 204) return undefined;\n    return res.json();\n  }\n")

	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				continue
			}
			sb.WriteString("\n")
			writeJsSdkMethod(&sb, mod, act)
		}
	}
	sb.WriteString("}\n\n")
	sb.WriteString(fmt.Sprintf("module.exports = { %s, VeldApiError };\n", className))

	return os.WriteFile(filepath.Join(dir, "client.js"), []byte(sb.String()), 0644)
}

func writeJsSdkMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	camelName := emitter.ToCamelCase(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	var urlExpr string
	if len(pathParams) > 0 {
		urlExpr = "`" + emitter.ToTemplateLiteral(routePath) + "`"
	} else {
		urlExpr = "'" + routePath + "'"
	}

	var sigParams []string
	for _, p := range pathParams {
		sigParams = append(sigParams, p)
	}
	if act.Input != "" {
		sigParams = append(sigParams, "input")
	}

	sb.WriteString(fmt.Sprintf("  /** %s %s */\n", method, routePath))
	sb.WriteString(fmt.Sprintf("  async %s(%s) {\n", camelName, strings.Join(sigParams, ", ")))
	if method == "GET" || act.Input == "" {
		sb.WriteString(fmt.Sprintf("    return this._request('%s', %s);\n  }\n", method, urlExpr))
	} else {
		sb.WriteString(fmt.Sprintf("    return this._request('%s', %s, input);\n  }\n", method, urlExpr))
	}
}

// emitJsSdkConstants writes constants from the consumed service into sdk/<name>/constants/.
func emitJsSdkConstants(consumed emitter.ConsumedServiceInfo, dir string) error {
	if len(consumed.AST.Constants) == 0 {
		return nil
	}
	constDir := filepath.Join(dir, "constants")
	if err := os.MkdirAll(constDir, 0755); err != nil {
		return err
	}
	var barrelExports []string
	for _, cg := range consumed.AST.Constants {
		fileName := emitter.ToSnakeCase(cg.Name)
		barrelExports = append(barrelExports, fileName)
		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", cg.Description))
		}
		for _, f := range cg.Fields {
			val := jsSdkConstValue(f)
			sb.WriteString(fmt.Sprintf("module.exports.%s = %s;\n", f.Name, val))
		}
		if err := os.WriteFile(filepath.Join(constDir, fileName+".js"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	for _, name := range barrelExports {
		barrel.WriteString(fmt.Sprintf("Object.assign(module.exports, require('./%s'));\n", name))
	}
	return os.WriteFile(filepath.Join(constDir, "index.js"), []byte(barrel.String()), 0644)
}

func jsSdkConstValue(f ast.ConstantField) string {
	switch f.Type {
	case "string", "uuid", "date", "datetime", "decimal":
		return fmt.Sprintf("%q", f.Value)
	case "int", "float":
		return f.Value
	case "bool":
		return f.Value
	default:
		return fmt.Sprintf("%q", f.Value)
	}
}

func emitJsSdkIndex(consumed emitter.ConsumedServiceInfo, dir string) error {
	className := sdkhelpers.ServiceClassName(consumed.Name)
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("const { %s, VeldApiError } = require('./client');\n", className))
	sb.WriteString("// Models are documented in ./models/index.js (JSDoc typedefs)\n")
	sb.WriteString(fmt.Sprintf("module.exports = { %s, VeldApiError };\n", className))
	if len(consumed.AST.Constants) > 0 {
		sb.WriteString("Object.assign(module.exports, require('./constants'));\n")
	}
	return os.WriteFile(filepath.Join(dir, "index.js"), []byte(sb.String()), 0644)
}

func emitJsSdkBarrel(consumed []emitter.ConsumedServiceInfo, outDir string) error {
	dir := filepath.Join(outDir, "sdk")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	for _, c := range consumed {
		name := sdkhelpers.ServiceFileName(c.Name)
		className := sdkhelpers.ServiceClassName(c.Name)
		sb.WriteString(fmt.Sprintf("const { %s } = require('./%s');\n", className, name))
	}
	sb.WriteString("\nmodule.exports = {\n")
	for _, c := range consumed {
		sb.WriteString(fmt.Sprintf("  %s,\n", sdkhelpers.ServiceClassName(c.Name)))
	}
	sb.WriteString("};\n")
	return os.WriteFile(filepath.Join(dir, "index.js"), []byte(sb.String()), 0644)
}
