package javascript

// types.go — emits types/{module}.js + types/index.js barrel.
//
// Types are emitted as JSDoc @typedef blocks. Each type is "owned" by the
// first module that references it. Later modules re-export it.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *JSEmitter) emitPerModuleTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// claimed tracks which module file "owns" each type definition.
	claimed := make(map[string]string) // typeName → moduleLowerName

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceFile → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

		// Re-exports from other module type files.
		for source, names := range reExports {
			for _, name := range names {
				sb.WriteString(fmt.Sprintf("/**\n * Re-exported from ./%s.js\n * @typedef {import('./%s').%s} %s\n */\n\n", source, source, name, name))
			}
		}

		// Owned enums as JSDoc string union typedefs.
		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("'%s'", v)
			}
			sb.WriteString(fmt.Sprintf("/** @typedef {%s} %s */\n\n", strings.Join(quoted, " | "), en.Name))
		}

		// Owned models as JSDoc @typedef blocks.
		for _, m := range ownedModels {
			if m.Extends != "" {
				// Extends: intersection type with parent.
				if m.Description != "" {
					sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
				}
				if len(m.Fields) == 0 {
					sb.WriteString(fmt.Sprintf("/** @typedef {%s} %s */\n\n", m.Extends, m.Name))
				} else {
					sb.WriteString(fmt.Sprintf("/**\n * @typedef {%s & {", m.Extends))
					for _, f := range m.Fields {
						opt := ""
						if f.Optional {
							opt = "="
						}
						sb.WriteString(fmt.Sprintf("\n *   %s%s: %s,", f.Name, opt, veldFieldToJSDoc(f)))
					}
					sb.WriteString(fmt.Sprintf("\n * }} %s\n */\n\n", m.Name))
				}
			} else {
				sb.WriteString("/**\n")
				if m.Description != "" {
					sb.WriteString(fmt.Sprintf(" * %s\n", m.Description))
				}
				sb.WriteString(fmt.Sprintf(" * @typedef {Object} %s\n", m.Name))
				for _, f := range m.Fields {
					if f.Deprecated != "" {
						sb.WriteString(fmt.Sprintf(" * @property {%s} %s - @deprecated %s\n", veldFieldToJSDoc(f), propName(f), f.Deprecated))
					} else {
						sb.WriteString(fmt.Sprintf(" * @property {%s} %s\n", veldFieldToJSDoc(f), propName(f)))
					}
				}
				sb.WriteString(" */\n\n")
			}
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".js"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: types/index.js re-exports everything from all module files.
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	barrel.WriteString("// This file re-exports all types for convenience.\n")
	barrel.WriteString("// Types are defined as JSDoc @typedef in per-module files.\n\n")
	for _, mod := range a.Modules {
		barrel.WriteString(fmt.Sprintf("/** @typedef {import('./%s')} */\n", strings.ToLower(mod.Name)))
	}
	return os.WriteFile(filepath.Join(dir, "index.js"), []byte(barrel.String()), 0644)
}

// propName formats a field name for JSDoc @property, wrapping optional fields in [].
func propName(f ast.Field) string {
	if f.Optional {
		return "[" + f.Name + "]"
	}
	return f.Name
}
