package javascript

// types.go — emits types/{module}.js + types/index.js barrel.
//
// Types are emitted as JSDoc @typedef blocks. Each type is "owned" by the
// first module that references it. Later modules re-export it.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *JSEmitter) emitPerModuleTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// claimed tracks which module file "owns" each type definition.
	claimed := make(map[string]string) // typeName → moduleLowerName

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceFile → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

		// Re-exports from other module type files.
		for source, names := range reExports {
			for _, name := range names {
				sb.WriteString(fmt.Sprintf("/**\n * Re-exported from ./%s.js\n * @typedef {import('./%s').%s} %s\n */\n\n", source, source, name, name))
			}
		}

		// Owned enums as JSDoc string union typedefs.
		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("'%s'", v)
			}
			sb.WriteString(fmt.Sprintf("/** @typedef {%s} %s */\n\n", strings.Join(quoted, " | "), en.Name))
		}

		// Owned models as JS classes.
		for _, m := range ownedModels {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("class %s extends %s {\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("class %s {\n", m.Name))
			}
			// Constructor
			sb.WriteString("  constructor(data = {}) {\n")
			if m.Extends != "" {
				sb.WriteString("    super(data);\n")
			}
			for _, f := range m.Fields {
				if f.Optional {
					sb.WriteString(fmt.Sprintf("    this.%s = data.%s ?? undefined;\n", f.Name, f.Name))
				} else {
					sb.WriteString(fmt.Sprintf("    this.%s = data.%s ?? %s;\n", f.Name, f.Name, jsDefaultVal(f)))
				}
			}
			sb.WriteString("  }\n")
			// Getters and setters
			for _, f := range m.Fields {
				pascal := strings.ToUpper(f.Name[:1]) + f.Name[1:]
				sb.WriteString(fmt.Sprintf("\n  get%s() { return this.%s; }\n", pascal, f.Name))
				sb.WriteString(fmt.Sprintf("  set%s(value) { this.%s = value; }\n", pascal, f.Name))
			}
			sb.WriteString("\n  toJSON() { return { ...this }; }\n")
			sb.WriteString(fmt.Sprintf("  static fromJSON(data) { return new %s(data); }\n", m.Name))
			sb.WriteString("}\n\n")
		}

		// Export all classes in this module
		var classNames []string
		for _, m := range ownedModels {
			classNames = append(classNames, m.Name)
		}
		if len(classNames) > 0 {
			sb.WriteString(fmt.Sprintf("module.exports = { %s };\n", strings.Join(classNames, ", ")))
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".js"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Emit unclaimed models/enums (e.g. from shared imports or no-module contracts)
	// into types/common.js — mirrors what tsshared does for common.ts.
	var unclaimedEnums []ast.Enum
	var unclaimedModels []ast.Model
	for _, en := range a.Enums {
		if _, taken := claimed[en.Name]; !taken {
			unclaimedEnums = append(unclaimedEnums, en)
		}
	}
	for _, m := range a.Models {
		if _, taken := claimed[m.Name]; !taken {
			unclaimedModels = append(unclaimedModels, m)
		}
	}
	hasCommon := len(unclaimedEnums) > 0 || len(unclaimedModels) > 0
	if hasCommon {
		var csb strings.Builder
		csb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

		for _, en := range unclaimedEnums {
			if en.Description != "" {
				csb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("'%s'", v)
			}
			csb.WriteString(fmt.Sprintf("/** @typedef {%s} %s */\n\n", strings.Join(quoted, " | "), en.Name))
		}

		for _, m := range unclaimedModels {
			if m.Description != "" {
				csb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			if m.Extends != "" {
				csb.WriteString(fmt.Sprintf("class %s extends %s {\n", m.Name, m.Extends))
			} else {
				csb.WriteString(fmt.Sprintf("class %s {\n", m.Name))
			}
			csb.WriteString("  constructor(data = {}) {\n")
			if m.Extends != "" {
				csb.WriteString("    super(data);\n")
			}
			for _, f := range m.Fields {
				if f.Optional {
					csb.WriteString(fmt.Sprintf("    this.%s = data.%s ?? undefined;\n", f.Name, f.Name))
				} else {
					csb.WriteString(fmt.Sprintf("    this.%s = data.%s ?? %s;\n", f.Name, f.Name, jsDefaultVal(f)))
				}
			}
			csb.WriteString("  }\n")
			for _, f := range m.Fields {
				pascal := strings.ToUpper(f.Name[:1]) + f.Name[1:]
				csb.WriteString(fmt.Sprintf("\n  get%s() { return this.%s; }\n", pascal, f.Name))
				csb.WriteString(fmt.Sprintf("  set%s(value) { this.%s = value; }\n", pascal, f.Name))
			}
			csb.WriteString("\n  toJSON() { return { ...this }; }\n")
			csb.WriteString(fmt.Sprintf("  static fromJSON(data) { return new %s(data); }\n", m.Name))
			csb.WriteString("}\n\n")
		}

		// Export all unclaimed classes.
		var commonClassNames []string
		for _, m := range unclaimedModels {
			commonClassNames = append(commonClassNames, m.Name)
		}
		if len(commonClassNames) > 0 {
			csb.WriteString(fmt.Sprintf("module.exports = { %s };\n", strings.Join(commonClassNames, ", ")))
		}

		if err := os.WriteFile(filepath.Join(dir, "common.js"), []byte(csb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: types/index.js re-exports everything from all module files.
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	barrel.WriteString("// This file re-exports all types for convenience.\n")
	barrel.WriteString("// Types are defined as JSDoc @typedef in per-module files.\n\n")
	for _, mod := range a.Modules {
		barrel.WriteString(fmt.Sprintf("/** @typedef {import('./%s')} */\n", strings.ToLower(mod.Name)))
	}
	if hasCommon {
		barrel.WriteString("/** @typedef {import('./common')} */\n")
	}
	return os.WriteFile(filepath.Join(dir, "index.js"), []byte(barrel.String()), 0644)
}

// propName formats a field name for JSDoc @property, wrapping optional fields in [].
func propName(f ast.Field) string {
	if f.Optional {
		return "[" + f.Name + "]"
	}
	return f.Name
}

// jsDefaultVal returns the JavaScript default value for a field.
// If the field has an explicit default (via = value or @default), it is used;
// otherwise a type-based zero value is returned.
func jsDefaultVal(f ast.Field) string {
	if f.Default != "" {
		return jsConvertDefault(f.Default, f.Type)
	}
	if f.IsArray {
		return "[]"
	}
	if f.IsMap {
		return "{}"
	}
	switch f.Type {
	case "string", "date", "datetime", "uuid", "decimal":
		return "''"
	case "int", "float":
		return "0"
	case "bool":
		return "false"
	default:
		return "undefined"
	}
}

// jsConvertDefault converts a Veld default value to a JavaScript literal.
func jsConvertDefault(val, veldType string) string {
	// Already a quoted string → JS single-quote string
	if strings.HasPrefix(val, "\"") && strings.HasSuffix(val, "\"") {
		inner := val[1 : len(val)-1]
		return "'" + inner + "'"
	}
	// Booleans
	if val == "true" || val == "false" {
		return val
	}
	// Numeric — pass through
	if veldType == "int" || veldType == "float" || veldType == "decimal" {
		return val
	}
	// Enum value or identifier — emit as string
	return "'" + val + "'"
}
