package strategy

import (
	"fmt"
	"strings"
)

// AspNetStrategy generates ASP.NET Core controller code.
// It produces [ApiController] / [HttpGet] / [HttpPost] style attributes,
// IActionResult return types, and an ASP.NET Web SDK .csproj.
type AspNetStrategy struct{}

func (s *AspNetStrategy) ControllerBaseClass() string { return "ControllerBase" }

func (s *AspNetStrategy) ControllerAnnotations() []string {
	return []string{"[ApiController]"}
}

func (s *AspNetStrategy) RouteAnnotation(method, path string) string {
	aspPath := toAspNetPath(path) // :id → {id}
	route := fmt.Sprintf("(\"%s\")", aspPath)
	switch strings.ToUpper(method) {
	case "GET":
		return "[HttpGet" + route + "]"
	case "POST":
		return "[HttpPost" + route + "]"
	case "PUT":
		return "[HttpPut" + route + "]"
	case "DELETE":
		return "[HttpDelete" + route + "]"
	case "PATCH":
		return "[HttpPatch" + route + "]"
	default:
		return fmt.Sprintf("[HttpGet(\"%s\")] // TODO: unsupported method %s", aspPath, method)
	}
}

func (s *AspNetStrategy) InputParamAnnotation() string        { return "[FromBody] " }
func (s *AspNetStrategy) PathParamAnnotation(_ string) string { return "[FromRoute] " }
func (s *AspNetStrategy) ResponseWrapper() string             { return "IActionResult" }

func (s *AspNetStrategy) OkResponse(expr string) string {
	return fmt.Sprintf("return Ok(%s);", expr)
}

func (s *AspNetStrategy) CreatedResponse(expr string) string {
	return fmt.Sprintf("return StatusCode(201, %s);", expr)
}

func (s *AspNetStrategy) NoContentResponse() string { return "return NoContent();" }

func (s *AspNetStrategy) ErrorResponse(errVar string) string {
	return fmt.Sprintf("return StatusCode(500, new { error = %s.Message });", errVar)
}

func (s *AspNetStrategy) ControllerUsings() []string {
	return []string{
		"using Microsoft.AspNetCore.Mvc;",
		"using System.Collections.Generic;",
	}
}

func (s *AspNetStrategy) ProjectFileContent() string { return aspNetCsproj }

const aspNetCsproj = `<!-- AUTO-GENERATED BY VELD — DO NOT EDIT -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>VeldGenerated</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <!-- Match implicit usings from Sdk.Web so generated middleware/controllers compile -->
  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
`

func (s *AspNetStrategy) WSActionMethod(actionName, routePath, emitType, streamType string) string {
	aspPath := toAspNetPath(routePath)
	if emitType == "" {
		emitType = "string"
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n    // WebSocket endpoint — add to Program.cs:\n"))
	sb.WriteString(fmt.Sprintf("    // app.MapGet(\"%s\", async (HttpContext context, I%sService service) => {\n", aspPath, "Module"))
	sb.WriteString("    //     if (context.WebSockets.IsWebSocketRequest) {\n")
	sb.WriteString("    //         var ws = await context.WebSockets.AcceptWebSocketAsync();\n")
	sb.WriteString(fmt.Sprintf("    //         await service.On%sConnect(ws);\n", actionName))
	sb.WriteString("    //     }\n")
	sb.WriteString("    // });\n")
	return sb.String()
}

// toAspNetPath converts Veld/Express :param syntax to ASP.NET Core {param} syntax.
func toAspNetPath(path string) string {
	parts := strings.Split(path, "/")
	for i, p := range parts {
		if strings.HasPrefix(p, ":") {
			parts[i] = "{" + p[1:] + "}"
		}
	}
	return strings.Join(parts, "/")
}
