package strategy

import "fmt"

// PlainStrategy generates C# interfaces only — no ASP.NET Core dependency.
// Users implement the generated interfaces and wire them into any HTTP layer of their choice.
type PlainStrategy struct{}

func (s *PlainStrategy) ControllerBaseClass() string     { return "" }
func (s *PlainStrategy) ControllerAnnotations() []string { return nil }

func (s *PlainStrategy) RouteAnnotation(method, path string) string {
	return fmt.Sprintf("// %s %s", method, path)
}

func (s *PlainStrategy) InputParamAnnotation() string        { return "" }
func (s *PlainStrategy) PathParamAnnotation(_ string) string { return "" }
func (s *PlainStrategy) ResponseWrapper() string             { return "object" }

func (s *PlainStrategy) OkResponse(expr string) string {
	return fmt.Sprintf("return %s;", expr)
}

func (s *PlainStrategy) CreatedResponse(expr string) string {
	return fmt.Sprintf("return %s; // 201", expr)
}

func (s *PlainStrategy) NoContentResponse() string { return "return; // 204" }

func (s *PlainStrategy) ErrorResponse(errVar string) string {
	return fmt.Sprintf("throw new Exception(%s.Message);", errVar)
}

func (s *PlainStrategy) ControllerUsings() []string { return nil }

func (s *PlainStrategy) ProjectFileContent() string { return plainCsproj }

func (s *PlainStrategy) WSActionMethod(actionName, routePath, emitType, streamType string) string {
	if emitType == "" {
		emitType = "string"
	}
	return fmt.Sprintf("\n    // WebSocket: WS %s\n    // Implement: On%sConnect(WebSocket socket, params)\n    // Implement: On%sMessage(WebSocket socket, %s msg)\n    // Implement: On%sClose(WebSocket socket)\n",
		routePath, actionName, actionName, emitType, actionName)
}

const plainCsproj = `<Project Sdk="Microsoft.NET.Sdk">
  <!-- AUTO-GENERATED BY VELD — DO NOT EDIT -->
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
`
