package typescript

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func testAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{Name: "User", Fields: []ast.Field{
				{Name: "id", Type: "uuid"},
				{Name: "email", Type: "string"},
				{Name: "name", Type: "string"},
			}},
			{Name: "CreateUserInput", Fields: []ast.Field{
				{Name: "email", Type: "string"},
				{Name: "name", Type: "string"},
			}},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user"}},
		},
		Modules: []ast.Module{{
			Name:   "Users",
			Prefix: "/api",
			Actions: []ast.Action{
				{Name: "List", Method: "GET", Path: "/users", Output: "User", OutputArray: true, Middleware: []string{}},
				{Name: "Get", Method: "GET", Path: "/users/:id", Output: "User", Middleware: []string{}},
				{Name: "Create", Method: "POST", Path: "/users", Input: "CreateUserInput", Output: "User", Middleware: []string{}},
				{Name: "Delete", Method: "DELETE", Path: "/users/:id", Middleware: []string{}},
			},
		}},
	}
}

func TestSummary(t *testing.T) {
	e := New()
	lines := e.Summary([]string{"Users", "Auth"})
	if len(lines) != 1 {
		t.Fatalf("expected 1 summary line, got %d", len(lines))
	}
	if lines[0].Dir != "client/" {
		t.Errorf("expected dir 'client/', got %q", lines[0].Dir)
	}
	if !strings.Contains(lines[0].Files, "usersApi.ts") {
		t.Error("summary should include usersApi.ts")
	}
	if !strings.Contains(lines[0].Files, "authApi.ts") {
		t.Error("summary should include authApi.ts")
	}
}

func TestEmitDryRun(t *testing.T) {
	e := New()
	err := e.Emit(testAST(), t.TempDir(), emitter.EmitOptions{DryRun: true})
	if err != nil {
		t.Fatalf("dry run should not error: %v", err)
	}
}

func TestEmitCreatesClientDir(t *testing.T) {
	dir := t.TempDir()

	// Create required sibling directories that the emitter expects
	os.MkdirAll(filepath.Join(dir, "types"), 0755)
	os.MkdirAll(filepath.Join(dir, "errors"), 0755)

	e := New()
	err := e.Emit(testAST(), dir, emitter.EmitOptions{})
	if err != nil {
		t.Fatalf("emit error: %v", err)
	}

	clientDir := filepath.Join(dir, "client")
	if _, err := os.Stat(clientDir); os.IsNotExist(err) {
		t.Fatal("client/ directory should be created")
	}
}

func TestEmitGeneratesExpectedFiles(t *testing.T) {
	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, "types"), 0755)
	os.MkdirAll(filepath.Join(dir, "errors"), 0755)

	e := New()
	if err := e.Emit(testAST(), dir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("emit error: %v", err)
	}

	expectedFiles := []string{
		"client/_internal.ts",
		"client/api.ts",
		"client/types.ts",
		"client/errors.ts",
		"client/package.json",
		"client/usersApi.ts",
	}

	for _, f := range expectedFiles {
		path := filepath.Join(dir, f)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestEmitInternalContainsVeldApiError(t *testing.T) {
	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, "types"), 0755)
	os.MkdirAll(filepath.Join(dir, "errors"), 0755)

	e := New()
	if err := e.Emit(testAST(), dir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("emit error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "client", "_internal.ts"))
	if err != nil {
		t.Fatalf("read error: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "VeldApiError") {
		t.Error("_internal.ts should contain VeldApiError class")
	}
	if !strings.Contains(content, "AUTO-GENERATED BY VELD") {
		t.Error("should contain auto-generated header")
	}
}

func TestEmitModuleApiContainsTypedMethods(t *testing.T) {
	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, "types"), 0755)
	os.MkdirAll(filepath.Join(dir, "errors"), 0755)

	e := New()
	if err := e.Emit(testAST(), dir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("emit error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "client", "usersApi.ts"))
	if err != nil {
		t.Fatalf("read error: %v", err)
	}
	content := string(data)

	// Should contain typed API methods
	if !strings.Contains(content, "list") {
		t.Error("usersApi.ts should contain list method")
	}
}
