// Package svelte generates Svelte 5 runes-based stores wrapping the TypeScript API client.
package svelte

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	tsEmitter "github.com/Adhamzineldin/Veld/internal/emitter/frontend/typescript"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterFrontend("svelte", New())
}

type SvelteEmitter struct{}

func New() *SvelteEmitter          { return &SvelteEmitter{} }
func (*SvelteEmitter) IsFrontend() {}

func (e *SvelteEmitter) Summary(modules []string) []emitter.SummaryLine {
	lines := []emitter.SummaryLine{
		{Dir: "client/", Files: "api.ts"},
	}
	files := make([]string, len(modules))
	for i, m := range modules {
		files[i] = strings.ToLower(m) + ".store.ts"
	}
	lines = append(lines, emitter.SummaryLine{Dir: "stores/", Files: strings.Join(files, ", ")})
	lines = append(lines, emitter.SummaryLine{Dir: "stores/", Files: "index.ts"})
	return lines
}

func (e *SvelteEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	// Base TS client
	tsE := tsEmitter.New()
	if err := tsE.Emit(a, outDir, opts); err != nil {
		return fmt.Errorf("typescript base: %w", err)
	}

	storesDir := filepath.Join(outDir, "stores")
	if err := os.MkdirAll(storesDir, 0755); err != nil {
		return err
	}

	var barrelExports []string
	for _, mod := range a.Modules {
		if err := e.emitStore(a, mod, storesDir); err != nil {
			return fmt.Errorf("store %s: %w", mod.Name, err)
		}
		barrelExports = append(barrelExports, fmt.Sprintf("export * from './%s.store';", strings.ToLower(mod.Name)))
	}

	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, exp := range barrelExports {
		barrel.WriteString(exp + "\n")
	}
	return os.WriteFile(filepath.Join(storesDir, "index.ts"), []byte(barrel.String()), 0644)
}

func (e *SvelteEmitter) emitStore(a ast.AST, mod ast.Module, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import { writable, derived, type Writable } from 'svelte/store';\n")
	sb.WriteString("import { api } from '../client/api';\n")

	usedTypes := emitter.CollectUsedTypes(a, mod)
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types';\n", strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	// Create store factory function
	storeName := "create" + mod.Name + "Store"
	sb.WriteString(fmt.Sprintf("export function %s() {\n", storeName))
	sb.WriteString("  const loading = writable(false);\n")
	sb.WriteString("  const error: Writable<Error | null> = writable(null);\n\n")

	for _, act := range mod.Actions {
		outputType := tshelpers.FormatOutputType(act)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		var params []string
		var args []string
		for _, p := range pathParams {
			params = append(params, p+": string")
			args = append(args, p)
		}
		if act.Input != "" {
			params = append(params, "input: "+act.Input)
			args = append(args, "input")
		}
		if act.Query != "" {
			params = append(params, "query?: "+act.Query)
			args = append(args, "query")
		}

		paramsStr := strings.Join(params, ", ")
		argsStr := strings.Join(args, ", ")

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("  /** %s */\n", act.Description))
		}
		sb.WriteString(fmt.Sprintf("  async function %s(%s): Promise<%s | undefined> {\n", act.Name, paramsStr, outputType))
		sb.WriteString("    loading.set(true);\n")
		sb.WriteString("    error.set(null);\n")
		sb.WriteString("    try {\n")
		sb.WriteString(fmt.Sprintf("      const result = await api.%s.%s(%s);\n", mod.Name, act.Name, argsStr))
		sb.WriteString("      return result;\n")
		sb.WriteString("    } catch (e) {\n")
		sb.WriteString("      error.set(e instanceof Error ? e : new Error(String(e)));\n")
		sb.WriteString("      return undefined;\n")
		sb.WriteString("    } finally {\n")
		sb.WriteString("      loading.set(false);\n")
		sb.WriteString("    }\n")
		sb.WriteString("  }\n\n")
	}

	sb.WriteString("  return {\n")
	sb.WriteString("    loading: { subscribe: loading.subscribe },\n")
	sb.WriteString("    error: { subscribe: error.subscribe },\n")
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("    %s,\n", act.Name))
	}
	sb.WriteString("  };\n")
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, strings.ToLower(mod.Name)+".store.ts"), []byte(sb.String()), 0644)
}
