package strategy

import (
	"fmt"
	"strings"
)

// AxumStrategy generates Axum 0.7 HTTP handler code.
// It produces Router::new() setups, axum extractors (Json, Path, State),
// and a Tokio main entry point.
type AxumStrategy struct{}

func (s *AxumStrategy) HandlerImports() []string {
	return []string{
		"axum::{",
		"    extract::{Json, Path, State},",
		"    http::StatusCode,",
		"    response::IntoResponse,",
		"    routing::{delete, get, patch, post, put},",
		"    Router,",
		"};",
		"use std::sync::Arc;",
	}
}

func (s *AxumStrategy) RouterImports() []string {
	return []string{
		"axum::Router",
	}
}

func (s *AxumStrategy) WrapHandler(method, returnType, serviceCall string) string {
	if returnType == "" {
		switch strings.ToUpper(method) {
		case "DELETE":
			return fmt.Sprintf("%s\nOk(StatusCode::NO_CONTENT)", serviceCall)
		default:
			return fmt.Sprintf("%s\nOk(StatusCode::OK)", serviceCall)
		}
	}
	statusCode := "StatusCode::OK"
	if strings.ToUpper(method) == "POST" {
		statusCode = "StatusCode::CREATED"
	}
	return fmt.Sprintf("let result = %s?;\nOk((%s, Json(result)))", serviceCall, statusCode)
}

func (s *AxumStrategy) BuildRouter(routes []RouteEntry) string {
	if len(routes) == 0 {
		return "Router::new()"
	}
	var sb strings.Builder
	sb.WriteString("Router::new()")
	for _, r := range routes {
		sb.WriteString(fmt.Sprintf("\n    .route(%q, %s(%s))", r.Path, axumMethodFn(r.Method), r.Handler))
	}
	return sb.String()
}

func (s *AxumStrategy) CargoTomlDependencies() []string {
	return []string{
		`axum = "0.7"`,
		`tokio = { version = "1", features = ["full"] }`,
		`serde = { version = "1", features = ["derive"] }`,
		`serde_json = "1"`,
		`async-trait = "0.1"`,
	}
}

func (s *AxumStrategy) MainRsContent() string {
	return `// AUTO-GENERATED BY VELD — DO NOT EDIT
use std::net::SocketAddr;

mod models;
mod services;
mod router;

#[tokio::main]
async fn main() {
    // TODO: initialise your service implementations and pass them to build_router().
    let app = router::build_router();

    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("Listening on {}", addr);

    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
`
}

// axumMethodFn maps an HTTP method string to the Axum routing function name.
func axumMethodFn(method string) string {
	switch strings.ToUpper(method) {
	case "GET":
		return "get"
	case "POST":
		return "post"
	case "PUT":
		return "put"
	case "DELETE":
		return "delete"
	case "PATCH":
		return "patch"
	default:
		return "get"
	}
}
