package strategy

import (
	"fmt"
	"strings"
)

// AxumStrategy generates Axum 0.7 HTTP handler code.
// It produces Router::new() setups, axum extractors (Json, Path, State),
// and a Tokio main entry point.
type AxumStrategy struct{}

func (s *AxumStrategy) HandlerImports() []string {
	return []string{
		"axum::{",
		"    extract::{Json, Path, State},",
		"    http::StatusCode,",
		"    response::IntoResponse,",
		"    routing::{delete, get, patch, post, put},",
		"    Router,",
		"};",
		"use std::sync::Arc;",
	}
}

func (s *AxumStrategy) RouterImports() []string {
	return []string{
		"axum::Router",
	}
}

func (s *AxumStrategy) WrapHandler(method, returnType, serviceCall string) string {
	if returnType == "" {
		switch strings.ToUpper(method) {
		case "DELETE":
			return fmt.Sprintf("%s\nOk(StatusCode::NO_CONTENT)", serviceCall)
		default:
			return fmt.Sprintf("%s\nOk(StatusCode::OK)", serviceCall)
		}
	}
	statusCode := "StatusCode::OK"
	if strings.ToUpper(method) == "POST" {
		statusCode = "StatusCode::CREATED"
	}
	return fmt.Sprintf("let result = %s?;\nOk((%s, Json(result)))", serviceCall, statusCode)
}

func (s *AxumStrategy) BuildRouter(routes []RouteEntry) string {
	if len(routes) == 0 {
		return "Router::new()"
	}
	var sb strings.Builder
	sb.WriteString("Router::new()")
	for _, r := range routes {
		sb.WriteString(fmt.Sprintf("\n    .route(%q, %s(%s))", r.Path, axumMethodFn(r.Method), r.Handler))
	}
	return sb.String()
}

func (s *AxumStrategy) CargoTomlDependencies() []string {
	return []string{
		`axum = "0.7"`,
		`tokio = { version = "1", features = ["full"] }`,
		`serde = { version = "1", features = ["derive"] }`,
		`serde_json = "1"`,
		`async-trait = "0.1"`,
	}
}

func (s *AxumStrategy) MainRsContent() string {
	return `// AUTO-GENERATED BY VELD — DO NOT EDIT
use std::net::SocketAddr;

mod models;
mod services;
mod router;

#[tokio::main]
async fn main() {
    // TODO: initialise your service implementations and pass them to build_router().
    let app = router::build_router();

    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("Listening on {}", addr);

    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
`
}

func (s *AxumStrategy) WSHandlerCode(handlerName, routePath, serviceName, streamType, emitType string, pathParams []string) string {
	if emitType == "" {
		emitType = "serde_json::Value"
	}
	var sb strings.Builder

	// Build Path extractor params.
	var pathExtract string
	if len(pathParams) == 1 {
		pathExtract = fmt.Sprintf("\n    Path(%s): Path<String>,", pathParams[0])
	} else if len(pathParams) > 1 {
		names := strings.Join(pathParams, ", ")
		types := strings.Repeat("String, ", len(pathParams))
		types = strings.TrimRight(types, ", ")
		pathExtract = fmt.Sprintf("\n    Path((%s)): Path<(%s)>,", names, types)
	}

	// Build service call args.
	var connectArgs []string
	connectArgs = append(connectArgs, "socket")
	for _, p := range pathParams {
		connectArgs = append(connectArgs, p)
	}

	sb.WriteString(fmt.Sprintf("/// WebSocket handler for %s\n", routePath))
	sb.WriteString(fmt.Sprintf("pub async fn %s(\n", handlerName))
	sb.WriteString(fmt.Sprintf("    ws: axum::extract::ws::WebSocketUpgrade,%s\n", pathExtract))
	sb.WriteString(fmt.Sprintf("    State(service): State<Arc<dyn %s>>,\n", serviceName))
	sb.WriteString(") -> impl axum::response::IntoResponse {\n")
	if len(pathParams) > 0 {
		sb.WriteString(fmt.Sprintf("    let svc = service.clone();\n"))
		sb.WriteString(fmt.Sprintf("    ws.on_upgrade(move |socket| async move {\n"))
		sb.WriteString(fmt.Sprintf("        // TODO: implement service.on_%s_connect(%s).await\n", handlerName, strings.Join(connectArgs, ", ")))
	} else {
		sb.WriteString("    ws.on_upgrade(move |socket| async move {\n")
		sb.WriteString(fmt.Sprintf("        // TODO: implement service.on_%s_connect(socket).await\n", handlerName))
	}
	if emitType != "serde_json::Value" || streamType != "" {
		sb.WriteString(fmt.Sprintf("        // on message: service.on_%s_message(&mut socket, msg: %s).await\n", handlerName, emitType))
	}
	if streamType != "" {
		sb.WriteString(fmt.Sprintf("        // broadcast: sends %s to client via socket.send()\n", streamType))
	}
	sb.WriteString("    })\n")
	sb.WriteString("}\n")
	return sb.String()
}

// axumMethodFn maps an HTTP method string to the Axum routing function name.
func axumMethodFn(method string) string {
	switch strings.ToUpper(method) {
	case "GET":
		return "get"
	case "POST":
		return "post"
	case "PUT":
		return "put"
	case "DELETE":
		return "delete"
	case "PATCH":
		return "patch"
	default:
		return "get"
	}
}
