package docsgen

import (
	"fmt"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// BuildHTML generates a standalone single-file HTML SPA for API documentation.
// services carries workspace grouping; pass nil for single-service mode.
func BuildHTML(a ast.AST, services []ServiceInfo) string {
	if len(services) == 0 {
		names := make([]string, len(a.Modules))
		for i, m := range a.Modules {
			names[i] = m.Name
		}
		services = []ServiceInfo{{Name: "API", ModuleNames: names}}
	}

	modelSet := make(map[string]bool, len(a.Models))
	for _, m := range a.Models {
		modelSet[m.Name] = true
	}
	enumSet := make(map[string]bool, len(a.Enums))
	for _, e := range a.Enums {
		enumSet[e.Name] = true
	}
	moduleByName := make(map[string]ast.Module, len(a.Modules))
	for _, mod := range a.Modules {
		moduleByName[mod.Name] = mod
	}

	typeChip := func(t string) string {
		if t == "" {
			return ""
		}
		isArray := strings.HasSuffix(t, "[]")
		base := strings.TrimSuffix(t, "[]")
		suffix := ""
		if isArray {
			suffix = "[]"
		}
		if modelSet[base] {
			id := "model-" + slug(base)
			return fmt.Sprintf(`<a class="type-chip" href="#%s" onclick="navigateTo('%s');return false">%s%s</a>`, id, id, esc(base), esc(suffix))
		}
		if enumSet[base] {
			id := "enum-" + slug(base)
			return fmt.Sprintf(`<a class="type-chip" href="#%s" onclick="navigateTo('%s');return false">%s%s</a>`, id, id, esc(base), esc(suffix))
		}
		return `<span class="plain-chip">` + esc(t) + `</span>`
	}

	fieldTypeChip := func(f ast.Field) string {
		if f.IsMap {
			return fmt.Sprintf(`<span class="plain-chip">Map&lt;string,&nbsp;%s&gt;</span>`, typeChip(f.MapValueType))
		}
		t := f.Type
		if f.IsArray {
			t += "[]"
		}
		return typeChip(t)
	}

	var sb strings.Builder
	sb.WriteString(htmlHead)

	// ── Sidebar ───────────────────────────────────────────────────────────────
	sb.WriteString("<nav class=\"sidebar\">\n")
	sb.WriteString("  <div class=\"sidebar-brand\">\n")
	sb.WriteString("    <div class=\"brand-name\">\n")
	sb.WriteString("      <svg class=\"brand-icon\" viewBox=\"0 0 20 20\" fill=\"none\"><path d=\"M10 2L17.3 6V14L10 18L2.7 14V6L10 2Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linejoin=\"round\"/><path d=\"M10 2V18\" stroke=\"currentColor\" stroke-width=\"1\" opacity=\".4\"/><path d=\"M2.7 6L17.3 14\" stroke=\"currentColor\" stroke-width=\"1\" opacity=\".4\"/><path d=\"M17.3 6L2.7 14\" stroke=\"currentColor\" stroke-width=\"1\" opacity=\".4\"/></svg>\n")
	sb.WriteString("      API Reference\n")
	sb.WriteString("    </div>\n")
	sb.WriteString("    <div class=\"brand-sub\">Generated by Veld</div>\n")
	sb.WriteString("  </div>\n")
	sb.WriteString("  <div class=\"search-wrap\">\n")
	sb.WriteString("    <div class=\"search-inner\">\n")
	sb.WriteString("      <svg class=\"search-icon-svg\" width=\"13\" height=\"13\" viewBox=\"0 0 14 14\" fill=\"none\"><circle cx=\"6\" cy=\"6\" r=\"4.5\" stroke=\"currentColor\" stroke-width=\"1.5\"/><line x1=\"9.5\" y1=\"9.5\" x2=\"12.5\" y2=\"12.5\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/></svg>\n")
	sb.WriteString("      <input type=\"text\" id=\"nav-search\" placeholder=\"Search endpoints, models\u2026\" autocomplete=\"off\" oninput=\"filterNav(this.value)\">\n")
	sb.WriteString("      <kbd class=\"search-hint\">/</kbd>\n")
	sb.WriteString("    </div>\n")
	sb.WriteString("  </div>\n")
	sb.WriteString("  <div class=\"nav-tree\">\n")

	multiService := len(services) > 1

	for _, svc := range services {
		svcSlug := slug(svc.Name)
		sb.WriteString(fmt.Sprintf("    <div class=\"nav-svc\" id=\"nav-svc-%s\">\n", svcSlug))
		if multiService {
			sb.WriteString(fmt.Sprintf("      <div class=\"nav-svc-label\" onclick=\"toggleSvc(this)\"><span>%s</span><span class=\"nav-toggle\">\u25be</span></div>\n", esc(svc.Name)))
		}
		sb.WriteString("      <div class=\"nav-svc-body\">\n")

		for _, mn := range svc.ModuleNames {
			mod, ok := moduleByName[mn]
			if !ok {
				continue
			}
			modSlug := slug(mn)
			sb.WriteString("        <div class=\"nav-mod\">\n")
			sb.WriteString(fmt.Sprintf("          <div class=\"nav-mod-label\" onclick=\"toggleMod(this)\"><span>%s</span><span class=\"nav-badge\">%d</span></div>\n", esc(mod.Name), len(mod.Actions)))
			sb.WriteString("          <div class=\"nav-mod-body\">\n")

			for _, act := range mod.Actions {
				actID := fmt.Sprintf("action-%s-%s-%s", svcSlug, modSlug, slug(act.Name))
				method := strings.ToUpper(act.Method)
				search := strings.ToLower(act.Name) + " " + strings.ToLower(method) + " " + strings.ToLower(act.Path)
				sb.WriteString(fmt.Sprintf("            <a class=\"nav-ep\" href=\"#%s\" data-target=\"%s\" data-search=\"%s\" onclick=\"navigateTo('%s');return false;\">\n",
					actID, actID, esc(search), actID))
				sb.WriteString(fmt.Sprintf("              <span class=\"nav-method nav-method-%s\">%s</span>\n", method, method))
				sb.WriteString(fmt.Sprintf("              <span class=\"nav-ep-name\">%s</span>\n", esc(act.Name)))
				sb.WriteString("            </a>\n")
			}

			sb.WriteString("          </div>\n        </div>\n")
		}

		sb.WriteString("      </div>\n    </div>\n")
	}

	if len(a.Models) > 0 {
		sb.WriteString("    <div class=\"nav-group\">\n")
		sb.WriteString(fmt.Sprintf("      <div class=\"nav-group-label\" onclick=\"toggleGroup(this)\">Models <span class=\"nav-badge\">%d</span></div>\n", len(a.Models)))
		sb.WriteString("      <div class=\"nav-group-body\">\n")
		for _, m := range a.Models {
			id := "model-" + slug(m.Name)
			sb.WriteString(fmt.Sprintf("        <a class=\"nav-type\" href=\"#%s\" data-target=\"%s\" data-search=\"%s\" onclick=\"navigateTo('%s');return false;\">%s</a>\n",
				id, id, strings.ToLower(m.Name), id, esc(m.Name)))
		}
		sb.WriteString("      </div>\n    </div>\n")
	}

	if len(a.Enums) > 0 {
		sb.WriteString("    <div class=\"nav-group\">\n")
		sb.WriteString(fmt.Sprintf("      <div class=\"nav-group-label\" onclick=\"toggleGroup(this)\">Enums <span class=\"nav-badge\">%d</span></div>\n", len(a.Enums)))
		sb.WriteString("      <div class=\"nav-group-body\">\n")
		for _, en := range a.Enums {
			id := "enum-" + slug(en.Name)
			sb.WriteString(fmt.Sprintf("        <a class=\"nav-type\" href=\"#%s\" data-target=\"%s\" data-search=\"%s\" onclick=\"navigateTo('%s');return false;\">%s</a>\n",
				id, id, strings.ToLower(en.Name), id, esc(en.Name)))
		}
		sb.WriteString("      </div>\n    </div>\n")
	}

	sb.WriteString("  </div>\n</nav>\n")

	// ── Main area ─────────────────────────────────────────────────────────────
	sb.WriteString("<div class=\"main\">\n")

	// Topbar
	sb.WriteString("  <div class=\"topbar\">\n")
	sb.WriteString("    <nav class=\"breadcrumbs\" id=\"breadcrumbs\"><span class=\"bc-item\">API Reference</span></nav>\n")
	sb.WriteString("    <div class=\"topbar-right\">\n")
	sb.WriteString("      <button class=\"theme-btn\" onclick=\"toggleTheme()\" title=\"Toggle dark mode\">\U0001f319</button>\n")
	sb.WriteString("    </div>\n")
	sb.WriteString("  </div>\n")

	// Content
	sb.WriteString("  <div class=\"content\">\n")

	// Stats row
	totalActions := 0
	for _, mod := range a.Modules {
		totalActions += len(mod.Actions)
	}
	sb.WriteString("    <div class=\"stats-row\">\n")
	if multiService {
		sb.WriteString(fmt.Sprintf("      <div class=\"stat-card\"><div class=\"stat-num\">%d</div><div class=\"stat-lbl\">Services</div></div>\n", len(services)))
	}
	sb.WriteString(fmt.Sprintf("      <div class=\"stat-card\"><div class=\"stat-num\">%d</div><div class=\"stat-lbl\">Modules</div></div>\n", len(a.Modules)))
	sb.WriteString(fmt.Sprintf("      <div class=\"stat-card\"><div class=\"stat-num\">%d</div><div class=\"stat-lbl\">Endpoints</div></div>\n", totalActions))
	sb.WriteString(fmt.Sprintf("      <div class=\"stat-card\"><div class=\"stat-num\">%d</div><div class=\"stat-lbl\">Models</div></div>\n", len(a.Models)))
	if len(a.Enums) > 0 {
		sb.WriteString(fmt.Sprintf("      <div class=\"stat-card\"><div class=\"stat-num\">%d</div><div class=\"stat-lbl\">Enums</div></div>\n", len(a.Enums)))
	}
	sb.WriteString("    </div>\n\n")

	// Services → Modules → Endpoints
	for _, svc := range services {
		svcSlug := slug(svc.Name)

		if multiService {
			sb.WriteString(fmt.Sprintf("    <div class=\"svc-block\" id=\"service-%s\" data-bc=\"%s\">\n", svcSlug, esc(svc.Name)))
			sb.WriteString(fmt.Sprintf("      <h2 class=\"svc-title\">%s", esc(svc.Name)))
			if svc.BaseUrl != "" {
				sb.WriteString(fmt.Sprintf(" <code class=\"svc-url\">%s</code>", esc(svc.BaseUrl)))
			}
			sb.WriteString("</h2>\n")
			if svc.Description != "" {
				sb.WriteString(fmt.Sprintf("      <p class=\"svc-desc\">%s</p>\n", esc(svc.Description)))
			}
			sb.WriteString("    </div>\n")
		}

		for _, mn := range svc.ModuleNames {
			mod, ok := moduleByName[mn]
			if !ok {
				continue
			}
			modSlug := slug(mn)
			modBC := esc(mod.Name)
			if multiService {
				modBC = esc(svc.Name) + " \u203a " + esc(mod.Name)
			}

			sb.WriteString(fmt.Sprintf("    <div class=\"mod-header\" id=\"mod-%s-%s\" data-bc=\"%s\">\n", svcSlug, modSlug, modBC))
			sb.WriteString(fmt.Sprintf("      <h3 class=\"mod-title\">%s", esc(mod.Name)))
			if mod.Prefix != "" {
				sb.WriteString(fmt.Sprintf(" <code class=\"mod-prefix\">%s</code>", esc(mod.Prefix)))
			}
			sb.WriteString("</h3>\n")
			if mod.Description != "" {
				sb.WriteString(fmt.Sprintf("      <p class=\"mod-desc\">%s</p>\n", esc(mod.Description)))
			}
			sb.WriteString("    </div>\n")

			for _, act := range mod.Actions {
				actID := fmt.Sprintf("action-%s-%s-%s", svcSlug, modSlug, slug(act.Name))
				routePath := act.Path
				if mod.Prefix != "" {
					routePath = mod.Prefix + act.Path
				}
				method := strings.ToUpper(act.Method)
				actBC := modBC + " \u203a " + esc(act.Name)

				depCls := ""
				if act.Deprecated != "" {
					depCls = " ep-deprecated"
				}

				sb.WriteString(fmt.Sprintf("    <div class=\"ep ep-%s%s\" id=\"%s\" data-bc=\"%s\">\n", method, depCls, actID, actBC))
				sb.WriteString("      <div class=\"ep-head\" onclick=\"toggleEp(this)\">\n")
				sb.WriteString(fmt.Sprintf("        <span class=\"mtag mtag-%s\">%s</span>\n", method, method))
				sb.WriteString(fmt.Sprintf("        <span class=\"ep-path\">%s</span>\n", buildPathHTML(routePath)))
				sb.WriteString("        <span class=\"ep-info\">\n")
				sb.WriteString(fmt.Sprintf("          <span class=\"ep-name\">%s", esc(act.Name)))
				if act.Deprecated != "" {
					sb.WriteString(fmt.Sprintf(` <span class="depr-tag" title="%s">deprecated</span>`, esc(act.Deprecated)))
				}
				sb.WriteString("</span>\n")
				sb.WriteString(fmt.Sprintf("          <button class=\"copy-btn\" data-path=\"%s\" onclick=\"copyPath(event,this.dataset.path)\" title=\"Copy path\">\u2398</button>\n", esc(routePath)))
				sb.WriteString("        </span>\n")
				sb.WriteString("        <span class=\"chevron\">\u25b6</span>\n")
				sb.WriteString("      </div>\n")

				sb.WriteString("      <div class=\"ep-detail\">\n")
				if act.Description != "" {
					sb.WriteString(fmt.Sprintf("        <p class=\"ep-desc\">%s</p>\n", esc(act.Description)))
				}
				sb.WriteString("        <dl class=\"ep-meta\">\n")

				if act.Input != "" {
					sb.WriteString(fmt.Sprintf("          <dt>Input</dt><dd>%s</dd>\n", typeChip(act.Input)))
				}

				output := act.Output
				if act.OutputArray {
					output += "[]"
				}
				if output != "" {
					sb.WriteString(fmt.Sprintf("          <dt>Output</dt><dd>%s</dd>\n", typeChip(output)))
				} else {
					sb.WriteString("          <dt>Output</dt><dd><span class=\"plain-chip\">void</span></dd>\n")
				}

				if len(act.OutputFields) > 0 {
					sb.WriteString("          <dt>Response</dt><dd>\n")
					sb.WriteString("            <div class=\"field-table-wrap\"><table class=\"field-table\"><thead><tr><th>Field</th><th>Type</th><th>Attrs</th></tr></thead><tbody>\n")
					for _, f := range act.OutputFields {
						sb.WriteString(fmt.Sprintf("              <tr><td class=\"fn\">%s</td><td>%s</td><td><div class=\"attr-wrap\">%s</div></td></tr>\n",
							esc(f.Name), fieldTypeChip(f), fieldAttrs(f)))
					}
					sb.WriteString("            </tbody></table></div></dd>\n")
				}

				if act.Query != "" {
					sb.WriteString(fmt.Sprintf("          <dt>Query</dt><dd>%s</dd>\n", typeChip(act.Query)))
				}

				if len(act.QueryFields) > 0 {
					sb.WriteString("          <dt>Params</dt><dd>\n")
					sb.WriteString("            <div class=\"field-table-wrap\"><table class=\"field-table\"><thead><tr><th>Field</th><th>Type</th><th>Attrs</th></tr></thead><tbody>\n")
					for _, f := range act.QueryFields {
						sb.WriteString(fmt.Sprintf("              <tr><td class=\"fn\">%s</td><td>%s</td><td><div class=\"attr-wrap\">%s</div></td></tr>\n",
							esc(f.Name), fieldTypeChip(f), fieldAttrs(f)))
					}
					sb.WriteString("            </tbody></table></div></dd>\n")
				}

				if act.Method == "WS" {
					if act.Stream != "" {
						sb.WriteString(fmt.Sprintf("          <dt>Receive</dt><dd>%s</dd>\n", typeChip(act.Stream)))
					}
					if act.Emit != "" {
						sb.WriteString(fmt.Sprintf("          <dt>Emit</dt><dd>%s</dd>\n", typeChip(act.Emit)))
					}
				}

				if len(act.Middleware) > 0 {
					sb.WriteString("          <dt>Auth</dt><dd>")
					for i, mw := range act.Middleware {
						if i > 0 {
							sb.WriteString(" ")
						}
						sb.WriteString(fmt.Sprintf(`<span class="mw-chip">%s</span>`, esc(mw)))
					}
					sb.WriteString("</dd>\n")
				}

				if len(act.Errors) > 0 {
					sb.WriteString("          <dt>Errors</dt><dd>")
					for i, e := range act.Errors {
						if i > 0 {
							sb.WriteString(" ")
						}
						if status, ok := act.ErrorStatuses[e]; ok {
							sb.WriteString(fmt.Sprintf(`<span class="err-chip">%s <em>%d</em></span>`, esc(e), status))
						} else {
							sb.WriteString(fmt.Sprintf(`<span class="err-chip">%s</span>`, esc(e)))
						}
					}
					sb.WriteString("</dd>\n")
				}

				sb.WriteString("        </dl>\n      </div>\n    </div>\n")
			}
		}
	}

	// ── Models ────────────────────────────────────────────────────────────────
	if len(a.Models) > 0 {
		sb.WriteString("    <h2 class=\"types-title\" id=\"section-models\" data-bc=\"Models\">Models</h2>\n")
		for _, m := range a.Models {
			modelID := "model-" + slug(m.Name)
			sb.WriteString(fmt.Sprintf("    <div class=\"type-card\" id=\"%s\" data-bc=\"Models \u203a %s\">\n", modelID, esc(m.Name)))
			sb.WriteString("      <div class=\"type-head\">\n")
			sb.WriteString(fmt.Sprintf("        <span class=\"type-name\">%s</span>\n", esc(m.Name)))
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("        <span class=\"extends-note\">extends %s</span>\n", typeChip(m.Extends)))
			}
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("        <span class=\"type-desc\">%s</span>\n", esc(m.Description)))
			}
			usedBy := collectModelUsages(a, m.Name)
			if len(usedBy) > 0 {
				sb.WriteString("        <span class=\"used-by\">Used by: ")
				for i, u := range usedBy {
					if i > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(fmt.Sprintf(`<span class="ub-chip">%s</span>`, esc(u)))
				}
				sb.WriteString("</span>\n")
			}
			sb.WriteString("      </div>\n")
			if len(m.Fields) > 0 {
				sb.WriteString("      <table class=\"fields-table\"><thead><tr><th>Field</th><th>Type</th><th>Attributes</th></tr></thead><tbody>\n")
				for _, f := range m.Fields {
					depCls := ""
					if f.Deprecated != "" {
						depCls = " class=\"depr-row\""
					}
					sb.WriteString(fmt.Sprintf("        <tr%s><td class=\"fn\">%s</td><td>%s</td><td><div class=\"attr-wrap\">%s</div></td></tr>\n",
						depCls, esc(f.Name), fieldTypeChip(f), fieldAttrs(f)))
				}
				sb.WriteString("      </tbody></table>\n")
			}
			sb.WriteString("    </div>\n")
		}
	}

	// ── Enums ─────────────────────────────────────────────────────────────────
	if len(a.Enums) > 0 {
		sb.WriteString("    <h2 class=\"types-title\" id=\"section-enums\" data-bc=\"Enums\">Enums</h2>\n")
		for _, en := range a.Enums {
			enumID := "enum-" + slug(en.Name)
			sb.WriteString(fmt.Sprintf("    <div class=\"type-card\" id=\"%s\" data-bc=\"Enums \u203a %s\">\n", enumID, esc(en.Name)))
			sb.WriteString("      <div class=\"type-head\">\n")
			sb.WriteString(fmt.Sprintf("        <span class=\"type-name\">%s</span>\n", esc(en.Name)))
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("        <span class=\"type-desc\">%s</span>\n", esc(en.Description)))
			}
			usedBy := collectEnumUsages(a, en.Name)
			if len(usedBy) > 0 {
				sb.WriteString("        <span class=\"used-by\">Used by: ")
				for i, u := range usedBy {
					if i > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(fmt.Sprintf(`<span class="ub-chip">%s</span>`, esc(u)))
				}
				sb.WriteString("</span>\n")
			}
			sb.WriteString("      </div>\n")
			sb.WriteString("      <div class=\"enum-chips\">\n")
			for _, v := range en.Values {
				sb.WriteString(fmt.Sprintf("        <span class=\"ev-chip\">%s</span>\n", esc(v)))
			}
			sb.WriteString("      </div>\n    </div>\n")
		}
	}

	sb.WriteString("    <div class=\"footer\">Generated by <strong>Veld</strong></div>\n")
	sb.WriteString("  </div>\n</div>\n")
	sb.WriteString(htmlScript)
	sb.WriteString("</body>\n</html>\n")
	return sb.String()
}

// buildPathHTML renders a route path with :param segments highlighted.
func buildPathHTML(path string) string {
	segs := strings.Split(path, "/")
	for i, seg := range segs {
		if strings.HasPrefix(seg, ":") {
			segs[i] = `<span class="path-param">` + esc(seg) + `</span>`
		} else {
			segs[i] = esc(seg)
		}
	}
	return strings.Join(segs, "/")
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func slug(s string) string {
	return strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(s, " ", "-"), "_", "-"))
}

func esc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}

func fieldAttrs(f ast.Field) string {
	var parts []string
	if f.Optional {
		parts = append(parts, `<span class="fa-opt">optional</span>`)
	}
	if f.Default != "" {
		parts = append(parts, fmt.Sprintf(`<span class="fa-default">= %s</span>`, esc(f.Default)))
	}
	if f.Unique {
		parts = append(parts, `<span class="fa-badge">unique</span>`)
	}
	if f.Index {
		parts = append(parts, `<span class="fa-badge">index</span>`)
	}
	if f.Relation != "" {
		parts = append(parts, fmt.Sprintf(`<span class="fa-badge">&rarr; %s</span>`, esc(f.Relation)))
	}
	if f.ServerSet {
		parts = append(parts, `<span class="fa-badge">serverSet</span>`)
	}
	if f.Deprecated != "" {
		parts = append(parts, fmt.Sprintf(`<span class="fa-depr" title="%s">deprecated</span>`, esc(f.Deprecated)))
	}
	if len(parts) == 0 {
		return `<span class="fa-none">&mdash;</span>`
	}
	return strings.Join(parts, " ")
}

func collectModelUsages(a ast.AST, name string) []string {
	var usages []string
	seen := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			label := mod.Name + "." + act.Name
			if (act.Input == name || act.Output == name || act.Query == name) && !seen[label] {
				usages = append(usages, label)
				seen[label] = true
			}
		}
	}
	return usages
}

func collectEnumUsages(a ast.AST, name string) []string {
	var usages []string
	seen := make(map[string]bool)
	for _, m := range a.Models {
		for _, f := range m.Fields {
			if (f.Type == name || f.MapValueType == name) && !seen[m.Name] {
				usages = append(usages, m.Name)
				seen[m.Name] = true
			}
		}
	}
	return usages
}

// ── CSS ───────────────────────────────────────────────────────────────────────

const htmlHead = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>API Reference &mdash; Veld</title>
<style>
/* ── Reset ── */
*, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

/* ── Design tokens ── */
:root {
  --bg:         #f8fafc;
  --fg:         #0f172a;
  --sub-fg:     #334155;
  --muted:      #64748b;
  --muted2:     #94a3b8;

  --card:       #ffffff;
  --card-bd:    #e2e8f0;
  --card-sh:    0 1px 3px rgba(0,0,0,.06);

  --code-bg:    #f1f5f9;
  --code-fg:    #0f172a;
  --divider:    #e2e8f0;

  --accent:     #6366f1;
  --accent-dim: #4f46e5;
  --accent-bg:  #eef2ff;
  --accent-fg:  #4338ca;

  --sb-bg:       #0f172a;
  --sb-bd:       rgba(255,255,255,.06);
  --sb-fg:       #94a3b8;
  --sb-fg2:      #64748b;
  --sb-hover:    rgba(255,255,255,.05);
  --sb-act-bg:   rgba(99,102,241,.15);
  --sb-act-fg:   #a5b4fc;
  --sb-act-bd:   #6366f1;

  --get:    #10b981; --get-bg:    #d1fae5; --get-fg:    #064e3b;
  --post:   #3b82f6; --post-bg:   #dbeafe; --post-fg:   #1e3a8a;
  --put:    #f59e0b; --put-bg:    #fef3c7; --put-fg:    #78350f;
  --del:    #ef4444; --del-bg:    #fee2e2; --del-fg:    #7f1d1d;
  --patch:  #f97316; --patch-bg:  #ffedd5; --patch-fg:  #7c2d12;
  --ws:     #8b5cf6; --ws-bg:     #ede9fe; --ws-fg:     #3b0764;

  --mono: 'JetBrains Mono','Fira Code','SF Mono',Consolas,'Liberation Mono',monospace;
  --sans: -apple-system,BlinkMacSystemFont,'Inter','Segoe UI',system-ui,sans-serif;
  --r3: 3px; --r5: 5px; --r8: 8px;
}

[data-theme="dark"] {
  --bg:         #0c1222;
  --fg:         #e2e8f0;
  --sub-fg:     #cbd5e1;
  --muted:      #64748b;
  --muted2:     #475569;

  --card:       #0f172a;
  --card-bd:    #1e293b;
  --card-sh:    0 1px 4px rgba(0,0,0,.3);

  --code-bg:    #1e293b;
  --code-fg:    #e2e8f0;
  --divider:    #1e293b;

  --accent:     #818cf8;
  --accent-dim: #a5b4fc;
  --accent-bg:  rgba(99,102,241,.12);
  --accent-fg:  #c7d2fe;

  --sb-bg:       #060d19;
  --sb-bd:       rgba(255,255,255,.04);
  --sb-fg:       #64748b;
  --sb-fg2:      #475569;
  --sb-hover:    rgba(255,255,255,.04);

  --get:    #34d399; --get-bg:   rgba(5,150,105,.2);  --get-fg:   #a7f3d0;
  --post:   #60a5fa; --post-bg:  rgba(37,99,235,.2);  --post-fg:  #bfdbfe;
  --put:    #fbbf24; --put-bg:   rgba(217,119,6,.2);  --put-fg:   #fde68a;
  --del:    #f87171; --del-bg:   rgba(220,38,38,.2);  --del-fg:   #fecaca;
  --patch:  #fb923c; --patch-bg: rgba(234,88,12,.2);  --patch-fg: #fed7aa;
  --ws:     #a78bfa; --ws-bg:    rgba(124,58,237,.2); --ws-fg:    #ddd6fe;
}

/* ── Base ── */
html { scroll-behavior: smooth; }
body {
  font-family: var(--sans);
  background: var(--bg);
  color: var(--fg);
  line-height: 1.6;
  display: grid;
  grid-template-columns: 260px 1fr;
  min-height: 100vh;
}
a { color: inherit; text-decoration: none; }

/* ── Sidebar ── */
.sidebar {
  background: var(--sb-bg);
  height: 100vh;
  position: sticky;
  top: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  border-right: 1px solid var(--sb-bd);
}

.sidebar-brand {
  padding: 18px 16px 14px;
  border-bottom: 1px solid var(--sb-bd);
  flex-shrink: 0;
}
.brand-name {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  font-weight: 700;
  color: #f1f5f9;
  letter-spacing: -.01em;
}
.brand-icon { width: 18px; height: 18px; color: var(--accent); flex-shrink: 0; }
.brand-sub  { font-size: 11px; color: var(--sb-fg2); margin-top: 3px; }

/* Search */
.search-wrap {
  padding: 10px 12px;
  border-bottom: 1px solid var(--sb-bd);
  flex-shrink: 0;
}
.search-inner { position: relative; display: flex; align-items: center; }
.search-icon-svg {
  position: absolute;
  left: 9px;
  color: var(--sb-fg2);
  pointer-events: none;
  flex-shrink: 0;
}
#nav-search {
  width: 100%;
  background: rgba(255,255,255,.06);
  border: 1px solid rgba(255,255,255,.1);
  border-radius: var(--r5);
  padding: 6px 30px 6px 28px;
  font-size: 12px;
  color: #f1f5f9;
  outline: none;
  font-family: var(--sans);
  transition: border-color .15s, background .15s;
}
#nav-search::placeholder { color: var(--sb-fg2); }
#nav-search:focus { border-color: var(--accent); background: rgba(255,255,255,.09); }
.search-hint {
  position: absolute;
  right: 8px;
  font-size: 10px;
  color: var(--sb-fg2);
  background: rgba(255,255,255,.07);
  padding: 1px 5px;
  border-radius: 3px;
  border: 1px solid rgba(255,255,255,.1);
  font-family: var(--sans);
  pointer-events: none;
  transition: opacity .15s;
}
#nav-search:focus ~ .search-hint,
#nav-search:not(:placeholder-shown) ~ .search-hint { opacity: 0; }

/* Nav tree */
.nav-tree {
  flex: 1;
  overflow-y: auto;
  padding: 6px 0 24px;
  scrollbar-width: thin;
  scrollbar-color: rgba(255,255,255,.08) transparent;
}
.nav-tree::-webkit-scrollbar { width: 3px; }
.nav-tree::-webkit-scrollbar-thumb { background: rgba(255,255,255,.08); border-radius: 2px; }

/* Service block */
.nav-svc { margin-bottom: 4px; }
.nav-svc-label {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 16px 4px;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: .08em;
  text-transform: uppercase;
  color: var(--sb-fg);
  cursor: pointer;
  user-select: none;
  transition: color .15s;
}
.nav-svc-label:hover { color: #cbd5e1; }
.nav-toggle { font-size: 9px; transition: transform .2s; display: inline-block; }
.nav-svc.collapsed .nav-toggle  { transform: rotate(-90deg); }
.nav-svc.collapsed .nav-svc-body { display: none; }

/* Module block */
.nav-mod { margin-bottom: 1px; }
.nav-mod-label {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 5px 16px;
  font-size: 11px;
  font-weight: 600;
  color: var(--sb-fg);
  cursor: pointer;
  user-select: none;
  transition: color .12s, background .12s;
}
.nav-mod-label:hover { color: #cbd5e1; background: var(--sb-hover); }
.nav-badge {
  font-size: 9px;
  font-weight: 700;
  background: rgba(255,255,255,.08);
  color: var(--sb-fg2);
  padding: 1px 6px;
  border-radius: 10px;
  flex-shrink: 0;
}
.nav-mod.collapsed .nav-mod-body { display: none; }

/* Endpoint nav link */
.nav-ep {
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 3px 12px 3px 20px;
  font-size: 11.5px;
  color: var(--sb-fg);
  cursor: pointer;
  transition: color .12s, background .12s;
  border-left: 2px solid transparent;
  overflow: hidden;
  text-decoration: none;
}
.nav-ep:hover { color: #e2e8f0; background: var(--sb-hover); }
.nav-ep.active {
  color: var(--sb-act-fg);
  background: var(--sb-act-bg);
  border-left-color: var(--sb-act-bd);
}
.nav-method {
  font-size: 9px;
  font-weight: 800;
  font-family: var(--mono);
  letter-spacing: .02em;
  min-width: 40px;
  text-align: left;
  flex-shrink: 0;
}
.nav-method-GET    { color: var(--get); }
.nav-method-POST   { color: var(--post); }
.nav-method-PUT    { color: var(--put); }
.nav-method-DELETE { color: var(--del); }
.nav-method-PATCH  { color: var(--patch); }
.nav-method-WS     { color: var(--ws); }
.nav-ep-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

/* Type groups (models / enums) */
.nav-group { margin-top: 10px; }
.nav-group-label {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 16px;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: .08em;
  text-transform: uppercase;
  color: var(--sb-fg2);
  cursor: pointer;
  user-select: none;
  transition: color .15s;
}
.nav-group-label:hover { color: var(--sb-fg); }
.nav-group.collapsed .nav-group-body { display: none; }
.nav-type {
  display: block;
  padding: 3px 16px 3px 20px;
  font-size: 11.5px;
  font-family: var(--mono);
  color: var(--sb-fg2);
  cursor: pointer;
  transition: color .12s, background .12s;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  text-decoration: none;
}
.nav-type:hover { color: #e2e8f0; background: var(--sb-hover); }
.nav-type.active { color: var(--sb-act-fg); background: var(--sb-act-bg); }

/* ── Main layout ── */
.main { display: flex; flex-direction: column; min-height: 100vh; }

/* Topbar */
.topbar {
  position: sticky;
  top: 0;
  z-index: 10;
  background: var(--bg);
  border-bottom: 1px solid var(--divider);
  padding: 0 40px;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-shrink: 0;
}
.breadcrumbs {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  min-width: 0;
  overflow: hidden;
}
.bc-item { color: var(--muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.bc-item.bc-last { color: var(--fg); font-weight: 500; }
.bc-sep { color: var(--muted2); flex-shrink: 0; }
.topbar-right { display: flex; align-items: center; flex-shrink: 0; }
.theme-btn {
  width: 30px; height: 30px;
  background: var(--card);
  border: 1px solid var(--card-bd);
  border-radius: var(--r5);
  cursor: pointer;
  font-size: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: border-color .15s;
  line-height: 1;
}
.theme-btn:hover { border-color: var(--accent); }

/* Content */
.content { flex: 1; padding: 32px 40px 64px; max-width: 900px; }

/* Stats */
.stats-row { display: flex; gap: 12px; margin-bottom: 36px; flex-wrap: wrap; }
.stat-card {
  background: var(--card);
  border: 1px solid var(--card-bd);
  border-radius: var(--r8);
  padding: 14px 20px;
  box-shadow: var(--card-sh);
  min-width: 100px;
  text-align: center;
}
.stat-num {
  font-size: 26px;
  font-weight: 800;
  color: var(--accent);
  line-height: 1;
  letter-spacing: -.02em;
}
.stat-lbl {
  font-size: 10px;
  color: var(--muted);
  margin-top: 5px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: .05em;
}

/* Service + Module headers */
.svc-block  { margin: 32px 0 8px; }
.svc-title {
  font-size: 22px;
  font-weight: 800;
  letter-spacing: -.025em;
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
}
.svc-url {
  font-size: 11px;
  font-weight: 400;
  color: var(--muted);
  background: var(--code-bg);
  padding: 2px 8px;
  border-radius: var(--r3);
  font-family: var(--mono);
}
.svc-desc { font-size: 13px; color: var(--muted); margin-top: 6px; }
.mod-header {
  margin: 28px 0 2px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--divider);
}
.mod-title {
  font-size: 16px;
  font-weight: 700;
  display: flex;
  align-items: center;
  gap: 8px;
}
.mod-prefix {
  font-size: 11px;
  font-weight: 500;
  color: var(--muted);
  background: var(--code-bg);
  padding: 2px 8px;
  border-radius: var(--r3);
  font-family: var(--mono);
}
.mod-desc { font-size: 13px; color: var(--muted); margin-top: 4px; }

/* ── Endpoint cards ── */
.ep {
  border: 1px solid var(--card-bd);
  border-left-width: 3px;
  border-radius: var(--r8);
  background: var(--card);
  margin: 6px 0;
  box-shadow: var(--card-sh);
  overflow: hidden;
  transition: box-shadow .15s;
}
.ep:hover { box-shadow: 0 3px 12px rgba(0,0,0,.09); }
.ep.ep-open { box-shadow: 0 4px 16px rgba(0,0,0,.1); }
.ep-deprecated { opacity: .6; }
.ep-GET    { border-left-color: var(--get); }
.ep-POST   { border-left-color: var(--post); }
.ep-PUT    { border-left-color: var(--put); }
.ep-DELETE { border-left-color: var(--del); }
.ep-PATCH  { border-left-color: var(--patch); }
.ep-WS     { border-left-color: var(--ws); }

.ep-head {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 14px;
  cursor: pointer;
  user-select: none;
  transition: background .1s;
}
.ep-head:hover { background: var(--code-bg); }
.ep.ep-open .ep-head { background: var(--code-bg); }

/* Method tags */
.mtag {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 60px;
  padding: 3px 6px;
  border-radius: var(--r3);
  font-size: 10px;
  font-weight: 800;
  letter-spacing: .04em;
  font-family: var(--mono);
  flex-shrink: 0;
}
.mtag-GET    { background: var(--get-bg);   color: var(--get-fg); }
.mtag-POST   { background: var(--post-bg);  color: var(--post-fg); }
.mtag-PUT    { background: var(--put-bg);   color: var(--put-fg); }
.mtag-DELETE { background: var(--del-bg);   color: var(--del-fg); }
.mtag-PATCH  { background: var(--patch-bg); color: var(--patch-fg); }
.mtag-WS     { background: var(--ws-bg);    color: var(--ws-fg); }

.ep-path {
  flex: 1;
  font-family: var(--mono);
  font-size: 12.5px;
  font-weight: 500;
  color: var(--fg);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.path-param { color: var(--accent); font-weight: 700; }
.ep-info { display: flex; align-items: center; gap: 6px; flex-shrink: 0; }
.ep-name { font-size: 11px; color: var(--muted); white-space: nowrap; }
.depr-tag {
  font-size: 9px;
  font-weight: 700;
  background: var(--put-bg);
  color: var(--put-fg);
  padding: 1px 5px;
  border-radius: 3px;
  text-transform: uppercase;
  letter-spacing: .04em;
}
.copy-btn {
  opacity: 0;
  background: none;
  border: 1px solid var(--card-bd);
  color: var(--muted);
  padding: 2px 6px;
  border-radius: var(--r3);
  font-size: 12px;
  cursor: pointer;
  transition: opacity .12s, color .12s, border-color .12s;
  line-height: 1.3;
}
.ep-head:hover .copy-btn { opacity: 1; }
.copy-btn:hover { color: var(--accent); border-color: var(--accent); }
.chevron {
  font-size: 9px;
  color: var(--muted2);
  transition: transform .2s;
  flex-shrink: 0;
}
.ep.ep-open .chevron { transform: rotate(90deg); }

/* Endpoint detail */
.ep-detail {
  display: none;
  padding: 14px 18px 16px;
  border-top: 1px solid var(--card-bd);
}
.ep.ep-open .ep-detail { display: block; }
.ep-desc {
  font-size: 13px;
  color: var(--sub-fg);
  margin-bottom: 14px;
  line-height: 1.55;
}
.ep-meta {
  display: grid;
  grid-template-columns: 90px 1fr;
  gap: 8px 12px;
  align-items: start;
}
.ep-meta dt {
  font-size: 10px;
  font-weight: 700;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: .06em;
  padding-top: 4px;
}
.ep-meta dd {
  margin: 0;
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  align-items: center;
}

/* Chips */
.type-chip {
  display: inline-flex;
  align-items: center;
  background: var(--accent-bg);
  color: var(--accent-fg);
  padding: 2px 8px;
  border-radius: var(--r3);
  font-size: 11.5px;
  font-weight: 600;
  font-family: var(--mono);
  cursor: pointer;
  transition: background .12s, color .12s;
  text-decoration: none;
}
.type-chip:hover { background: var(--accent); color: #fff; }
.plain-chip {
  display: inline-block;
  background: var(--code-bg);
  color: var(--code-fg);
  padding: 2px 8px;
  border-radius: var(--r3);
  font-size: 11.5px;
  font-family: var(--mono);
}
.mw-chip {
  display: inline-block;
  background: var(--ws-bg);
  color: var(--ws-fg);
  padding: 2px 8px;
  border-radius: var(--r3);
  font-size: 11px;
  font-weight: 600;
  font-family: var(--mono);
}
.err-chip {
  display: inline-block;
  background: var(--del-bg);
  color: var(--del-fg);
  padding: 2px 8px;
  border-radius: var(--r3);
  font-size: 11px;
  font-family: var(--mono);
}
.err-chip em { font-style: normal; opacity: .65; margin-left: 3px; }

/* Inline field tables */
.field-table-wrap {
  border: 1px solid var(--card-bd);
  border-radius: var(--r5);
  overflow: hidden;
  width: 100%;
  margin-top: 2px;
}
.field-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}
.field-table thead tr { background: var(--code-bg); }
.field-table th {
  text-align: left;
  padding: 5px 12px;
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: .05em;
  color: var(--muted);
  border-bottom: 1px solid var(--card-bd);
}
.field-table td {
  padding: 6px 12px;
  border-bottom: 1px solid var(--card-bd);
  vertical-align: middle;
}
.field-table tr:last-child td { border-bottom: none; }
.field-table tr:hover td { background: var(--code-bg); }

/* ── Type cards (Models + Enums) ── */
.types-title {
  font-size: 20px;
  font-weight: 800;
  letter-spacing: -.02em;
  margin: 48px 0 14px;
  padding-top: 20px;
  border-top: 2px solid var(--divider);
}
.type-card {
  background: var(--card);
  border: 1px solid var(--card-bd);
  border-radius: var(--r8);
  margin-bottom: 10px;
  box-shadow: var(--card-sh);
  overflow: hidden;
}
.type-head {
  padding: 14px 18px;
  border-bottom: 1px solid var(--card-bd);
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px;
}
.type-name {
  font-family: var(--mono);
  font-size: 14px;
  font-weight: 700;
  color: var(--fg);
}
.extends-note {
  font-size: 11px;
  color: var(--muted);
  display: flex;
  align-items: center;
  gap: 4px;
}
.type-desc { font-size: 12px; color: var(--muted); width: 100%; margin-top: 2px; }
.used-by {
  font-size: 11px;
  color: var(--muted2);
  width: 100%;
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  align-items: center;
}
.ub-chip {
  font-family: var(--mono);
  font-size: 10px;
  background: var(--code-bg);
  color: var(--muted);
  padding: 1px 6px;
  border-radius: 3px;
}
.fields-table {
  width: 100%;
  border-collapse: collapse;
}
.fields-table thead tr { background: var(--code-bg); }
.fields-table th {
  text-align: left;
  padding: 7px 16px;
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: .06em;
  color: var(--muted);
  border-bottom: 1px solid var(--card-bd);
}
.fields-table td {
  padding: 8px 16px;
  font-size: 12px;
  border-bottom: 1px solid var(--card-bd);
  vertical-align: middle;
}
.fields-table tr:last-child td { border-bottom: none; }
.fields-table tr:hover td { background: var(--code-bg); }
.depr-row td { opacity: .5; text-decoration: line-through; }
.fn { font-family: var(--mono); font-size: 12px; font-weight: 600; }

/* Field attribute badges */
.attr-wrap  { display: flex; flex-wrap: wrap; gap: 3px; align-items: center; }
.fa-opt     { font-size: 9px; font-weight: 700; background: var(--post-bg); color: var(--post-fg); padding: 1px 5px; border-radius: 3px; }
.fa-badge   { font-size: 9px; font-weight: 600; background: var(--code-bg); color: var(--muted);   padding: 1px 5px; border-radius: 3px; }
.fa-default { font-size: 9px; font-weight: 500; background: var(--code-bg); color: var(--muted);   padding: 1px 5px; border-radius: 3px; font-family: var(--mono); }
.fa-depr    { font-size: 9px; font-weight: 700; background: var(--put-bg);  color: var(--put-fg);  padding: 1px 5px; border-radius: 3px; }
.fa-none    { color: var(--muted2); }

/* Enum chips */
.enum-chips { display: flex; flex-wrap: wrap; gap: 6px; padding: 12px 18px; }
.ev-chip {
  font-family: var(--mono);
  font-size: 12px;
  font-weight: 600;
  background: var(--ws-bg);
  color: var(--ws-fg);
  padding: 4px 12px;
  border-radius: var(--r5);
}

/* Flash highlight */
@keyframes ep-flash {
  0%   { outline: 2px solid var(--accent); outline-offset: 1px; }
  60%  { outline: 2px solid var(--accent); outline-offset: 3px; }
  100% { outline: 2px solid transparent;   outline-offset: 4px; }
}
.ep-flash { animation: ep-flash 1s ease-out forwards; }

/* Footer */
.footer {
  text-align: center;
  padding: 36px 0 20px;
  font-size: 12px;
  color: var(--muted2);
  border-top: 1px solid var(--divider);
  margin-top: 40px;
}

/* Mobile */
@media (max-width: 760px) {
  body { grid-template-columns: 1fr; }
  .sidebar { display: none; }
  .content { padding: 20px; }
  .topbar  { padding: 0 20px; }
  .ep-meta { grid-template-columns: 70px 1fr; }
}
</style>
</head>
<body>
`

// ── JavaScript ────────────────────────────────────────────────────────────────

const htmlScript = `<script>
// ── Theme ──
(function() {
  var t = localStorage.getItem('vt');
  if (t === 'dark') document.documentElement.setAttribute('data-theme', 'dark');
})();
function toggleTheme() {
  var dark = document.documentElement.getAttribute('data-theme') === 'dark';
  document.documentElement.setAttribute('data-theme', dark ? '' : 'dark');
  localStorage.setItem('vt', dark ? '' : 'dark');
  document.querySelector('.theme-btn').textContent = dark ? '\u{1F319}' : '\u2600\uFE0F';
}

// ── Endpoint expand / collapse ──
function toggleEp(header) {
  header.closest('.ep').classList.toggle('ep-open');
}

// ── Copy path ──
function copyPath(e, path) {
  e.stopPropagation();
  var btn = e.currentTarget;
  if (!navigator.clipboard) return;
  navigator.clipboard.writeText(path).then(function() {
    var orig = btn.textContent;
    btn.textContent = '\u2713';
    btn.style.cssText = 'opacity:1;color:var(--get);border-color:var(--get)';
    setTimeout(function() {
      btn.textContent = orig;
      btn.style.cssText = '';
    }, 1300);
  }).catch(function() {
    btn.textContent = '\u2717';
    setTimeout(function() { btn.textContent = '\u2398'; }, 1000);
  });
}

// ── Navigate to an element by id ──
function navigateTo(id) {
  var el = document.getElementById(id);
  if (!el) return;
  el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  el.classList.remove('ep-flash');
  void el.offsetWidth;
  el.classList.add('ep-flash');
  if (el.classList.contains('ep')) el.classList.add('ep-open');
  var bc = el.dataset.bc;
  if (!bc) { var p = el.closest('[data-bc]'); if (p) bc = p.dataset.bc; }
  if (bc) updateBreadcrumb(bc);
  updateActiveNav(id);
}

function updateBreadcrumb(t) {
  var el = document.getElementById('breadcrumbs');
  if (!el) return;
  var parts = t.split(' \u203a ');
  el.innerHTML = parts.map(function(s, i) {
    var last = i === parts.length - 1;
    return '<span class="bc-item' + (last ? ' bc-last' : '') + '">' + s + '</span>';
  }).join('<span class="bc-sep"> \u203a </span>');
}

function updateActiveNav(id) {
  document.querySelectorAll('.nav-ep, .nav-type').forEach(function(a) {
    a.classList.toggle('active', a.dataset.target === id);
  });
}

// ── Keyboard shortcuts ──
document.addEventListener('keydown', function(e) {
  var search = document.getElementById('nav-search');
  if (e.key === '/' && document.activeElement !== search) {
    e.preventDefault();
    search.focus();
    search.select();
  }
  if (e.key === 'Escape' && document.activeElement === search) {
    search.value = '';
    search.blur();
    filterNav('');
  }
});

// ── Search / filter nav ──
function filterNav(q) {
  q = q.toLowerCase().trim();
  var eps    = document.querySelectorAll('.nav-ep, .nav-type');
  var mods   = document.querySelectorAll('.nav-mod');
  var svcs   = document.querySelectorAll('.nav-svc');
  var groups = document.querySelectorAll('.nav-group');

  if (!q) {
    eps.forEach(function(a) { a.style.display = ''; });
    mods.forEach(function(m) { m.style.display = ''; m.classList.remove('collapsed'); });
    svcs.forEach(function(s) { s.style.display = ''; s.classList.remove('collapsed'); });
    groups.forEach(function(g) { g.style.display = ''; g.classList.remove('collapsed'); });
    return;
  }

  eps.forEach(function(a) {
    var text = (a.dataset.search || a.textContent).toLowerCase();
    a.style.display = text.indexOf(q) >= 0 ? '' : 'none';
  });
  mods.forEach(function(m) {
    var vis = Array.from(m.querySelectorAll('.nav-ep, .nav-type')).some(function(a) { return a.style.display !== 'none'; });
    m.style.display = vis ? '' : 'none';
    if (vis) m.classList.remove('collapsed');
  });
  svcs.forEach(function(s) {
    var vis = Array.from(s.querySelectorAll('.nav-ep, .nav-type')).some(function(a) { return a.style.display !== 'none'; });
    s.style.display = vis ? '' : 'none';
    if (vis) s.classList.remove('collapsed');
  });
  groups.forEach(function(g) {
    var vis = Array.from(g.querySelectorAll('.nav-type')).some(function(a) { return a.style.display !== 'none'; });
    g.style.display = vis ? '' : 'none';
    if (vis) g.classList.remove('collapsed');
  });
}

// ── Nav collapse toggles ──
function toggleSvc(el)   { el.closest('.nav-svc').classList.toggle('collapsed'); }
function toggleMod(el)   { el.closest('.nav-mod').classList.toggle('collapsed'); }
function toggleGroup(el) { el.closest('.nav-group').classList.toggle('collapsed'); }

// ── Intersection observer: breadcrumb + active nav on scroll ──
(function() {
  var els = document.querySelectorAll('[data-bc]');
  if (!els.length) return;
  var io = new IntersectionObserver(function(entries) {
    for (var i = 0; i < entries.length; i++) {
      if (entries[i].isIntersecting) {
        var bc = entries[i].target.dataset.bc;
        var id = entries[i].target.id;
        if (bc) updateBreadcrumb(bc);
        if (id) updateActiveNav(id);
        break;
      }
    }
  }, { rootMargin: '-56px 0px -72% 0px', threshold: 0 });
  els.forEach(function(el) { io.observe(el); });
})();
</script>
`
