// Package docsgen generates API documentation (HTML + Markdown) from a Veld AST.
package docsgen

import (
	"fmt"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// BuildMarkdown generates Markdown API documentation.
// services carries workspace grouping; pass nil for single-service mode.
func BuildMarkdown(a ast.AST, services []ServiceInfo) string {
	if len(services) == 0 {
		names := make([]string, len(a.Modules))
		for i, m := range a.Modules {
			names[i] = m.Name
		}
		services = []ServiceInfo{{Name: "API", ModuleNames: names}}
	}

	moduleByName := make(map[string]ast.Module, len(a.Modules))
	for _, mod := range a.Modules {
		moduleByName[mod.Name] = mod
	}

	multiService := len(services) > 1

	var sb strings.Builder
	sb.WriteString("# API Documentation\n\n")
	sb.WriteString("*Generated by Veld*\n\n")

	// ── Table of contents ──
	sb.WriteString("## Table of Contents\n\n")
	for _, svc := range services {
		if multiService {
			sb.WriteString(fmt.Sprintf("- **%s**", svc.Name))
			if svc.BaseUrl != "" {
				sb.WriteString(fmt.Sprintf(" — `%s`", svc.BaseUrl))
			}
			sb.WriteString("\n")
		}
		for _, mn := range svc.ModuleNames {
			mod, ok := moduleByName[mn]
			if !ok {
				continue
			}
			if multiService {
				sb.WriteString(fmt.Sprintf("  - [%s](#%s)\n", mod.Name, strings.ToLower(mod.Name)))
			} else {
				sb.WriteString(fmt.Sprintf("- [%s](#%s)\n", mod.Name, strings.ToLower(mod.Name)))
			}
		}
	}
	if len(a.Models) > 0 {
		sb.WriteString("- [Models](#models)\n")
		for _, m := range a.Models {
			sb.WriteString(fmt.Sprintf("  - [%s](#%s)\n", m.Name, strings.ToLower(m.Name)))
		}
	}
	if len(a.Enums) > 0 {
		sb.WriteString("- [Enums](#enums)\n")
		for _, en := range a.Enums {
			sb.WriteString(fmt.Sprintf("  - [%s](#%s)\n", en.Name, strings.ToLower(en.Name)))
		}
	}
	sb.WriteString("\n---\n\n")

	// ── Services / Modules / Actions ──
	for _, svc := range services {
		if multiService {
			sb.WriteString(fmt.Sprintf("## Service: %s\n\n", svc.Name))
			if svc.Description != "" {
				sb.WriteString(svc.Description + "\n\n")
			}
			if svc.BaseUrl != "" {
				sb.WriteString(fmt.Sprintf("**Base URL:** `%s`\n\n", svc.BaseUrl))
			}
		}

		for _, mn := range svc.ModuleNames {
			mod, ok := moduleByName[mn]
			if !ok {
				continue
			}

			if multiService {
				sb.WriteString(fmt.Sprintf("### %s\n\n", mod.Name))
			} else {
				sb.WriteString(fmt.Sprintf("## %s\n\n", mod.Name))
			}
			if mod.Description != "" {
				sb.WriteString(mod.Description + "\n\n")
			}
			if mod.Prefix != "" {
				sb.WriteString(fmt.Sprintf("**Prefix:** `%s`\n\n", mod.Prefix))
			}

			sb.WriteString("| Method | Path | Name | Input | Output | Description |\n")
			sb.WriteString("|--------|------|------|-------|--------|-------------|\n")
			for _, act := range mod.Actions {
				routePath := act.Path
				if mod.Prefix != "" {
					routePath = mod.Prefix + act.Path
				}
				input := "—"
				if act.Input != "" {
					input = "`" + act.Input + "`"
				}
				output := "—"
				if act.Output != "" {
					o := act.Output
					if act.OutputArray {
						o += "[]"
					}
					output = "`" + o + "`"
				}
				dep := ""
				if act.Deprecated != "" {
					dep = " ⚠️"
				}
				sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %s%s | %s | %s | %s |\n",
					act.Method, routePath, act.Name, dep, input, output, act.Description))
			}
			sb.WriteString("\n")
		}

		if multiService {
			sb.WriteString("---\n\n")
		}
	}

	// ── Models ──
	if len(a.Models) > 0 {
		sb.WriteString("## Models\n\n")
		for _, m := range a.Models {
			sb.WriteString(fmt.Sprintf("### %s\n\n", m.Name))
			if m.Description != "" {
				sb.WriteString(m.Description + "\n\n")
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("*Extends `%s`*\n\n", m.Extends))
			}
			// Show usages
			usedBy := collectModelUsages(a, m.Name)
			if len(usedBy) > 0 {
				sb.WriteString("**Used by:** " + strings.Join(usedBy, ", ") + "\n\n")
			}

			sb.WriteString("| Field | Type | Optional | Default | Attributes |\n")
			sb.WriteString("|-------|------|----------|---------|------------|\n")
			for _, f := range m.Fields {
				typeName := f.Type
				if f.IsArray {
					typeName += "[]"
				}
				if f.IsMap {
					typeName = fmt.Sprintf("Map<string, %s>", f.MapValueType)
				}
				opt := ""
				if f.Optional {
					opt = "✓"
				}
				attrs := ""
				if f.Unique {
					attrs += "unique "
				}
				if f.Index {
					attrs += "index "
				}
				if f.Relation != "" {
					attrs += "→" + f.Relation + " "
				}
				if f.Deprecated != "" {
					attrs += "⚠️deprecated "
				}
				sb.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s | %s |\n", f.Name, typeName, opt, f.Default, strings.TrimSpace(attrs)))
			}
			sb.WriteString("\n")
		}
	}

	// ── Enums ──
	if len(a.Enums) > 0 {
		sb.WriteString("## Enums\n\n")
		for _, en := range a.Enums {
			sb.WriteString(fmt.Sprintf("### %s\n\n", en.Name))
			if en.Description != "" {
				sb.WriteString(en.Description + "\n\n")
			}
			usedBy := collectEnumUsages(a, en.Name)
			if len(usedBy) > 0 {
				sb.WriteString("**Used by:** " + strings.Join(usedBy, ", ") + "\n\n")
			}
			sb.WriteString("Values: `" + strings.Join(en.Values, "`, `") + "`\n\n")
		}
	}
	return sb.String()
}
