// Package docsgen generates API documentation (HTML + Markdown) from a Veld AST.
package docsgen

import (
	"fmt"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// BuildMarkdown generates Markdown API documentation.
func BuildMarkdown(a ast.AST) string {
	var sb strings.Builder
	sb.WriteString("# API Documentation\n\n")
	sb.WriteString("*Generated by Veld*\n\n")

	sb.WriteString("## Modules\n\n")
	for _, mod := range a.Modules {
		sb.WriteString(fmt.Sprintf("- [%s](#%s)\n", mod.Name, strings.ToLower(mod.Name)))
	}
	sb.WriteString("\n")

	for _, mod := range a.Modules {
		sb.WriteString(fmt.Sprintf("## %s\n\n", mod.Name))
		if mod.Description != "" {
			sb.WriteString(mod.Description + "\n\n")
		}
		sb.WriteString("| Method | Path | Name | Description |\n")
		sb.WriteString("|--------|------|------|-------------|\n")
		for _, act := range mod.Actions {
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s |\n", act.Method, routePath, act.Name, act.Description))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Models\n\n")
	for _, m := range a.Models {
		sb.WriteString(fmt.Sprintf("### %s\n\n", m.Name))
		if m.Description != "" {
			sb.WriteString(m.Description + "\n\n")
		}
		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("*Extends %s*\n\n", m.Extends))
		}
		sb.WriteString("| Field | Type | Optional | Default |\n")
		sb.WriteString("|-------|------|----------|---------|\n")
		for _, f := range m.Fields {
			typeName := f.Type
			if f.IsArray {
				typeName += "[]"
			}
			if f.IsMap {
				typeName = fmt.Sprintf("Map<string, %s>", f.MapValueType)
			}
			opt := ""
			if f.Optional {
				opt = "yes"
			}
			sb.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s |\n", f.Name, typeName, opt, f.Default))
		}
		sb.WriteString("\n")
	}

	if len(a.Enums) > 0 {
		sb.WriteString("## Enums\n\n")
		for _, en := range a.Enums {
			sb.WriteString(fmt.Sprintf("### %s\n\n", en.Name))
			if en.Description != "" {
				sb.WriteString(en.Description + "\n\n")
			}
			sb.WriteString("Values: `" + strings.Join(en.Values, "`, `") + "`\n\n")
		}
	}
	return sb.String()
}
