// AUTO-GENERATED BY VELD — DO NOT EDIT

package routes

import (
	"net/http"

	"example.com/veld-generated/internal/interfaces"
	"example.com/veld-generated/internal/models"
	"github.com/go-chi/chi/v5"
)

// setupAuthRoutes registers the Auth module routes.
func setupAuthRoutes(r chi.Router, authSvc interfaces.AuthService) {
	r.Post("/auth/login", loginHandler(authSvc))
	r.Post("/auth/register", registerHandler(authSvc))
	r.Get("/auth/current_user", meHandler(authSvc))
	r.Post("/auth/logout", logoutHandler(authSvc))
}

// loginHandler handles POST /auth/login requests.
func loginHandler(svc interfaces.AuthService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req models.LoginInput
		if err := readJSON(r, &req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]interface{}{"error": "invalid request body"})
			return
		}

		resp, err := svc.Login(r.Context(), &req)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
			return
		}

		writeJSON(w, http.StatusCreated, resp)
	}
}

// registerHandler handles POST /auth/register requests.
func registerHandler(svc interfaces.AuthService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req models.RegisterInput
		if err := readJSON(r, &req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]interface{}{"error": "invalid request body"})
			return
		}

		resp, err := svc.Register(r.Context(), &req)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
			return
		}

		writeJSON(w, http.StatusCreated, resp)
	}
}

// meHandler handles GET /auth/current_user requests.
func meHandler(svc interfaces.AuthService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		resp, err := svc.Me(r.Context())
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
			return
		}

		writeJSON(w, http.StatusOK, resp)
	}
}

// logoutHandler handles POST /auth/logout requests.
func logoutHandler(svc interfaces.AuthService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		resp, err := svc.Logout(r.Context())
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
			return
		}

		writeJSON(w, http.StatusCreated, resp)
	}
}
