// AUTO-GENERATED BY VELD — DO NOT EDIT

package routes

import (
	"net/http"

	"example.com/veld-generated/internal/interfaces"
	"example.com/veld-generated/internal/models"
	"github.com/go-chi/chi/v5"
)

// setupfoodRoutes registers the food module routes.
func setupfoodRoutes(r chi.Router, foodSvc interfaces.FoodService) {
	r.Get("/food/all", getAllFoodsHandler(foodSvc))
	r.Post("/food", addFoodHandler(foodSvc))
}

// getAllFoodsHandler handles GET /food/all requests.
func getAllFoodsHandler(svc interfaces.FoodService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		resp, err := svc.GetAllFoods(r.Context())
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
			return
		}

		writeJSON(w, http.StatusOK, resp)
	}
}

// addFoodHandler handles POST /food requests.
func addFoodHandler(svc interfaces.FoodService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req models.CreateFoodInput
		if err := readJSON(r, &req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]interface{}{"error": "invalid request body"})
			return
		}

		resp, err := svc.AddFood(r.Context(), &req)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
			return
		}

		writeJSON(w, http.StatusCreated, resp)
	}
}
