// AUTO-GENERATED BY VELD — DO NOT EDIT

package models

// LoginInput is a generated data model.
type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterInput is a generated data model.
type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

// User is a generated data model.
type User struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

// SuccessResponse is a generated data model.
type SuccessResponse struct {
	Success bool `json:"success"`
}

// Food is a generated data model.
type Food struct {
	Id    string   `json:"id"`
	Name  string   `json:"name"`
	Price int64    `json:"price"`
	Tags  []string `json:"tags"`
	Type  string   `json:"type"`
}

// FoodList is a generated data model.
type FoodList struct {
	Items []Food `json:"items"`
	Total int64  `json:"total"`
}

// CreateFoodInput is a generated data model.
type CreateFoodInput struct {
	Name  string   `json:"name"`
	Price int64    `json:"price"`
	Tags  []string `json:"tags"`
	Type  string   `json:"type"`
}
