package csharp_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
	"github.com/veld-dev/veld/internal/emitter/backend/csharp"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

func TestCSharpEmitterEmit(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "VeldGenerated.csproj"),
		filepath.Join(outDir, "Models", "LoginInput.cs"),
		filepath.Join(outDir, "Models", "User.cs"),
		filepath.Join(outDir, "Models", "Role.cs"),
		filepath.Join(outDir, "Services", "IAuthService.cs"),
		filepath.Join(outDir, "Controllers", "AuthController.cs"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestCSharpEmitterDryRun(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, got %d entries", len(entries))
	}
}

func TestCSharpEmitterModelContent(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "Models", "User.cs"))
	if err != nil {
		t.Fatalf("ReadFile User.cs: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"namespace", "namespace VeldGenerated.Models;"},
		{"list using", "using System.Collections.Generic;"},
		{"record declaration", "public record User("},
		{"string field", "string Email"},
		{"list field", "List<string> Tags"},
		{"nullable optional", "string? Bio"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("User.cs missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestCSharpEmitterEnumContent(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "Models", "Role.cs"))
	if err != nil {
		t.Fatalf("ReadFile Role.cs: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"JsonConverter attribute", "[JsonConverter(typeof(JsonStringEnumConverter))]"},
		{"enum declaration", "public enum Role"},
		{"Admin member", "Admin,"},
		{"EnumMember attribute", `[System.Runtime.Serialization.EnumMember(Value = "admin")]`},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("Role.cs missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestCSharpEmitterInterfaceContent(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "Services", "IAuthService.cs"))
	if err != nil {
		t.Fatalf("ReadFile IAuthService.cs: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"namespace", "namespace VeldGenerated.Services;"},
		{"interface", "public interface IAuthService"},
		{"login method", "Task<User> Login(LoginInput input);"},
		{"me method", "Task<User> Me();"},
		{"logout void", "Task Logout();"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("IAuthService.cs missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestCSharpEmitterControllerContent(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "Controllers", "AuthController.cs"))
	if err != nil {
		t.Fatalf("ReadFile AuthController.cs: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"api controller", "[ApiController]"},
		{"route attribute", "[Route(\"api\")]"},
		{"class", "public class AuthController : ControllerBase"},
		{"constructor", "public AuthController(IAuthService service)"},
		{"post attribute", `[HttpPost("/auth/login")]`},
		{"get attribute", `[HttpGet("/auth/me")]`},
		{"delete attribute", `[HttpDelete("/auth/logout")]`},
		{"from body", "[FromBody]"},
		{"post 201", "return StatusCode(201, result);"},
		{"delete no content", "return NoContent();"},
		{"try/catch", "catch (Exception e)"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("AuthController.cs missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestCSharpEmitterPathParams(t *testing.T) {
	e := csharp.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "Controllers", "ItemsController.cs"))
	content := string(data)

	// ASP.NET Core uses {id} syntax.
	if strings.Contains(content, `"/items/:id"`) {
		t.Error("controller should use {id} not :id")
	}
	if !strings.Contains(content, `"/items/{id}"`) {
		t.Errorf("controller should use {id} ASP.NET Core syntax:\n%s", content)
	}
	if !strings.Contains(content, "[FromRoute] string Id") {
		t.Errorf("controller should have [FromRoute] string Id param:\n%s", content)
	}
}

func TestCSharpEmitterSummary(t *testing.T) {
	e := csharp.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}
	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	for _, want := range []string{"Models/", "Services/", "Controllers/", "./"} {
		if !dirs[want] {
			t.Errorf("Summary() missing dir %q", want)
		}
	}
}

func TestCSharpEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("csharp"); err != nil {
		t.Errorf("csharp backend not registered: %v", err)
	}
}
