package csharp

// errors.go — emits error handling middleware for ASP.NET Core.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// emitErrorHandling writes Models/ApiErrorResponse.cs and Middleware/ErrorHandlingMiddleware.cs.
func (e *CSharpEmitter) emitErrorHandling(outDir string) error {
	// Ensure Middleware directory exists
	mwDir := filepath.Join(outDir, "Middleware")
	if err := os.MkdirAll(mwDir, 0755); err != nil {
		return err
	}

	// ApiErrorResponse
	modelsDir := filepath.Join(outDir, "Models")
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("namespace %s.Models;\n\n", csNamespace))
	sb.WriteString("/// <summary>Standard API error response.</summary>\n")
	sb.WriteString("public record ApiErrorResponse(\n")
	sb.WriteString("    int Code,\n")
	sb.WriteString("    string Message,\n")
	sb.WriteString("    string? Details\n")
	sb.WriteString(");\n")
	if err := os.WriteFile(filepath.Join(modelsDir, "ApiErrorResponse.cs"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	// ErrorHandlingMiddleware
	var mw strings.Builder
	mw.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	mw.WriteString("using System.Net;\n")
	mw.WriteString("using System.Text.Json;\n")
	mw.WriteString(fmt.Sprintf("using %s.Models;\n\n", csNamespace))
	mw.WriteString(fmt.Sprintf("namespace %s.Middleware;\n\n", csNamespace))

	mw.WriteString("/// <summary>Global error handling middleware that catches exceptions and returns JSON errors.</summary>\n")
	mw.WriteString("public class ErrorHandlingMiddleware\n{\n")
	mw.WriteString("    private readonly RequestDelegate _next;\n")
	mw.WriteString("    private readonly ILogger<ErrorHandlingMiddleware> _logger;\n\n")

	mw.WriteString("    public ErrorHandlingMiddleware(RequestDelegate next, ILogger<ErrorHandlingMiddleware> logger)\n")
	mw.WriteString("    {\n")
	mw.WriteString("        _next = next;\n")
	mw.WriteString("        _logger = logger;\n")
	mw.WriteString("    }\n\n")

	mw.WriteString("    public async Task InvokeAsync(HttpContext context)\n")
	mw.WriteString("    {\n")
	mw.WriteString("        try\n")
	mw.WriteString("        {\n")
	mw.WriteString("            await _next(context);\n")
	mw.WriteString("        }\n")
	mw.WriteString("        catch (ValidationException ex)\n")
	mw.WriteString("        {\n")
	mw.WriteString("            _logger.LogWarning(ex, \"Validation error\");\n")
	mw.WriteString("            context.Response.StatusCode = (int)HttpStatusCode.BadRequest;\n")
	mw.WriteString("            context.Response.ContentType = \"application/json\";\n")
	mw.WriteString("            var error = new ApiErrorResponse(400, \"Validation failed\", ex.Message);\n")
	mw.WriteString("            await context.Response.WriteAsync(JsonSerializer.Serialize(error));\n")
	mw.WriteString("        }\n")
	mw.WriteString("        catch (Exception ex)\n")
	mw.WriteString("        {\n")
	mw.WriteString("            _logger.LogError(ex, \"Unhandled exception\");\n")
	mw.WriteString("            context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;\n")
	mw.WriteString("            context.Response.ContentType = \"application/json\";\n")
	mw.WriteString("            var error = new ApiErrorResponse(500, \"Internal server error\", null);\n")
	mw.WriteString("            await context.Response.WriteAsync(JsonSerializer.Serialize(error));\n")
	mw.WriteString("        }\n")
	mw.WriteString("    }\n")
	mw.WriteString("}\n")

	return os.WriteFile(filepath.Join(mwDir, "ErrorHandlingMiddleware.cs"), []byte(mw.String()), 0644)
}
