package csharp

// sdk.go — service SDK generation for C# backend.
// Generates typed HTTP clients using System.Net.Http.HttpClient.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
)

func (e *CSharpEmitter) EmitServiceSdk(consumed []emitter.ConsumedServiceInfo, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun || len(consumed) == 0 {
		return nil
	}
	for _, c := range consumed {
		if err := emitCSharpSdk(c, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", c.Name, err)
		}
	}
	return nil
}

func emitCSharpSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	dir := filepath.Join(outDir, "Sdk", capitalize(consumed.Name))
	modelsDir := filepath.Join(dir, "Models")
	if err := os.MkdirAll(modelsDir, 0755); err != nil {
		return err
	}
	if err := emitCSharpSdkTypes(consumed, modelsDir); err != nil {
		return err
	}
	return emitCSharpSdkClient(consumed, dir)
}

func emitCSharpSdkTypes(consumed emitter.ConsumedServiceInfo, modelsDir string) error {
	a := consumed.AST
	modelGroups, enumGroups, _, _ := emitter.AssignModelsToModules(a)
	keys := emitter.SortedGroupKeys(modelGroups, enumGroups)

	for _, group := range keys {
		var sb strings.Builder
		sb.WriteString("// Code generated by Veld — DO NOT EDIT.\nusing System.Text.Json.Serialization;\n\nnamespace Veld.Generated.Sdk;\n\n")

		for _, en := range enumGroups[group] {
			sb.WriteString("[JsonConverter(typeof(JsonStringEnumConverter))]\n")
			sb.WriteString(fmt.Sprintf("public enum %s\n{\n", en.Name))
			for _, v := range en.Values {
				sb.WriteString(fmt.Sprintf("    %s,\n", capitalize(v)))
			}
			sb.WriteString("}\n\n")
		}

		for _, m := range modelGroups[group] {
			sb.WriteString(fmt.Sprintf("public class %s\n{\n", m.Name))
			for _, f := range m.Fields {
				csType := csSdkType(f)
				if f.Optional {
					csType += "?"
				}
				sb.WriteString(fmt.Sprintf("    [JsonPropertyName(%q)]\n    public %s %s { get; set; }\n\n", f.Name, csType, capitalize(f.Name)))
			}
			sb.WriteString(fmt.Sprintf("    public %s() { }\n\n", m.Name))
			if len(m.Fields) > 0 {
				var ctorParams []string
				for _, f := range m.Fields {
					csType := csSdkType(f)
					if f.Optional {
						csType += "?"
					}
					ctorParams = append(ctorParams, fmt.Sprintf("%s %s", csType, csCamelCase(f.Name)))
				}
				sb.WriteString(fmt.Sprintf("    public %s(%s)\n    {\n", m.Name, strings.Join(ctorParams, ", ")))
				for _, f := range m.Fields {
					sb.WriteString(fmt.Sprintf("        %s = %s;\n", capitalize(f.Name), csCamelCase(f.Name)))
				}
				sb.WriteString("    }\n")
			}
			sb.WriteString("}\n\n")
		}

		filename := capitalize(group) + "Models.cs"
		if err := os.WriteFile(filepath.Join(modelsDir, filename), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	return nil
}

func emitCSharpSdkClient(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString("using System.Net.Http;\nusing System.Net.Http.Json;\nusing System.Text;\nusing System.Text.Json;\n\nnamespace Veld.Generated.Sdk;\n\n")

	sb.WriteString(fmt.Sprintf("public class %s\n{\n", className))
	sb.WriteString("    private readonly string _base;\n    private readonly HttpClient _client;\n    private readonly Dictionary<string, string> _headers;\n\n")

	sb.WriteString(fmt.Sprintf("    public %s(string? baseUrl = null, Dictionary<string, string>? headers = null)\n    {\n", className))
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("        _base = baseUrl ?? Environment.GetEnvironmentVariable(%q) ?? %q;\n", envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("        _base = baseUrl ?? Environment.GetEnvironmentVariable(%q)\n", envVar))
		sb.WriteString(fmt.Sprintf("            ?? throw new ArgumentException(\"No base URL for %s — pass baseUrl or set %s\");\n", consumed.Name, envVar))
	}
	sb.WriteString("        _client = new HttpClient();\n        _headers = headers ?? new();\n    }\n\n")

	sb.WriteString("    private async Task<string> RequestAsync(HttpMethod method, string path, object? body = null)\n    {\n")
	sb.WriteString("        var req = new HttpRequestMessage(method, _base + path);\n")
	sb.WriteString("        foreach (var (k, v) in _headers) req.Headers.TryAddWithoutValidation(k, v);\n")
	sb.WriteString("        if (body != null) req.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, \"application/json\");\n")
	sb.WriteString("        var res = await _client.SendAsync(req);\n")
	sb.WriteString("        var text = await res.Content.ReadAsStringAsync();\n")
	sb.WriteString("        if (!res.IsSuccessStatusCode) throw new HttpRequestException($\"HTTP {(int)res.StatusCode}: {text}\");\n")
	sb.WriteString("        return text;\n    }\n")

	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				continue
			}
			sb.WriteString("\n")
			writeCSharpSdkMethod(&sb, mod, act)
		}
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, className+".cs"), []byte(sb.String()), 0644)
}

func writeCSharpSdkMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	methodName := capitalize(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	retType := "Task"
	if act.Output != "" {
		retType = "Task<string>"
	}

	var params []string
	for _, p := range pathParams {
		params = append(params, "string "+p)
	}
	if act.Input != "" {
		params = append(params, "object body")
	}

	sb.WriteString(fmt.Sprintf("    /// <summary>%s %s</summary>\n", method, routePath))
	sb.WriteString(fmt.Sprintf("    public async %s %sAsync(%s)\n    {\n", retType, methodName, strings.Join(params, ", ")))

	urlExpr := csSdkBuildUrl(routePath, pathParams)
	bodyArg := "null"
	if act.Input != "" {
		bodyArg = "body"
	}

	httpMethod := fmt.Sprintf("HttpMethod.%s", capitalize(strings.ToLower(method)))
	if method == "PATCH" {
		httpMethod = "new HttpMethod(\"PATCH\")"
	}

	if act.Output != "" {
		sb.WriteString(fmt.Sprintf("        return await RequestAsync(%s, %s, %s);\n    }\n", httpMethod, urlExpr, bodyArg))
	} else {
		sb.WriteString(fmt.Sprintf("        await RequestAsync(%s, %s, %s);\n    }\n", httpMethod, urlExpr, bodyArg))
	}
}

func csSdkBuildUrl(routePath string, pathParams []string) string {
	if len(pathParams) == 0 {
		return fmt.Sprintf("%q", routePath)
	}
	expr := routePath
	for _, p := range pathParams {
		expr = strings.Replace(expr, ":"+p, "{"+p+"}", 1)
	}
	return "$\"" + expr + "\""
}

func csSdkType(f ast.Field) string {
	base := csSdkScalar(f.Type)
	if f.IsArray {
		return "List<" + base + ">"
	}
	if f.IsMap {
		return "Dictionary<string, " + csSdkScalar(f.MapValueType) + ">"
	}
	return base
}

func csSdkScalar(t string) string {
	switch t {
	case "string", "uuid":
		return "string"
	case "int":
		return "long"
	case "float":
		return "double"
	case "decimal":
		return "decimal"
	case "bool":
		return "bool"
	case "date", "datetime":
		return "DateTime"
	case "any", "json":
		return "object"
	default:
		return t
	}
}
