package csharp

// validation.go — emits a ValidationHelper.cs with DataAnnotations-based validation.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// emitValidationHelper writes Models/ValidationHelper.cs.
func (e *CSharpEmitter) emitValidationHelper(outDir string) error {
	dir := filepath.Join(outDir, "Models")

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("using System.ComponentModel.DataAnnotations;\n")
	sb.WriteString("using System.Collections.Generic;\n")
	sb.WriteString("using System.Linq;\n\n")
	sb.WriteString(fmt.Sprintf("namespace %s.Models;\n\n", csNamespace))

	sb.WriteString("/// <summary>Shared validation utility for all Veld-generated models.</summary>\n")
	sb.WriteString("public static class ValidationHelper\n{\n")
	sb.WriteString("    public record ValidationError(string Field, string Message);\n\n")

	sb.WriteString("    /// <summary>Validates an object using DataAnnotations.</summary>\n")
	sb.WriteString("    public static List<ValidationError> Validate<T>(T obj) where T : notnull\n")
	sb.WriteString("    {\n")
	sb.WriteString("        var context = new ValidationContext(obj);\n")
	sb.WriteString("        var results = new List<ValidationResult>();\n")
	sb.WriteString("        Validator.TryValidateObject(obj, context, results, true);\n")
	sb.WriteString("        return results.Select(r => new ValidationError(\n")
	sb.WriteString("            r.MemberNames.FirstOrDefault() ?? \"unknown\",\n")
	sb.WriteString("            r.ErrorMessage ?? \"validation failed\")).ToList();\n")
	sb.WriteString("    }\n\n")

	sb.WriteString("    /// <summary>Validates and throws if there are errors.</summary>\n")
	sb.WriteString("    public static void ValidateOrThrow<T>(T obj) where T : notnull\n")
	sb.WriteString("    {\n")
	sb.WriteString("        var errors = Validate(obj);\n")
	sb.WriteString("        if (errors.Count > 0)\n")
	sb.WriteString("        {\n")
	sb.WriteString("            var msg = string.Join(\"; \", errors.Select(e => $\"{e.Field}: {e.Message}\"));\n")
	sb.WriteString("            throw new ValidationException($\"Validation failed: {msg}\");\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "ValidationHelper.cs"), []byte(sb.String()), 0644)
}

// csValidationAttributes returns DataAnnotation attributes for a field.
func csValidationAttributes(f ast.Field) []string {
	var attrs []string

	if !f.Optional {
		attrs = append(attrs, "    [Required]")
	}
	if f.Type == "string" && !f.IsArray && !f.IsMap && !f.Optional {
		attrs = append(attrs, "    [MinLength(1)]")
	}
	if strings.Contains(strings.ToLower(f.Name), "email") {
		attrs = append(attrs, "    [EmailAddress]")
	}
	if strings.HasSuffix(strings.ToLower(f.Name), "url") {
		attrs = append(attrs, "    [Url]")
	}

	return attrs
}
