// AUTO-GENERATED BY VELD — DO NOT EDIT

package interfaces

import (
	"context"

	"example.com/veld-generated/internal/models"
)

// AuthService defines the contract for Auth business logic.
// Implement this interface in your application code.
type AuthService interface {
	Login(ctx context.Context, input *models.LoginInput) (*models.User, error)
	Register(ctx context.Context, input *models.RegisterInput) (*models.User, error)
	Me(ctx context.Context) (*models.User, error)
	Logout(ctx context.Context) (*models.SuccessResponse, error)
}
