package php

// errors.go — emits:
//   app/Exceptions/ApiException.php — base class
//   app/Exceptions/{convenience}.php — 7 convenience subclasses
//   app/Exceptions/ErrorHelpers.php — free-standing helper functions
//   app/Exceptions/VeldExceptionHandler.php — Laravel handler
//   errors/{Action}Exception.php — per-action typed exception
//   errors/{Module}Errors.php — per-module error factory class
//
// Per-action + per-module errors in errors/ folder, base in app/Exceptions.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// emitAllErrors generates the full errors/ directory + base exceptions in one shot.
func (e *PhpEmitter) emitAllErrors(a ast.AST, outDir string) error {
	excDir := filepath.Join(outDir, "app", "Exceptions")
	if err := os.MkdirAll(excDir, 0755); err != nil {
		return err
	}
	errDir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(errDir, 0755); err != nil {
		return err
	}

	// Base ApiException
	if err := emitPhpApiException(excDir); err != nil {
		return err
	}
	// 7 convenience subclasses
	if err := emitPhpConvenienceExceptions(excDir); err != nil {
		return err
	}
	// Helper functions
	if err := emitPhpErrorHelpers(excDir); err != nil {
		return err
	}
	// Laravel exception handler
	if err := emitPhpExceptionHandler(excDir); err != nil {
		return err
	}
	// Per-action typed exceptions
	for _, mod := range a.Modules {
		if err := emitPhpActionExceptions(mod, errDir); err != nil {
			return fmt.Errorf("action exceptions %s: %w", mod.Name, err)
		}
	}
	// Per-module error factories
	for _, mod := range a.Modules {
		if err := emitPhpModuleErrorFactories(mod, errDir); err != nil {
			return fmt.Errorf("module errors %s: %w", mod.Name, err)
		}
	}
	return nil
}

func emitPhpApiException(dir string) error {
	var sb strings.Builder
	sb.WriteString("<?php\n\n// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("declare(strict_types=1);\n\nnamespace App\\Exceptions;\n\n")
	sb.WriteString("use RuntimeException;\nuse DateTimeImmutable;\nuse DateTimeInterface;\n\n")
	sb.WriteString("class ApiException extends RuntimeException\n{\n")
	sb.WriteString("    public readonly string $timestamp;\n\n")
	sb.WriteString("    public function __construct(\n")
	sb.WriteString("        public readonly string $code,\n")
	sb.WriteString("        public readonly int $status,\n")
	sb.WriteString("        string $message = '',\n")
	sb.WriteString("    ) {\n")
	sb.WriteString("        parent::__construct($message ?: $code);\n")
	sb.WriteString("        $this->timestamp = (new DateTimeImmutable())->format(DateTimeInterface::ATOM);\n")
	sb.WriteString("    }\n\n")
	sb.WriteString("    public function toArray(): array\n    {\n")
	sb.WriteString("        return ['error' => $this->getMessage(), 'code' => $this->code, 'status' => $this->status];\n")
	sb.WriteString("    }\n\n")
	sb.WriteString("    public function isErrorCode(string $errorCode): bool { return $this->code === $errorCode; }\n")
	sb.WriteString("    public function isHttpStatus(int $httpStatus): bool { return $this->status === $httpStatus; }\n")
	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, "ApiException.php"), []byte(sb.String()), 0644)
}

func emitPhpConvenienceExceptions(dir string) error {
	type errDef struct {
		name, msg, codeConst string
		status               int
	}
	defs := []errDef{
		{"NotFoundException", "Not Found", "NOT_FOUND", 404},
		{"BadRequestException", "Bad Request", "BAD_REQUEST", 400},
		{"UnauthorizedException", "Unauthorized", "UNAUTHORIZED", 401},
		{"ForbiddenException", "Forbidden", "FORBIDDEN", 403},
		{"ConflictException", "Conflict", "CONFLICT", 409},
		{"ValidationException", "Validation Failed", "VALIDATION_FAILED", 422},
		{"InternalException", "Internal Server Error", "INTERNAL_SERVER_ERROR", 500},
	}
	for _, d := range defs {
		var sb strings.Builder
		sb.WriteString("<?php\n\n// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
		sb.WriteString("declare(strict_types=1);\n\nnamespace App\\Exceptions;\n\n")
		sb.WriteString(fmt.Sprintf("class %s extends ApiException\n{\n", d.name))
		sb.WriteString("    public function __construct(?string $message = null, ?string $code = null)\n    {\n")
		sb.WriteString(fmt.Sprintf("        parent::__construct($code ?? '%s', %d, $message ?? '%s');\n", d.codeConst, d.status, d.msg))
		sb.WriteString("    }\n}\n")
		if err := os.WriteFile(filepath.Join(dir, d.name+".php"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	return nil
}

func emitPhpErrorHelpers(dir string) error {
	var sb strings.Builder
	sb.WriteString("<?php\n\n// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("declare(strict_types=1);\n\nnamespace App\\Exceptions;\n\nuse Throwable;\n\n")
	sb.WriteString("function is_api_exception(Throwable $e): bool { return $e instanceof ApiException; }\n\n")
	sb.WriteString("function is_error_code(Throwable $e, string $code): bool {\n")
	sb.WriteString("    return $e instanceof ApiException && $e->code === $code;\n}\n\n")
	sb.WriteString("function to_error_response(Throwable $e): array {\n")
	sb.WriteString("    if ($e instanceof ApiException) return $e->toArray();\n")
	sb.WriteString("    return ['error' => $e->getMessage(), 'code' => 'INTERNAL_ERROR', 'status' => 500];\n}\n\n")
	sb.WriteString("function error_handler(Throwable $e): array {\n")
	sb.WriteString("    $resp = to_error_response($e);\n")
	sb.WriteString("    return [['error' => $resp['error'], 'code' => $resp['code']], $resp['status']];\n}\n")
	return os.WriteFile(filepath.Join(dir, "ErrorHelpers.php"), []byte(sb.String()), 0644)
}

func emitPhpExceptionHandler(dir string) error {
	var sb strings.Builder
	sb.WriteString("<?php\n\n// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("declare(strict_types=1);\n\nnamespace App\\Exceptions;\n\n")
	sb.WriteString("use Illuminate\\Foundation\\Exceptions\\Handler as ExceptionHandler;\n")
	sb.WriteString("use Illuminate\\Http\\JsonResponse;\nuse Throwable;\n\n")
	sb.WriteString("class VeldExceptionHandler extends ExceptionHandler\n{\n")
	sb.WriteString("    public function render($request, Throwable $e): JsonResponse\n    {\n")
	sb.WriteString("        if ($e instanceof ApiException) {\n")
	sb.WriteString("            return response()->json(['error' => $e->getMessage(), 'code' => $e->code], $e->status);\n")
	sb.WriteString("        }\n")
	sb.WriteString("        return response()->json(['error' => 'Internal server error', 'code' => 'INTERNAL_ERROR'], 500);\n")
	sb.WriteString("    }\n}\n")
	return os.WriteFile(filepath.Join(dir, "VeldExceptionHandler.php"), []byte(sb.String()), 0644)
}

// emitPhpActionExceptions writes per-action typed exception classes.
func emitPhpActionExceptions(mod ast.Module, dir string) error {
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		className := capitalize(act.Name) + "Exception"

		var sb strings.Builder
		sb.WriteString("<?php\n\n// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
		sb.WriteString("declare(strict_types=1);\n\nnamespace App\\Errors;\n\n")
		sb.WriteString("use App\\Exceptions\\ApiException;\n\n")
		sb.WriteString(fmt.Sprintf("class %s extends ApiException\n{\n", className))

		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			methodName := emitter.ToCamelCase(errName)
			sb.WriteString(fmt.Sprintf("    public static function %s(?string $message = null): self\n    {\n", methodName))
			sb.WriteString(fmt.Sprintf("        return new self('%s', %d, $message ?? '%s');\n    }\n\n", code, status, errName))
		}

		sb.WriteString("}\n")
		if err := os.WriteFile(filepath.Join(dir, className+".php"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	return nil
}

// emitPhpModuleErrorFactories writes per-module aggregate error factory classes.
func emitPhpModuleErrorFactories(mod ast.Module, dir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	className := mod.Name + "Errors"
	var sb strings.Builder
	sb.WriteString("<?php\n\n// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("declare(strict_types=1);\n\nnamespace App\\Errors;\n\n")
	sb.WriteString("use App\\Exceptions\\ApiException;\n\n")

	// Per-action inner classes (PHP has no inner classes, so companion classes in same file)
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		innerClass := capitalize(act.Name) + "Errors"
		exceptionClass := capitalize(act.Name) + "Exception"
		sb.WriteString(fmt.Sprintf("/** Error factories and code constants for %s. */\n", act.Name))
		sb.WriteString(fmt.Sprintf("final class %s\n{\n", innerClass))
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ActionErrorStatus(act, errName)
			methodName := emitter.ToCamelCase(errName)
			constName := emitter.ToScreamingSnake(errName) + "_CODE"
			constStatus := emitter.ToScreamingSnake(errName) + "_STATUS"
			sb.WriteString(fmt.Sprintf("    /** mirrors TS .%s.code */\n", methodName))
			sb.WriteString(fmt.Sprintf("    public const %s = '%s';\n", constName, code))
			sb.WriteString(fmt.Sprintf("    public const %s = %d;\n\n", constStatus, status))
			sb.WriteString(fmt.Sprintf("    public function %s(?string $message = null): %s\n    {\n", methodName, exceptionClass))
			sb.WriteString(fmt.Sprintf("        return new %s('%s', %d, $message ?? '%s');\n    }\n\n", exceptionClass, code, status, errName))
		}
		sb.WriteString("}\n\n")
	}

	// Aggregate class with lazy singleton accessors — mirrors TS: UsersErrors::getUser()->notFound("msg")
	sb.WriteString(fmt.Sprintf("/** Error factories for %s — mirrors TypeScript %sErrors pattern.\n", mod.Name, strings.ToLower(mod.Name)))
	sb.WriteString(fmt.Sprintf(" * Usage: throw %s::getUser()->notFound('message');\n */\n", className))
	sb.WriteString(fmt.Sprintf("final class %s\n{\n", className))
	sb.WriteString("    private static array $instances = [];\n\n")
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		methodName := emitter.ToCamelCase(act.Name)
		innerClass := capitalize(act.Name) + "Errors"
		sb.WriteString(fmt.Sprintf("    public static function %s(): %s\n    {\n", methodName, innerClass))
		sb.WriteString(fmt.Sprintf("        return self::$instances[__FUNCTION__] ??= new %s();\n    }\n\n", innerClass))
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, className+".php"), []byte(sb.String()), 0644)
}

// Legacy no-ops
func (e *PhpEmitter) emitErrorHandler(_ string) error               { return nil }
func (e *PhpEmitter) emitModuleErrors(_ ast.Module, _ string) error { return nil }
