package php

// interfaces.go — emits app/Services/I{Module}Service.php PHP interfaces.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *PhpEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "app", "Services")

	enumNames := make(map[string]bool, len(a.Enums))
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	// Collect model types used by this module for use statements.
	usedTypes := emitter.CollectUsedTypes(a, mod)

	var sb strings.Builder
	sb.WriteString("<?php\n\n")
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("declare(strict_types=1);\n\n")
	sb.WriteString("namespace App\\Services;\n\n")
	for _, t := range usedTypes {
		sb.WriteString(fmt.Sprintf("use App\\Models\\%s;\n", t))
	}
	if len(usedTypes) > 0 {
		sb.WriteString("\n")
	}

	modClass := capitalize(mod.Name)

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", mod.Description))
	}
	sb.WriteString(fmt.Sprintf("interface I%sService\n{\n", modClass))

	for _, act := range mod.Actions {
		returnType := phpReturnType(act, enumNames)

		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		var params []string
		for _, p := range pathParams {
			params = append(params, "string $"+phpSnakeName(p))
		}
		if act.Input != "" {
			params = append(params, act.Input+" $input")
		}
		if act.Query != "" {
			params = append(params, "array $query")
		}

		hasDoc := act.Description != "" || len(act.Errors) > 0
		if hasDoc {
			sb.WriteString("    /**\n")
			if act.Description != "" {
				sb.WriteString(fmt.Sprintf("     * %s\n", act.Description))
			}
			for _, errName := range act.Errors {
				code := emitter.ErrorCode(act.Name, errName)
				sb.WriteString(fmt.Sprintf("     * @throws %sException %s — %s\n", capitalize(act.Name), code, errName))
			}
			sb.WriteString("     */\n")
		}
		sb.WriteString(fmt.Sprintf("    public function %s(%s): %s;\n\n",
			phpCamelName(act.Name), strings.Join(params, ", "), returnType))
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("I%sService.php", modClass)), []byte(sb.String()), 0644)
}

// phpReturnType returns the PHP return type annotation for a service method.
func phpReturnType(act ast.Action, enumNames map[string]bool) string {
	if act.Output == "" {
		return "void"
	}
	base := veldScalarToPhp(act.Output, enumNames)
	if act.OutputArray {
		return "array"
	}
	return base
}

// phpCamelName converts a name to camelCase for PHP method names.
func phpCamelName(name string) string {
	parts := strings.FieldsFunc(phpSnakeName(name), func(r rune) bool { return r == '_' })
	if len(parts) == 0 {
		return name
	}
	var sb strings.Builder
	sb.WriteString(parts[0])
	for _, p := range parts[1:] {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return sb.String()
}
