package php

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("php", New())
}

// PhpEmitter generates a typed PHP (Laravel, PHP 8.1+) backend from a Veld AST.
// Output layout mirrors a Laravel project:
//
//	outDir/
//	├── composer.json
//	├── routes/api.php        — all route registrations
//	└── app/
//	    ├── Models/           — one .php per model + one per enum
//	    ├── Services/         — I{Module}Service.php per module
//	    └── Http/Controllers/ — {Module}Controller.php per module
type PhpEmitter struct{}

func (*PhpEmitter) IsBackend() {}
func New() *PhpEmitter         { return &PhpEmitter{} }

// capitalize returns s with its first character uppercased.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// Summary returns a human-readable list of files that will be generated.
func (e *PhpEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine

	lines = append(lines, emitter.SummaryLine{Dir: "app/Models/", Files: "<Model>.php, <Enum>.php"})

	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "I"+capitalize(m)+"Service.php")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "app/Services/", Files: strings.Join(ifaceFiles, ", ")})
	}

	ctrlFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ctrlFiles = append(ctrlFiles, capitalize(m)+"Controller.php")
	}
	if len(ctrlFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "app/Http/Controllers/", Files: strings.Join(ctrlFiles, ", ")})
	}

	lines = append(lines, emitter.SummaryLine{Dir: "routes/", Files: "api.php"})
	lines = append(lines, emitter.SummaryLine{Dir: "./", Files: "composer.json"})
	return lines
}

// Emit writes all generated files to outDir.
func (e *PhpEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	if err := e.createDirs(outDir); err != nil {
		return err
	}
	if err := e.emitModels(a, outDir); err != nil {
		return fmt.Errorf("models: %w", err)
	}
	if err := e.emitErrorHandler(outDir); err != nil {
		return fmt.Errorf("error handler: %w", err)
	}
	for _, mod := range a.Modules {
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("service interface %s: %w", mod.Name, err)
		}
		if err := e.emitController(a, mod, outDir); err != nil {
			return fmt.Errorf("controller %s: %w", mod.Name, err)
		}
		if err := e.emitModuleErrors(mod, outDir); err != nil {
			return fmt.Errorf("errors %s: %w", mod.Name, err)
		}
	}
	if err := e.emitRoutes(a, outDir); err != nil {
		return fmt.Errorf("routes: %w", err)
	}
	return e.emitComposer(outDir)
}

func (e *PhpEmitter) createDirs(outDir string) error {
	for _, sub := range []string{
		"app/Models",
		"app/Services",
		"app/Http/Controllers",
		"routes",
	} {
		if err := os.MkdirAll(filepath.Join(outDir, sub), 0755); err != nil {
			return err
		}
	}
	return nil
}

func (e *PhpEmitter) emitComposer(outDir string) error {
	const composer = `{
    "name": "veld/generated",
    "description": "AUTO-GENERATED BY VELD — DO NOT EDIT",
    "type": "project",
    "require": {
        "php": "^8.1",
        "laravel/framework": "^10.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    }
}
`
	return os.WriteFile(filepath.Join(outDir, "composer.json"), []byte(composer), 0644)
}
