package php_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
	"github.com/veld-dev/veld/internal/emitter/backend/php"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

func TestPhpEmitterEmit(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "composer.json"),
		filepath.Join(outDir, "routes", "api.php"),
		filepath.Join(outDir, "app", "Models", "LoginInput.php"),
		filepath.Join(outDir, "app", "Models", "User.php"),
		filepath.Join(outDir, "app", "Models", "Role.php"),
		filepath.Join(outDir, "app", "Services", "IAuthService.php"),
		filepath.Join(outDir, "app", "Http", "Controllers", "AuthController.php"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestPhpEmitterDryRun(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, got %d entries", len(entries))
	}
}

func TestPhpEmitterModelContent(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "app", "Models", "User.php"))
	if err != nil {
		t.Fatalf("ReadFile User.php: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"php tag", "<?php"},
		{"header", "AUTO-GENERATED BY VELD"},
		{"strict types", "declare(strict_types=1);"},
		{"namespace", "namespace App\\Models;"},
		{"class declaration", "class User"},
		{"readonly constructor", "public function __construct("},
		{"string field", "public readonly string $email"},
		{"array field", "public readonly array $tags"},
		{"optional nullable", "public readonly ?string $bio = null"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("User.php missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPhpEmitterEnumContent(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "app", "Models", "Role.php"))
	if err != nil {
		t.Fatalf("ReadFile Role.php: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"backed enum", "enum Role: string"},
		{"admin case", "case Admin = 'admin';"},
		{"user case", "case User = 'user';"},
		{"guest case", "case Guest = 'guest';"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("Role.php missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPhpEmitterInterfaceContent(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "app", "Services", "IAuthService.php"))
	if err != nil {
		t.Fatalf("ReadFile IAuthService.php: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"namespace", "namespace App\\Services;"},
		{"interface declaration", "interface IAuthService"},
		{"login method", "public function login(LoginInput $input): User;"},
		{"me method", "public function me(): User;"},
		{"logout void", "public function logout(): void;"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("IAuthService.php missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPhpEmitterControllerContent(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "app", "Http", "Controllers", "AuthController.php"))
	if err != nil {
		t.Fatalf("ReadFile AuthController.php: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"namespace", "namespace App\\Http\\Controllers;"},
		{"laravel imports", "use Illuminate\\Http\\Request;"},
		{"service use", "use App\\Services\\IAuthService;"},
		{"class declaration", "class AuthController extends Controller"},
		{"constructor injection", "private readonly IAuthService $service"},
		{"post 201", "response()->json($result, 201)"},
		{"delete no content", "response()->noContent()"},
		{"try/catch", "catch (\\Exception $e)"},
		{"error json", "response()->json(['error' => $e->getMessage()], 500)"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("AuthController.php missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPhpEmitterRoutesContent(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "routes", "api.php"))
	if err != nil {
		t.Fatalf("ReadFile api.php: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"route facade import", "use Illuminate\\Support\\Facades\\Route;"},
		{"controller import", "use App\\Http\\Controllers\\AuthController;"},
		{"post route", "Route::post('/api/auth/login', [AuthController::class, 'login']);"},
		{"get route", "Route::get('/api/auth/me', [AuthController::class, 'me']);"},
		{"delete route", "Route::delete('/api/auth/logout', [AuthController::class, 'logout']);"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("api.php missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPhpEmitterPathParams(t *testing.T) {
	e := php.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "routes", "api.php"))
	routesContent := string(data)
	// Laravel uses {id} syntax.
	if !strings.Contains(routesContent, "'/items/{id}'") {
		t.Errorf("api.php should use {id} Laravel syntax:\n%s", routesContent)
	}

	data2, _ := os.ReadFile(filepath.Join(outDir, "app", "Http", "Controllers", "ItemsController.php"))
	ctrlContent := string(data2)
	if !strings.Contains(ctrlContent, "string $id") {
		t.Errorf("controller should have string $id param:\n%s", ctrlContent)
	}
}

func TestPhpEmitterSummary(t *testing.T) {
	e := php.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}
	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	for _, want := range []string{"app/Models/", "app/Services/", "app/Http/Controllers/", "routes/", "./"} {
		if !dirs[want] {
			t.Errorf("Summary() missing dir %q", want)
		}
	}
}

func TestPhpEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("php"); err != nil {
		t.Errorf("php backend not registered: %v", err)
	}
}
