package php

// routes.go — emits app/Http/Controllers/{Module}Controller.php and
// routes/api.php with all route registrations. Status codes: 201 for POST,
// 204 for DELETE with no output, 200 for everything else.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	phpstrategy "github.com/Adhamzineldin/Veld/internal/emitter/backend/php/strategy"
)

func (e *PhpEmitter) emitController(a ast.AST, mod ast.Module, outDir string, strat phpstrategy.PHPFrameworkStrategy) error {
	dir := filepath.Join(outDir, "app", "Http", "Controllers")

	enumNames := make(map[string]bool, len(a.Enums))
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	modClass := capitalize(mod.Name)

	seen := make(map[string]bool)
	var modelUses []string
	for _, act := range mod.Actions {
		if act.Input != "" && !seen[act.Input] {
			seen[act.Input] = true
			modelUses = append(modelUses, act.Input)
		}
	}

	var sb strings.Builder
	sb.WriteString("<?php\n\n")
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("declare(strict_types=1);\n\n")
	sb.WriteString("namespace App\\Http\\Controllers;\n\n")

	// Strategy-supplied use statements.
	for _, u := range strat.ControllerUses() {
		sb.WriteString(u + "\n")
	}
	sb.WriteString(fmt.Sprintf("use App\\Services\\I%sService;\n", modClass))
	for _, m := range modelUses {
		sb.WriteString(fmt.Sprintf("use App\\Models\\%s;\n", m))
	}
	sb.WriteString("\n")

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", mod.Description))
	}

	baseClass := strat.ControllerBaseClass()
	if baseClass != "" {
		sb.WriteString(fmt.Sprintf("class %sController extends %s\n{\n", modClass, baseClass))
	} else {
		sb.WriteString(fmt.Sprintf("class %sController\n{\n", modClass))
	}
	sb.WriteString("    public function __construct(\n")
	sb.WriteString(fmt.Sprintf("        private readonly I%sService $service,\n", modClass))
	sb.WriteString("    ) {}\n")

	for _, act := range mod.Actions {
		if act.Method == "WS" {
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			sb.WriteString(strat.WSActionMethod(phpCamelName(act.Name), routePath, act.Emit, act.Stream))
		} else {
			writePhpAction(&sb, mod, act, enumNames, strat)
		}
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, modClass+"Controller.php"), []byte(sb.String()), 0644)
}

// writePhpAction appends a single controller action to sb using the strategy.
func writePhpAction(sb *strings.Builder, mod ast.Module, act ast.Action, enumNames map[string]bool, strat phpstrategy.PHPFrameworkStrategy) {
	routePath := act.Path
	if mod.Prefix != "" {
		routePath = mod.Prefix + act.Path
	}

	pathParams := emitter.ExtractPathParams(routePath)
	returnType := phpReturnType(act, enumNames)
	methodName := phpCamelName(act.Name)
	requestType := strat.RequestType()

	sb.WriteString("\n")
	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("    /** %s */\n", act.Description))
	}

	// Method signature: request param first, then path params.
	var sigParams []string
	sigParams = append(sigParams, requestType+" $request")
	for _, p := range pathParams {
		sigParams = append(sigParams, "string $"+phpSnakeName(p))
	}

	responseHint := "mixed"
	if requestType == "Request" {
		// Laravel: typed return hints.
		responseHint = "\\Illuminate\\Http\\JsonResponse"
		if act.Method == "DELETE" && returnType == "void" {
			responseHint = "\\Illuminate\\Http\\Response|\\Illuminate\\Http\\JsonResponse"
		}
	}

	sb.WriteString(fmt.Sprintf("    public function %s(%s): %s\n    {\n",
		methodName, strings.Join(sigParams, ", "), responseHint))
	sb.WriteString("        try {\n")

	// Build service call arguments.
	var callArgs []string
	for _, p := range pathParams {
		callArgs = append(callArgs, "$"+phpSnakeName(p))
	}
	if act.Input != "" {
		sb.WriteString(fmt.Sprintf("            $input = new %s(...$request->validate($request->all()));\n", act.Input))
		callArgs = append(callArgs, "$input")
	}
	if act.Query != "" {
		callArgs = append(callArgs, "$request->query()")
	}
	if act.Headers != "" {
		callArgs = append(callArgs, "$request->headers->all()")
	}

	serviceCall := fmt.Sprintf("$this->service->%s(%s)", methodName, strings.Join(callArgs, ", "))

	switch {
	case act.Method == "DELETE" && returnType == "void":
		sb.WriteString(fmt.Sprintf("            %s;\n", serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.ReturnNoContent()))
	case act.Method == "POST":
		sb.WriteString(fmt.Sprintf("            $result = %s;\n", serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.ReturnCreated("$result")))
	default:
		sb.WriteString(fmt.Sprintf("            $result = %s;\n", serviceCall))
		sb.WriteString(fmt.Sprintf("            %s\n", strat.ReturnOk("$result")))
	}

	sb.WriteString("        } catch (\\Exception $e) {\n")
	sb.WriteString(fmt.Sprintf("            %s\n", strat.ReturnError(500, "$e->getMessage()")))
	sb.WriteString("        }\n    }\n")
}

// emitRoutes writes routes/api.php with all module route registrations.
func (e *PhpEmitter) emitRoutes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "routes")

	var sb strings.Builder
	sb.WriteString("<?php\n\n")
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("use Illuminate\\Support\\Facades\\Route;\n")

	for _, mod := range a.Modules {
		sb.WriteString(fmt.Sprintf("use App\\Http\\Controllers\\%sController;\n", capitalize(mod.Name)))
	}
	sb.WriteString("\n")

	for _, mod := range a.Modules {
		modClass := capitalize(mod.Name)
		if mod.Description != "" {
			sb.WriteString(fmt.Sprintf("// %s\n", mod.Description))
		}
		for _, act := range mod.Actions {
			if act.Method == "WS" {
				routePath := act.Path
				if mod.Prefix != "" {
					routePath = mod.Prefix + act.Path
				}
				// WebSocket routes are registered via Laravel WebSockets / Reverb — comment stub only.
				sb.WriteString(fmt.Sprintf("// WebSocket: WS %s — register via Laravel WebSockets or Reverb, not Route::\n", routePath))
				continue
			}
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			// Laravel uses {param} route syntax (same as ASP.NET Core / Chi).
			laravelPath := emitter.ToChiPath(routePath)
			method := strings.ToLower(act.Method)
			methodName := phpCamelName(act.Name)
			sb.WriteString(fmt.Sprintf("Route::%s('%s', [%sController::class, '%s']);\n",
				method, laravelPath, modClass, methodName))
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(dir, "api.php"), []byte(sb.String()), 0644)
}
