// Package python implements the Veld service SDK emitter for Python.
//
// It generates typed, urllib-based HTTP client classes for consumed services,
// enabling type-safe inter-service communication. Each consumed service gets
// its own directory under generated/sdk/<service>/ with:
//   - client.py   — the typed client class (stdlib urllib only)
//   - types.py    — TypedDict models used by that service's actions
//   - __init__.py — barrel import
//
// Self-registers under the name "python" (matching the backend emitter name).
package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
)

func init() {
	emitter.RegisterServiceSdk("python", New())
}

// Emitter generates Python service SDK clients.
type Emitter struct{}

func New() *Emitter            { return &Emitter{} }
func (*Emitter) IsServiceSdk() {}

// Summary returns a human-friendly breakdown of generated SDK files.
func (e *Emitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine
	for _, m := range modules {
		name := sdkhelpers.ServiceFileName(m)
		lines = append(lines, emitter.SummaryLine{
			Dir:   fmt.Sprintf("sdk/%s/", name),
			Files: "client.py, types.py, __init__.py",
		})
	}
	return lines
}

// Emit generates SDK client files for each consumed service.
func (e *Emitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	for _, consumed := range opts.ConsumedServices {
		if err := emitServiceSdk(consumed, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", consumed.Name, err)
		}
	}

	// Emit sdk/__init__.py barrel.
	if len(opts.ConsumedServices) > 0 {
		if err := emitSdkBarrel(opts.ConsumedServices, outDir); err != nil {
			return fmt.Errorf("sdk barrel: %w", err)
		}
	}

	return nil
}

func emitServiceSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	dir := filepath.Join(outDir, "sdk", name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	if err := emitSdkTypes(consumed, dir); err != nil {
		return fmt.Errorf("types: %w", err)
	}
	if err := emitSdkClient(consumed, dir); err != nil {
		return fmt.Errorf("client: %w", err)
	}
	if err := emitSdkInit(consumed, dir); err != nil {
		return fmt.Errorf("init: %w", err)
	}
	return nil
}

// ── types.py ──────────────────────────────────────────────────────────────────

func emitSdkTypes(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST

	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("# Service SDK types for: %s\n", consumed.Name))
	sb.WriteString("from __future__ import annotations\n")

	// Collect all models and enums used across modules.
	usedModels := make(map[string]bool)
	usedEnums := make(map[string]bool)
	for _, mod := range a.Modules {
		for k, v := range emitter.CollectTransitiveModels(a, mod) {
			if v {
				usedModels[k] = true
			}
		}
		for k, v := range emitter.CollectUsedEnums(a, mod) {
			if v {
				usedEnums[k] = true
			}
		}
	}

	// Determine typing imports needed.
	needsList, needsOptional, needsDict, needsAny := false, false, false, false
	needsLiteral := len(usedEnums) > 0
	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		for _, f := range m.Fields {
			if f.IsArray {
				needsList = true
			}
			if f.Optional {
				needsOptional = true
			}
			if f.IsMap {
				needsDict = true
			}
			if f.Type == "any" || f.Type == "json" || f.MapValueType == "any" || f.MapValueType == "json" {
				needsAny = true
			}
		}
	}

	typingImports := []string{"TypedDict"}
	if needsAny {
		typingImports = append(typingImports, "Any")
	}
	if needsList {
		typingImports = append(typingImports, "List")
	}
	if needsOptional {
		typingImports = append(typingImports, "Optional")
	}
	if needsLiteral {
		typingImports = append(typingImports, "Literal")
	}
	if needsDict {
		typingImports = append(typingImports, "Dict")
	}
	sb.WriteString(fmt.Sprintf("from typing import %s\n\n", strings.Join(typingImports, ", ")))

	// Emit enums as Literal types.
	for _, en := range a.Enums {
		if !usedEnums[en.Name] {
			continue
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
	}

	// Emit models as TypedDict classes.
	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
		}
		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("class %s(%s, total=False):\n", m.Name, m.Extends))
		} else {
			sb.WriteString(fmt.Sprintf("class %s(TypedDict, total=False):\n", m.Name))
		}
		if len(m.Fields) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, f := range m.Fields {
			pyType := veldFieldToPy(f)
			if f.Optional {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}
			sb.WriteString(fmt.Sprintf("    %s: %s\n", emitter.ToSnakeCase(f.Name), pyType))
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(dir, "types.py"), []byte(sb.String()), 0644)
}

// ── client.py ─────────────────────────────────────────────────────────────────

func emitSdkClient(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)

	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("# Service SDK: %s client for inter-service communication\n", consumed.Name))
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("import json\n")
	sb.WriteString("import os\n")
	sb.WriteString("from typing import Any, Dict, Optional\n")
	sb.WriteString("from urllib.request import Request, urlopen\n")
	sb.WriteString("from urllib.error import HTTPError\n")
	sb.WriteString("from urllib.parse import urlencode\n\n")

	// Import types.
	allTypes := collectAllUsedTypes(a)
	if len(allTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from .types import %s\n\n", strings.Join(allTypes, ", ")))
	}

	// VeldApiError class.
	sb.WriteString("class VeldApiError(Exception):\n")
	sb.WriteString("    \"\"\"HTTP error from a consumed service.\"\"\"\n")
	sb.WriteString("    def __init__(self, status: int, body: str):\n")
	sb.WriteString("        super().__init__(f\"HTTP {status}: {body}\")\n")
	sb.WriteString("        self.status = status\n")
	sb.WriteString("        self.body = body\n\n\n")

	// Client class.
	sb.WriteString(fmt.Sprintf("class %s:\n", className))
	sb.WriteString(fmt.Sprintf("    \"\"\"Typed HTTP client for the %s service.\"\"\"\n\n", consumed.Name))

	// Constructor.
	sb.WriteString("    def __init__(\n")
	sb.WriteString("        self,\n")
	sb.WriteString("        base_url: Optional[str] = None,\n")
	sb.WriteString("        headers: Optional[Dict[str, str]] = None,\n")
	sb.WriteString("    ):\n")
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("        self._base = base_url or os.environ.get(%q) or %q\n", envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("        resolved = base_url or os.environ.get(%q)\n", envVar))
		sb.WriteString(fmt.Sprintf("        if not resolved:\n"))
		sb.WriteString(fmt.Sprintf("            raise ValueError(\n"))
		sb.WriteString(fmt.Sprintf("                'No base URL for %s — pass base_url or set %s'\n", consumed.Name, envVar))
		sb.WriteString(fmt.Sprintf("            )\n"))
		sb.WriteString("        self._base = resolved\n")
	}
	sb.WriteString("        self._headers = headers or {}\n\n")

	// Private _request method.
	sb.WriteString("    def _request(self, method: str, path: str, body: Any = None) -> Any:\n")
	sb.WriteString("        data = json.dumps(body).encode() if body is not None else None\n")
	sb.WriteString("        hdrs = {'Content-Type': 'application/json', **self._headers}\n")
	sb.WriteString("        req = Request(self._base + path, data=data, headers=hdrs, method=method)\n")
	sb.WriteString("        try:\n")
	sb.WriteString("            with urlopen(req) as res:\n")
	sb.WriteString("                if res.status == 204:\n")
	sb.WriteString("                    return None\n")
	sb.WriteString("                return json.loads(res.read())\n")
	sb.WriteString("        except HTTPError as e:\n")
	sb.WriteString("            raise VeldApiError(e.code, e.read().decode()) from e\n\n")

	// Per-module methods.
	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				sb.WriteString(fmt.Sprintf("    # WebSocket action %s.%s not supported in service SDK\n\n", mod.Name, act.Name))
				continue
			}
			writeActionMethod(&sb, mod, act)
		}
	}

	return os.WriteFile(filepath.Join(dir, "client.py"), []byte(sb.String()), 0644)
}

func writeActionMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	snakeName := emitter.ToSnakeCase(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	// Return type annotation.
	returnType := formatPyOutputType(act)

	// Build signature.
	var sigParts []string
	sigParts = append(sigParts, "self")
	for _, p := range pathParams {
		sigParts = append(sigParts, fmt.Sprintf("%s: str", emitter.ToSnakeCase(p)))
	}
	if act.Input != "" {
		sigParts = append(sigParts, fmt.Sprintf("input_data: %s", act.Input))
	}
	if act.Query != "" {
		sigParts = append(sigParts, fmt.Sprintf("query: Optional[%s] = None", act.Query))
	}

	// Docstring.
	if act.Deprecated != "" {
		sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n", snakeName, strings.Join(sigParts, ", "), returnType))
		sb.WriteString(fmt.Sprintf("        \"\"\"%s %s\n\n        .. deprecated:: %s\n        \"\"\"\n", method, routePath, act.Deprecated))
	} else if act.Description != "" {
		sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n", snakeName, strings.Join(sigParts, ", "), returnType))
		sb.WriteString(fmt.Sprintf("        \"\"\"%s %s — %s\"\"\"\n", method, routePath, act.Description))
	} else {
		sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n", snakeName, strings.Join(sigParts, ", "), returnType))
		sb.WriteString(fmt.Sprintf("        \"\"\"%s %s\"\"\"\n", method, routePath))
	}

	// Build URL with path param interpolation.
	urlExpr := buildPyUrlExpr(routePath, pathParams)

	// Query string.
	if act.Query != "" {
		sb.WriteString("        qs = '?' + urlencode({k: v for k, v in (query or {}).items() if v is not None}) if query else ''\n")
		urlExpr = urlExpr + " + qs"
	}

	// Body.
	bodyArg := "None"
	if act.Input != "" {
		bodyArg = "input_data"
	}

	if act.Output == "" {
		sb.WriteString(fmt.Sprintf("        self._request(%q, %s, %s)\n\n", method, urlExpr, bodyArg))
	} else {
		sb.WriteString(fmt.Sprintf("        return self._request(%q, %s, %s)\n\n", method, urlExpr, bodyArg))
	}
}

// ── __init__.py ───────────────────────────────────────────────────────────────

func emitSdkInit(consumed emitter.ConsumedServiceInfo, dir string) error {
	className := sdkhelpers.ServiceClassName(consumed.Name)
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("from .client import %s, VeldApiError  # noqa: F401\n", className))
	sb.WriteString("from .types import *  # noqa: F401,F403\n")
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(sb.String()), 0644)
}

func emitSdkBarrel(consumed []emitter.ConsumedServiceInfo, outDir string) error {
	dir := filepath.Join(outDir, "sdk")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("# Service SDK barrel — re-exports all consumed service clients\n")
	for _, c := range consumed {
		name := sdkhelpers.ServiceFileName(c.Name)
		className := sdkhelpers.ServiceClassName(c.Name)
		sb.WriteString(fmt.Sprintf("from .%s import %s  # noqa: F401\n", name, className))
	}
	if len(consumed) > 0 {
		first := sdkhelpers.ServiceFileName(consumed[0].Name)
		sb.WriteString(fmt.Sprintf("from .%s import VeldApiError  # noqa: F401\n", first))
	}
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(sb.String()), 0644)
}

// ── helpers ───────────────────────────────────────────────────────────────────

func veldScalarToPy(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "str"
	case "any", "json":
		return "Any"
	default:
		return t
	}
}

func veldFieldToPy(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("Dict[str, %s]", veldScalarToPy(f.MapValueType))
	}
	base := veldScalarToPy(f.Type)
	if f.IsArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

func formatPyOutputType(act ast.Action) string {
	if act.Output == "" {
		return "None"
	}
	base := act.Output
	if act.OutputArray {
		return fmt.Sprintf("list[%s]", base)
	}
	return base
}

func buildPyUrlExpr(routePath string, pathParams []string) string {
	if len(pathParams) == 0 {
		return fmt.Sprintf("%q", routePath)
	}
	// Convert :param to {param} for Python f-string.
	fstr := routePath
	for _, p := range pathParams {
		fstr = strings.ReplaceAll(fstr, ":"+p, "{"+emitter.ToSnakeCase(p)+"}")
	}
	return fmt.Sprintf("f%q", fstr)
}

func collectAllUsedTypes(a ast.AST) []string {
	seen := make(map[string]bool)
	var result []string
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			if !seen[t] {
				seen[t] = true
				result = append(result, t)
			}
		}
	}
	return result
}
