// Package scaffold generates test boilerplate for each backend language.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterTool("scaffold-tests", New())
}

type TestScaffoldEmitter struct{}

func New() *TestScaffoldEmitter      { return &TestScaffoldEmitter{} }
func (*TestScaffoldEmitter) IsTool() {}

func (e *TestScaffoldEmitter) Summary(modules []string) []emitter.SummaryLine {
	files := make([]string, len(modules))
	for i, m := range modules {
		files[i] = strings.ToLower(m) + "_test.*"
	}
	return []emitter.SummaryLine{
		{Dir: "tests/", Files: strings.Join(files, ", ")},
	}
}

func (e *TestScaffoldEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	testDir := filepath.Join(outDir, "tests")
	if err := os.MkdirAll(testDir, 0755); err != nil {
		return err
	}

	lang := detectLanguage(outDir)

	for _, mod := range a.Modules {
		var content string
		var ext string
		switch lang {
		case "go":
			content, ext = goTest(mod), "_test.go"
		case "rust":
			content, ext = rustTest(mod), "_test.rs"
		case "java":
			content, ext = javaTest(mod), "Test.java"
		case "csharp":
			content, ext = csharpTest(mod), "Tests.cs"
		case "php":
			content, ext = phpTest(mod), "Test.php"
		case "python":
			content, ext = pythonTest(mod), "_test.py"
		default:
			content, ext = nodeTest(mod), ".test.ts"
		}

		filename := strings.ToLower(mod.Name) + ext
		if err := os.WriteFile(filepath.Join(testDir, filename), []byte(content), 0644); err != nil {
			return fmt.Errorf("test for %s: %w", mod.Name, err)
		}
	}
	return nil
}

func detectLanguage(outDir string) string {
	checks := []struct {
		file string
		lang string
	}{
		{"go.mod", "go"},
		{"Cargo.toml", "rust"},
		{"pom.xml", "java"},
		{"VeldGenerated.csproj", "csharp"},
		{"composer.json", "php"},
		{"package.json", "node"},
	}
	for _, c := range checks {
		if _, err := os.Stat(filepath.Join(outDir, c.file)); err == nil {
			return c.lang
		}
	}
	if _, err := os.Stat(filepath.Join(outDir, "schemas", "schemas.py")); err == nil {
		return "python"
	}
	return "node"
}

func nodeTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — Test scaffold\n")
	sb.WriteString("import { describe, it, expect, vi } from 'vitest';\n")
	sb.WriteString(fmt.Sprintf("import type { I%sService } from '../interfaces/I%sService';\n\n", mod.Name, mod.Name))

	sb.WriteString(fmt.Sprintf("describe('%s Service', () => {\n", mod.Name))
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("  it('should handle %s', async () => {\n", act.Name))
		sb.WriteString("    // TODO: implement test\n")
		sb.WriteString("    expect(true).toBe(true);\n")
		sb.WriteString("  });\n\n")
	}
	sb.WriteString("});\n")
	return sb.String()
}

func goTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — Test scaffold\n")
	sb.WriteString("package tests\n\n")
	sb.WriteString("import \"testing\"\n\n")

	for _, act := range mod.Actions {
		testName := fmt.Sprintf("Test%s%s", mod.Name, capitalize(act.Name))
		sb.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", testName))
		sb.WriteString(fmt.Sprintf("\t// TODO: implement test for %s.%s\n", mod.Name, act.Name))
		sb.WriteString("\tt.Skip(\"not implemented\")\n")
		sb.WriteString("}\n\n")
	}
	return sb.String()
}

func rustTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — Test scaffold\n")
	sb.WriteString("#[cfg(test)]\n")
	sb.WriteString(fmt.Sprintf("mod %s_tests {\n", strings.ToLower(mod.Name)))
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("    #[test]\n    fn test_%s() {\n", toSnakeCase(act.Name)))
		sb.WriteString(fmt.Sprintf("        // TODO: implement test for %s::%s\n", mod.Name, act.Name))
		sb.WriteString("        assert!(true);\n")
		sb.WriteString("    }\n\n")
	}
	sb.WriteString("}\n")
	return sb.String()
}

func javaTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — Test scaffold\n")
	sb.WriteString("package com.example.generated.tests;\n\n")
	sb.WriteString("import org.junit.jupiter.api.Test;\n")
	sb.WriteString("import static org.junit.jupiter.api.Assertions.*;\n\n")

	sb.WriteString(fmt.Sprintf("class %sTest {\n\n", mod.Name))
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("    @Test\n    void test%s() {\n", capitalize(act.Name)))
		sb.WriteString(fmt.Sprintf("        // TODO: implement test for %s.%s\n", mod.Name, act.Name))
		sb.WriteString("        assertTrue(true);\n")
		sb.WriteString("    }\n\n")
	}
	sb.WriteString("}\n")
	return sb.String()
}

func csharpTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — Test scaffold\n")
	sb.WriteString("using Xunit;\n\n")

	sb.WriteString(fmt.Sprintf("public class %sTests\n{{\n", mod.Name))
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("    [Fact]\n    public void %s_ShouldWork()\n    {{\n", capitalize(act.Name)))
		sb.WriteString(fmt.Sprintf("        // TODO: implement test for %s.%s\n", mod.Name, act.Name))
		sb.WriteString("        Assert.True(true);\n")
		sb.WriteString("    }}\n\n")
	}
	sb.WriteString("}}\n")
	return sb.String()
}

func phpTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("<?php\n\n")
	sb.WriteString("// AUTO-GENERATED BY VELD — Test scaffold\n\n")
	sb.WriteString("namespace Tests;\n\n")
	sb.WriteString("use PHPUnit\\Framework\\TestCase;\n\n")

	sb.WriteString(fmt.Sprintf("class %sTest extends TestCase\n{\n", mod.Name))
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("    public function test%s(): void\n    {\n", capitalize(act.Name)))
		sb.WriteString(fmt.Sprintf("        // TODO: implement test for %s::%s\n", mod.Name, act.Name))
		sb.WriteString("        $this->assertTrue(true);\n")
		sb.WriteString("    }\n\n")
	}
	sb.WriteString("}\n")
	return sb.String()
}

func pythonTest(mod ast.Module) string {
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — Test scaffold\n")
	sb.WriteString("import pytest\n\n\n")

	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("def test_%s_%s():\n", strings.ToLower(mod.Name), toSnakeCase(act.Name)))
		sb.WriteString(fmt.Sprintf("    \"\"\"Test %s.%s\"\"\"\n", mod.Name, act.Name))
		sb.WriteString("    # TODO: implement test\n")
		sb.WriteString("    assert True\n\n\n")
	}
	return sb.String()
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
