import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

// Generated by `veld generate` — do not edit
import { api } from '../generated/client/api';
import type { Todo, CreateTodoInput } from '../generated/types/index';

@Component({
  selector: 'app-todo',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <h2>Todos</h2>

      <form (ngSubmit)="create()">
        <input [(ngModel)]="newTitle" name="title" placeholder="New todo title" required />
        <button type="submit">Add</button>
      </form>

      <ul>
        @for (todo of todos(); track todo.id) {
          <li>
            <input type="checkbox"
                   [checked]="todo.completed"
                   (change)="toggle(todo)" />
            {{ todo.title }}
            <button (click)="remove(todo.id)">Delete</button>
          </li>
        }
      </ul>
    </div>
  `,
})
export class TodoComponent implements OnInit {
  todos = signal<Todo[]>([]);
  newTitle = '';

  // Hard-coded for the demo; in a real app wire this from an auth service.
  private readonly userId = 'user-1';

  async ngOnInit(): Promise<void> {
    const result = await api.Todos.ListTodos();
    this.todos.set(result);
  }

  async create(): Promise<void> {
    if (!this.newTitle.trim()) return;
    const input: CreateTodoInput = { title: this.newTitle.trim(), userId: this.userId };
    const created = await api.Todos.CreateTodo(input);
    this.todos.update(list => [...list, created]);
    this.newTitle = '';
  }

  async toggle(todo: Todo): Promise<void> {
    const updated = await api.Todos.UpdateTodo(todo.id, { completed: !todo.completed });
    this.todos.update(list => list.map(t => (t.id === updated.id ? updated : t)));
  }

  async remove(id: string): Promise<void> {
    await api.Todos.DeleteTodo(id);
    this.todos.update(list => list.filter(t => t.id !== id));
  }
}
