// AUTO-GENERATED BY VELD — DO NOT EDIT

use std::net::SocketAddr;

mod models;
mod services;
mod router;
mod auth;
mod food;

#[tokio::main]
async fn main() {
    // TODO: initialise your service implementations and pass them to build_router().
    let app = router::build_router();

    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("Listening on {}", addr);

    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
