// AUTO-GENERATED BY VELD — DO NOT EDIT

use serde::{Deserialize, Serialize};

/// LoginInput is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoginInput {
    pub email: String,
    pub password: String,
}

/// RegisterInput is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterInput {
    pub email: String,
    pub password: String,
    pub name: String,
}

/// User is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct User {
    pub id: String,
    pub email: String,
    pub name: String,
}

/// SuccessResponse is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SuccessResponse {
    pub success: bool,
}

/// Food is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Food {
    pub id: String,
    pub name: String,
    pub price: i64,
    pub tags: Vec<String>,
    pub r#type: String,
}

/// FoodList is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FoodList {
    pub items: Vec<Food>,
    pub total: i64,
}

/// CreateFoodInput is a generated data model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateFoodInput {
    pub name: String,
    pub price: i64,
    pub tags: Vec<String>,
    pub r#type: String,
}

