// AUTO-GENERATED BY VELD — DO NOT EDIT

use axum::Router;

use crate::auth::router as auth_router;
use crate::food::router as food_router;

/// Build the complete Axum router with all module routes.
pub fn build_router() -> Router {
    auth_router()
        .merge(food_router())
}
