package rustbackend

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *RustEmitter) emitConstants(a ast.AST, outDir string) error {
	if len(a.Constants) == 0 {
		return nil
	}
	dir := filepath.Join(outDir, "src", "constants")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var mods []string
	for _, cg := range a.Constants {
		fileName := emitter.ToSnakeCase(cg.Name)
		mods = append(mods, fileName)
		var sb strings.Builder
		sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n\n")
		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("/// %s\n", cg.Description))
		}
		for _, f := range cg.Fields {
			rType := rustConstType(f.Type)
			rVal := rustConstValue(f)
			sb.WriteString(fmt.Sprintf("pub const %s: %s = %s;\n", f.Name, rType, rVal))
		}
		if err := os.WriteFile(filepath.Join(dir, fileName+".rs"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	var mod strings.Builder
	mod.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	for _, m := range mods {
		mod.WriteString(fmt.Sprintf("pub mod %s;\n", m))
	}
	return os.WriteFile(filepath.Join(dir, "mod.rs"), []byte(mod.String()), 0644)
}

func rustConstType(veldType string) string {
	switch veldType {
	case "string", "uuid", "date", "datetime", "decimal":
		return "&str"
	case "int":
		return "i32"
	case "float":
		return "f64"
	case "bool":
		return "bool"
	default:
		return "&str"
	}
}

func rustConstValue(f ast.ConstantField) string {
	switch f.Type {
	case "string", "uuid", "date", "datetime", "decimal":
		return fmt.Sprintf("%q", f.Value)
	case "int", "float":
		return f.Value
	case "bool":
		return f.Value
	default:
		return fmt.Sprintf("%q", f.Value)
	}
}
