package rustbackend_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	rustbackend "github.com/Adhamzineldin/Veld/internal/emitter/backend/rust"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "name", Type: "string"},
					{Name: "bio", Type: "string", Optional: true},
					{Name: "tags", Type: "string", IsArray: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name: "Auth",
				Actions: []ast.Action{
					{Name: "Login", Method: "POST", Path: "/auth/login", Input: "LoginInput", Output: "User"},
					{Name: "Me", Method: "GET", Path: "/auth/me", Output: "User"},
					{Name: "Logout", Method: "DELETE", Path: "/auth/logout"},
				},
			},
		},
	}
}

func TestRustEmitterEmit(t *testing.T) {
	e := rustbackend.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "axum"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expected := []string{
		filepath.Join(outDir, "Cargo.toml"),
		filepath.Join(outDir, "src", "main.rs"),
		filepath.Join(outDir, "src", "lib.rs"),
		filepath.Join(outDir, "src", "models.rs"),
		filepath.Join(outDir, "src", "services.rs"),
		filepath.Join(outDir, "src", "router.rs"),
		filepath.Join(outDir, "src", "auth", "mod.rs"),
	}
	for _, f := range expected {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestRustEmitterDryRun(t *testing.T) {
	e := rustbackend.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, got %d entries", len(entries))
	}
}

func TestRustEmitterModelsContent(t *testing.T) {
	e := rustbackend.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "axum"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "src", "models.rs"))
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"header", "AUTO-GENERATED BY VELD"},
		{"serde import", "use serde::{Deserialize, Serialize};"},
		{"User struct", "pub struct User {"},
		{"derive macro", "#[derive(Debug, Clone, Serialize, Deserialize)]"},
		{"optional field", "Option<String>"},
		{"vec field", "Vec<String>"},
		{"Role enum", "pub enum Role {"},
		{"enum variant Admin", "Admin,"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("models.rs missing %s: want %q", c.desc, c.needle)
		}
	}
}

func TestRustEmitterServicesContent(t *testing.T) {
	e := rustbackend.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "axum"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "src", "services.rs"))
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"async-trait import", "use async_trait::async_trait;"},
		{"AuthService trait", "pub trait AuthService"},
		{"Login method", "async fn login("},
		{"Me no input", "async fn me(&self)"},
		{"Result return", "Result<"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("services.rs missing %s: want %q", c.desc, c.needle)
		}
	}
}

func TestRustEmitterRouteHandlerContent(t *testing.T) {
	e := rustbackend.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "axum"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "src", "auth", "mod.rs"))
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"axum import", "use axum::{"},
		{"router function", "pub fn router<S>() -> impl std::any::Any"},
		{"POST login route", `.route("/auth/login", post(login))`},
		{"GET me route", `.route("/auth/me", get(me))`},
		{"DELETE logout route", `.route("/auth/logout", delete(logout))`},
		{"async handler", "pub async fn login("},
		{"JSON extractor", "Json(payload): Json<LoginInput>"},
		{"StatusCode::CREATED", "StatusCode::CREATED"},
		{"StatusCode::OK", "StatusCode::OK"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("auth/mod.rs missing %s: want %q", c.desc, c.needle)
		}
	}
}

func TestRustEmitterCargoToml(t *testing.T) {
	e := rustbackend.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{BackendFramework: "axum"}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "Cargo.toml"))
	content := string(data)

	for _, dep := range []string{"axum", "tokio", "serde", "serde_json", "async-trait"} {
		if !strings.Contains(content, dep) {
			t.Errorf("Cargo.toml missing dependency %q", dep)
		}
	}
}

func TestRustEmitterSummary(t *testing.T) {
	e := rustbackend.New()
	lines := e.Summary([]string{"Auth", "Users"})
	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}

	combined := ""
	for _, l := range lines {
		combined += l.Dir + l.Files
	}
	if !strings.Contains(combined, "src/") {
		t.Error("Summary() should mention src/ directory")
	}
	if !strings.Contains(combined, "Cargo.toml") {
		t.Error("Summary() should mention Cargo.toml")
	}
}

func TestRustEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("rust"); err != nil {
		t.Errorf("rust backend not registered: %v", err)
	}
}
