// types.go - Rust struct and enum generation
package rustbackend

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/codegen"
	"github.com/Adhamzineldin/Veld/internal/emitter/lang"
)

const header = "// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n"

// generateTypes writes src/models/{group}.rs per module group and a
// src/models/mod.rs barrel that re-exports everything, so callers can use
// either `use crate::models::User` (via re-export) or
// `use crate::models::auth::User` (direct module path).
func (e *RustEmitter) generateTypes(a ast.AST, outDir string) error {
	modelGroups, enumGroups, _, _ := emitter.AssignModelsToModules(a)
	keys := emitter.SortedGroupKeys(modelGroups, enumGroups)

	modDir := filepath.Join(outDir, "src", "models")
	if err := os.MkdirAll(modDir, 0755); err != nil {
		return err
	}

	for _, group := range keys {
		models := modelGroups[group]
		enums := enumGroups[group]

		needsHashMap := false
		for _, m := range models {
			for _, f := range m.Fields {
				if f.IsMap {
					needsHashMap = true
				}
			}
		}

		w := codegen.NewWriter("    ")
		w.Writeln(header)
		w.Writeln("use serde::{Deserialize, Serialize};")
		if needsHashMap {
			w.Writeln("use std::collections::HashMap;")
		}
		w.BlankLine()

		for _, enum := range enums {
			e.writeEnum(w, enum)
		}
		for _, model := range models {
			if err := e.writeStruct(w, model); err != nil {
				return err
			}
			w.BlankLine()
		}

		if err := os.WriteFile(filepath.Join(modDir, group+".rs"), w.Bytes(), 0644); err != nil {
			return err
		}
	}

	// mod.rs: declare each submodule and re-export its contents so that
	// `use crate::models::Type` still works (barrel pattern).
	var modFile strings.Builder
	modFile.WriteString(header + "\n")
	for _, group := range keys {
		modFile.WriteString(fmt.Sprintf("pub mod %s;\n", group))
	}
	modFile.WriteString("\n")
	for _, group := range keys {
		modFile.WriteString(fmt.Sprintf("pub use %s::*;\n", group))
	}
	return os.WriteFile(filepath.Join(modDir, "mod.rs"), []byte(modFile.String()), 0644)
}

// writeEnum generates a Rust enum with Serde rename_all = "camelCase".
func (e *RustEmitter) writeEnum(w *codegen.Writer, enum ast.Enum) {
	w.Writeln(fmt.Sprintf("/// %s enumeration.", enum.Name))
	w.Writeln("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
	w.Writeln(`#[serde(rename_all = "camelCase")]`)
	w.WriteBlock(fmt.Sprintf("pub enum %s {", e.adapter.NamingConvention(enum.Name, lang.NamingContextExported)))
	for _, val := range enum.Values {
		variantName := e.adapter.NamingConvention(val, lang.NamingContextExported)
		// The serde rename_all = "camelCase" attribute on the enum handles most cases.
		// Add an explicit rename only when the variant string deviates from camelCase.
		expectedJSON := strings.ToLower(val[:1]) + val[1:]
		if expectedJSON != val {
			w.Writeln(fmt.Sprintf(`#[serde(rename = "%s")]`, val))
		}
		w.Writeln(variantName + ",")
	}
	w.Dedent()
	w.Writeln("}")
	w.BlankLine()
}

// writeStruct generates a Rust struct with Serde derives, constructor, and getters/setters.
func (e *RustEmitter) writeStruct(w *codegen.Writer, model ast.Model) error {
	w.Writeln(fmt.Sprintf("/// %s is a generated data model.", model.Name))
	w.Writeln("#[derive(Debug, Clone, Serialize, Deserialize)]")
	w.Writeln(`#[serde(rename_all = "camelCase")]`)
	w.WriteBlock(fmt.Sprintf("pub struct %s {", e.adapter.NamingConvention(model.Name, lang.NamingContextExported)))

	for _, field := range model.Fields {
		rustType, err := e.mapFieldType(field)
		if err != nil {
			return fmt.Errorf("struct %s field %s: %w", model.Name, field.Name, err)
		}

		fieldName := safeRustIdent(e.adapter.NamingConvention(field.Name, lang.NamingContextPrivate))
		if strings.TrimPrefix(fieldName, "r#") != field.Name {
			w.Writeln(fmt.Sprintf(`#[serde(rename = "%s")]`, field.Name))
		}
		if field.Optional {
			w.Writeln(`#[serde(skip_serializing_if = "Option::is_none")]`)
		}
		if field.Default != "" {
			w.Writeln(fmt.Sprintf(`#[serde(default = "%s_default_%s")]`, strings.ToLower(model.Name), strings.TrimPrefix(fieldName, "r#")))
		}
		w.Writeln(fmt.Sprintf("pub %s: %s,", fieldName, rustType))
	}

	w.Dedent()
	w.Writeln("}")
	w.BlankLine()

	// Default value helper functions for serde
	for _, field := range model.Fields {
		if field.Default == "" {
			continue
		}
		rustType, _ := e.mapFieldType(field)
		fieldName := safeRustIdent(e.adapter.NamingConvention(field.Name, lang.NamingContextPrivate))
		bareName := strings.TrimPrefix(fieldName, "r#")
		fnName := fmt.Sprintf("%s_default_%s", strings.ToLower(model.Name), bareName)
		w.Writeln(fmt.Sprintf("fn %s() -> %s { %s }", fnName, rustType, rustDefaultLiteral(field.Default, field.Type)))
		w.BlankLine()
	}

	// impl block with new() + getters/setters
	structName := e.adapter.NamingConvention(model.Name, lang.NamingContextExported)
	w.WriteBlock(fmt.Sprintf("impl %s {", structName))

	// Constructor
	var ctorParams []string
	var ctorFields []string
	for _, field := range model.Fields {
		rustType, _ := e.mapFieldType(field)
		fieldName := safeRustIdent(e.adapter.NamingConvention(field.Name, lang.NamingContextPrivate))
		ctorParams = append(ctorParams, fmt.Sprintf("%s: %s", fieldName, rustType))
		ctorFields = append(ctorFields, fmt.Sprintf("    %s,", fieldName))
	}
	w.Writeln(fmt.Sprintf("pub fn new(%s) -> Self {", strings.Join(ctorParams, ", ")))
	w.Writeln("    Self {")
	for _, cf := range ctorFields {
		w.Writeln("    " + cf)
	}
	w.Writeln("    }")
	w.Writeln("}")

	// Getters and setters
	for _, field := range model.Fields {
		rustType, _ := e.mapFieldType(field)
		fieldName := safeRustIdent(e.adapter.NamingConvention(field.Name, lang.NamingContextPrivate))
		bareField := strings.TrimPrefix(fieldName, "r#")
		w.BlankLine()
		w.Writeln(fmt.Sprintf("pub fn %s(&self) -> &%s { &self.%s }", bareField, rustType, fieldName))
		w.Writeln(fmt.Sprintf("pub fn set_%s(&mut self, v: %s) { self.%s = v; }", bareField, rustType, fieldName))
	}

	w.Dedent()
	w.Writeln("}")

	return nil
}

// rustKeywords is the set of Rust reserved keywords that cannot be used as bare identifiers.
var rustKeywords = map[string]bool{
	"abstract": true, "as": true, "async": true, "await": true,
	"become": true, "box": true, "break": true, "const": true,
	"continue": true, "crate": true, "do": true, "dyn": true,
	"else": true, "enum": true, "extern": true, "false": true,
	"final": true, "fn": true, "for": true, "if": true,
	"impl": true, "in": true, "let": true, "loop": true,
	"macro": true, "match": true, "mod": true, "move": true,
	"mut": true, "override": true, "priv": true, "pub": true,
	"ref": true, "return": true, "self": true, "static": true,
	"struct": true, "super": true, "trait": true, "true": true,
	"try": true, "type": true, "typeof": true, "union": true,
	"unsafe": true, "unsized": true, "use": true, "virtual": true,
	"where": true, "while": true, "yield": true,
}

// safeRustIdent returns a raw identifier (r#name) if name is a Rust keyword.
func safeRustIdent(name string) string {
	if rustKeywords[name] {
		return "r#" + name
	}
	return name
}

// mapFieldType converts an AST field to the appropriate Rust type.
func (e *RustEmitter) mapFieldType(f ast.Field) (string, error) {
	if f.IsMap {
		valType, _, err := e.adapter.MapType(f.MapValueType)
		if err != nil {
			return "", err
		}
		rustType := "HashMap<String, " + valType + ">"
		if f.Optional {
			return e.adapter.NullableType(rustType), nil
		}
		return rustType, nil
	}

	baseType, _, err := e.adapter.MapType(f.Type)
	if err != nil {
		return "", err
	}

	if f.IsArray {
		rustType := "Vec<" + baseType + ">"
		if f.Optional {
			return e.adapter.NullableType(rustType), nil
		}
		return rustType, nil
	}

	if f.Optional {
		return e.adapter.NullableType(baseType), nil
	}
	return baseType, nil
}

// astNeedsHashMap returns true if any field uses Map<K,V>.
func (e *RustEmitter) astNeedsHashMap(a ast.AST) bool {
	for _, model := range a.Models {
		for _, field := range model.Fields {
			if field.IsMap || strings.HasPrefix(field.Type, "Map<") {
				return true
			}
		}
	}
	return false
}

// rustDefaultLiteral converts a Veld default value to a Rust literal expression.
func rustDefaultLiteral(val, veldType string) string {
	// Already a quoted string → Rust String::from(...)
	if strings.HasPrefix(val, "\"") && strings.HasSuffix(val, "\"") {
		return fmt.Sprintf("String::from(%s)", val)
	}
	// Booleans
	if val == "true" || val == "false" {
		return val
	}
	// Numeric
	if veldType == "int" {
		return val
	}
	if veldType == "float" {
		if !strings.Contains(val, ".") {
			return val + ".0"
		}
		return val
	}
	// String types (date, datetime, uuid, decimal) → String::from(...)
	if veldType == "string" || veldType == "date" || veldType == "datetime" ||
		veldType == "uuid" || veldType == "decimal" {
		return fmt.Sprintf("String::from(\"%s\")", val)
	}
	// Enum value or identifier → String::from(...)
	return fmt.Sprintf("String::from(\"%s\")", val)
}
