// AUTO-GENERATED BY VELD — DO NOT EDIT

package main

import "log"

func main() {
	svc := &Services{}
	// TODO: initialise your service implementations here
	// e.g. svc.Auth = &myapp.AuthServiceImpl{DB: db}

	server := NewServer(svc)
	log.Printf("listening on %s", server.Addr)
	log.Fatal(server.ListenAndServe())
}
