// AUTO-GENERATED BY VELD — DO NOT EDIT

package main

import (
	"net/http"
	"time"

	"example.com/veld-generated/internal/interfaces"
	"example.com/veld-generated/internal/middleware"
	"example.com/veld-generated/internal/routes"
	"github.com/go-chi/chi/v5"
)

// Services holds the concrete implementations of all service interfaces.
// Populate these fields with your own implementations before calling NewServer.
type Services struct {
	Auth interfaces.AuthService
	Food interfaces.FoodService
}

// NewServer creates and configures the HTTP server.
func NewServer(svc *Services) *http.Server {
	r := chi.NewRouter()

	r.Use(middleware.RecoverPanic)

	routes.SetupRoutes(r, svc.Auth, svc.Food)

	return &http.Server{
		Addr:         ":8080",
		Handler:      r,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}
}
