// Package vue generates Vue 3 composables wrapping the TypeScript API client.
package vue

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	tsEmitter "github.com/Adhamzineldin/Veld/internal/emitter/frontend/typescript"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterFrontend("vue", New())
}

type VueEmitter struct{}

func New() *VueEmitter          { return &VueEmitter{} }
func (*VueEmitter) IsFrontend() {}

func (e *VueEmitter) Summary(modules []string) []emitter.SummaryLine {
	lines := []emitter.SummaryLine{
		{Dir: "client/", Files: "api.ts, package.json"},
	}
	files := make([]string, len(modules))
	for i, m := range modules {
		files[i] = "use" + m + ".ts"
	}
	lines = append(lines, emitter.SummaryLine{Dir: "composables/", Files: strings.Join(files, ", ")})
	lines = append(lines, emitter.SummaryLine{Dir: "composables/", Files: "index.ts, package.json"})
	return lines
}

func (e *VueEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	// Base TS client
	tsE := tsEmitter.New()
	if err := tsE.Emit(a, outDir, opts); err != nil {
		return fmt.Errorf("typescript base: %w", err)
	}

	dir := filepath.Join(outDir, "composables")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var barrelExports []string
	for _, mod := range a.Modules {
		if err := e.emitComposable(a, mod, dir); err != nil {
			return fmt.Errorf("composable %s: %w", mod.Name, err)
		}
		barrelExports = append(barrelExports, fmt.Sprintf("export * from './use%s';", mod.Name))
	}

	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, exp := range barrelExports {
		barrel.WriteString(exp + "\n")
	}
	if err := os.WriteFile(filepath.Join(dir, "index.ts"), []byte(barrel.String()), 0644); err != nil {
		return err
	}

	// Write composables/package.json
	pkgJSON := `{
  "name": "@veld/composables",
  "private": true,
  "types": "./index.ts",
  "exports": {
    ".": "./index.ts"
  }
}
`
	return os.WriteFile(filepath.Join(dir, "package.json"), []byte(pkgJSON), 0644)
}

func (e *VueEmitter) emitComposable(a ast.AST, mod ast.Module, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import { ref, type Ref } from 'vue';\n")
	sb.WriteString("import { api } from '../client/api';\n")

	usedTypes := emitter.CollectUsedTypes(a, mod)
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types';\n", strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	hookName := "use" + mod.Name
	sb.WriteString(fmt.Sprintf("export function %s() {\n", hookName))
	sb.WriteString("  const loading = ref(false);\n")
	sb.WriteString("  const error: Ref<Error | null> = ref(null);\n\n")

	for _, act := range mod.Actions {
		outputType := tshelpers.FormatOutputType(act)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		var paramTypes []string
		var argsList []string
		for _, p := range pathParams {
			paramTypes = append(paramTypes, p+": string")
			argsList = append(argsList, p)
		}
		if act.Input != "" {
			paramTypes = append(paramTypes, "input: "+act.Input)
			argsList = append(argsList, "input")
		}
		if act.Query != "" {
			paramTypes = append(paramTypes, "query?: "+act.Query)
			argsList = append(argsList, "query")
		}

		paramsStr := strings.Join(paramTypes, ", ")
		argsStr := strings.Join(argsList, ", ")

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("  /** %s */\n", act.Description))
		}
		sb.WriteString(fmt.Sprintf("  async function %s(%s): Promise<%s | undefined> {\n", act.Name, paramsStr, outputType))
		sb.WriteString("    loading.value = true;\n")
		sb.WriteString("    error.value = null;\n")
		sb.WriteString("    try {\n")
		sb.WriteString(fmt.Sprintf("      const result = await api.%s.%s(%s);\n", mod.Name, act.Name, argsStr))
		sb.WriteString("      return result;\n")
		sb.WriteString("    } catch (e) {\n")
		sb.WriteString("      error.value = e instanceof Error ? e : new Error(String(e));\n")
		sb.WriteString("      return undefined;\n")
		sb.WriteString("    } finally {\n")
		sb.WriteString("      loading.value = false;\n")
		sb.WriteString("    }\n")
		sb.WriteString("  }\n\n")
	}

	sb.WriteString("  return {\n")
	sb.WriteString("    loading,\n")
	sb.WriteString("    error,\n")
	for _, act := range mod.Actions {
		sb.WriteString(fmt.Sprintf("    %s,\n", act.Name))
	}
	sb.WriteString("  };\n")
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "use"+mod.Name+".ts"), []byte(sb.String()), 0644)
}
