package node

// barrel.go — emits the root index.ts barrel export and package.json alias.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

func (e *NodeEmitter) emitBarrel(a ast.AST, outDir string) error {
	if err := writeIndexTS(a, outDir); err != nil {
		return err
	}
	return writePackageJSON(a, outDir)
}

func writeIndexTS(a ast.AST, outDir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("export * from './types';\n")
	return os.WriteFile(filepath.Join(outDir, "index.ts"), []byte(sb.String()), 0644)
}

func writePackageJSON(a ast.AST, outDir string) error {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString("  \"name\": \"@veld/generated\",\n")
	sb.WriteString("  \"private\": true,\n")
	sb.WriteString("  \"types\": \"./index.ts\",\n")
	sb.WriteString("  \"exports\": {\n")
	sb.WriteString("    \".\": \"./index.ts\",\n")
	sb.WriteString("    \"./types\": \"./types/index.ts\",\n")
	sb.WriteString("    \"./client\": \"./client/api.ts\"")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf(",\n    \"./client/%sApi\": \"./client/%sApi.ts\"", moduleLower, moduleLower))
	}
	sb.WriteString("\n  }\n}\n")
	return os.WriteFile(filepath.Join(outDir, "package.json"), []byte(sb.String()), 0644)
}
