package node

// errors.go — emits errors/_base.ts (shared ApiError class) and
// errors/{module}.errors.ts with per-action typed error classes.
// Each action gets its own error type so the compiler prevents returning wrong errors.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// emitErrorsBase writes errors/_base.ts with the shared ApiError class.
// Called once from Emit() so all module error files can import it.
func (e *NodeEmitter) emitErrorsBase(a ast.AST, outDir string) error {
	// Only emit if at least one module has errors.
	hasAnyErrors := false
	for _, mod := range a.Modules {
		if emitter.HasErrors(mod) {
			hasAnyErrors = true
			break
		}
	}
	if !hasAnyErrors {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("export class ApiError<Code extends string = string> extends Error {\n")
	sb.WriteString("  readonly code: Code;\n")
	sb.WriteString("  readonly status: number;\n\n")
	sb.WriteString("  constructor(code: Code, status: number, message?: string) {\n")
	sb.WriteString("    super(message ?? code);\n")
	sb.WriteString("    this.name = 'ApiError';\n")
	sb.WriteString("    this.code = code;\n")
	sb.WriteString("    this.status = status;\n")
	sb.WriteString("  }\n\n")
	sb.WriteString("  toJSON() {\n")
	sb.WriteString("    return { error: this.message, code: this.code };\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "_base.ts"), []byte(sb.String()), 0644)
}

// emitErrorsBarrel writes errors/index.ts that re-exports the base ApiError
// and all per-module error types/factories.
func (e *NodeEmitter) emitErrorsBarrel(a ast.AST, outDir string) error {
	hasAnyErrors := false
	for _, mod := range a.Modules {
		if emitter.HasErrors(mod) {
			hasAnyErrors = true
			break
		}
	}
	if !hasAnyErrors {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("export { ApiError } from './_base';\n")
	for _, mod := range a.Modules {
		if !emitter.HasErrors(mod) {
			continue
		}
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf("export * from './%s.errors';\n", moduleLower))
	}

	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(sb.String()), 0644)
}

// emitErrors writes errors/{moduleLower}.errors.ts if the module has any
// actions with typed errors defined.
func (e *NodeEmitter) emitErrors(mod ast.Module, outDir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	var sb strings.Builder

	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")

	// Import ApiError for local use (new ApiError(...) in factories below)
	// and re-export it so consumers can also import from this module's error file.
	sb.WriteString("import { ApiError } from './_base';\n")
	sb.WriteString("export { ApiError } from './_base';\n\n")

	// Per-action error types and factory objects
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		pascal := act.Name

		// Build union of error codes for this action
		var codes []string
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			codes = append(codes, fmt.Sprintf("'%s'", code))
		}

		// Type alias: union of all error codes for this action
		sb.WriteString(fmt.Sprintf("/** Error codes for %s */\n", pascal))
		sb.WriteString(fmt.Sprintf("export type %sErrorCode = %s;\n\n", pascal, strings.Join(codes, " | ")))

		// Typed error type: ApiError narrowed to only this action's codes
		sb.WriteString(fmt.Sprintf("/** Typed error for %s — can only carry %s error codes */\n", pascal, pascal))
		sb.WriteString(fmt.Sprintf("export type %sError = ApiError<%sErrorCode>;\n\n", pascal, pascal))

		// Factory object
		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf("/** Error factories for %s */\n", pascal))
		sb.WriteString(fmt.Sprintf("export const %sErrors = {\n", camelAction))
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			camelErr := emitter.ToCamelCase(errName)
			sb.WriteString(fmt.Sprintf("  %s: (message?: string): %sError =>\n", camelErr, pascal))
			sb.WriteString(fmt.Sprintf("    new ApiError('%s', %d, message ?? '%s'),\n", code, status, errName))
		}
		sb.WriteString("} as const;\n\n")
	}

	// Aggregate module errors namespace for convenience
	sb.WriteString(fmt.Sprintf("export const %sErrors = {\n", moduleLower))
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sErrors,\n", camelAction, camelAction))
	}
	sb.WriteString("} as const;\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+".errors.ts"), []byte(sb.String()), 0644)
}
