package node_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/backend/node"
	_ "github.com/Adhamzineldin/Veld/internal/emitter/backend/node"
)

// minimalAST returns a small but representative AST for testing.
func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

func TestNodeEmitterEmit(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "index.ts"),
		filepath.Join(outDir, "package.json"),
		filepath.Join(outDir, "types", "auth.ts"),
		filepath.Join(outDir, "types", "index.ts"),
		filepath.Join(outDir, "interfaces", "IAuthService.ts"),
		filepath.Join(outDir, "routes", "auth.routes.ts"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestNodeEmitterDryRun(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestNodeEmitterTypesContent(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "types", "auth.ts"))
	if err != nil {
		t.Fatalf("ReadFile types/auth.ts: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"User class", "export class User {"},
		{"optional field", "bio?: string;"},
		{"required field", "tags!: string[];"},
		{"constructor", "constructor(data?: Partial<User>)"},
		{"getter", "getTags(): string[]"},
		{"setter", "setTags(value: string[])"},
		{"toJSON", "toJSON(): Record<string, unknown>"},
		{"fromJSON", "static fromJSON(data: Record<string, unknown>): User"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("types/auth.ts missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestNodeEmitterInterfaceContent(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "interfaces", "IAuthService.ts"))
	if err != nil {
		t.Fatalf("ReadFile IAuthService.ts: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"interface declaration", "export interface IAuthService {"},
		{"login method with input", "login(input: LoginInput): Promise<User>;"},
		{"me method no input", "me(): Promise<User>;"},
		{"logout returns void", "logout(): Promise<void>;"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("IAuthService.ts missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestNodeEmitterRoutesContent(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "routes", "auth.routes.ts"))
	if err != nil {
		t.Fatalf("ReadFile auth.routes.ts: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"import service interface", "import type { IAuthService }"},
		{"export function", "export function authRouter("},
		{"post route", "router.post('/api/auth/login'"},
		{"get route", "router.get('/api/auth/me'"},
		{"delete route", "router.delete('/api/auth/logout'"},
		{"post 201 status", "res.status(201).json(result)"},
		{"delete 204 status", "res.status(204).end()"},
		{"try/catch", "} catch (err: any) {"},
		{"service call camelCase", "service.login("},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("auth.routes.ts missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestNodeEmitterPathParams(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
					{Name: "Delete", Method: "DELETE", Path: "/items/:id"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "routes", "items.routes.ts"))
	content := string(data)

	if !strings.Contains(content, "req.params.id") {
		t.Error("path param :id should be extracted via req.params.id")
	}

	data2, _ := os.ReadFile(filepath.Join(outDir, "interfaces", "IItemsService.ts"))
	iface := string(data2)
	if !strings.Contains(iface, "id: string") {
		t.Error("interface should include path param id: string")
	}
}

func TestNodeEmitterModulePrefix(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "User", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name:   "Users",
				Prefix: "/api/v1",
				Actions: []ast.Action{
					{Name: "List", Method: "GET", Path: "/users", Output: "User"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "routes", "users.routes.ts"))
	if !strings.Contains(string(data), "'/api/v1/users'") {
		t.Error("module prefix should be prepended to the route path")
	}
}

func TestNodeEmitterSummary(t *testing.T) {
	e := node.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}

	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	for _, want := range []string{"types/", "interfaces/", "routes/"} {
		if !dirs[want] {
			t.Errorf("Summary() missing entry for directory %q", want)
		}
	}
}

func TestNodeEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("node-ts"); err != nil {
		t.Errorf("node-ts backend not registered: %v", err)
	}
}

// TestNodeEmitterModelsWithNoModules verifies ALL models/enums are generated
// even when the AST has zero modules (no actions at all).
func TestNodeEmitterModelsWithNoModules(t *testing.T) {
	e := node.New()
	outDir := t.TempDir()

	modelsOnlyAST := ast.AST{
		Models: []ast.Model{
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "string"},
					{Name: "email", Type: "string"},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
			{
				Name: "Product",
				Fields: []ast.Field{
					{Name: "name", Type: "string"},
					{Name: "price", Type: "float"},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user"}},
		},
		Modules: []ast.Module{}, // ZERO modules
	}

	if err := e.Emit(modelsOnlyAST, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	commonPath := filepath.Join(outDir, "types", "common.ts")
	data, err := os.ReadFile(commonPath)
	if err != nil {
		t.Fatalf("types/common.ts must exist when there are models but no modules: %v", err)
	}
	content := string(data)

	checks := []struct{ desc, needle string }{
		{"User class", "export class User {"},
		{"Product class", "export class Product {"},
		{"constructor", "constructor(data?: Partial<User>)"},
		{"getter", "getEmail():"},
		{"setter", "setEmail(value:"},
		{"toJSON", "toJSON(): Record<string, unknown>"},
		{"fromJSON", "static fromJSON(data:"},
		{"Role enum", "export type Role"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("types/common.ts missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}

	barrelData, err := os.ReadFile(filepath.Join(outDir, "types", "index.ts"))
	if err != nil {
		t.Fatalf("types/index.ts must exist: %v", err)
	}
	if !strings.Contains(string(barrelData), "common") {
		t.Errorf("types/index.ts must reference common.ts:\n%s", string(barrelData))
	}
}
