package node

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
	"github.com/veld-dev/veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterBackend("node", New())
}

type NodeEmitter struct{}

func (*NodeEmitter) IsBackend() {}
func New() *NodeEmitter         { return &NodeEmitter{} }

func (e *NodeEmitter) Summary(modules []string) []emitter.SummaryLine {
	lines := []emitter.SummaryLine{
		{Dir: "types/", Files: "types.ts"},
	}
	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "I"+m+"Service.ts")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "interfaces/", Files: strings.Join(ifaceFiles, ", ")})
	}
	routeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		routeFiles = append(routeFiles, strings.ToLower(m)+".routes.ts")
	}
	if len(routeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "routes/", Files: strings.Join(routeFiles, ", ")})
	}
	lines = append(lines, emitter.SummaryLine{Dir: "schemas/", Files: "schemas.ts"})
	return lines
}

func (e *NodeEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	if err := e.emitAllTypes(a, outDir); err != nil {
		return fmt.Errorf("types: %w", err)
	}
	for _, mod := range a.Modules {
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("interface for %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(a, mod, outDir); err != nil {
			return fmt.Errorf("routes for %s: %w", mod.Name, err)
		}
	}
	if err := e.emitZodSchemas(a, outDir); err != nil {
		return fmt.Errorf("zod schemas: %w", err)
	}
	if err := e.emitBarrel(a, outDir); err != nil {
		return fmt.Errorf("barrel: %w", err)
	}
	return nil
}

// ── types/types.ts — single file with ALL types (no duplicates) ───────────────

func (e *NodeEmitter) emitAllTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")

	for _, en := range a.Enums {
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("\"%s\"", v)
		}
		sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", en.Name, strings.Join(quoted, " | ")))
	}

	for _, m := range a.Models {
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
		}
		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("export interface %s extends %s {\n", m.Name, m.Extends))
		} else {
			sb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
		}
		for _, f := range m.Fields {
			tsType := tshelpers.VeldFieldToTS(f)
			opt := ""
			if f.Optional {
				opt = "?"
			}
			sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, tsType))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "types.ts"), []byte(sb.String()), 0644)
}

// ── interfaces/I{Module}Service.ts ────────────────────────────────────────────

func (e *NodeEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	usedTypes := emitter.CollectUsedTypes(a, mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types/types';\n", strings.Join(usedTypes, ", ")))
	}

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("\n/** %s */\n", mod.Description))
	}
	sb.WriteString(fmt.Sprintf("\nexport interface I%sService {\n", mod.Name))
	for _, act := range mod.Actions {
		outputType := tshelpers.FormatOutputType(act)
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("  /** %s */\n", act.Description))
		}
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		var params []string
		for _, p := range pathParams {
			params = append(params, p+": string")
		}
		if act.Input != "" {
			params = append(params, "input: "+act.Input)
		}
		if act.Query != "" {
			params = append(params, "query: "+act.Query)
		}

		sb.WriteString(fmt.Sprintf("  %s(%s): Promise<%s>;\n", act.Name, strings.Join(params, ", "), outputType))
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("I%sService.ts", mod.Name)), []byte(sb.String()), 0644)
}

// ── routes/{module}.routes.ts — with try/catch, status codes, Zod validation ──

func (e *NodeEmitter) emitRoutes(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	funcName := moduleLower + "Router"
	allMiddleware := emitter.CollectModuleMiddleware(mod)

	// Collect which schemas we need to import for validation
	seen := make(map[string]bool)
	var schemaImports []string
	for _, act := range mod.Actions {
		if act.Input != "" && !seen[act.Input] {
			seen[act.Input] = true
			schemaImports = append(schemaImports, act.Input+"Schema")
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("import type { I%sService } from '../interfaces/I%sService';\n", mod.Name, mod.Name))

	if len(schemaImports) > 0 {
		sb.WriteString(fmt.Sprintf("import { %s } from '../schemas/schemas';\n", strings.Join(schemaImports, ", ")))
	}

	if len(allMiddleware) > 0 {
		sb.WriteString("\nexport interface Middleware {\n")
		for _, mw := range allMiddleware {
			sb.WriteString(fmt.Sprintf("  %s: (req: any, res: any, next: () => void) => void;\n", mw))
		}
		sb.WriteString("}\n")
	}

	sb.WriteString("\n")
	if len(allMiddleware) > 0 {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService, middleware: Middleware): void {\n", funcName, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService): void {\n", funcName, mod.Name))
	}

	for _, act := range mod.Actions {
		method := strings.ToLower(act.Method)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("\n  // %s\n", act.Description))
		}

		mwArgs := ""
		for _, mw := range act.Middleware {
			mwArgs += fmt.Sprintf("middleware.%s, ", mw)
		}

		sb.WriteString(fmt.Sprintf("\n  router.%s('%s', %sasync (req: any, res: any) => {\n", method, routePath, mwArgs))
		sb.WriteString("    try {\n")

		pathParams := emitter.ExtractPathParams(routePath)
		var callArgs []string
		for _, p := range pathParams {
			callArgs = append(callArgs, fmt.Sprintf("req.params.%s", p))
		}
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf("      const input = %sSchema.parse(req.body);\n", act.Input))
			callArgs = append(callArgs, "input")
		}
		if act.Query != "" {
			callArgs = append(callArgs, "req.query")
		}

		serviceCall := fmt.Sprintf("service.%s(%s)", act.Name, strings.Join(callArgs, ", "))

		switch {
		case act.Method == "DELETE" && act.Output == "":
			sb.WriteString(fmt.Sprintf("      await %s;\n", serviceCall))
			sb.WriteString("      res.status(204).end();\n")
		case act.Method == "POST":
			sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
			sb.WriteString("      res.status(201).json(result);\n")
		default:
			sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
			sb.WriteString("      res.json(result);\n")
		}

		sb.WriteString("    } catch (err: any) {\n")
		sb.WriteString("      if (err.name === 'ZodError') {\n")
		sb.WriteString("        return res.status(400).json({ error: 'Validation failed', details: err.errors });\n")
		sb.WriteString("      }\n")
		sb.WriteString("      const status = err.status ?? err.statusCode ?? 500;\n")
		sb.WriteString("      res.status(status).json({ error: err.message ?? 'Internal Server Error' });\n")
		sb.WriteString("    }\n")
		sb.WriteString("  });\n")
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+".routes.ts"), []byte(sb.String()), 0644)
}

// ── schemas/schemas.ts — Zod validation schemas ──────────────────────────────

func (e *NodeEmitter) emitZodSchemas(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "schemas")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	enumNames := make(map[string]bool)
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("import { z } from 'zod';\n\n")

	for _, en := range a.Enums {
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("'%s'", v)
		}
		sb.WriteString(fmt.Sprintf("export const %sSchema = z.enum([%s]);\n\n", en.Name, strings.Join(quoted, ", ")))
	}

	for _, m := range a.Models {
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
		}
		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("export const %sSchema = %sSchema.extend({\n", m.Name, m.Extends))
		} else {
			sb.WriteString(fmt.Sprintf("export const %sSchema = z.object({\n", m.Name))
		}
		for _, f := range m.Fields {
			zodType := veldFieldToZod(f, enumNames)
			if f.Default != "" {
				defaultVal := f.Default
				if !strings.HasPrefix(defaultVal, "\"") && defaultVal != "true" && defaultVal != "false" && !isNumericDefault(defaultVal) {
					defaultVal = "'" + defaultVal + "'"
				} else if strings.HasPrefix(defaultVal, "\"") {
					defaultVal = "'" + strings.Trim(defaultVal, "\"") + "'"
				}
				zodType += fmt.Sprintf(".default(%s)", defaultVal)
			}
			if f.Optional && f.Default == "" {
				zodType += ".optional()"
			}
			sb.WriteString(fmt.Sprintf("  %s: %s,\n", f.Name, zodType))
		}
		sb.WriteString("});\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "schemas.ts"), []byte(sb.String()), 0644)
}

// ── barrel index.ts + package.json ───────────────────────────────────────────

func (e *NodeEmitter) emitBarrel(a ast.AST, outDir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("export * from './types/types';\n")
	sb.WriteString("export * from './schemas/schemas';\n")
	if err := os.WriteFile(filepath.Join(outDir, "index.ts"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	pkg := `{
  "name": "@veld/generated",
  "private": true,
  "types": "./index.ts",
  "exports": {
    ".": "./index.ts",
    "./types": "./types/types.ts",
    "./schemas": "./schemas/schemas.ts",
    "./client": "./client/api.ts"
  }
}
`
	return os.WriteFile(filepath.Join(outDir, "package.json"), []byte(pkg), 0644)
}

// ── helpers ──────────────────────────────────────────────────────────────────

func isNumericDefault(s string) bool {
	if len(s) == 0 {
		return false
	}
	start := 0
	if s[0] == '-' {
		start = 1
	}
	if start >= len(s) {
		return false
	}
	for i := start; i < len(s); i++ {
		if (s[i] < '0' || s[i] > '9') && s[i] != '.' {
			return false
		}
	}
	return true
}

func veldFieldToZod(f ast.Field, enumNames map[string]bool) string {
	if f.IsMap {
		return fmt.Sprintf("z.record(z.string(), %s)", veldTypeToZod(f.MapValueType, false, enumNames))
	}
	return veldTypeToZod(f.Type, f.IsArray, enumNames)
}

func veldTypeToZod(t string, isArray bool, enumNames map[string]bool) string {
	var base string
	switch t {
	case "string":
		base = "z.string()"
	case "int":
		base = "z.number().int()"
	case "float":
		base = "z.number()"
	case "bool":
		base = "z.boolean()"
	case "date":
		base = "z.string().date()"
	case "datetime":
		base = "z.string().datetime()"
	case "uuid":
		base = "z.string().uuid()"
	default:
		base = fmt.Sprintf("%sSchema", t)
	}
	if isArray {
		return fmt.Sprintf("z.array(%s)", base)
	}
	return base
}
