package node

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
	"github.com/veld-dev/veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterBackend("node", New())
}

// NodeEmitter generates TypeScript types, service interfaces, and route
// files from a parsed AST.
type NodeEmitter struct{}

func (*NodeEmitter) IsBackend() {} // marker for BackendEmitter

// New returns a NodeEmitter.
func New() *NodeEmitter { return &NodeEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *NodeEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine

	typeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		typeFiles = append(typeFiles, strings.ToLower(m)+".ts")
	}
	if len(typeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "types/", Files: strings.Join(typeFiles, ", ")})
	}

	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "I"+m+"Service.ts")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "interfaces/", Files: strings.Join(ifaceFiles, ", ")})
	}

	routeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		routeFiles = append(routeFiles, strings.ToLower(m)+".routes.ts")
	}
	if len(routeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "routes/", Files: strings.Join(routeFiles, ", ")})
	}

	lines = append(lines, emitter.SummaryLine{Dir: "schemas/", Files: "schemas.ts"})
	return lines
}

// Emit writes all generated files into outDir.
func (e *NodeEmitter) Emit(a ast.AST, outDir string) error {
	for _, mod := range a.Modules {
		if err := e.emitTypes(a, mod, outDir); err != nil {
			return fmt.Errorf("types for module %s: %w", mod.Name, err)
		}
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("interface for module %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(a, mod, outDir); err != nil {
			return fmt.Errorf("routes for module %s: %w", mod.Name, err)
		}
	}
	if err := e.emitZodSchemas(a, outDir); err != nil {
		return fmt.Errorf("zod schemas: %w", err)
	}
	return nil
}

// emitTypes writes generated/types/{module}.ts with TypeScript interfaces and enums.
func (e *NodeEmitter) emitTypes(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	usedNames := emitter.CollectTransitiveModels(a, mod)
	usedEnums := emitter.CollectUsedEnums(a, mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")

	for _, en := range a.Enums {
		if !usedEnums[en.Name] {
			continue
		}
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("\"%s\"", v)
		}
		sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", en.Name, strings.Join(quoted, " | ")))
	}

	for _, m := range a.Models {
		if !usedNames[m.Name] {
			continue
		}
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
		}
		sb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
		for _, f := range m.Fields {
			tsType := tshelpers.VeldTypeToTS(f.Type, f.IsArray)
			optMark := ""
			if f.Optional {
				optMark = "?"
			}
			sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, optMark, tsType))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, strings.ToLower(mod.Name)+".ts"), []byte(sb.String()), 0644)
}

// emitInterface writes generated/interfaces/I{Module}Service.ts.
func (e *NodeEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	usedTypes := emitter.CollectUsedTypes(a, mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types/%s';\n", strings.Join(usedTypes, ", "), moduleLower))
	}

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("\n/** %s */\n", mod.Description))
	}
	sb.WriteString(fmt.Sprintf("\nexport interface I%sService {\n", mod.Name))
	for _, act := range mod.Actions {
		outputType := tshelpers.FormatOutputType(act)
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("  /** %s */\n", act.Description))
		}
		if act.Input != "" && act.Query != "" {
			sb.WriteString(fmt.Sprintf("  %s(input: %s, query: %s): Promise<%s>;\n", act.Name, act.Input, act.Query, outputType))
		} else if act.Input != "" {
			sb.WriteString(fmt.Sprintf("  %s(input: %s): Promise<%s>;\n", act.Name, act.Input, outputType))
		} else if act.Query != "" {
			sb.WriteString(fmt.Sprintf("  %s(query: %s): Promise<%s>;\n", act.Name, act.Query, outputType))
		} else {
			sb.WriteString(fmt.Sprintf("  %s(userId: string): Promise<%s>;\n", act.Name, outputType))
		}
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("I%sService.ts", mod.Name)), []byte(sb.String()), 0644)
}

// emitRoutes writes generated/routes/{module}.routes.ts.
func (e *NodeEmitter) emitRoutes(_ ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	funcName := moduleLower + "Router"
	allMiddleware := emitter.CollectModuleMiddleware(mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("import type { I%sService } from '../interfaces/I%sService';\n", mod.Name, mod.Name))

	if len(allMiddleware) > 0 {
		sb.WriteString("\n// Middleware functions your app must supply.\n")
		sb.WriteString("export interface Middleware {\n")
		for _, mw := range allMiddleware {
			sb.WriteString(fmt.Sprintf("  %s: (req: any, res: any, next: () => void) => void;\n", mw))
		}
		sb.WriteString("}\n")
	}

	sb.WriteString(fmt.Sprintf("\n// Pass any Express-compatible router, your service, and middleware implementations.\n"))
	if len(allMiddleware) > 0 {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService, middleware: Middleware): void {\n", funcName, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService): void {\n", funcName, mod.Name))
	}

	for _, act := range mod.Actions {
		method := strings.ToLower(act.Method)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("\n  // %s\n", act.Description))
		}

		mwArgs := ""
		for _, mw := range act.Middleware {
			mwArgs += fmt.Sprintf("middleware.%s, ", mw)
		}

		sb.WriteString(fmt.Sprintf("\n  router.%s('%s', %sasync (req: any, res: any) => {\n", method, routePath, mwArgs))

		if act.Input != "" && act.Query != "" {
			sb.WriteString(fmt.Sprintf("    const result = await service.%s(req.body, req.query);\n", act.Name))
		} else if act.Input != "" {
			sb.WriteString(fmt.Sprintf("    const result = await service.%s(req.body);\n", act.Name))
		} else if act.Query != "" {
			sb.WriteString(fmt.Sprintf("    const result = await service.%s(req.query);\n", act.Name))
		} else {
			sb.WriteString(fmt.Sprintf("    const result = await service.%s(req.user?.id);\n", act.Name))
		}
		sb.WriteString("    res.json(result);\n")
		sb.WriteString("  });\n")
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+".routes.ts"), []byte(sb.String()), 0644)
}

// emitZodSchemas writes generated/schemas/schemas.ts with Zod validation schemas.
func (e *NodeEmitter) emitZodSchemas(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "schemas")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	enumNames := make(map[string]bool)
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("import { z } from 'zod';\n\n")

	for _, en := range a.Enums {
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("'%s'", v)
		}
		sb.WriteString(fmt.Sprintf("export const %sSchema = z.enum([%s]);\n\n", en.Name, strings.Join(quoted, ", ")))
	}

	for _, m := range a.Models {
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
		}
		sb.WriteString(fmt.Sprintf("export const %sSchema = z.object({\n", m.Name))
		for _, f := range m.Fields {
			zodType := veldTypeToZod(f.Type, f.IsArray, enumNames)
			if f.Default != "" {
				defaultVal := f.Default
				if !strings.HasPrefix(defaultVal, "\"") && defaultVal != "true" && defaultVal != "false" && !isNumericDefault(defaultVal) {
					defaultVal = "'" + defaultVal + "'"
				} else if strings.HasPrefix(defaultVal, "\"") {
					defaultVal = "'" + strings.Trim(defaultVal, "\"") + "'"
				}
				zodType += fmt.Sprintf(".default(%s)", defaultVal)
			}
			if f.Optional && f.Default == "" {
				zodType += ".optional()"
			}
			sb.WriteString(fmt.Sprintf("  %s: %s,\n", f.Name, zodType))
		}
		sb.WriteString("});\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "schemas.ts"), []byte(sb.String()), 0644)
}

// ── node-specific helpers (not shared) ────────────────────────────────────────

// isNumericDefault returns true if the default value string looks like a number.
func isNumericDefault(s string) bool {
	if len(s) == 0 {
		return false
	}
	start := 0
	if s[0] == '-' {
		start = 1
	}
	if start >= len(s) {
		return false
	}
	for i := start; i < len(s); i++ {
		if (s[i] < '0' || s[i] > '9') && s[i] != '.' {
			return false
		}
	}
	return true
}

// veldTypeToZod maps a Veld type name to its Zod equivalent.
func veldTypeToZod(t string, isArray bool, enumNames map[string]bool) string {
	var base string
	switch t {
	case "string":
		base = "z.string()"
	case "int":
		base = "z.number().int()"
	case "float":
		base = "z.number()"
	case "bool":
		base = "z.boolean()"
	case "date":
		base = "z.string().date()"
	case "datetime":
		base = "z.string().datetime()"
	case "uuid":
		base = "z.string().uuid()"
	default:
		base = fmt.Sprintf("%sSchema", t)
	}
	if isArray {
		return fmt.Sprintf("z.array(%s)", base)
	}
	return base
}
