package node

// routes.go — emits routes/{module}.routes.ts with try/catch and
// correct HTTP status codes (201 for POST, 204 for DELETE with no output).
//
// When EmitOptions.Validate is true, route handlers are augmented with:
//   - parseX(req.body)  — validates input shape before passing to service (→ 400)
//   - assertX(result)   — guards output shape before sending to client   (→ 500)

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *NodeEmitter) emitRoutes(a ast.AST, mod ast.Module, outDir string, opts emitter.EmitOptions) error {
	dir := filepath.Join(outDir, "routes")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	funcName := moduleLower + "Router"
	allMiddleware := emitter.CollectModuleMiddleware(mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("import type { I%sService } from '../interfaces/I%sService';\n", mod.Name, mod.Name))

	if emitter.HasErrors(mod) {
		sb.WriteString(fmt.Sprintf("import { ApiError } from '../errors/%s.errors';\n", moduleLower))
	}

	if len(allMiddleware) > 0 {
		// Import from the single shared middleware interface.
		sb.WriteString("import type { IMiddleware } from '../middleware/IMiddleware';\n")
	}

	// When validation is enabled, import the generated zero-dep validators.
	if opts.Validate {
		if imports := buildValidatorImports(mod); len(imports) > 0 {
			sb.WriteString(fmt.Sprintf("import { %s } from '../_validators';\n", strings.Join(imports, ", ")))
		}
	}

	sb.WriteString("\n")
	if len(allMiddleware) > 0 {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService, middleware: IMiddleware): void {\n", funcName, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService): void {\n", funcName, mod.Name))
	}

	for _, act := range mod.Actions {
		if err := writeRouteHandler(&sb, mod, act, opts); err != nil {
			return err
		}
	}

	sb.WriteString("}\n")

	if err := os.WriteFile(filepath.Join(dir, moduleLower+".routes.ts"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	return nil
}

// writeRouteHandler appends a single route registration + async handler to sb.
func writeRouteHandler(sb *strings.Builder, mod ast.Module, act ast.Action, opts emitter.EmitOptions) error {
	method := strings.ToLower(act.Method)
	routePath := act.Path
	if mod.Prefix != "" {
		routePath = mod.Prefix + act.Path
	}
	camelName := emitter.ToCamelCase(act.Name)

	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("\n  // %s\n", act.Description))
	}

	// WebSocket actions: commented stub only, no validation needed.
	if act.Method == "WS" {
		sb.WriteString(fmt.Sprintf("\n  // WebSocket: %s\n", routePath))
		sb.WriteString("  // To handle this route, set up a WebSocket server (e.g. 'ws' package)\n")
		sb.WriteString(fmt.Sprintf("  // and call service.%s(ws", camelName))
		for _, p := range emitter.ExtractPathParams(routePath) {
			sb.WriteString(fmt.Sprintf(", %s", p))
		}
		sb.WriteString(") on connection.\n")
		return nil
	}

	mwArgs := ""
	for _, mw := range act.Middleware {
		mwArgs += fmt.Sprintf("middleware.%s, ", emitter.ToCamelCase(mw))
	}

	sb.WriteString(fmt.Sprintf("\n  router.%s('%s', %sasync (req: any, res: any) => {\n", method, routePath, mwArgs))
	sb.WriteString("    try {\n")

	// ── Build service call arguments ─────────────────────────────────────────
	pathParams := emitter.ExtractPathParams(routePath)
	callArgs := make([]string, 0, len(pathParams)+2)
	for _, p := range pathParams {
		callArgs = append(callArgs, fmt.Sprintf("req.params.%s", p))
	}

	if act.Input != "" {
		if opts.Validate {
			// Parse and validate the request body; throws VeldValidationError (400) on failure.
			sb.WriteString(fmt.Sprintf("      const body = parse%s(req.body);\n", act.Input))
			callArgs = append(callArgs, "body")
		} else {
			callArgs = append(callArgs, "req.body")
		}
	}

	if act.Query != "" {
		callArgs = append(callArgs, "req.query")
	}

	serviceCall := fmt.Sprintf("service.%s(%s)", camelName, strings.Join(callArgs, ", "))

	// ── Service call + optional output assertion + response ──────────────────
	switch {
	case act.Method == "DELETE" && act.Output == "":
		sb.WriteString(fmt.Sprintf("      await %s;\n", serviceCall))
		sb.WriteString("      res.status(204).end();\n")

	case act.Method == "POST":
		sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
		if opts.Validate && act.Output != "" {
			writeNodeOutputAssertion(sb, act)
		}
		sb.WriteString("      res.status(201).json(result);\n")

	default:
		sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
		if opts.Validate && act.Output != "" {
			writeNodeOutputAssertion(sb, act)
		}
		sb.WriteString("      res.json(result);\n")
	}

	// Catch block: handles VeldValidationError (400), VeldContractError (500), and service errors.
	sb.WriteString("    } catch (err: any) {\n")
	sb.WriteString("      const status = err.status ?? err.statusCode ?? 500;\n")
	sb.WriteString("      const body: Record<string, string> = { error: err.message ?? 'Internal Server Error' };\n")
	sb.WriteString("      if (err.code) body.code = err.code;\n")
	sb.WriteString("      res.status(status).json(body);\n")
	sb.WriteString("    }\n")
	sb.WriteString("  });\n")
	return nil
}

// writeNodeOutputAssertion emits assertX(result) or assertXArray(result).
// These throw VeldContractError (→ 500) if the service returns the wrong shape.
func writeNodeOutputAssertion(sb *strings.Builder, act ast.Action) {
	if act.OutputArray {
		sb.WriteString(fmt.Sprintf("      assert%sArray(result);\n", act.Output))
	} else {
		sb.WriteString(fmt.Sprintf("      assert%s(result);\n", act.Output))
	}
}

// emitMiddlewareInterface writes middleware/IMiddleware.ts — a single shared
// interface containing all unique middleware methods used across ALL modules.
// This way developers implement one middleware object and pass it to every module's router.
func (e *NodeEmitter) emitMiddlewareInterface(a ast.AST, outDir string) error {
	allMiddleware := emitter.CollectAllMiddleware(a.Modules)
	if len(allMiddleware) == 0 {
		return nil
	}

	dir := filepath.Join(outDir, "middleware")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("/**\n * Shared middleware interface for all modules.\n")
	sb.WriteString(" * Implement this interface once and pass it to every module's route registrar.\n */\n")
	sb.WriteString("export interface IMiddleware {\n")
	for _, mw := range allMiddleware {
		camelMw := emitter.ToCamelCase(mw)
		sb.WriteString(fmt.Sprintf("  /** %s middleware handler. */\n", mw))
		sb.WriteString(fmt.Sprintf("  %s(req: any, res: any, next: () => void): void;\n", camelMw))
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "IMiddleware.ts"), []byte(sb.String()), 0644)
}
