package node

// routes.go — emits routes/{module}.routes.ts with try/catch and
// correct HTTP status codes (201 for POST, 204 for DELETE with no output).

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *NodeEmitter) emitRoutes(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	funcName := moduleLower + "Router"
	allMiddleware := emitter.CollectModuleMiddleware(mod)

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("import type { I%sService } from '../interfaces/I%sService';\n", mod.Name, mod.Name))

	// Import typed errors if the module defines any.
	if emitter.HasErrors(mod) {
		sb.WriteString(fmt.Sprintf("import { ApiError } from '../errors/%s.errors';\n", moduleLower))
	}

	if len(allMiddleware) > 0 {
		sb.WriteString("\nexport interface Middleware {\n")
		for _, mw := range allMiddleware {
			sb.WriteString(fmt.Sprintf("  %s: (req: any, res: any, next: () => void) => void;\n", mw))
		}
		sb.WriteString("}\n")
	}

	sb.WriteString("\n")
	if len(allMiddleware) > 0 {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService, middleware: Middleware): void {\n", funcName, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("export function %s(router: any, service: I%sService): void {\n", funcName, mod.Name))
	}

	for _, act := range mod.Actions {
		if err := writeRouteHandler(&sb, mod, act); err != nil {
			return err
		}
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, moduleLower+".routes.ts"), []byte(sb.String()), 0644)
}

// writeRouteHandler appends a single route registration + async handler to sb.
func writeRouteHandler(sb *strings.Builder, mod ast.Module, act ast.Action) error {
	method := strings.ToLower(act.Method)
	routePath := act.Path
	if mod.Prefix != "" {
		routePath = mod.Prefix + act.Path
	}
	camelName := emitter.ToCamelCase(act.Name)

	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("\n  // %s\n", act.Description))
	}

	// WebSocket actions generate a commented handler stub
	if act.Method == "WS" {
		sb.WriteString(fmt.Sprintf("\n  // WebSocket: %s\n", routePath))
		sb.WriteString(fmt.Sprintf("  // To handle this route, set up a WebSocket server (e.g. 'ws' package)\n"))
		sb.WriteString(fmt.Sprintf("  // and call service.%s(ws", camelName))
		pathParams := emitter.ExtractPathParams(routePath)
		for _, p := range pathParams {
			sb.WriteString(fmt.Sprintf(", %s", p))
		}
		sb.WriteString(") on connection.\n")
		return nil
	}

	mwArgs := ""
	for _, mw := range act.Middleware {
		mwArgs += fmt.Sprintf("middleware.%s, ", mw)
	}

	sb.WriteString(fmt.Sprintf("\n  router.%s('%s', %sasync (req: any, res: any) => {\n", method, routePath, mwArgs))
	sb.WriteString("    try {\n")

	pathParams := emitter.ExtractPathParams(routePath)
	var callArgs []string
	for _, p := range pathParams {
		callArgs = append(callArgs, fmt.Sprintf("req.params.%s", p))
	}
	if act.Input != "" {
		callArgs = append(callArgs, "req.body")
	}
	if act.Query != "" {
		callArgs = append(callArgs, "req.query")
	}

	serviceCall := fmt.Sprintf("service.%s(%s)", camelName, strings.Join(callArgs, ", "))

	switch {
	case act.Method == "DELETE" && act.Output == "":
		sb.WriteString(fmt.Sprintf("      await %s;\n", serviceCall))
		sb.WriteString("      res.status(204).end();\n")
	case act.Method == "POST":
		sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
		sb.WriteString("      res.status(201).json(result);\n")
	default:
		sb.WriteString(fmt.Sprintf("      const result = await %s;\n", serviceCall))
		sb.WriteString("      res.json(result);\n")
	}

	sb.WriteString("    } catch (err: any) {\n")
	sb.WriteString("      const status = err.status ?? err.statusCode ?? 500;\n")
	sb.WriteString("      const body: Record<string, string> = { error: err.message ?? 'Internal Server Error' };\n")
	sb.WriteString("      if (err.code) body.code = err.code;\n")
	sb.WriteString("      res.status(status).json(body);\n")
	sb.WriteString("    }\n")
	sb.WriteString("  });\n")
	return nil
}
