package node

// sdk.go — service SDK generation for TypeScript/Node.js backend.
// Generates typed, fetch-based HTTP client classes for consumed services.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

// EmitServiceSdk generates TypeScript service SDK clients for each consumed service.
func (e *NodeEmitter) EmitServiceSdk(consumed []emitter.ConsumedServiceInfo, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun || len(consumed) == 0 {
		return nil
	}
	for _, c := range consumed {
		if err := emitNodeSdk(c, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", c.Name, err)
		}
	}
	return emitNodeSdkBarrel(consumed, outDir)
}

func emitNodeSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	dir := filepath.Join(outDir, "sdk", name)
	modelsDir := filepath.Join(dir, "models")
	if err := os.MkdirAll(modelsDir, 0755); err != nil {
		return err
	}
	if err := emitNodeSdkModels(consumed, modelsDir); err != nil {
		return err
	}
	if err := emitNodeSdkClient(consumed, dir); err != nil {
		return err
	}
	return emitNodeSdkIndex(consumed, dir)
}

// ── models/ ───────────────────────────────────────────────────────────────────

func emitNodeSdkModels(consumed emitter.ConsumedServiceInfo, modelsDir string) error {
	a := consumed.AST
	modelGroups, enumGroups, modelOwner, enumOwner := emitter.AssignModelsToModules(a)
	keys := emitter.SortedGroupKeys(modelGroups, enumGroups)

	for _, group := range keys {
		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString(fmt.Sprintf("// Service SDK types for: %s (%s)\n\n", consumed.Name, group))

		// Cross-group imports for extends / field references.
		models := modelGroups[group]
		crossImports := emitter.CrossGroupTypeNames(group, models, modelOwner, enumOwner)
		for _, fromGroup := range sortedStringKeys(crossImports) {
			types := crossImports[fromGroup]
			sb.WriteString(fmt.Sprintf("import type { %s } from './%s';\n", strings.Join(types, ", "), fromGroup))
		}
		if len(crossImports) > 0 {
			sb.WriteString("\n")
		}

		for _, en := range enumGroups[group] {
			sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n",
				en.Name, "'"+strings.Join(en.Values, "' | '")+"'"))
		}

		for _, m := range models {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("export class %s extends %s {\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("export class %s {\n", m.Name))
			}
			// Fields
			for _, f := range m.Fields {
				tsType := tshelpers.VeldFieldToTS(f)
				if f.Optional {
					sb.WriteString(fmt.Sprintf("  %s?: %s;\n", f.Name, tsType))
				} else {
					sb.WriteString(fmt.Sprintf("  %s!: %s;\n", f.Name, tsType))
				}
			}
			sb.WriteString("\n")
			// Constructor
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("  constructor(data?: Partial<%s>) {\n    super(data);\n    if (data) Object.assign(this, data);\n  }\n", m.Name))
			} else {
				sb.WriteString(fmt.Sprintf("  constructor(data?: Partial<%s>) {\n    if (data) Object.assign(this, data);\n  }\n", m.Name))
			}
			// Getters and setters
			for _, f := range m.Fields {
				tsType := tshelpers.VeldFieldToTS(f)
				pascal := strings.ToUpper(f.Name[:1]) + f.Name[1:]
				if f.Optional {
					sb.WriteString(fmt.Sprintf("\n  get%s(): %s | undefined { return this.%s; }\n", pascal, tsType, f.Name))
					sb.WriteString(fmt.Sprintf("  set%s(value: %s | undefined): void { this.%s = value; }\n", pascal, tsType, f.Name))
				} else {
					sb.WriteString(fmt.Sprintf("\n  get%s(): %s { return this.%s; }\n", pascal, tsType, f.Name))
					sb.WriteString(fmt.Sprintf("  set%s(value: %s): void { this.%s = value; }\n", pascal, tsType, f.Name))
				}
			}
			// toJSON + fromJSON
			sb.WriteString(fmt.Sprintf("\n  toJSON(): Record<string, unknown> { return { ...this }; }\n"))
			sb.WriteString(fmt.Sprintf("  static fromJSON(data: Record<string, unknown>): %s { return new %s(data as any); }\n", m.Name, m.Name))
			sb.WriteString("}\n\n")
		}

		if err := os.WriteFile(filepath.Join(modelsDir, group+".ts"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel index.ts
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	barrel.WriteString(fmt.Sprintf("// Service SDK types barrel for: %s\n\n", consumed.Name))
	for _, group := range keys {
		barrel.WriteString(fmt.Sprintf("export * from './%s';\n", group))
	}
	return os.WriteFile(filepath.Join(modelsDir, "index.ts"), []byte(barrel.String()), 0644)
}

// ── client.ts ─────────────────────────────────────────────────────────────────

func emitNodeSdkClient(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)

	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("// Service SDK: %s client for inter-service communication\n\n", consumed.Name))

	allTypes := nodeSdkCollectTypes(a)
	if len(allTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from './models';\n\n", strings.Join(allTypes, ", ")))
	}

	sb.WriteString("export class VeldApiError extends Error {\n")
	sb.WriteString("  constructor(public readonly status: number, public readonly body: string) {\n")
	sb.WriteString("    super(`HTTP ${status}: ${body}`);\n")
	sb.WriteString("    this.name = 'VeldApiError';\n")
	sb.WriteString("  }\n}\n\n")

	sb.WriteString("function buildQueryString(params?: Record<string, unknown>): string {\n")
	sb.WriteString("  if (!params) return '';\n")
	sb.WriteString("  const parts: string[] = [];\n")
	sb.WriteString("  for (const [k, v] of Object.entries(params)) {\n")
	sb.WriteString("    if (v !== undefined && v !== null) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);\n")
	sb.WriteString("  }\n")
	sb.WriteString("  return parts.length ? '?' + parts.join('&') : '';\n}\n\n")

	sb.WriteString(fmt.Sprintf("export class %s {\n", className))
	sb.WriteString("  private readonly base: string;\n")
	sb.WriteString("  private readonly hdrs: Record<string, string>;\n\n")

	sb.WriteString("  constructor(baseUrl?: string, headers?: Record<string, string>) {\n")
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("    this.base = baseUrl ?? process.env.%s ?? %q;\n", envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("    const resolved = baseUrl ?? process.env.%s;\n", envVar))
		sb.WriteString(fmt.Sprintf("    if (!resolved) throw new Error('No base URL for %s — pass baseUrl or set %s');\n", consumed.Name, envVar))
		sb.WriteString("    this.base = resolved;\n")
	}
	sb.WriteString("    this.hdrs = headers ?? {};\n  }\n\n")

	sb.WriteString("  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {\n")
	sb.WriteString("    const res = await fetch(this.base + path, {\n")
	sb.WriteString("      method,\n")
	sb.WriteString("      headers: { 'Content-Type': 'application/json', ...this.hdrs },\n")
	sb.WriteString("      body: body !== undefined ? JSON.stringify(body) : undefined,\n")
	sb.WriteString("    });\n")
	sb.WriteString("    if (!res.ok) throw new VeldApiError(res.status, await res.text());\n")
	sb.WriteString("    if (res.status === 204) return undefined as T;\n")
	sb.WriteString("    return res.json() as Promise<T>;\n  }\n")

	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				continue
			}
			sb.WriteString("\n")
			writeNodeSdkMethod(&sb, mod, act)
		}
	}
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "client.ts"), []byte(sb.String()), 0644)
}

func writeNodeSdkMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	outputType := tshelpers.FormatOutputType(act)
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	camelName := emitter.ToCamelCase(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("  /** %s %s — %s */\n", method, routePath, act.Description))
	} else {
		sb.WriteString(fmt.Sprintf("  /** %s %s */\n", method, routePath))
	}

	var urlExpr string
	if len(pathParams) > 0 {
		urlExpr = "`" + emitter.ToTemplateLiteral(routePath) + "`"
	} else {
		urlExpr = "'" + routePath + "'"
	}

	var sigParams []string
	for _, p := range pathParams {
		sigParams = append(sigParams, p+": string")
	}
	if act.Input != "" {
		sigParams = append(sigParams, "input: "+act.Input)
	}
	if act.Query != "" {
		sigParams = append(sigParams, "query?: "+act.Query)
	}

	queryAppend := ""
	if act.Query != "" {
		queryAppend = " + buildQueryString(query as Record<string, unknown>)"
	}

	sb.WriteString(fmt.Sprintf("  %s(%s): Promise<%s> {\n", camelName, strings.Join(sigParams, ", "), outputType))
	if method == "GET" || act.Input == "" {
		sb.WriteString(fmt.Sprintf("    return this.request('%s', %s%s);\n", method, urlExpr, queryAppend))
	} else {
		sb.WriteString(fmt.Sprintf("    return this.request('%s', %s%s, input);\n", method, urlExpr, queryAppend))
	}
	sb.WriteString("  }\n")
}

// ── index.ts / barrel ─────────────────────────────────────────────────────────

func emitNodeSdkIndex(consumed emitter.ConsumedServiceInfo, dir string) error {
	className := sdkhelpers.ServiceClassName(consumed.Name)
	content := "// AUTO-GENERATED BY VELD — DO NOT EDIT\n" +
		fmt.Sprintf("export { %s, VeldApiError } from './client';\n", className) +
		"export * from './models';\n"
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(content), 0644)
}

func emitNodeSdkBarrel(consumed []emitter.ConsumedServiceInfo, outDir string) error {
	dir := filepath.Join(outDir, "sdk")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	for _, c := range consumed {
		name := sdkhelpers.ServiceFileName(c.Name)
		className := sdkhelpers.ServiceClassName(c.Name)
		sb.WriteString(fmt.Sprintf("export { %s } from './%s';\n", className, name))
	}
	if len(consumed) > 0 {
		sb.WriteString(fmt.Sprintf("\nexport { VeldApiError } from './%s';\n", sdkhelpers.ServiceFileName(consumed[0].Name)))
	}
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(sb.String()), 0644)
}

func nodeSdkCollectTypes(a ast.AST) []string {
	seen := make(map[string]bool)
	var result []string
	// Collect types referenced by actions first.
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			if !seen[t] {
				seen[t] = true
				result = append(result, t)
			}
		}
	}
	// Always include every declared model and enum so services with no actions
	// (e.g. message-broker-only services) still have their types imported.
	for _, m := range a.Models {
		if !seen[m.Name] {
			seen[m.Name] = true
			result = append(result, m.Name)
		}
	}
	for _, en := range a.Enums {
		if !seen[en.Name] {
			seen[en.Name] = true
			result = append(result, en.Name)
		}
	}
	return result
}

func sortedStringKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
