package node

// types.go — emits types/{module}.ts + types/index.ts barrel.
//
// Types are "owned" by the first module that references them. Later modules
// that also need the same type import+re-export it from the canonical file.
// A barrel types/index.ts re-exports everything for convenience.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
	"github.com/veld-dev/veld/internal/emitter/tshelpers"
)

func (e *NodeEmitter) emitPerModuleTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// claimed tracks which module file "owns" each type definition.
	claimed := make(map[string]string) // typeName → moduleLowerName

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceFile → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")

		for source, names := range reExports {
			sb.WriteString(fmt.Sprintf("export { %s } from './%s';\n", strings.Join(names, ", "), source))
		}
		if len(reExports) > 0 && (len(ownedEnums) > 0 || len(ownedModels) > 0) {
			sb.WriteString("\n")
		}

		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", en.Name, strings.Join(quoted, " | ")))
		}

		for _, m := range ownedModels {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("export interface %s extends %s {\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
			}
			for _, f := range m.Fields {
				opt := ""
				if f.Optional {
					opt = "?"
				}
				sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, tshelpers.VeldFieldToTS(f)))
			}
			sb.WriteString("}\n\n")
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".ts"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: types/index.ts re-exports everything from all module files.
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	for _, mod := range a.Modules {
		barrel.WriteString(fmt.Sprintf("export * from './%s';\n", strings.ToLower(mod.Name)))
	}
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(barrel.String()), 0644)
}
