package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
)

// PythonEmitter generates Python TypedDict types, ABC service interfaces,
// and Flask route files from a parsed AST.
type PythonEmitter struct{}

// New returns a PythonEmitter.
func New() *PythonEmitter { return &PythonEmitter{} }

// Emit writes all generated files into outDir.
func (e *PythonEmitter) Emit(a ast.AST, outDir string) error {
	// Write top-level __init__.py files so generated/ is a proper package.
	for _, sub := range []string{"", "types", "interfaces", "routes"} {
		dir := filepath.Join(outDir, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		init := filepath.Join(dir, "__init__.py")
		if _, err := os.Stat(init); os.IsNotExist(err) {
			if err := os.WriteFile(init, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
				return err
			}
		}
	}

	for _, mod := range a.Modules {
		if err := e.emitTypes(a, mod, outDir); err != nil {
			return fmt.Errorf("types for module %s: %w", mod.Name, err)
		}
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("interface for module %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(a, mod, outDir); err != nil {
			return fmt.Errorf("routes for module %s: %w", mod.Name, err)
		}
	}
	return nil
}

// emitTypes writes generated/types/{module}.py with TypedDict classes and Literal enums.
func (e *PythonEmitter) emitTypes(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "types")

	usedNames := collectTransitiveModels(a, mod)
	usedEnums := collectUsedEnums(a, mod)

	// Determine needed imports
	needsList := false
	needsOptional := false
	needsLiteral := len(usedEnums) > 0

	for _, m := range a.Models {
		if !usedNames[m.Name] {
			continue
		}
		for _, f := range m.Fields {
			if f.IsArray {
				needsList = true
			}
			if f.Optional {
				needsOptional = true
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")

	// Build typing import
	typingImports := []string{"TypedDict"}
	if needsList {
		typingImports = append(typingImports, "List")
	}
	if needsOptional {
		typingImports = append(typingImports, "Optional")
	}
	if needsLiteral {
		typingImports = append(typingImports, "Literal")
	}
	sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
	sb.WriteString("\n")

	// Emit enums as Literal types
	for _, en := range a.Enums {
		if !usedEnums[en.Name] {
			continue
		}
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("\"%s\"", v)
		}
		sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
	}

	for _, m := range a.Models {
		if !usedNames[m.Name] {
			continue
		}
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
		}
		sb.WriteString(fmt.Sprintf("class %s(TypedDict, total=False):\n", m.Name))
		if len(m.Fields) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, f := range m.Fields {
			pyType := veldTypeToPy(f.Type, f.IsArray)
			if f.Optional {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}
			sb.WriteString(fmt.Sprintf("    %s: %s\n", toSnakeCase(f.Name), pyType))
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(dir, strings.ToLower(mod.Name)+".py"), []byte(sb.String()), 0644)
}

// emitInterface writes generated/interfaces/i_{module}_service.py as an ABC.
func (e *PythonEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	moduleLower := strings.ToLower(mod.Name)
	usedTypes := collectUsedTypes(a, mod)

	// Check if any action uses List[] output
	needsList := false
	for _, act := range mod.Actions {
		if act.OutputArray {
			needsList = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("from abc import ABC, abstractmethod\n")
	if needsList {
		sb.WriteString("from typing import List\n")
	}
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from ..types.%s import %s\n", moduleLower, strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("\nclass I%sService(ABC):\n", mod.Name))
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n\n", mod.Description))
	} else {
		sb.WriteString(fmt.Sprintf("\nclass I%sService(ABC):\n", mod.Name))
	}

	for _, act := range mod.Actions {
		outputType := formatPyOutputType(act)
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("    @abstractmethod\n    def %s(self", toSnakeCase(act.Name)))
		} else {
			sb.WriteString(fmt.Sprintf("    @abstractmethod\n    def %s(self", toSnakeCase(act.Name)))
		}
		if act.Input != "" && act.Query != "" {
			sb.WriteString(fmt.Sprintf(", input: %s, query: %s", act.Input, act.Query))
		} else if act.Input != "" {
			sb.WriteString(fmt.Sprintf(", input: %s", act.Input))
		} else if act.Query != "" {
			sb.WriteString(fmt.Sprintf(", query: %s", act.Query))
		} else {
			sb.WriteString(", user_id: str")
		}
		sb.WriteString(fmt.Sprintf(") -> %s:\n", outputType))
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("        \"\"\"%s\"\"\"\n", act.Description))
		}
		sb.WriteString("        ...\n\n")
	}

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("i_%s_service.py", moduleLower)), []byte(sb.String()), 0644)
}

// emitRoutes writes generated/routes/{module}_routes.py.
func (e *PythonEmitter) emitRoutes(_ ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	moduleLower := strings.ToLower(mod.Name)

	// Collect all unique middleware names used in this module.
	allMiddleware := collectModuleMiddleware(mod)
	hasMiddleware := len(allMiddleware) > 0

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from flask import request, jsonify\n")
	if hasMiddleware {
		sb.WriteString("from typing import Callable, Dict\n")
	}
	sb.WriteString(fmt.Sprintf("from ..interfaces.i_%s_service import I%sService\n\n", moduleLower, mod.Name))

	if hasMiddleware {
		sb.WriteString(fmt.Sprintf("def register_%s_routes(app, service: I%sService, middleware: Dict[str, Callable]) -> None:\n", moduleLower, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("def register_%s_routes(app, service: I%sService) -> None:\n", moduleLower, mod.Name))
	}
	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", mod.Description))
	}

	for _, act := range mod.Actions {
		fnName := fmt.Sprintf("%s_%s", moduleLower, toSnakeCase(act.Name))
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("\n    # %s\n", act.Description))
		}
		sb.WriteString(fmt.Sprintf("\n    def %s():\n", fnName))
		if act.Input != "" && act.Query != "" {
			sb.WriteString(fmt.Sprintf("        result = service.%s(request.get_json(), request.args.to_dict())\n", toSnakeCase(act.Name)))
		} else if act.Input != "" {
			sb.WriteString(fmt.Sprintf("        result = service.%s(request.get_json())\n", toSnakeCase(act.Name)))
		} else if act.Query != "" {
			sb.WriteString(fmt.Sprintf("        result = service.%s(request.args.to_dict())\n", toSnakeCase(act.Name)))
		} else {
			sb.WriteString(fmt.Sprintf("        result = service.%s(None)\n", toSnakeCase(act.Name)))
		}
		sb.WriteString("        return jsonify(result)\n")

		// Apply middleware as decorators (wrapping the function)
		if len(act.Middleware) > 0 {
			// Apply in reverse order so the first middleware is outermost
			for i := len(act.Middleware) - 1; i >= 0; i-- {
				mw := act.Middleware[i]
				sb.WriteString(fmt.Sprintf("    %s = middleware['%s'](%s)\n", fnName, mw, fnName))
			}
		}

		methods := fmt.Sprintf("['%s']", strings.ToUpper(act.Method))
		sb.WriteString(fmt.Sprintf("    app.add_url_rule('%s', '%s', %s, methods=%s)\n",
			routePath, fnName, fnName, methods))
	}
	sb.WriteString("\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+"_routes.py"), []byte(sb.String()), 0644)
}

// collectModuleMiddleware returns all unique middleware names used in a module.
func collectModuleMiddleware(mod ast.Module) []string {
	seen := make(map[string]bool)
	var result []string
	for _, act := range mod.Actions {
		for _, mw := range act.Middleware {
			if !seen[mw] {
				seen[mw] = true
				result = append(result, mw)
			}
		}
	}
	return result
}

// ── helpers ───────────────────────────────────────────────────────────────────

func collectTransitiveModels(a ast.AST, mod ast.Module) map[string]bool {
	byName := make(map[string]ast.Model, len(a.Models))
	for _, m := range a.Models {
		byName[m.Name] = m
	}
	used := make(map[string]bool)
	queue := []string{}
	for _, act := range mod.Actions {
		if act.Input != "" {
			queue = append(queue, act.Input)
		}
		if act.Output != "" {
			queue = append(queue, act.Output)
		}
		if act.Query != "" {
			queue = append(queue, act.Query)
		}
	}
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if used[name] {
			continue
		}
		used[name] = true
		if m, ok := byName[name]; ok {
			for _, f := range m.Fields {
				base := f.Type
				if _, isModel := byName[base]; isModel && !used[base] {
					queue = append(queue, base)
				}
			}
		}
	}
	return used
}

func collectUsedEnums(a ast.AST, mod ast.Module) map[string]bool {
	enumNames := make(map[string]bool)
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	usedModels := collectTransitiveModels(a, mod)
	usedEnums := make(map[string]bool)

	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		for _, f := range m.Fields {
			if enumNames[f.Type] {
				usedEnums[f.Type] = true
			}
		}
	}
	return usedEnums
}

func collectUsedTypes(a ast.AST, mod ast.Module) []string {
	seen := make(map[string]bool)
	var result []string

	enumNames := make(map[string]bool)
	for _, en := range a.Enums {
		enumNames[en.Name] = true
	}

	// Direct action references
	for _, act := range mod.Actions {
		for _, name := range []string{act.Input, act.Output, act.Query} {
			if name != "" && !seen[name] && !isPrimitive(name) {
				seen[name] = true
				result = append(result, name)
			}
		}
	}

	// Transitive references
	usedModels := collectTransitiveModels(a, mod)
	byName := make(map[string]ast.Model, len(a.Models))
	for _, m := range a.Models {
		byName[m.Name] = m
	}
	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		if !seen[m.Name] {
			seen[m.Name] = true
			result = append(result, m.Name)
		}
		for _, f := range m.Fields {
			base := f.Type
			if _, isModel := byName[base]; isModel && !seen[base] {
				seen[base] = true
				result = append(result, base)
			}
			if enumNames[base] && !seen[base] {
				seen[base] = true
				result = append(result, base)
			}
		}
	}

	// Enums
	usedEnums := collectUsedEnums(a, mod)
	for _, en := range a.Enums {
		if usedEnums[en.Name] && !seen[en.Name] {
			seen[en.Name] = true
			result = append(result, en.Name)
		}
	}

	return result
}

func isPrimitive(t string) bool {
	switch t {
	case "string", "int", "float", "bool", "date", "datetime", "uuid":
		return true
	}
	return false
}

// formatPyOutputType returns the Python type for an action output.
func formatPyOutputType(act ast.Action) string {
	base := veldScalarToPy(act.Output)
	if act.OutputArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

func veldScalarToPy(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "str"
	default:
		return t // model/enum reference
	}
}

// veldTypeToPy maps a Veld type to its Python equivalent.
func veldTypeToPy(t string, isArray bool) string {
	base := veldScalarToPy(t)
	if isArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

// toSnakeCase converts a camelCase or PascalCase name to snake_case.
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32) // to lower
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
