package dart

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

func (e *DartEmitter) emitConstants(a ast.AST, outDir string) error {
	if len(a.Constants) == 0 {
		return nil
	}
	dir := filepath.Join(outDir, "client")
	// dir already exists from Emit

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

	for _, cg := range a.Constants {
		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("/// %s\n", cg.Description))
		}
		sb.WriteString(fmt.Sprintf("class %s {\n", cg.Name))
		sb.WriteString(fmt.Sprintf("  %s._();\n\n", cg.Name))
		for _, f := range cg.Fields {
			dType := dartConstType(f.Type)
			dVal := dartConstValue(f)
			sb.WriteString(fmt.Sprintf("  static const %s %s = %s;\n", dType, f.Name, dVal))
		}
		sb.WriteString("}\n\n")
	}
	return os.WriteFile(filepath.Join(dir, "constants.dart"), []byte(sb.String()), 0644)
}

func dartConstType(veldType string) string {
	switch veldType {
	case "string", "uuid", "date", "datetime", "decimal":
		return "String"
	case "int":
		return "int"
	case "float":
		return "double"
	case "bool":
		return "bool"
	default:
		return "String"
	}
}

func dartConstValue(f ast.ConstantField) string {
	switch f.Type {
	case "string", "uuid", "date", "datetime", "decimal":
		return fmt.Sprintf("'%s'", f.Value)
	case "int", "float":
		return f.Value
	case "bool":
		return f.Value
	default:
		return fmt.Sprintf("'%s'", f.Value)
	}
}
