package dart_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/frontend/dart"
	_ "github.com/Adhamzineldin/Veld/internal/emitter/frontend/dart"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:        "Login",
						Description: "Log in with credentials",
						Method:      "POST",
						Path:        "/auth/login",
						Input:       "LoginInput",
						Output:      "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
				},
			},
		},
	}
}

func TestDartEmitterEmit(t *testing.T) {
	e := dart.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	path := filepath.Join(outDir, "client", "api_client.dart")
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Errorf("expected file %s to exist", path)
	}
}

func TestDartEmitterDryRun(t *testing.T) {
	e := dart.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestDartEmitterContent(t *testing.T) {
	e := dart.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "client", "api_client.dart"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"dart import", "import 'dart:convert'"},
		{"VeldApiError", "class VeldApiError"},
		{"User class", "class User {"},
		{"enum", "enum Role {"},
		{"VeldApi class", "class VeldApi {"},
		{"route doc comment", "/// POST /api/auth/login"},
		{"login method", "login("},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("api_client.dart missing %s: want %q", c.desc, c.needle)
		}
	}
}

func TestDartEmitterPathParams(t *testing.T) {
	e := dart.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "client", "api_client.dart"))
	content := string(data)

	if !strings.Contains(content, "String id") {
		t.Error("path param should generate String id parameter")
	}
}

func TestDartEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetFrontend("dart"); err != nil {
		t.Errorf("dart frontend not registered: %v", err)
	}
}

func TestDartEmitterRouteDocComments(t *testing.T) {
	e := dart.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "client", "api_client.dart"))
	content := string(data)

	if !strings.Contains(content, "/// POST /api/auth/login") {
		t.Error("missing route doc comment for POST /api/auth/login")
	}
	if !strings.Contains(content, "/// GET /api/auth/me") {
		t.Error("missing route doc comment for GET /api/auth/me")
	}
}
