package dart

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterFrontend("dart", New())
}

// DartEmitter generates the frontend Dart/Flutter SDK (generated/client/api_client.dart).
type DartEmitter struct{}

func (*DartEmitter) IsFrontend() {}

// New returns a DartEmitter.
func New() *DartEmitter { return &DartEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *DartEmitter) Summary(modules []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "client/", Files: "api_client.dart"},
	}
}

func veldTypeToDart(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "double"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "String"
	default:
		return t
	}
}

func dartFieldType(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("Map<String, %s>", veldTypeToDart(f.MapValueType))
	}
	base := veldTypeToDart(f.Type)
	if f.IsArray {
		return fmt.Sprintf("List<%s>", base)
	}
	return base
}

// Emit writes generated/client/api_client.dart into outDir.
func (e *DartEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	dir := filepath.Join(outDir, "client")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Collect all used types
	allTypes := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			allTypes[t] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import 'dart:convert';\nimport 'dart:io';\n\n")

	// VeldApiError class
	sb.WriteString(`class VeldApiError implements Exception {
  final int status;
  final String body;
  VeldApiError(this.status, this.body);

  @override
  String toString() => 'VeldApiError($status): $body';
}

`)

	// Enums
	for _, en := range a.Enums {
		if !allTypes[en.Name] {
			continue
		}
		sb.WriteString(fmt.Sprintf("enum %s {\n", en.Name))
		for _, v := range en.Values {
			sb.WriteString(fmt.Sprintf("  %s,\n", v))
		}
		sb.WriteString("}\n\n")
	}

	// Model classes
	modelMap := make(map[string]ast.Model)
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}
	for _, m := range a.Models {
		if !allTypes[m.Name] {
			continue
		}
		// Collect all fields including inherited
		allFields := collectAllFields(m, modelMap)

		sb.WriteString(fmt.Sprintf("class %s {\n", m.Name))
		for _, f := range allFields {
			ft := dartFieldType(f)
			if f.Optional {
				sb.WriteString(fmt.Sprintf("  %s? %s;\n", ft, f.Name))
			} else {
				sb.WriteString(fmt.Sprintf("  %s %s;\n", ft, f.Name))
			}
		}
		sb.WriteString("\n")

		// Constructor
		sb.WriteString(fmt.Sprintf("  %s({", m.Name))
		for i, f := range allFields {
			if i > 0 {
				sb.WriteString(", ")
			}
			if f.Optional {
				sb.WriteString(fmt.Sprintf("this.%s", f.Name))
			} else {
				sb.WriteString(fmt.Sprintf("required this.%s", f.Name))
			}
		}
		sb.WriteString("});\n\n")

		// fromJson factory
		sb.WriteString(fmt.Sprintf("  factory %s.fromJson(Map<String, dynamic> json) {\n", m.Name))
		sb.WriteString(fmt.Sprintf("    return %s(\n", m.Name))
		for _, f := range allFields {
			sb.WriteString(fmt.Sprintf("      %s: json['%s'],\n", f.Name, f.Name))
		}
		sb.WriteString("    );\n  }\n\n")

		// toJson method
		sb.WriteString("  Map<String, dynamic> toJson() => {\n")
		for _, f := range allFields {
			if f.Optional {
				sb.WriteString(fmt.Sprintf("    if (%s != null) '%s': %s,\n", f.Name, f.Name, f.Name))
			} else {
				sb.WriteString(fmt.Sprintf("    '%s': %s,\n", f.Name, f.Name))
			}
		}
		sb.WriteString("  };\n")
		sb.WriteString("}\n\n")
	}

	// VeldApi class
	if opts.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("class VeldApi {\n  final String baseUrl;\n  final HttpClient _client = HttpClient();\n\n  VeldApi({this.baseUrl = '%s'});\n\n", opts.BaseUrl))
	} else {
		sb.WriteString("class VeldApi {\n  final String baseUrl;\n  final HttpClient _client = HttpClient();\n\n  VeldApi({this.baseUrl = ''});\n\n")
	}

	// Helper methods
	sb.WriteString(`  Future<Map<String, dynamic>> _request(String method, String path, {Map<String, dynamic>? body}) async {
    final request = await _client.openUrl(method, Uri.parse('$baseUrl$path'));
    request.headers.set('Content-Type', 'application/json');
    if (body != null) {
      request.write(jsonEncode(body));
    }
    final response = await request.close();
    final responseBody = await response.transform(utf8.decoder).join();
    if (response.statusCode >= 400) {
      throw VeldApiError(response.statusCode, responseBody);
    }
    if (responseBody.isEmpty) return {};
    return jsonDecode(responseBody);
  }

`)

	// Module methods
	for _, mod := range a.Modules {
		sb.WriteString(fmt.Sprintf("  // — %s\n", mod.Name))
		for _, act := range mod.Actions {
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			method := strings.ToUpper(act.Method)
			pathParams := emitter.ExtractPathParams(routePath)

			// Doc comment
			desc := act.Description
			if desc != "" {
				desc = " — " + desc
			}
			if method == "WS" {
				sb.WriteString(fmt.Sprintf("  /// WS %s%s\n", routePath, desc))
			} else {
				sb.WriteString(fmt.Sprintf("  /// %s %s%s\n", method, routePath, desc))
			}

			// WebSocket action
			if method == "WS" {
				var sigParams []string
				for _, p := range pathParams {
					sigParams = append(sigParams, fmt.Sprintf("String %s", p))
				}
				sig := strings.Join(sigParams, ", ")
				wsPath := dartTemplateLiteral(routePath)
				sb.WriteString(fmt.Sprintf("  Future<WebSocket> %s(%s) async {\n", lcFirst(act.Name), sig))
				sb.WriteString(fmt.Sprintf("    return WebSocket.connect('$baseUrl%s');\n", wsPath))
				sb.WriteString("  }\n\n")
				continue
			}

			// Build return type
			outputType := "void"
			if act.Output != "" {
				base := veldTypeToDart(act.Output)
				if act.OutputArray {
					outputType = fmt.Sprintf("List<%s>", base)
				} else {
					outputType = base
				}
			}

			// Build signature
			var sigParams []string
			for _, p := range pathParams {
				sigParams = append(sigParams, fmt.Sprintf("String %s", p))
			}
			if act.Input != "" {
				sigParams = append(sigParams, fmt.Sprintf("%s input", act.Input))
			}
			if act.Query != "" {
				sigParams = append(sigParams, fmt.Sprintf("{%s? query}", act.Query))
			}
			sig := strings.Join(sigParams, ", ")

			// Build URL
			urlExpr := dartTemplateLiteral(routePath)

			sb.WriteString(fmt.Sprintf("  Future<%s> %s(%s) async {\n", outputType, lcFirst(act.Name), sig))

			if act.Query != "" {
				sb.WriteString(fmt.Sprintf("    var url = '%s';\n", urlExpr))
				sb.WriteString("    if (query != null) {\n")
				sb.WriteString("      final qs = query!.toJson().entries.map((e) => '${e.key}=${e.value}').join('&');\n")
				sb.WriteString("      url = '$url?$qs';\n")
				sb.WriteString("    }\n")
			}

			bodyArg := "null"
			if act.Input != "" {
				bodyArg = "input.toJson()"
			}

			path := urlExpr
			if act.Query != "" {
				path = "url"
			} else {
				path = "'" + urlExpr + "'"
			}

			if act.Output == "" {
				sb.WriteString(fmt.Sprintf("    await _request('%s', %s", method, path))
				if act.Input != "" {
					sb.WriteString(fmt.Sprintf(", body: %s", bodyArg))
				}
				sb.WriteString(");\n")
			} else {
				sb.WriteString(fmt.Sprintf("    final json = await _request('%s', %s", method, path))
				if act.Input != "" {
					sb.WriteString(fmt.Sprintf(", body: %s", bodyArg))
				}
				sb.WriteString(");\n")
				if act.OutputArray {
					sb.WriteString(fmt.Sprintf("    return (json as List).map((e) => %s.fromJson(e)).toList();\n", veldTypeToDart(act.Output)))
				} else if emitter.IsPrimitive(act.Output) {
					sb.WriteString("    return json;\n")
				} else {
					sb.WriteString(fmt.Sprintf("    return %s.fromJson(json);\n", veldTypeToDart(act.Output)))
				}
			}
			sb.WriteString("  }\n\n")
		}
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "api_client.dart"), []byte(sb.String()), 0644)
}

func collectAllFields(m ast.Model, models map[string]ast.Model) []ast.Field {
	if m.Extends == "" {
		return m.Fields
	}
	parent, ok := models[m.Extends]
	if !ok {
		return m.Fields
	}
	parentFields := collectAllFields(parent, models)
	return append(parentFields, m.Fields...)
}

func dartTemplateLiteral(path string) string {
	return emitter.ToTemplateLiteral(path)
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
