package dart

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterFrontend("dart", New())
}

// DartEmitter generates the frontend Dart/Flutter SDK (generated/client/api_client.dart).
type DartEmitter struct{}

func (*DartEmitter) IsFrontend() {}

// New returns a DartEmitter.
func New() *DartEmitter { return &DartEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *DartEmitter) Summary(modules []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "client/", Files: "api_client.dart, pubspec.yaml"},
	}
}

// Emit writes generated/client/api_client.dart into outDir.
func (e *DartEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	dir := filepath.Join(outDir, "client")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Collect all used types across all modules (deduplicated).
	allTypes := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			allTypes[t] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import 'dart:convert';\nimport 'dart:io';\n\n")

	// VeldApiError class
	sb.WriteString(`class VeldApiError implements Exception {
  final int status;
  final String body;
  VeldApiError(this.status, this.body);

  @override
  String toString() => 'VeldApiError($status): $body';
}

`)

	emitEnums(&sb, a, allTypes)
	emitModels(&sb, a, allTypes)
	emitApiClass(&sb, a, opts)

	if err := os.WriteFile(filepath.Join(dir, "api_client.dart"), []byte(sb.String()), 0644); err != nil {
		return err
	}

	// Write client/pubspec.yaml
	pubspec := `name: veld_client
description: Generated Veld API client for Dart/Flutter
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
`
	return os.WriteFile(filepath.Join(dir, "pubspec.yaml"), []byte(pubspec), 0644)
}
