package gobackend

// errors.go — emits internal/errors/api_error.go (base type + convenience constructors
// + helper functions + HTTP error handler) and internal/errors/{module}.go with
// per-action typed error factories. Matches the comprehensive approach used by
// the TypeScript/Node emitter.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// generateAllErrors generates the full internal/errors/ directory in one shot.
func (e *GoEmitter) generateAllErrors(a ast.AST, outDir string) error {
	hasAny := false
	for _, mod := range a.Modules {
		if emitter.HasErrors(mod) {
			hasAny = true
			break
		}
	}
	if !hasAny {
		return nil
	}

	dir := filepath.Join(outDir, "internal", "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	if err := emitGoErrorsBase(dir); err != nil {
		return err
	}
	for _, mod := range a.Modules {
		if err := emitGoModuleErrors(mod, dir); err != nil {
			return fmt.Errorf("errors %s: %w", mod.Name, err)
		}
	}
	return nil
}

// emitGoErrorsBase writes internal/errors/api_error.go with the core ApiError type,
// 7 convenience constructors, helper functions, and an HTTP error handler.
func emitGoErrorsBase(dir string) error {
	var sb strings.Builder

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString("package errors\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"time\"\n")
	sb.WriteString(")\n\n")

	// ── Core ApiError type
	sb.WriteString("// ApiError is a typed API error with a machine-readable code and HTTP status.\n")
	sb.WriteString("// Every Veld-generated error factory returns *ApiError.\n")
	sb.WriteString("type ApiError struct {\n")
	sb.WriteString("\tCode      string `json:\"code\"`\n")
	sb.WriteString("\tMessage   string `json:\"error\"`\n")
	sb.WriteString("\tStatus    int    `json:\"-\"`\n")
	sb.WriteString("\tTimestamp string `json:\"timestamp,omitempty\"`\n")
	sb.WriteString("}\n\n")

	sb.WriteString("func (e *ApiError) Error() string {\n")
	sb.WriteString("\treturn fmt.Sprintf(\"%s: %s\", e.Code, e.Message)\n")
	sb.WriteString("}\n\n")

	// New constructor
	sb.WriteString("// New creates a new ApiError with the given code, status, and message.\n")
	sb.WriteString("func New(code string, status int, message string) *ApiError {\n")
	sb.WriteString("\treturn &ApiError{\n")
	sb.WriteString("\t\tCode:      code,\n")
	sb.WriteString("\t\tMessage:   message,\n")
	sb.WriteString("\t\tStatus:    status,\n")
	sb.WriteString("\t\tTimestamp: time.Now().UTC().Format(time.RFC3339),\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// ── ErrorResponse type
	sb.WriteString("// ErrorResponse is the standard JSON error response shape.\n")
	sb.WriteString("type ErrorResponse struct {\n")
	sb.WriteString("\tError  string `json:\"error\"`\n")
	sb.WriteString("\tCode   string `json:\"code\"`\n")
	sb.WriteString("\tStatus int    `json:\"status\"`\n")
	sb.WriteString("}\n\n")

	// ── Type guard helpers
	sb.WriteString("// ── Type Guards ──────────────────────────────────────────────────────\n\n")

	sb.WriteString("// IsApiError checks if an error is an *ApiError.\n")
	sb.WriteString("func IsApiError(err error) bool {\n")
	sb.WriteString("\t_, ok := err.(*ApiError)\n")
	sb.WriteString("\treturn ok\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// AsApiError attempts to extract an *ApiError from the given error.\n")
	sb.WriteString("// Returns nil if the error is not an *ApiError.\n")
	sb.WriteString("func AsApiError(err error) *ApiError {\n")
	sb.WriteString("\tif ae, ok := err.(*ApiError); ok {\n")
	sb.WriteString("\t\treturn ae\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// IsErrorCode checks if an error is an *ApiError with the given code.\n")
	sb.WriteString("func IsErrorCode(err error, code string) bool {\n")
	sb.WriteString("\tae, ok := err.(*ApiError)\n")
	sb.WriteString("\treturn ok && ae.Code == code\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// IsHttpStatus checks if an error is an *ApiError with the given HTTP status.\n")
	sb.WriteString("func IsHttpStatus(err error, status int) bool {\n")
	sb.WriteString("\tae, ok := err.(*ApiError)\n")
	sb.WriteString("\treturn ok && ae.Status == status\n")
	sb.WriteString("}\n\n")

	// ── toErrorResponse
	sb.WriteString("// ToErrorResponse converts any error into a consistent ErrorResponse.\n")
	sb.WriteString("func ToErrorResponse(err error) ErrorResponse {\n")
	sb.WriteString("\tif ae, ok := err.(*ApiError); ok {\n")
	sb.WriteString("\t\treturn ErrorResponse{Error: ae.Message, Code: ae.Code, Status: ae.Status}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn ErrorResponse{Error: err.Error(), Code: \"INTERNAL_ERROR\", Status: http.StatusInternalServerError}\n")
	sb.WriteString("}\n\n")

	// ── Convenience constructors
	sb.WriteString("// ── Convenience Constructors ─────────────────────────────────────────\n\n")

	type errDef struct {
		name      string
		status    string
		msg       string
		codeConst string
	}
	defs := []errDef{
		{"NewNotFoundError", "http.StatusNotFound", "Not Found", "NOT_FOUND"},
		{"NewBadRequestError", "http.StatusBadRequest", "Bad Request", "BAD_REQUEST"},
		{"NewUnauthorizedError", "http.StatusUnauthorized", "Unauthorized", "UNAUTHORIZED"},
		{"NewForbiddenError", "http.StatusForbidden", "Forbidden", "FORBIDDEN"},
		{"NewConflictError", "http.StatusConflict", "Conflict", "CONFLICT"},
		{"NewValidationError", "http.StatusUnprocessableEntity", "Validation Failed", "VALIDATION_FAILED"},
		{"NewInternalError", "http.StatusInternalServerError", "Internal Server Error", "INTERNAL_SERVER_ERROR"},
	}

	for _, d := range defs {
		sb.WriteString(fmt.Sprintf("// %s creates a %s error. If no message is given, defaults to %q.\n", d.name, d.msg, d.msg))
		sb.WriteString(fmt.Sprintf("func %s(msg ...string) *ApiError {\n", d.name))
		sb.WriteString(fmt.Sprintf("\tm := \"%s\"\n", d.msg))
		sb.WriteString("\tif len(msg) > 0 && msg[0] != \"\" {\n")
		sb.WriteString("\t\tm = msg[0]\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\treturn New(\"%s\", %s, m)\n", d.codeConst, d.status))
		sb.WriteString("}\n\n")
	}

	// ── HTTP error handler
	sb.WriteString("// ── HTTP Error Handler ───────────────────────────────────────────────\n\n")

	sb.WriteString("// HandleError writes a JSON error response to w.\n")
	sb.WriteString("// If the error is an *ApiError, it uses its status and code.\n")
	sb.WriteString("// Otherwise, it responds with 500 Internal Server Error.\n")
	sb.WriteString("//\n")
	sb.WriteString("// Usage in an HTTP handler:\n")
	sb.WriteString("//\n")
	sb.WriteString("//\tif err != nil {\n")
	sb.WriteString("//\t\terrors.HandleError(w, err)\n")
	sb.WriteString("//\t\treturn\n")
	sb.WriteString("//\t}\n")
	sb.WriteString("func HandleError(w http.ResponseWriter, err error) {\n")
	sb.WriteString("\tresp := ToErrorResponse(err)\n")
	sb.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	sb.WriteString("\tw.WriteHeader(resp.Status)\n")
	sb.WriteString("\t_ = json.NewEncoder(w).Encode(map[string]interface{}{\n")
	sb.WriteString("\t\t\"error\": resp.Error,\n")
	sb.WriteString("\t\t\"code\":  resp.Code,\n")
	sb.WriteString("\t})\n")
	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "api_error.go"), []byte(sb.String()), 0644)
}

// emitGoModuleErrors writes internal/errors/{module_lower}.go with per-action
// typed error factories.
func emitGoModuleErrors(mod ast.Module, dir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	moduleLower := strings.ToLower(mod.Name)
	var sb strings.Builder

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString("package errors\n\n")
	sb.WriteString("import \"net/http\"\n\n")

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			funcName := act.Name + errName
			httpConst := httpStatusConst(status)

			sb.WriteString(fmt.Sprintf("// %s creates a %s error for the %s action.\n", funcName, errName, act.Name))
			sb.WriteString(fmt.Sprintf("func %s(msg ...string) *ApiError {\n", funcName))
			sb.WriteString(fmt.Sprintf("\tm := \"%s\"\n", errName))
			sb.WriteString("\tif len(msg) > 0 && msg[0] != \"\" {\n")
			sb.WriteString("\t\tm = msg[0]\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\treturn New(\"%s\", %s, m)\n", code, httpConst))
			sb.WriteString("}\n\n")
		}
	}

	return os.WriteFile(filepath.Join(dir, moduleLower+".go"), []byte(sb.String()), 0644)
}

// generateErrors is kept for backward compat — now a no-op since generateAllErrors handles everything.
func (e *GoEmitter) generateErrors(mod ast.Module, outDir string) error {
	return nil
}

// httpStatusConst returns the net/http constant name for a status code.
func httpStatusConst(status int) string {
	switch status {
	case 400:
		return "http.StatusBadRequest"
	case 401:
		return "http.StatusUnauthorized"
	case 403:
		return "http.StatusForbidden"
	case 404:
		return "http.StatusNotFound"
	case 409:
		return "http.StatusConflict"
	case 410:
		return "http.StatusGone"
	case 422:
		return "http.StatusUnprocessableEntity"
	case 429:
		return "http.StatusTooManyRequests"
	case 501:
		return "http.StatusNotImplemented"
	case 503:
		return "http.StatusServiceUnavailable"
	default:
		return "http.StatusInternalServerError"
	}
}
