package gobackend

// errors.go — emits internal/errors/{module_lower}.go with typed error
// constants and factory functions for the Go backend.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *GoEmitter) generateErrors(mod ast.Module, outDir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	dir := filepath.Join(outDir, "internal", "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	moduleLower := strings.ToLower(mod.Name)
	var sb strings.Builder

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString("package errors\n\n")
	sb.WriteString("import (\n\t\"fmt\"\n\t\"net/http\"\n)\n\n")

	// ApiError type (written once; guarded by build tags via filename).
	// We put it in a shared file instead. Let's emit the shared type
	// only if it doesn't exist yet.
	sharedFile := filepath.Join(dir, "api_error.go")
	if _, err := os.Stat(sharedFile); os.IsNotExist(err) {
		var shared strings.Builder
		shared.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
		shared.WriteString("package errors\n\n")
		shared.WriteString("import \"fmt\"\n\n")
		shared.WriteString("// ApiError is a typed API error with a machine-readable code and HTTP status.\n")
		shared.WriteString("type ApiError struct {\n")
		shared.WriteString("\tCode    string `json:\"code\"`\n")
		shared.WriteString("\tMessage string `json:\"error\"`\n")
		shared.WriteString("\tStatus  int    `json:\"-\"`\n")
		shared.WriteString("}\n\n")
		shared.WriteString("func (e *ApiError) Error() string {\n")
		shared.WriteString("\treturn fmt.Sprintf(\"%s: %s\", e.Code, e.Message)\n")
		shared.WriteString("}\n")
		if err := os.WriteFile(sharedFile, []byte(shared.String()), 0644); err != nil {
			return err
		}
	}

	// Per-module error factories.
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			funcName := act.Name + errName // PascalCase: e.g. ListUsersNotFound
			httpConst := httpStatusConst(status)

			sb.WriteString(fmt.Sprintf("// %s creates a %s error for the %s action.\n", funcName, errName, act.Name))
			sb.WriteString(fmt.Sprintf("func %s(msg ...string) *ApiError {\n", funcName))
			sb.WriteString(fmt.Sprintf("\tm := \"%s\"\n", errName))
			sb.WriteString("\tif len(msg) > 0 && msg[0] != \"\" {\n")
			sb.WriteString("\t\tm = msg[0]\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\treturn &ApiError{Code: \"%s\", Message: m, Status: %s}\n", code, httpConst))
			sb.WriteString("}\n\n")
		}
	}

	// Suppress "imported and not used" for fmt and net/http.
	return os.WriteFile(filepath.Join(dir, moduleLower+".go"), []byte(sb.String()), 0644)
}

// httpStatusConst returns the net/http constant name for a status code.
func httpStatusConst(status int) string {
	switch status {
	case 400:
		return "http.StatusBadRequest"
	case 401:
		return "http.StatusUnauthorized"
	case 403:
		return "http.StatusForbidden"
	case 404:
		return "http.StatusNotFound"
	case 409:
		return "http.StatusConflict"
	case 410:
		return "http.StatusGone"
	case 422:
		return "http.StatusUnprocessableEntity"
	case 429:
		return "http.StatusTooManyRequests"
	case 501:
		return "http.StatusNotImplemented"
	case 503:
		return "http.StatusServiceUnavailable"
	default:
		return "http.StatusInternalServerError"
	}
}
