package gobackend_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	gobackend "github.com/Adhamzineldin/Veld/internal/emitter/backend/go"
)

// minimalAST returns a small but representative AST for testing.
func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "name", Type: "string"},
					{Name: "bio", Type: "string", Optional: true},
					{Name: "tags", Type: "string", IsArray: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

func TestGoEmitterEmit(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := minimalAST()
	opts := emitter.EmitOptions{}

	if err := e.Emit(a, outDir, opts); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	// Verify key files were created.
	expectedFiles := []string{
		filepath.Join(outDir, "go.mod"),
		filepath.Join(outDir, "server.go"),
		filepath.Join(outDir, "main.go"),
		filepath.Join(outDir, "internal", "models", "types.go"),
		filepath.Join(outDir, "internal", "interfaces", "auth.go"),
		filepath.Join(outDir, "internal", "routes", "routes.go"),
		filepath.Join(outDir, "internal", "routes", "auth.go"),
		filepath.Join(outDir, "internal", "middleware", "errors.go"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestGoEmitterDryRun(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := minimalAST()
	opts := emitter.EmitOptions{DryRun: true}

	if err := e.Emit(a, outDir, opts); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	// No files should be written in dry-run mode.
	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestGoEmitterTypesContent(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := minimalAST()
	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "internal", "models", "types.go"))
	if err != nil {
		t.Fatalf("ReadFile types.go: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"package", "package models"},
		{"User struct", "type User struct {"},
		{"optional pointer field", "*string"},
		{"slice field", "[]string"},
		{"Role enum type", "type Role string"},
		{"enum const block", "const ("},
		{"enum admin value", `RoleAdmin Role = "admin"`},
		{"uuid maps to string", "Id string"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("types.go missing %s: expected to find %q", c.desc, c.needle)
		}
	}

	// time import only when needed — no time types in minimalAST, so should be absent.
	if strings.Contains(content, `"time"`) {
		t.Error("types.go should not import 'time' when no date/datetime fields exist")
	}
}

func TestGoEmitterInterfaceContent(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := minimalAST()
	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "internal", "interfaces", "auth.go"))
	if err != nil {
		t.Fatalf("ReadFile auth.go: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"package", "package interfaces"},
		{"context import", `"context"`},
		{"models import", "internal/models"},
		{"interface declaration", "type AuthService interface {"},
		{"Login method", "Login(ctx context.Context, input *models.LoginInput)"},
		{"Me return type", "(*models.User, error)"},
		{"Logout no output", "Logout(ctx context.Context) error"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("interfaces/auth.go missing %s: expected to find %q", c.desc, c.needle)
		}
	}
}

func TestGoEmitterRoutesContent(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := minimalAST()
	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "internal", "routes", "auth.go"))
	if err != nil {
		t.Fatalf("ReadFile routes/auth.go: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"package", "package routes"},
		{"setup function", "func setupAuthRoutes(r chi.Router"},
		{"POST Login route", `r.Post("/auth/login", loginHandler`},
		{"GET Me route", `r.Get("/auth/me", meHandler`},
		{"DELETE Logout route", `r.Delete("/auth/logout", logoutHandler`},
		{"handler signature", "func loginHandler(svc interfaces.AuthService) http.HandlerFunc"},
		{"JSON body decode", "readJSON(r, &req)"},
		{"POST status 201", "http.StatusCreated"},
		{"DELETE no-content", "http.StatusNoContent"},
		{"error handling", "err.Error()"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("routes/auth.go missing %s: expected to find %q", c.desc, c.needle)
		}
	}

	// There should be NO duplicate ":=" for the service call.
	if strings.Count(content, "resp, err :=") > strings.Count(content, "func") {
		t.Error("routes/auth.go has suspicious duplicate service calls")
	}
}

func TestGoEmitterPathParams(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
					{Name: "Delete", Method: "DELETE", Path: "/items/:id"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "internal", "routes", "items.go"))
	content := string(data)

	// Chi uses {id} not :id.
	if strings.Contains(content, `"/items/:id"`) {
		t.Error("routes should use Chi syntax {id}, not Express :id")
	}
	if !strings.Contains(content, `"/items/{id}"`) {
		t.Error("routes should contain Chi-style /items/{id}")
	}
	if !strings.Contains(content, `chi.URLParam(r, "id")`) {
		t.Error("handler should extract path param using chi.URLParam")
	}
}

func TestGoEmitterModulePrefix(t *testing.T) {
	e := gobackend.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "User", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name:   "Users",
				Prefix: "/api/v1",
				Actions: []ast.Action{
					{Name: "List", Method: "GET", Path: "/users", Output: "User"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "internal", "routes", "users.go"))
	content := string(data)

	if !strings.Contains(content, `"/api/v1/users"`) {
		t.Error("module prefix should be applied to route path")
	}
}

func TestGoEmitterSummary(t *testing.T) {
	e := gobackend.New()
	modules := []string{"Auth", "Users"}
	lines := e.Summary(modules)

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}

	// Check that all important directories are mentioned.
	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	for _, want := range []string{"internal/models/", "internal/interfaces/", "internal/routes/", "internal/middleware/", "./"} {
		if !dirs[want] {
			t.Errorf("Summary() missing entry for directory %q", want)
		}
	}
}

func TestGoEmitterRegistered(t *testing.T) {
	_, err := emitter.GetBackend("go")
	if err != nil {
		t.Errorf("go backend not registered: %v", err)
	}
}
