// Package cicd generates CI/CD pipeline configuration files.
package cicd

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("cicd", New())
}

type CICDEmitter struct{}

func New() *CICDEmitter         { return &CICDEmitter{} }
func (*CICDEmitter) IsBackend() {}

func (e *CICDEmitter) Summary(_ []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: ".github/workflows/", Files: "ci.yml"},
	}
}

func (e *CICDEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	dir := filepath.Join(outDir, ".github", "workflows")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	lang := detectLanguage(outDir)
	content := generateWorkflow(lang, a)
	return os.WriteFile(filepath.Join(dir, "ci.yml"), []byte(content), 0644)
}

func detectLanguage(outDir string) string {
	checks := []struct {
		file string
		lang string
	}{
		{"go.mod", "go"},
		{"Cargo.toml", "rust"},
		{"pom.xml", "java"},
		{"VeldGenerated.csproj", "csharp"},
		{"composer.json", "php"},
		{"package.json", "node"},
	}
	for _, c := range checks {
		if _, err := os.Stat(filepath.Join(outDir, c.file)); err == nil {
			return c.lang
		}
	}
	return "node"
}

func generateWorkflow(lang string, a ast.AST) string {
	_ = a // available for future customization based on modules

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("name: CI\n\n")
	sb.WriteString("on:\n")
	sb.WriteString("  push:\n")
	sb.WriteString("    branches: [main, develop]\n")
	sb.WriteString("  pull_request:\n")
	sb.WriteString("    branches: [main]\n\n")
	sb.WriteString("jobs:\n")
	sb.WriteString("  build:\n")

	switch lang {
	case "go":
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-go@v5\n")
		sb.WriteString("        with:\n")
		sb.WriteString("          go-version: '1.22'\n")
		sb.WriteString("      - name: Download dependencies\n")
		sb.WriteString("        run: go mod download\n")
		sb.WriteString("      - name: Build\n")
		sb.WriteString("        run: go build ./...\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: go test ./... -v\n")
		sb.WriteString("      - name: Vet\n")
		sb.WriteString("        run: go vet ./...\n")

	case "rust":
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: dtolnay/rust-toolchain@stable\n")
		sb.WriteString("      - name: Build\n")
		sb.WriteString("        run: cargo build --release\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: cargo test\n")
		sb.WriteString("      - name: Clippy\n")
		sb.WriteString("        run: cargo clippy -- -D warnings\n")

	case "java":
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-java@v4\n")
		sb.WriteString("        with:\n")
		sb.WriteString("          java-version: '17'\n")
		sb.WriteString("          distribution: 'temurin'\n")
		sb.WriteString("      - name: Build\n")
		sb.WriteString("        run: mvn package -DskipTests -B\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: mvn test -B\n")

	case "csharp":
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-dotnet@v4\n")
		sb.WriteString("        with:\n")
		sb.WriteString("          dotnet-version: '8.0.x'\n")
		sb.WriteString("      - name: Restore\n")
		sb.WriteString("        run: dotnet restore\n")
		sb.WriteString("      - name: Build\n")
		sb.WriteString("        run: dotnet build --no-restore\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: dotnet test --no-build\n")

	case "php":
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: shivammathur/setup-php@v2\n")
		sb.WriteString("        with:\n")
		sb.WriteString("          php-version: '8.2'\n")
		sb.WriteString("      - name: Install dependencies\n")
		sb.WriteString("        run: composer install --no-interaction --prefer-dist\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: vendor/bin/phpunit\n")

	case "python":
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-python@v5\n")
		sb.WriteString("        with:\n")
		sb.WriteString("          python-version: '3.12'\n")
		sb.WriteString("      - name: Install dependencies\n")
		sb.WriteString("        run: pip install -r requirements.txt 2>/dev/null || pip install flask pydantic pytest\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: pytest\n")

	default: // node
		sb.WriteString("    runs-on: ubuntu-latest\n")
		sb.WriteString("    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-node@v4\n")
		sb.WriteString("        with:\n")
		sb.WriteString("          node-version: '20'\n")
		sb.WriteString("      - name: Install dependencies\n")
		sb.WriteString("        run: npm ci\n")
		sb.WriteString("      - name: Build\n")
		sb.WriteString("        run: npm run build --if-present\n")
		sb.WriteString("      - name: Test\n")
		sb.WriteString("        run: npm test\n")
		sb.WriteString("      - name: Lint\n")
		sb.WriteString("        run: npm run lint --if-present\n")
	}

	// Docker build step
	sb.WriteString("\n  docker:\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    needs: build\n")
	sb.WriteString("    if: github.ref == 'refs/heads/main'\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("      - uses: docker/setup-buildx-action@v3\n")
	sb.WriteString("      - name: Build Docker image\n")
	sb.WriteString("        run: docker build -t veld-app .\n")

	return sb.String()
}
