// Package angular generates Angular @Injectable services with HttpClient + RxJS.
package angular

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
	"github.com/Adhamzineldin/Veld/internal/emitter/tsshared"
)

func init() {
	emitter.RegisterFrontend("angular", New())
}

type AngularEmitter struct{}

func New() *AngularEmitter          { return &AngularEmitter{} }
func (*AngularEmitter) IsFrontend() {}

func (e *AngularEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine
	lines = append(lines, emitter.SummaryLine{Dir: "models/", Files: "index.ts"})
	svcFiles := make([]string, len(modules))
	for i, m := range modules {
		svcFiles[i] = strings.ToLower(m) + ".service.ts"
	}
	lines = append(lines, emitter.SummaryLine{Dir: "services/", Files: strings.Join(svcFiles, ", ")})
	lines = append(lines, emitter.SummaryLine{Dir: "services/", Files: "index.ts, package.json"})
	return lines
}

func (e *AngularEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	modelsDir := filepath.Join(outDir, "models")
	svcDir := filepath.Join(outDir, "services")
	for _, d := range []string{modelsDir, svcDir} {
		if err := os.MkdirAll(d, 0755); err != nil {
			return err
		}
	}

	// Emit models/index.ts with interfaces
	if err := e.emitModels(a, modelsDir); err != nil {
		return err
	}

	// Emit per-module services
	var barrelExports []string
	for _, mod := range a.Modules {
		if err := e.emitService(a, mod, svcDir, opts); err != nil {
			return fmt.Errorf("service %s: %w", mod.Name, err)
		}
		barrelExports = append(barrelExports, fmt.Sprintf("export { %sService } from './%s.service';", mod.Name, strings.ToLower(mod.Name)))
	}

	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, exp := range barrelExports {
		barrel.WriteString(exp + "\n")
	}
	if err := os.WriteFile(filepath.Join(svcDir, "index.ts"), []byte(barrel.String()), 0644); err != nil {
		return err
	}

	// Write services/package.json with per-module exports
	var pkg strings.Builder
	pkg.WriteString("{\n")
	pkg.WriteString("  \"name\": \"@veld/services\",\n")
	pkg.WriteString("  \"version\": \"0.0.0\",\n")
	pkg.WriteString("  \"private\": true,\n")
	pkg.WriteString("  \"types\": \"./index.ts\",\n")
	pkg.WriteString("  \"exports\": {\n")
	pkg.WriteString("    \".\": \"./index.ts\"")
	for _, mod := range a.Modules {
		modLower := strings.ToLower(mod.Name)
		pkg.WriteString(fmt.Sprintf(",\n    \"./%s.service\": \"./%s.service.ts\"", modLower, modLower))
	}
	pkg.WriteString("\n  }\n}\n")
	if err := os.WriteFile(filepath.Join(svcDir, "package.json"), []byte(pkg.String()), 0644); err != nil {
		return err
	}

	// Constants
	return tsshared.EmitTSConstants(a, outDir)
}

func (e *AngularEmitter) emitModels(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

	for _, en := range a.Enums {
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
		}
		vals := make([]string, len(en.Values))
		for i, v := range en.Values {
			vals[i] = fmt.Sprintf("  %s = '%s'", strings.ToUpper(v), v)
		}
		sb.WriteString(fmt.Sprintf("export enum %s {\n%s\n}\n\n", en.Name, strings.Join(vals, ",\n")))
	}

	for _, m := range a.Models {
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
		}
		ext := ""
		if m.Extends != "" {
			ext = " extends " + m.Extends
		}
		sb.WriteString(fmt.Sprintf("export interface %s%s {\n", m.Name, ext))
		for _, f := range m.Fields {
			tsType := tshelpers.VeldFieldToTS(f)
			opt := ""
			if f.Optional {
				opt = "?"
			}
			sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, tsType))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(sb.String()), 0644)
}

func (e *AngularEmitter) emitService(a ast.AST, mod ast.Module, dir string, opts emitter.EmitOptions) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import { Injectable } from '@angular/core';\n")
	sb.WriteString("import { HttpClient } from '@angular/common/http';\n")
	sb.WriteString("import { Observable } from 'rxjs';\n")

	usedTypes := emitter.CollectUsedTypes(a, mod)
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../models';\n", strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	baseUrlExpr := "''"
	if opts.BaseUrl != "" {
		baseUrlExpr = fmt.Sprintf("'%s'", opts.BaseUrl)
	}

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("/** %s */\n", mod.Description))
	}
	sb.WriteString("@Injectable({ providedIn: 'root' })\n")
	sb.WriteString(fmt.Sprintf("export class %sService {\n", mod.Name))
	sb.WriteString(fmt.Sprintf("  private baseUrl = %s;\n\n", baseUrlExpr))
	sb.WriteString("  constructor(private http: HttpClient) {}\n\n")

	for _, act := range mod.Actions {
		outputType := tshelpers.FormatOutputType(act)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)
		method := strings.ToLower(act.Method)

		var params []string
		for _, p := range pathParams {
			params = append(params, p+": string")
		}
		if act.Input != "" {
			params = append(params, "body: "+act.Input)
		}
		if act.Query != "" {
			params = append(params, "query?: "+act.Query)
		}

		// Build URL
		urlExpr := "`${this.baseUrl}" + emitter.ToTemplateLiteral(routePath) + "`"

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("  /** %s */\n", act.Description))
		}

		sb.WriteString(fmt.Sprintf("  %s(%s): Observable<%s> {\n", emitter.ToCamelCase(act.Name), strings.Join(params, ", "), outputType))

		// Query params
		if act.Query != "" {
			sb.WriteString("    const params = query ? Object.entries(query)\n")
			sb.WriteString("      .filter(([_, v]) => v !== undefined)\n")
			sb.WriteString("      .reduce((acc, [k, v]) => ({ ...acc, [k]: String(v) }), {} as Record<string, string>) : undefined;\n")
		}

		switch method {
		case "get":
			if act.Query != "" {
				sb.WriteString(fmt.Sprintf("    return this.http.get<%s>(%s, { params });\n", outputType, urlExpr))
			} else {
				sb.WriteString(fmt.Sprintf("    return this.http.get<%s>(%s);\n", outputType, urlExpr))
			}
		case "delete":
			sb.WriteString(fmt.Sprintf("    return this.http.delete<%s>(%s);\n", outputType, urlExpr))
		default:
			bodyArg := "body"
			if act.Input == "" {
				bodyArg = "{}"
			}
			sb.WriteString(fmt.Sprintf("    return this.http.%s<%s>(%s, %s);\n", method, outputType, urlExpr, bodyArg))
		}

		sb.WriteString("  }\n\n")
	}

	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, strings.ToLower(mod.Name)+".service.ts"), []byte(sb.String()), 0644)
}
