// Package node implements the Veld service SDK emitter for TypeScript/Node.js.
//
// It generates typed, fetch-based HTTP client classes for consumed services,
// enabling type-safe inter-service communication. Each consumed service gets
// its own directory under generated/sdk/<service>/ with:
//   - client.ts  — the typed client class
//   - types.ts   — only the models/enums used by that service's actions
//   - index.ts   — barrel export
//
// Self-registers under the name "node-ts" (matching the backend emitter name).
package node

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterServiceSdk("node-ts", New())
	emitter.RegisterServiceSdk("node-js", New())
}

// Emitter generates TypeScript service SDK clients.
type Emitter struct{}

func New() *Emitter            { return &Emitter{} }
func (*Emitter) IsServiceSdk() {}

// Summary returns a human-friendly breakdown of generated SDK files.
func (e *Emitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine
	for _, m := range modules {
		name := sdkhelpers.ServiceFileName(m)
		lines = append(lines, emitter.SummaryLine{
			Dir:   fmt.Sprintf("sdk/%s/", name),
			Files: "client.ts, types.ts, index.ts",
		})
	}
	return lines
}

// Emit generates SDK client files for each consumed service.
// The AST passed here is the CONSUMED service's AST, and outDir is the
// CONSUMER service's output directory.
func (e *Emitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	for _, consumed := range opts.ConsumedServices {
		if err := emitServiceSdk(consumed, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", consumed.Name, err)
		}
	}

	// Emit sdk/index.ts barrel that re-exports all consumed service clients.
	if len(opts.ConsumedServices) > 0 {
		if err := emitSdkBarrel(opts.ConsumedServices, outDir); err != nil {
			return fmt.Errorf("sdk barrel: %w", err)
		}
	}

	return nil
}

// emitServiceSdk generates the full SDK directory for one consumed service.
func emitServiceSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	dir := filepath.Join(outDir, "sdk", name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// 1. types.ts — models + enums used by the consumed service
	if err := emitSdkTypes(consumed, dir); err != nil {
		return fmt.Errorf("types: %w", err)
	}

	// 2. client.ts — typed HTTP client class
	if err := emitSdkClient(consumed, dir); err != nil {
		return fmt.Errorf("client: %w", err)
	}

	// 3. index.ts — barrel export
	if err := emitSdkIndex(consumed, dir); err != nil {
		return fmt.Errorf("index: %w", err)
	}

	return nil
}

// emitSdkTypes generates sdk/<name>/types.ts with all models and enums
// referenced by the consumed service's actions.
func emitSdkTypes(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("// Service SDK types for: %s\n\n", consumed.Name))

	a := consumed.AST

	// Collect all models used across all modules.
	usedModels := make(map[string]bool)
	for _, mod := range a.Modules {
		for k, v := range emitter.CollectTransitiveModels(a, mod) {
			if v {
				usedModels[k] = true
			}
		}
	}

	// Collect all enums used.
	usedEnums := make(map[string]bool)
	for _, mod := range a.Modules {
		for k, v := range emitter.CollectUsedEnums(a, mod) {
			if v {
				usedEnums[k] = true
			}
		}
	}

	// Emit enums.
	for _, en := range a.Enums {
		if !usedEnums[en.Name] {
			continue
		}
		sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n",
			en.Name,
			"'"+strings.Join(en.Values, "' | '")+"'",
		))
	}

	// Build model lookup for extends resolution.
	modelMap := make(map[string]ast.Model, len(a.Models))
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}

	// Emit models as interfaces.
	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
		}
		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("export interface %s extends %s {\n", m.Name, m.Extends))
		} else {
			sb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
		}
		for _, f := range m.Fields {
			tsType := tshelpers.VeldFieldToTS(f)
			opt := ""
			if f.Optional {
				opt = "?"
			}
			deprecated := ""
			if f.Deprecated != "" {
				deprecated = fmt.Sprintf(" /** @deprecated %s */", f.Deprecated)
			}
			sb.WriteString(fmt.Sprintf("  %s%s: %s;%s\n", f.Name, opt, tsType, deprecated))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "types.ts"), []byte(sb.String()), 0644)
}

// emitSdkClient generates sdk/<name>/client.ts with the typed HTTP client class.
func emitSdkClient(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)

	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("// Service SDK: %s client for inter-service communication\n\n", consumed.Name))

	// Collect all types used across modules for the import line.
	allTypes := collectAllUsedTypes(a)
	if len(allTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from './types';\n\n", strings.Join(allTypes, ", ")))
	}

	// VeldApiError class.
	sb.WriteString("export class VeldApiError extends Error {\n")
	sb.WriteString("  constructor(public readonly status: number, public readonly body: string) {\n")
	sb.WriteString("    super(`HTTP ${status}: ${body}`);\n")
	sb.WriteString("    this.name = 'VeldApiError';\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	// buildQueryString helper.
	sb.WriteString("function buildQueryString(params?: Record<string, unknown>): string {\n")
	sb.WriteString("  if (!params) return '';\n")
	sb.WriteString("  const parts: string[] = [];\n")
	sb.WriteString("  for (const [k, v] of Object.entries(params)) {\n")
	sb.WriteString("    if (v !== undefined && v !== null) parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);\n")
	sb.WriteString("  }\n")
	sb.WriteString("  return parts.length ? '?' + parts.join('&') : '';\n")
	sb.WriteString("}\n\n")

	// Client class.
	sb.WriteString(fmt.Sprintf("export class %s {\n", className))
	sb.WriteString("  private readonly base: string;\n")
	sb.WriteString("  private readonly hdrs: Record<string, string>;\n\n")

	// Constructor with env var fallback.
	sb.WriteString("  constructor(baseUrl?: string, headers?: Record<string, string>) {\n")
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("    this.base = baseUrl ?? process.env.%s ?? %q;\n", envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("    const resolved = baseUrl ?? process.env.%s;\n", envVar))
		sb.WriteString(fmt.Sprintf("    if (!resolved) throw new Error('No base URL for %s — pass baseUrl or set %s');\n", consumed.Name, envVar))
		sb.WriteString("    this.base = resolved;\n")
	}
	sb.WriteString("    this.hdrs = headers ?? {};\n")
	sb.WriteString("  }\n\n")

	// Private request method.
	sb.WriteString("  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {\n")
	sb.WriteString("    const res = await fetch(this.base + path, {\n")
	sb.WriteString("      method,\n")
	sb.WriteString("      headers: { 'Content-Type': 'application/json', ...this.hdrs },\n")
	sb.WriteString("      body: body !== undefined ? JSON.stringify(body) : undefined,\n")
	sb.WriteString("    });\n")
	sb.WriteString("    if (!res.ok) throw new VeldApiError(res.status, await res.text());\n")
	sb.WriteString("    if (res.status === 204) return undefined as T;\n")
	sb.WriteString("    return res.json() as Promise<T>;\n")
	sb.WriteString("  }\n")

	// Per-module methods.
	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			// Skip WebSocket actions in service SDK.
			if strings.ToUpper(act.Method) == "WS" {
				sb.WriteString(fmt.Sprintf("\n  // WebSocket action %s.%s not supported in service SDK\n", mod.Name, act.Name))
				continue
			}
			sb.WriteString("\n")
			writeActionMethod(&sb, mod, act)
		}
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "client.ts"), []byte(sb.String()), 0644)
}

// writeActionMethod writes a single typed method for an action.
func writeActionMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	outputType := tshelpers.FormatOutputType(act)
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	camelName := emitter.ToCamelCase(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	// JSDoc.
	if act.Deprecated != "" {
		sb.WriteString("  /**\n")
		sb.WriteString(fmt.Sprintf("   * %s %s\n", method, routePath))
		sb.WriteString(fmt.Sprintf("   * @deprecated %s\n", act.Deprecated))
		sb.WriteString("   */\n")
	} else if act.Description != "" {
		sb.WriteString(fmt.Sprintf("  /** %s %s — %s */\n", method, routePath, act.Description))
	} else {
		sb.WriteString(fmt.Sprintf("  /** %s %s */\n", method, routePath))
	}

	// URL expression.
	var urlExpr string
	if len(pathParams) > 0 {
		urlExpr = "`" + emitter.ToTemplateLiteral(routePath) + "`"
	} else {
		urlExpr = "'" + routePath + "'"
	}

	// Signature params.
	var sigParams []string
	for _, p := range pathParams {
		sigParams = append(sigParams, p+": string")
	}
	if act.Input != "" {
		sigParams = append(sigParams, "input: "+act.Input)
	}
	if act.Query != "" {
		sigParams = append(sigParams, "query?: "+act.Query)
	}
	sig := strings.Join(sigParams, ", ")

	queryAppend := ""
	if act.Query != "" {
		queryAppend = " + buildQueryString(query as Record<string, unknown>)"
	}

	sb.WriteString(fmt.Sprintf("  %s(%s): Promise<%s> {\n", camelName, sig, outputType))
	if method == "GET" {
		sb.WriteString(fmt.Sprintf("    return this.request('GET', %s%s);\n", urlExpr, queryAppend))
	} else {
		bodyArg := "input"
		if act.Input == "" {
			bodyArg = "{}"
		}
		sb.WriteString(fmt.Sprintf("    return this.request('%s', %s%s, %s);\n", method, urlExpr, queryAppend, bodyArg))
	}
	sb.WriteString("  }\n")
}

// emitSdkIndex generates sdk/<name>/index.ts barrel.
func emitSdkIndex(consumed emitter.ConsumedServiceInfo, dir string) error {
	className := sdkhelpers.ServiceClassName(consumed.Name)
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("export { %s, VeldApiError } from './client';\n", className))
	sb.WriteString("export * from './types';\n")
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(sb.String()), 0644)
}

// emitSdkBarrel generates sdk/index.ts that re-exports all consumed services.
func emitSdkBarrel(consumed []emitter.ConsumedServiceInfo, outDir string) error {
	dir := filepath.Join(outDir, "sdk")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("// Service SDK barrel — re-exports all consumed service clients\n\n")
	for _, c := range consumed {
		name := sdkhelpers.ServiceFileName(c.Name)
		className := sdkhelpers.ServiceClassName(c.Name)
		sb.WriteString(fmt.Sprintf("export { %s } from './%s';\n", className, name))
	}
	sb.WriteString("\n// Re-export VeldApiError from the first service (identical across all)\n")
	if len(consumed) > 0 {
		first := sdkhelpers.ServiceFileName(consumed[0].Name)
		sb.WriteString(fmt.Sprintf("export { VeldApiError } from './%s';\n", first))
	}
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(sb.String()), 0644)
}

// collectAllUsedTypes returns all model/enum names used across all modules.
func collectAllUsedTypes(a ast.AST) []string {
	seen := make(map[string]bool)
	var result []string
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			if !seen[t] {
				seen[t] = true
				result = append(result, t)
			}
		}
	}
	return result
}
