/**
 * Veld SDK usage example — vanilla TypeScript, no framework.
 *
 * Run with: npx tsx frontend/example.ts
 *
 * The `api` client is generated by `veld generate` and lives at
 * ../generated/client/api.ts. It uses native fetch and needs no
 * extra dependencies beyond the generated output itself.
 */

import { api } from '../generated/client/api';

async function main() {
  // ── Users ───────────────────────────────────────────────────────────

  console.log('--- List users ---');
  const users = await api.users.listUsers();
  console.log(users);

  console.log('--- Create user ---');
  const newUser = await api.users.createUser({ name: 'Carol', email: 'carol@example.com' });
  console.log(newUser);

  console.log('--- Get user by ID ---');
  const user = await api.users.getUser(newUser.id);
  console.log(user);

  // ── Todos ────────────────────────────────────────────────────────────

  console.log('--- List todos ---');
  const todos = await api.todos.listTodos();
  console.log(todos);

  console.log('--- Create todo ---');
  const newTodo = await api.todos.createTodo({ title: 'Read the Veld docs', userId: newUser.id });
  console.log(newTodo);

  console.log('--- Update todo ---');
  const updated = await api.todos.updateTodo(newTodo.id, { completed: true });
  console.log(updated);

  console.log('--- Delete todo ---');
  await api.todos.deleteTodo(newTodo.id);
  console.log('Deleted todo', newTodo.id);

  console.log('--- Delete user ---');
  await api.users.deleteUser(newUser.id);
  console.log('Deleted user', newUser.id);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
