package python

// errors.go — emits errors/{module_lower}_errors.py with typed error classes.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *PythonEmitter) emitErrors(mod ast.Module, outDir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// __init__.py
	initFile := filepath.Join(dir, "__init__.py")
	if _, err := os.Stat(initFile); os.IsNotExist(err) {
		if err := os.WriteFile(initFile, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
			return err
		}
	}

	moduleLower := strings.ToLower(mod.Name)
	var sb strings.Builder

	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("class ApiError(Exception):\n")
	sb.WriteString("    \"\"\"Typed API error with code and HTTP status.\"\"\"\n\n")
	sb.WriteString("    def __init__(self, code: str, status: int, message: str | None = None):\n")
	sb.WriteString("        super().__init__(message or code)\n")
	sb.WriteString("        self.code = code\n")
	sb.WriteString("        self.status = status\n\n")
	sb.WriteString("    def to_dict(self) -> dict:\n")
	sb.WriteString("        return {\"error\": str(self), \"code\": self.code}\n\n\n")

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		snakeAction := emitter.ToSnakeCase(act.Name)
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			snakeErr := emitter.ToSnakeCase(errName)
			funcName := snakeAction + "_" + snakeErr
			sb.WriteString(fmt.Sprintf("def %s(message: str | None = None) -> ApiError:\n", funcName))
			sb.WriteString(fmt.Sprintf("    return ApiError(\"%s\", %d, message or \"%s\")\n\n\n", code, status, errName))
		}
	}

	return os.WriteFile(filepath.Join(dir, moduleLower+"_errors.py"), []byte(sb.String()), 0644)
}
