package python

// interfaces.go — emits interfaces/i_{module}_service.py with ABC abstract methods.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
)

func (e *PythonEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	moduleLower := strings.ToLower(mod.Name)
	usedTypes := emitter.CollectUsedTypes(a, mod)

	needsList := false
	for _, act := range mod.Actions {
		if act.OutputArray {
			needsList = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("from abc import ABC, abstractmethod\n")
	if needsList {
		sb.WriteString("from typing import List\n")
	}
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from ..types.%s import %s\n", moduleLower, strings.Join(usedTypes, ", ")))
	}

	sb.WriteString(fmt.Sprintf("\n\nclass I%sService(ABC):\n", mod.Name))
	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n\n", mod.Description))
	}

	for _, act := range mod.Actions {
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		sb.WriteString("    @abstractmethod\n")
		sb.WriteString(fmt.Sprintf("    def %s(self", emitter.ToSnakeCase(act.Name)))
		for _, p := range pathParams {
			sb.WriteString(fmt.Sprintf(", %s: str", emitter.ToSnakeCase(p)))
		}
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf(", input: %s", act.Input))
		}
		if act.Query != "" {
			sb.WriteString(fmt.Sprintf(", query: %s", act.Query))
		}
		sb.WriteString(fmt.Sprintf(") -> %s:\n", formatPyOutputType(act)))
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("        \"\"\"%s\"\"\"\n", act.Description))
		}
		sb.WriteString("        ...\n\n")
	}

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("i_%s_service.py", moduleLower)), []byte(sb.String()), 0644)
}

// formatPyOutputType returns the Python return type annotation for an action.
func formatPyOutputType(act ast.Action) string {
	if act.Output == "" {
		return "None"
	}
	base := veldScalarToPy(act.Output)
	if act.OutputArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}
