package python

// interfaces.go — emits interfaces/i_{module}_service.py with ABC abstract methods.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *PythonEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	moduleLower := strings.ToLower(mod.Name)
	usedTypes := emitter.CollectUsedTypes(a, mod)

	needsList := false
	needsAny := false
	for _, act := range mod.Actions {
		if act.OutputArray {
			needsList = true
		}
		if act.Output == "any" || act.Output == "json" || act.Input == "any" || act.Input == "json" {
			needsAny = true
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("from abc import ABC, abstractmethod\n")
	if needsList && needsAny {
		sb.WriteString("from typing import Any, List\n")
	} else if needsList {
		sb.WriteString("from typing import List\n")
	} else if needsAny {
		sb.WriteString("from typing import Any\n")
	}
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from ..models.%s import %s\n", moduleLower, strings.Join(usedTypes, ", ")))
	}

	sb.WriteString(fmt.Sprintf("\n\nclass I%sService(ABC):\n", mod.Name))
	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n\n", mod.Description))
	}

	for _, act := range mod.Actions {
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		if act.Method == "WS" {
			// WS actions: emit lifecycle method signatures instead of a single service method.
			snakeName := emitter.ToSnakeCase(act.Name)

			// on_connect — required (abstractmethod)
			sb.WriteString("    @abstractmethod\n")
			sb.WriteString(fmt.Sprintf("    def on_%s_connect(self, client_id: str", snakeName))
			for _, p := range pathParams {
				sb.WriteString(fmt.Sprintf(", %s: str", emitter.ToSnakeCase(p)))
			}
			sb.WriteString(") -> None:\n")
			if act.Description != "" {
				sb.WriteString(fmt.Sprintf("        \"\"\"Called when a client connects. %s\"\"\"\n", act.Description))
			}
			sb.WriteString("        ...\n\n")

			// on_message — required only when emit type is set
			if act.Emit != "" {
				sb.WriteString("    @abstractmethod\n")
				sb.WriteString(fmt.Sprintf("    def on_%s_message(self, client_id: str, msg: %s) -> None:\n", snakeName, act.Emit))
				sb.WriteString(fmt.Sprintf("        \"\"\"Called when a client sends a %s message.\"\"\"\n", act.Emit))
				sb.WriteString("        ...\n\n")
			}

			// on_close — optional with default no-op
			sb.WriteString(fmt.Sprintf("    def on_%s_close(self, client_id: str) -> None:\n", snakeName))
			sb.WriteString("        \"\"\"Called when a client disconnects. Override to add cleanup logic.\"\"\"\n")
			sb.WriteString("        pass\n\n")
			continue
		}

		sb.WriteString("    @abstractmethod\n")
		sb.WriteString(fmt.Sprintf("    def %s(self", emitter.ToSnakeCase(act.Name)))
		for _, p := range pathParams {
			sb.WriteString(fmt.Sprintf(", %s: str", emitter.ToSnakeCase(p)))
		}
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf(", input: %s", act.Input))
		}
		if act.Query != "" {
			sb.WriteString(fmt.Sprintf(", query: %s", act.Query))
		}
		outputType := formatPyOutputType(act)
		sb.WriteString(fmt.Sprintf(") -> %s:\n", outputType))
		// Build docstring with description, deprecation notice, and Raises section
		hasDocContent := act.Description != "" || act.Deprecated != "" || len(act.Errors) > 0
		if hasDocContent {
			sb.WriteString("        \"\"\"\n")
			if act.Description != "" {
				sb.WriteString(fmt.Sprintf("        %s\n", act.Description))
			}
			if act.Deprecated != "" {
				sb.WriteString(fmt.Sprintf("\n        .. deprecated::\n            %s\n", act.Deprecated))
			}
			if len(act.Errors) > 0 {
				sb.WriteString("\n        Raises:\n")
				for _, errName := range act.Errors {
					code := emitter.ErrorCode(act.Name, errName)
					sb.WriteString(fmt.Sprintf("            ApiError: %s — %s\n", code, errName))
				}
			}
			sb.WriteString("        \"\"\"\n")
		}
		sb.WriteString("        ...\n\n")
	}

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("i_%s_service.py", moduleLower)), []byte(sb.String()), 0644)
}

// formatPyOutputType returns the Python return type annotation for an action.
func formatPyOutputType(act ast.Action) string {
	if act.Output == "" {
		return "None"
	}
	base := veldScalarToPy(act.Output)
	if act.OutputArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}
