package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	pystrategy "github.com/Adhamzineldin/Veld/internal/emitter/backend/python/strategy"
)

func init() {
	emitter.RegisterBackend("python", New())
}

// PythonEmitter generates a typed Python (Flask + Pydantic) backend from a Veld AST.
type PythonEmitter struct{}

func (*PythonEmitter) IsBackend() {}
func New() *PythonEmitter         { return &PythonEmitter{} }

// Summary returns a human-readable list of files that will be generated.
func (e *PythonEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine

	typeFiles := make([]string, 0, len(modules)+1)
	for _, m := range modules {
		typeFiles = append(typeFiles, strings.ToLower(m)+".py")
	}
	typeFiles = append(typeFiles, "__init__.py")
	lines = append(lines, emitter.SummaryLine{Dir: "models/", Files: strings.Join(typeFiles, ", ")})

	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "i_"+strings.ToLower(m)+"_service.py")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "interfaces/", Files: strings.Join(ifaceFiles, ", ")})
	}

	routeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		routeFiles = append(routeFiles, strings.ToLower(m)+"_routes.py")
	}
	if len(routeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "routes/", Files: strings.Join(routeFiles, ", ")})
	}

	return lines
}

// Emit writes all generated files to outDir.
// The output directory name itself becomes the Python package name.
// For example, if out=veld_gen then:
//
//	from veld_gen.models import User
//	from veld_gen.routes.auth_routes import register_auth_routes
func (e *PythonEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	if err := e.createDirs(outDir); err != nil {
		return err
	}

	strat := pystrategy.New(opts.BackendFramework)

	if err := e.emitPerModuleTypes(a, outDir); err != nil {
		return fmt.Errorf("types: %w", err)
	}
	for _, mod := range a.Modules {
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("interface for %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(mod, outDir, opts, strat); err != nil {
			return fmt.Errorf("routes for %s: %w", mod.Name, err)
		}
		if err := e.emitMiddlewareProtocol(mod, outDir); err != nil {
			return fmt.Errorf("middleware for %s: %w", mod.Name, err)
		}
		if err := e.emitErrors(mod, outDir); err != nil {
			return fmt.Errorf("errors for %s: %w", mod.Name, err)
		}
	}
	if opts.Validate {
		if err := e.emitValidators(a, outDir); err != nil {
			return fmt.Errorf("validators: %w", err)
		}
	}
	return nil
}

// createDirs ensures all output sub-directories and stub __init__.py files exist.
// The output directory itself is the Python package:
//
//	veld_gen/             ← __init__.py (outDir)
//	├── models/           ← per-module type files
//	├── interfaces/       ← ABC service interfaces
//	└── routes/           ← Flask route registrations
func (e *PythonEmitter) createDirs(outDir string) error {
	for _, sub := range []string{"", "models", "interfaces", "middleware", "routes"} {
		dir := filepath.Join(outDir, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		if sub == "models" {
			continue // models/__init__.py is the barrel, written by emitPerModuleTypes
		}
		initFile := filepath.Join(dir, "__init__.py")
		if _, err := os.Stat(initFile); os.IsNotExist(err) {
			if err := os.WriteFile(initFile, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
				return err
			}
		}
	}
	return nil
}
