package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("python", New())
}

// PythonEmitter generates a typed Python (Flask + Pydantic) backend from a Veld AST.
type PythonEmitter struct{}

func (*PythonEmitter) IsBackend() {}
func New() *PythonEmitter         { return &PythonEmitter{} }

// Summary returns a human-readable list of files that will be generated.
func (e *PythonEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine

	typeFiles := make([]string, 0, len(modules)+1)
	for _, m := range modules {
		typeFiles = append(typeFiles, strings.ToLower(m)+".py")
	}
	typeFiles = append(typeFiles, "__init__.py")
	lines = append(lines, emitter.SummaryLine{Dir: "veld_gen/models/", Files: strings.Join(typeFiles, ", ")})

	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "i_"+strings.ToLower(m)+"_service.py")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "veld_gen/interfaces/", Files: strings.Join(ifaceFiles, ", ")})
	}

	routeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		routeFiles = append(routeFiles, strings.ToLower(m)+"_routes.py")
	}
	if len(routeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "veld_gen/routes/", Files: strings.Join(routeFiles, ", ")})
	}

	lines = append(lines, emitter.SummaryLine{Dir: "veld_gen/schemas/", Files: "schemas.py"})
	return lines
}

// Emit writes all generated files to outDir.
func (e *PythonEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	if err := e.createDirs(outDir); err != nil {
		return err
	}
	// All sub-emitters write into outDir/veld_gen/ so imports use veld_gen.* namespace.
	pkg := filepath.Join(outDir, "veld_gen")
	if err := e.emitPerModuleTypes(a, pkg); err != nil {
		return fmt.Errorf("types: %w", err)
	}
	for _, mod := range a.Modules {
		if err := e.emitInterface(a, mod, pkg); err != nil {
			return fmt.Errorf("interface for %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(mod, pkg); err != nil {
			return fmt.Errorf("routes for %s: %w", mod.Name, err)
		}
	}
	if err := e.emitPydanticSchemas(a, pkg); err != nil {
		return fmt.Errorf("pydantic schemas: %w", err)
	}
	return nil
}

// createDirs ensures all output sub-directories and stub __init__.py files exist.
// All generated code lives under veld_gen/ so users import via:
//
//	from veld_gen.models import User
//	from veld_gen.interfaces.i_users_service import IUsersService
func (e *PythonEmitter) createDirs(outDir string) error {
	// Root __init__.py outside veld_gen — just marks outDir as a package.
	rootInit := filepath.Join(outDir, "__init__.py")
	if _, err := os.Stat(rootInit); os.IsNotExist(err) {
		if err := os.WriteFile(rootInit, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
			return err
		}
	}

	pkg := filepath.Join(outDir, "veld_gen")
	for _, sub := range []string{"", "models", "interfaces", "routes", "schemas"} {
		dir := filepath.Join(pkg, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		if sub == "models" {
			continue // models/__init__.py is the barrel, written by emitPerModuleTypes
		}
		initFile := filepath.Join(dir, "__init__.py")
		if _, err := os.Stat(initFile); os.IsNotExist(err) {
			if err := os.WriteFile(initFile, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
				return err
			}
		}
	}
	return nil
}
