package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("python", New())
}

type PythonEmitter struct{}

func (*PythonEmitter) IsBackend() {}
func New() *PythonEmitter         { return &PythonEmitter{} }

func (e *PythonEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine
	typeFiles := make([]string, 0, len(modules)+1)
	for _, m := range modules {
		typeFiles = append(typeFiles, strings.ToLower(m)+".py")
	}
	typeFiles = append(typeFiles, "__init__.py")
	if len(typeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "types/", Files: strings.Join(typeFiles, ", ")})
	}
	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "i_"+strings.ToLower(m)+"_service.py")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "interfaces/", Files: strings.Join(ifaceFiles, ", ")})
	}
	routeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		routeFiles = append(routeFiles, strings.ToLower(m)+"_routes.py")
	}
	if len(routeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "routes/", Files: strings.Join(routeFiles, ", ")})
	}
	lines = append(lines, emitter.SummaryLine{Dir: "schemas/", Files: "schemas.py"})
	return lines
}

func (e *PythonEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	for _, sub := range []string{"", "types", "interfaces", "routes", "schemas"} {
		dir := filepath.Join(outDir, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		init := filepath.Join(dir, "__init__.py")
		if sub != "types" { // types __init__.py is the barrel, written separately
			if _, err := os.Stat(init); os.IsNotExist(err) {
				if err := os.WriteFile(init, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
					return err
				}
			}
		}
	}

	if err := e.emitPerModuleTypes(a, outDir); err != nil {
		return fmt.Errorf("types: %w", err)
	}
	for _, mod := range a.Modules {
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("interface for %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(a, mod, outDir); err != nil {
			return fmt.Errorf("routes for %s: %w", mod.Name, err)
		}
	}
	if err := e.emitPydanticSchemas(a, outDir); err != nil {
		return fmt.Errorf("pydantic schemas: %w", err)
	}
	return nil
}

// ── types/{module}.py — per-module files, each type defined exactly once ──────

func (e *PythonEmitter) emitPerModuleTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "types")
	claimed := make(map[string]string) // typeName → owning module file

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceModule → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		// Determine typing imports needed for owned definitions
		needsList := false
		needsOptional := false
		needsLiteral := len(ownedEnums) > 0
		needsDict := false
		for _, m := range ownedModels {
			for _, f := range m.Fields {
				if f.IsArray {
					needsList = true
				}
				if f.Optional {
					needsOptional = true
				}
				if f.IsMap {
					needsDict = true
				}
			}
		}

		var sb strings.Builder
		sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString("from __future__ import annotations\n")

		if len(ownedModels) > 0 || len(ownedEnums) > 0 {
			typingImports := []string{"TypedDict"}
			if needsList {
				typingImports = append(typingImports, "List")
			}
			if needsOptional {
				typingImports = append(typingImports, "Optional")
			}
			if needsLiteral {
				typingImports = append(typingImports, "Literal")
			}
			if needsDict {
				typingImports = append(typingImports, "Dict")
			}
			sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
		}

		// Re-exports from other module files
		for source, names := range reExports {
			sb.WriteString(fmt.Sprintf("from .%s import %s  # noqa: F401\n", source, strings.Join(names, ", ")))
		}
		sb.WriteString("\n")

		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("\"%s\"", v)
			}
			sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
		}

		for _, m := range ownedModels {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("class %s(%s, total=False):\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("class %s(TypedDict, total=False):\n", m.Name))
			}
			if len(m.Fields) == 0 {
				sb.WriteString("    pass\n")
			}
			for _, f := range m.Fields {
				pyType := veldFieldToPy(f)
				if f.Optional {
					pyType = fmt.Sprintf("Optional[%s]", pyType)
				}
				sb.WriteString(fmt.Sprintf("    %s: %s\n", emitter.ToSnakeCase(f.Name), pyType))
			}
			sb.WriteString("\n")
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".py"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: types/__init__.py re-exports everything from all module files.
	var barrel strings.Builder
	barrel.WriteString("# AUTO-GENERATED BY VELD\n")
	for _, mod := range a.Modules {
		barrel.WriteString(fmt.Sprintf("from .%s import *  # noqa: F401,F403\n", strings.ToLower(mod.Name)))
	}
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(barrel.String()), 0644)
}

// ── interfaces/i_{module}_service.py ─────────────────────────────────────────

func (e *PythonEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	moduleLower := strings.ToLower(mod.Name)
	usedTypes := emitter.CollectUsedTypes(a, mod)

	needsList := false
	for _, act := range mod.Actions {
		if act.OutputArray {
			needsList = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("from abc import ABC, abstractmethod\n")
	if needsList {
		sb.WriteString("from typing import List\n")
	}
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from ..types.%s import %s\n", moduleLower, strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("\nclass I%sService(ABC):\n", mod.Name))
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n\n", mod.Description))
	} else {
		sb.WriteString(fmt.Sprintf("\nclass I%sService(ABC):\n", mod.Name))
	}

	for _, act := range mod.Actions {
		outputType := formatPyOutputType(act)
		sb.WriteString(fmt.Sprintf("    @abstractmethod\n    def %s(self", emitter.ToSnakeCase(act.Name)))

		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		for _, p := range pathParams {
			sb.WriteString(fmt.Sprintf(", %s: str", emitter.ToSnakeCase(p)))
		}
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf(", input: %s", act.Input))
		}
		if act.Query != "" {
			sb.WriteString(fmt.Sprintf(", query: %s", act.Query))
		}
		sb.WriteString(fmt.Sprintf(") -> %s:\n", outputType))
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("        \"\"\"%s\"\"\"\n", act.Description))
		}
		sb.WriteString("        ...\n\n")
	}

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("i_%s_service.py", moduleLower)), []byte(sb.String()), 0644)
}

// ── routes/{module}_routes.py — with try/except, status codes, Pydantic ──────

func (e *PythonEmitter) emitRoutes(_ ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	moduleLower := strings.ToLower(mod.Name)

	allMiddleware := emitter.CollectModuleMiddleware(mod)
	hasMiddleware := len(allMiddleware) > 0

	// Collect schemas to import
	seen := make(map[string]bool)
	var schemaImports []string
	for _, act := range mod.Actions {
		if act.Input != "" && !seen[act.Input] {
			seen[act.Input] = true
			schemaImports = append(schemaImports, act.Input+"Schema")
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from flask import request, jsonify\n")
	if hasMiddleware {
		sb.WriteString("from typing import Callable, Dict\n")
	}
	sb.WriteString(fmt.Sprintf("from ..interfaces.i_%s_service import I%sService\n", moduleLower, mod.Name))
	if len(schemaImports) > 0 {
		sb.WriteString(fmt.Sprintf("from ..schemas.schemas import %s\n", strings.Join(schemaImports, ", ")))
	}
	sb.WriteString("\n")

	if hasMiddleware {
		sb.WriteString(fmt.Sprintf("def register_%s_routes(app, service: I%sService, middleware: Dict[str, Callable]) -> None:\n", moduleLower, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("def register_%s_routes(app, service: I%sService) -> None:\n", moduleLower, mod.Name))
	}
	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", mod.Description))
	}

	for _, act := range mod.Actions {
		fnName := fmt.Sprintf("%s_%s", moduleLower, emitter.ToSnakeCase(act.Name))
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}

		pathParams := emitter.ExtractPathParams(routePath)
		flaskPath := emitter.ToFlaskPath(routePath)

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("\n    # %s\n", act.Description))
		}

		// Function signature with path params
		if len(pathParams) > 0 {
			pyParams := make([]string, len(pathParams))
			for i, p := range pathParams {
				pyParams[i] = emitter.ToSnakeCase(p)
			}
			sb.WriteString(fmt.Sprintf("\n    def %s(%s):\n", fnName, strings.Join(pyParams, ", ")))
		} else {
			sb.WriteString(fmt.Sprintf("\n    def %s():\n", fnName))
		}

		sb.WriteString("        try:\n")

		// Build service call with Pydantic validation
		var callArgs []string
		for _, p := range pathParams {
			callArgs = append(callArgs, emitter.ToSnakeCase(p))
		}
		if act.Input != "" {
			sb.WriteString(fmt.Sprintf("            input = %s(**request.get_json()).model_dump()\n", act.Input+"Schema"))
			callArgs = append(callArgs, "input")
		}
		if act.Query != "" {
			callArgs = append(callArgs, "request.args.to_dict()")
		}

		serviceCallStr := fmt.Sprintf("service.%s(%s)", emitter.ToSnakeCase(act.Name), strings.Join(callArgs, ", "))

		switch {
		case act.Method == "DELETE" && act.Output == "":
			sb.WriteString(fmt.Sprintf("            %s\n", serviceCallStr))
			sb.WriteString("            return '', 204\n")
		case act.Method == "POST":
			sb.WriteString(fmt.Sprintf("            result = %s\n", serviceCallStr))
			sb.WriteString("            return jsonify(result), 201\n")
		default:
			sb.WriteString(fmt.Sprintf("            result = %s\n", serviceCallStr))
			sb.WriteString("            return jsonify(result)\n")
		}

		sb.WriteString("        except Exception as e:\n")
		sb.WriteString("            status = getattr(e, 'status', getattr(e, 'status_code', 500))\n")
		sb.WriteString("            return jsonify({'error': str(e)}), status\n")

		if len(act.Middleware) > 0 {
			for i := len(act.Middleware) - 1; i >= 0; i-- {
				mw := act.Middleware[i]
				sb.WriteString(fmt.Sprintf("    %s = middleware['%s'](%s)\n", fnName, mw, fnName))
			}
		}

		methods := fmt.Sprintf("['%s']", strings.ToUpper(act.Method))
		sb.WriteString(fmt.Sprintf("    app.add_url_rule('%s', '%s', %s, methods=%s)\n",
			flaskPath, fnName, fnName, methods))
	}
	sb.WriteString("\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+"_routes.py"), []byte(sb.String()), 0644)
}

// ── schemas/schemas.py — Pydantic validation ─────────────────────────────────

func (e *PythonEmitter) emitPydanticSchemas(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "schemas")

	needsList := false
	needsOptional := false
	needsLiteral := len(a.Enums) > 0
	needsDict := false

	for _, m := range a.Models {
		for _, f := range m.Fields {
			if f.IsArray {
				needsList = true
			}
			if f.Optional {
				needsOptional = true
			}
			if f.IsMap {
				needsDict = true
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("from pydantic import BaseModel\n")

	typingImports := []string{}
	if needsList {
		typingImports = append(typingImports, "List")
	}
	if needsOptional {
		typingImports = append(typingImports, "Optional")
	}
	if needsLiteral {
		typingImports = append(typingImports, "Literal")
	}
	if needsDict {
		typingImports = append(typingImports, "Dict")
	}
	if len(typingImports) > 0 {
		sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
	}
	sb.WriteString("\n")

	for _, en := range a.Enums {
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("\"%s\"", v)
		}
		sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
	}

	for _, m := range a.Models {
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
		}
		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("class %sSchema(%sSchema):\n", m.Name, m.Extends))
		} else {
			sb.WriteString(fmt.Sprintf("class %sSchema(BaseModel):\n", m.Name))
		}
		if len(m.Fields) == 0 {
			sb.WriteString("    pass\n\n")
			continue
		}
		for _, f := range m.Fields {
			pyType := veldFieldToPy(f)
			fieldName := emitter.ToSnakeCase(f.Name)
			if f.Optional {
				if f.Default != "" {
					sb.WriteString(fmt.Sprintf("    %s: Optional[%s] = %s\n", fieldName, pyType, pyDefault(f)))
				} else {
					sb.WriteString(fmt.Sprintf("    %s: Optional[%s] = None\n", fieldName, pyType))
				}
			} else if f.Default != "" {
				sb.WriteString(fmt.Sprintf("    %s: %s = %s\n", fieldName, pyType, pyDefault(f)))
			} else {
				sb.WriteString(fmt.Sprintf("    %s: %s\n", fieldName, pyType))
			}
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(dir, "schemas.py"), []byte(sb.String()), 0644)
}

// ── helpers ──────────────────────────────────────────────────────────────────

func formatPyOutputType(act ast.Action) string {
	if act.Output == "" {
		return "None"
	}
	base := veldScalarToPy(act.Output)
	if act.OutputArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

func veldScalarToPy(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "str"
	default:
		return t
	}
}

func veldFieldToPy(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("Dict[str, %s]", veldScalarToPy(f.MapValueType))
	}
	base := veldScalarToPy(f.Type)
	if f.IsArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

func pyDefault(f ast.Field) string {
	d := f.Default
	if d == "true" {
		return "True"
	}
	if d == "false" {
		return "False"
	}
	if strings.HasPrefix(d, "\"") {
		return d // already quoted
	}
	// Enum default
	if f.Type != "int" && f.Type != "float" && f.Type != "bool" && f.Type != "string" {
		return fmt.Sprintf("\"%s\"", d)
	}
	return d
}
