package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/veld-dev/veld/internal/ast"
	"github.com/veld-dev/veld/internal/emitter"
)

func init() {
	emitter.RegisterBackend("python", New())
}

// PythonEmitter generates Python TypedDict types, ABC service interfaces,
// and Flask route files from a parsed AST.
type PythonEmitter struct{}

func (*PythonEmitter) IsBackend() {} // marker for BackendEmitter

// New returns a PythonEmitter.
func New() *PythonEmitter { return &PythonEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *PythonEmitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine

	typeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		typeFiles = append(typeFiles, strings.ToLower(m)+".py")
	}
	if len(typeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "types/", Files: strings.Join(typeFiles, ", ")})
	}

	ifaceFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		ifaceFiles = append(ifaceFiles, "i_"+strings.ToLower(m)+"_service.py")
	}
	if len(ifaceFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "interfaces/", Files: strings.Join(ifaceFiles, ", ")})
	}

	routeFiles := make([]string, 0, len(modules))
	for _, m := range modules {
		routeFiles = append(routeFiles, strings.ToLower(m)+"_routes.py")
	}
	if len(routeFiles) > 0 {
		lines = append(lines, emitter.SummaryLine{Dir: "routes/", Files: strings.Join(routeFiles, ", ")})
	}

	return lines
}

// Emit writes all generated files into outDir.
func (e *PythonEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	// Write top-level __init__.py files so generated/ is a proper package.
	for _, sub := range []string{"", "types", "interfaces", "routes"} {
		dir := filepath.Join(outDir, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		init := filepath.Join(dir, "__init__.py")
		if _, err := os.Stat(init); os.IsNotExist(err) {
			if err := os.WriteFile(init, []byte("# AUTO-GENERATED BY VELD\n"), 0644); err != nil {
				return err
			}
		}
	}

	for _, mod := range a.Modules {
		if err := e.emitTypes(a, mod, outDir); err != nil {
			return fmt.Errorf("types for module %s: %w", mod.Name, err)
		}
		if err := e.emitInterface(a, mod, outDir); err != nil {
			return fmt.Errorf("interface for module %s: %w", mod.Name, err)
		}
		if err := e.emitRoutes(a, mod, outDir); err != nil {
			return fmt.Errorf("routes for module %s: %w", mod.Name, err)
		}
	}
	return nil
}

// emitTypes writes generated/types/{module}.py with TypedDict classes and Literal enums.
func (e *PythonEmitter) emitTypes(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "types")

	usedNames := emitter.CollectTransitiveModels(a, mod)
	usedEnums := emitter.CollectUsedEnums(a, mod)

	needsList := false
	needsOptional := false
	needsLiteral := len(usedEnums) > 0

	for _, m := range a.Models {
		if !usedNames[m.Name] {
			continue
		}
		for _, f := range m.Fields {
			if f.IsArray {
				needsList = true
			}
			if f.Optional {
				needsOptional = true
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")

	typingImports := []string{"TypedDict"}
	if needsList {
		typingImports = append(typingImports, "List")
	}
	if needsOptional {
		typingImports = append(typingImports, "Optional")
	}
	if needsLiteral {
		typingImports = append(typingImports, "Literal")
	}
	sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
	sb.WriteString("\n")

	for _, en := range a.Enums {
		if !usedEnums[en.Name] {
			continue
		}
		if en.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", en.Description))
		}
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("\"%s\"", v)
		}
		sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
	}

	for _, m := range a.Models {
		if !usedNames[m.Name] {
			continue
		}
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
		}
		sb.WriteString(fmt.Sprintf("class %s(TypedDict, total=False):\n", m.Name))
		if len(m.Fields) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, f := range m.Fields {
			pyType := veldTypeToPy(f.Type, f.IsArray)
			if f.Optional {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}
			sb.WriteString(fmt.Sprintf("    %s: %s\n", emitter.ToSnakeCase(f.Name), pyType))
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(dir, strings.ToLower(mod.Name)+".py"), []byte(sb.String()), 0644)
}

// emitInterface writes generated/interfaces/i_{module}_service.py as an ABC.
func (e *PythonEmitter) emitInterface(a ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "interfaces")
	moduleLower := strings.ToLower(mod.Name)
	usedTypes := emitter.CollectUsedTypes(a, mod)

	needsList := false
	for _, act := range mod.Actions {
		if act.OutputArray {
			needsList = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from __future__ import annotations\n")
	sb.WriteString("from abc import ABC, abstractmethod\n")
	if needsList {
		sb.WriteString("from typing import List\n")
	}
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from ..types.%s import %s\n", moduleLower, strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("\nclass I%sService(ABC):\n", mod.Name))
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n\n", mod.Description))
	} else {
		sb.WriteString(fmt.Sprintf("\nclass I%sService(ABC):\n", mod.Name))
	}

	for _, act := range mod.Actions {
		outputType := formatPyOutputType(act)
		sb.WriteString(fmt.Sprintf("    @abstractmethod\n    def %s(self", emitter.ToSnakeCase(act.Name)))
		if act.Input != "" && act.Query != "" {
			sb.WriteString(fmt.Sprintf(", input: %s, query: %s", act.Input, act.Query))
		} else if act.Input != "" {
			sb.WriteString(fmt.Sprintf(", input: %s", act.Input))
		} else if act.Query != "" {
			sb.WriteString(fmt.Sprintf(", query: %s", act.Query))
		} else {
			sb.WriteString(", user_id: str")
		}
		sb.WriteString(fmt.Sprintf(") -> %s:\n", outputType))
		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("        \"\"\"%s\"\"\"\n", act.Description))
		}
		sb.WriteString("        ...\n\n")
	}

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("i_%s_service.py", moduleLower)), []byte(sb.String()), 0644)
}

// emitRoutes writes generated/routes/{module}_routes.py.
func (e *PythonEmitter) emitRoutes(_ ast.AST, mod ast.Module, outDir string) error {
	dir := filepath.Join(outDir, "routes")
	moduleLower := strings.ToLower(mod.Name)

	allMiddleware := emitter.CollectModuleMiddleware(mod)
	hasMiddleware := len(allMiddleware) > 0

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from flask import request, jsonify\n")
	if hasMiddleware {
		sb.WriteString("from typing import Callable, Dict\n")
	}
	sb.WriteString(fmt.Sprintf("from ..interfaces.i_%s_service import I%sService\n\n", moduleLower, mod.Name))

	if hasMiddleware {
		sb.WriteString(fmt.Sprintf("def register_%s_routes(app, service: I%sService, middleware: Dict[str, Callable]) -> None:\n", moduleLower, mod.Name))
	} else {
		sb.WriteString(fmt.Sprintf("def register_%s_routes(app, service: I%sService) -> None:\n", moduleLower, mod.Name))
	}
	if mod.Description != "" {
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", mod.Description))
	}

	for _, act := range mod.Actions {
		fnName := fmt.Sprintf("%s_%s", moduleLower, emitter.ToSnakeCase(act.Name))
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}

		if act.Description != "" {
			sb.WriteString(fmt.Sprintf("\n    # %s\n", act.Description))
		}
		sb.WriteString(fmt.Sprintf("\n    def %s():\n", fnName))
		if act.Input != "" && act.Query != "" {
			sb.WriteString(fmt.Sprintf("        result = service.%s(request.get_json(), request.args.to_dict())\n", emitter.ToSnakeCase(act.Name)))
		} else if act.Input != "" {
			sb.WriteString(fmt.Sprintf("        result = service.%s(request.get_json())\n", emitter.ToSnakeCase(act.Name)))
		} else if act.Query != "" {
			sb.WriteString(fmt.Sprintf("        result = service.%s(request.args.to_dict())\n", emitter.ToSnakeCase(act.Name)))
		} else {
			sb.WriteString(fmt.Sprintf("        result = service.%s(None)\n", emitter.ToSnakeCase(act.Name)))
		}
		sb.WriteString("        return jsonify(result)\n")

		if len(act.Middleware) > 0 {
			for i := len(act.Middleware) - 1; i >= 0; i-- {
				mw := act.Middleware[i]
				sb.WriteString(fmt.Sprintf("    %s = middleware['%s'](%s)\n", fnName, mw, fnName))
			}
		}

		methods := fmt.Sprintf("['%s']", strings.ToUpper(act.Method))
		sb.WriteString(fmt.Sprintf("    app.add_url_rule('%s', '%s', %s, methods=%s)\n",
			routePath, fnName, fnName, methods))
	}
	sb.WriteString("\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+"_routes.py"), []byte(sb.String()), 0644)
}

// ── python-specific helpers ───────────────────────────────────────────────────

func formatPyOutputType(act ast.Action) string {
	base := veldScalarToPy(act.Output)
	if act.OutputArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

func veldScalarToPy(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "str"
	default:
		return t
	}
}

func veldTypeToPy(t string, isArray bool) string {
	base := veldScalarToPy(t)
	if isArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}
