package python_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/backend/python"
	_ "github.com/Adhamzineldin/Veld/internal/emitter/backend/python"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
					{Name: "role", Type: "Role"},
					{Name: "tags", Type: "string", IsArray: true},
					{Name: "bio", Type: "string", Optional: true},
				},
			},
		},
		Enums: []ast.Enum{
			{Name: "Role", Values: []string{"admin", "user", "guest"}},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
					{
						Name:   "Logout",
						Method: "DELETE",
						Path:   "/auth/logout",
					},
				},
			},
		},
	}
}

func TestPythonEmitterEmit(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "models", "auth.py"),
		filepath.Join(outDir, "models", "__init__.py"),
		filepath.Join(outDir, "interfaces", "i_auth_service.py"),
		filepath.Join(outDir, "routes", "auth_routes.py"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestPythonEmitterDryRun(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestPythonEmitterTypesContent(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "models", "auth.py"))
	if err != nil {
		t.Fatalf("ReadFile models/auth.py: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"future annotations", "from __future__ import annotations"},
		{"TypedDict import", "from typing import"},
		{"User class", "class User(TypedDict, total=False):"},
		{"optional field", "Optional[str]"},
		{"list field", "List[str]"},
		{"enum type", "Role = Literal"},
		{"snake_case field", "bio: Optional[str]"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("models/auth.py missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPythonEmitterInterfaceContent(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "interfaces", "i_auth_service.py"))
	if err != nil {
		t.Fatalf("ReadFile interfaces/i_auth_service.py: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"abc import", "from abc import ABC, abstractmethod"},
		{"class declaration", "class IAuthService(ABC):"},
		{"abstractmethod decorator", "@abstractmethod"},
		{"login method", "def login(self, input: LoginInput)"},
		{"me method", "def me(self)"},
		{"logout return None", "-> None:"},
		{"login return User", "-> User:"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("interfaces/i_auth_service.py missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPythonEmitterRoutesContent(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "routes", "auth_routes.py"))
	if err != nil {
		t.Fatalf("ReadFile routes/auth_routes.py: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"flask import", "from flask import request, jsonify"},
		{"service import", "from ..interfaces.i_auth_service import IAuthService"},
		{"register function", "def register_auth_routes("},
		{"pydantic validation", "request.get_json()"},
		{"post 201", "return jsonify(result), 201"},
		{"delete 204", "return '', 204"},
		{"try/except", "except Exception as e:"},
		{"url rule", "app.add_url_rule("},
		{"POST method", "methods=['POST']"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("routes/auth_routes.py missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestPythonEmitterPathParams(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "Item", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name: "Items",
				Actions: []ast.Action{
					{Name: "GetById", Method: "GET", Path: "/items/:id", Output: "Item"},
					{Name: "Delete", Method: "DELETE", Path: "/items/:id"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "routes", "items_routes.py"))
	content := string(data)

	// Flask uses <id> syntax in URL rules.
	if !strings.Contains(content, "<id>") {
		t.Error("Flask routes should use <id> path syntax")
	}
	// The handler function should receive id as a parameter.
	if !strings.Contains(content, "def items_get_by_id(id)") {
		t.Errorf("handler function should have id param, got:\n%s", content)
	}
}

func TestPythonEmitterModulePrefix(t *testing.T) {
	e := python.New()
	outDir := t.TempDir()

	a := ast.AST{
		Models: []ast.Model{
			{Name: "User", Fields: []ast.Field{{Name: "id", Type: "string"}}},
		},
		Modules: []ast.Module{
			{
				Name:   "Users",
				Prefix: "/api/v1",
				Actions: []ast.Action{
					{Name: "List", Method: "GET", Path: "/users", Output: "User"},
				},
			},
		},
	}

	if err := e.Emit(a, outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(outDir, "routes", "users_routes.py"))
	if !strings.Contains(string(data), "'/api/v1/users'") {
		t.Error("module prefix should be prepended to the route path")
	}
}

func TestPythonEmitterSummary(t *testing.T) {
	e := python.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}

	dirs := make(map[string]bool)
	for _, l := range lines {
		dirs[l.Dir] = true
	}
	for _, want := range []string{"models/", "interfaces/", "routes/"} {
		if !dirs[want] {
			t.Errorf("Summary() missing entry for directory %q", want)
		}
	}
}

func TestPythonEmitterRegistered(t *testing.T) {
	if _, err := emitter.GetBackend("python"); err != nil {
		t.Errorf("python backend not registered: %v", err)
	}
}
