package python

// sdk.go — service SDK generation for Python backend.
// Generates typed, urllib-based HTTP client classes for consumed services.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
)

// EmitServiceSdk generates Python service SDK clients for each consumed service.
func (e *PythonEmitter) EmitServiceSdk(consumed []emitter.ConsumedServiceInfo, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun || len(consumed) == 0 {
		return nil
	}
	shared := emitter.DetectSharedSdkTypes(consumed)
	if shared.HasShared() {
		if err := emitPySdkShared(shared, outDir); err != nil {
			return fmt.Errorf("service sdk shared: %w", err)
		}
	}
	for _, c := range consumed {
		if err := emitPySdk(c, outDir, shared); err != nil {
			return fmt.Errorf("service sdk %s: %w", c.Name, err)
		}
	}
	return emitPySdkBarrel(consumed, outDir)
}

func emitPySdk(consumed emitter.ConsumedServiceInfo, outDir string, shared emitter.SharedSdkTypes) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	dir := filepath.Join(outDir, "sdk", name)
	modelsDir := filepath.Join(dir, "models")
	if err := os.MkdirAll(modelsDir, 0755); err != nil {
		return err
	}
	if err := emitPySdkModels(consumed, modelsDir, shared); err != nil {
		return err
	}
	if err := emitPySdkClient(consumed, dir); err != nil {
		return err
	}
	if err := emitPySdkConstants(consumed, dir); err != nil {
		return err
	}
	return emitPySdkInit(consumed, dir)
}

// ── models/ ───────────────────────────────────────────────────────────────────

func emitPySdkModels(consumed emitter.ConsumedServiceInfo, modelsDir string, shared emitter.SharedSdkTypes) error {
	a := consumed.AST
	modelGroups, enumGroups, modelOwner, enumOwner := emitter.AssignModelsToModules(a)
	keys := emitter.SortedGroupKeys(modelGroups, enumGroups)
	sharedModels := shared.ModelNames()
	sharedEnums := shared.EnumNames()

	// Determine whether this service uses any shared types (for barrel re-export).
	usesShared := false
	for _, m := range a.Models {
		if sharedModels[m.Name] {
			usesShared = true
			break
		}
	}
	if !usesShared {
		for _, en := range a.Enums {
			if sharedEnums[en.Name] {
				usesShared = true
				break
			}
		}
	}

	var writtenGroups []string
	for _, group := range keys {
		models := modelGroups[group]
		enums := enumGroups[group]

		// Filter out shared types.
		var filteredModels []ast.Model
		for _, m := range models {
			if !sharedModels[m.Name] {
				filteredModels = append(filteredModels, m)
			}
		}
		var filteredEnums []ast.Enum
		for _, en := range enums {
			if !sharedEnums[en.Name] {
				filteredEnums = append(filteredEnums, en)
			}
		}
		if len(filteredModels) == 0 && len(filteredEnums) == 0 {
			continue
		}
		writtenGroups = append(writtenGroups, group)

		var sb strings.Builder
		sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString(fmt.Sprintf("# Service SDK types for: %s (%s)\n", consumed.Name, group))
		sb.WriteString("from __future__ import annotations\n")

		// Compute typing imports needed for this group.
		needsList, needsOptional, needsDict, needsAny := false, false, false, false
		needsLiteral := len(filteredEnums) > 0
		for _, m := range filteredModels {
			for _, f := range m.Fields {
				if f.IsArray {
					needsList = true
				}
				if f.Optional {
					needsOptional = true
				}
				if f.IsMap {
					needsDict = true
				}
				if f.Type == "any" || f.Type == "json" || f.MapValueType == "any" || f.MapValueType == "json" {
					needsAny = true
				}
			}
		}
		typingImports := []string{}
		if needsAny {
			typingImports = append(typingImports, "Any")
		}
		if needsList {
			typingImports = append(typingImports, "List")
		}
		if needsOptional {
			typingImports = append(typingImports, "Optional")
		}
		if needsLiteral {
			typingImports = append(typingImports, "Literal")
		}
		if needsDict {
			typingImports = append(typingImports, "Dict")
		}
		if len(typingImports) > 0 {
			sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
		}

		// Cross-group imports (exclude shared types).
		crossImports := emitter.CrossGroupTypeNames(group, filteredModels, modelOwner, enumOwner)
		for _, fromGroup := range pySortedKeys(crossImports) {
			var nonShared []string
			for _, t := range crossImports[fromGroup] {
				if !sharedModels[t] && !sharedEnums[t] {
					nonShared = append(nonShared, t)
				}
			}
			if len(nonShared) > 0 {
				sb.WriteString(fmt.Sprintf("from .%s import %s\n", fromGroup, strings.Join(nonShared, ", ")))
			}
		}
		sb.WriteString("\n")

		for _, en := range filteredEnums {
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
		}

		for _, m := range filteredModels {
			writePySdkModelBlock(&sb, m)
		}

		if err := os.WriteFile(filepath.Join(modelsDir, group+".py"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel __init__.py
	var barrel strings.Builder
	barrel.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	barrel.WriteString(fmt.Sprintf("# Service SDK types barrel for: %s\n", consumed.Name))
	if usesShared {
		barrel.WriteString("from ...shared import *  # noqa: F401,F403\n")
	}
	for _, group := range writtenGroups {
		barrel.WriteString(fmt.Sprintf("from .%s import *  # noqa: F401,F403\n", group))
	}
	return os.WriteFile(filepath.Join(modelsDir, "__init__.py"), []byte(barrel.String()), 0644)
}

// emitPySdkShared writes sdk/shared/__init__.py and sdk/shared/types.py.
func emitPySdkShared(shared emitter.SharedSdkTypes, outDir string) error {
	dir := filepath.Join(outDir, "sdk", "shared")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("# Shared types used across multiple service SDKs\n")
	sb.WriteString("from __future__ import annotations\n")

	needsList, needsOptional, needsDict, needsAny := false, false, false, false
	needsLiteral := len(shared.Enums) > 0
	for _, m := range shared.Models {
		for _, f := range m.Fields {
			if f.IsArray {
				needsList = true
			}
			if f.Optional {
				needsOptional = true
			}
			if f.IsMap {
				needsDict = true
			}
			if f.Type == "any" || f.Type == "json" || f.MapValueType == "any" || f.MapValueType == "json" {
				needsAny = true
			}
		}
	}
	typingImports := []string{}
	if needsAny {
		typingImports = append(typingImports, "Any")
	}
	if needsList {
		typingImports = append(typingImports, "List")
	}
	if needsOptional {
		typingImports = append(typingImports, "Optional")
	}
	if needsLiteral {
		typingImports = append(typingImports, "Literal")
	}
	if needsDict {
		typingImports = append(typingImports, "Dict")
	}
	if len(typingImports) > 0 {
		sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
	}
	sb.WriteString("\n")

	for _, en := range shared.Enums {
		quoted := make([]string, len(en.Values))
		for i, v := range en.Values {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
	}
	for _, m := range shared.Models {
		writePySdkModelBlock(&sb, m)
	}

	if err := os.WriteFile(filepath.Join(dir, "types.py"), []byte(sb.String()), 0644); err != nil {
		return err
	}
	initContent := "# AUTO-GENERATED BY VELD — DO NOT EDIT\nfrom .types import *  # noqa: F401,F403\n"
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(initContent), 0644)
}

func writePySdkModelBlock(sb *strings.Builder, m ast.Model) {
	if m.Description != "" {
		sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
	}
	if m.Extends != "" {
		sb.WriteString(fmt.Sprintf("class %s(%s):\n", m.Name, m.Extends))
	} else {
		sb.WriteString(fmt.Sprintf("class %s:\n", m.Name))
	}
	initParams := []string{"self"}
	for _, f := range m.Fields {
		pyType := veldFieldToPy(f)
		snakeName := emitter.ToSnakeCase(f.Name)
		if f.Optional {
			initParams = append(initParams, fmt.Sprintf("%s: Optional[%s] = None", snakeName, pyType))
		} else {
			initParams = append(initParams, fmt.Sprintf("%s: %s = %s", snakeName, pyType, pyDefault(f)))
		}
	}
	sb.WriteString(fmt.Sprintf("    def __init__(%s):\n", strings.Join(initParams, ", ")))
	if m.Extends != "" {
		sb.WriteString("        super().__init__()\n")
	}
	if len(m.Fields) == 0 {
		sb.WriteString("        pass\n")
	}
	for _, f := range m.Fields {
		snakeName := emitter.ToSnakeCase(f.Name)
		sb.WriteString(fmt.Sprintf("        self.%s = %s\n", snakeName, snakeName))
	}
	sb.WriteString("\n")
	for _, f := range m.Fields {
		pyType := veldFieldToPy(f)
		snakeName := emitter.ToSnakeCase(f.Name)
		if f.Optional {
			sb.WriteString(fmt.Sprintf("    def get_%s(self) -> Optional[%s]:\n        return self.%s\n\n", snakeName, pyType, snakeName))
			sb.WriteString(fmt.Sprintf("    def set_%s(self, value: Optional[%s]) -> None:\n        self.%s = value\n\n", snakeName, pyType, snakeName))
		} else {
			sb.WriteString(fmt.Sprintf("    def get_%s(self) -> %s:\n        return self.%s\n\n", snakeName, pyType, snakeName))
			sb.WriteString(fmt.Sprintf("    def set_%s(self, value: %s) -> None:\n        self.%s = value\n\n", snakeName, pyType, snakeName))
		}
	}
	sb.WriteString("    def to_dict(self) -> dict:\n")
	sb.WriteString("        return {k: v for k, v in self.__dict__.items() if v is not None}\n\n")
	sb.WriteString(fmt.Sprintf("    @classmethod\n    def from_dict(cls, data: dict) -> '%s':\n", m.Name))
	sb.WriteString(fmt.Sprintf("        return cls(**{k: v for k, v in data.items()})\n\n"))
}

func pySortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ── client.py ─────────────────────────────────────────────────────────────────

func emitPySdkClient(consumed emitter.ConsumedServiceInfo, dir string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)
	className := sdkhelpers.ServiceClassName(consumed.Name)

	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("# Service SDK: %s client for inter-service communication\n", consumed.Name))
	sb.WriteString("from __future__ import annotations\nimport json\nimport os\n")
	sb.WriteString("from typing import Any, Dict, Optional\n")
	sb.WriteString("from urllib.request import Request, urlopen\nfrom urllib.error import HTTPError\nfrom urllib.parse import urlencode\n\n")

	allTypes := pySdkCollectTypes(a)
	if len(allTypes) > 0 {
		sb.WriteString(fmt.Sprintf("from .models import %s\n\n", strings.Join(allTypes, ", ")))
	}

	sb.WriteString("class VeldApiError(Exception):\n    def __init__(self, status: int, body: str):\n")
	sb.WriteString("        super().__init__(f\"HTTP {status}: {body}\")\n        self.status = status\n        self.body = body\n\n\n")

	sb.WriteString(fmt.Sprintf("class %s:\n", className))
	sb.WriteString(fmt.Sprintf("    \"\"\"Typed HTTP client for the %s service.\"\"\"\n\n", consumed.Name))
	sb.WriteString("    def __init__(self, base_url: Optional[str] = None, headers: Optional[Dict[str, str]] = None):\n")
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf("        self._base = base_url or os.environ.get(%q) or %q\n", envVar, consumed.BaseUrl))
	} else {
		sb.WriteString(fmt.Sprintf("        resolved = base_url or os.environ.get(%q)\n", envVar))
		sb.WriteString(fmt.Sprintf("        if not resolved:\n            raise ValueError('No base URL for %s — pass base_url or set %s')\n", consumed.Name, envVar))
		sb.WriteString("        self._base = resolved\n")
	}
	sb.WriteString("        self._headers = headers or {}\n\n")

	sb.WriteString("    def _request(self, method: str, path: str, body: Any = None) -> Any:\n")
	sb.WriteString("        data = json.dumps(body).encode() if body is not None else None\n")
	sb.WriteString("        hdrs = {'Content-Type': 'application/json', **self._headers}\n")
	sb.WriteString("        req = Request(self._base + path, data=data, headers=hdrs, method=method)\n")
	sb.WriteString("        try:\n            with urlopen(req) as res:\n")
	sb.WriteString("                if res.status == 204: return None\n                return json.loads(res.read())\n")
	sb.WriteString("        except HTTPError as e:\n            raise VeldApiError(e.code, e.read().decode()) from e\n\n")

	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				continue
			}
			writePySdkMethod(&sb, mod, act)
		}
	}

	return os.WriteFile(filepath.Join(dir, "client.py"), []byte(sb.String()), 0644)
}

func writePySdkMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	snakeName := emitter.ToSnakeCase(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)
	returnType := "None"
	if act.Output != "" {
		mapped := veldScalarToPy(act.Output)
		if act.OutputArray {
			returnType = fmt.Sprintf("list[%s]", mapped)
		} else {
			returnType = mapped
		}
	}

	var sigParts []string
	sigParts = append(sigParts, "self")
	for _, p := range pathParams {
		sigParts = append(sigParts, fmt.Sprintf("%s: str", emitter.ToSnakeCase(p)))
	}
	if act.Input != "" {
		inputType := veldScalarToPy(act.Input)
		sigParts = append(sigParts, fmt.Sprintf("input_data: %s", inputType))
	}
	if act.Query != "" {
		sigParts = append(sigParts, fmt.Sprintf("query: Optional[%s] = None", act.Query))
	}

	sb.WriteString(fmt.Sprintf("    def %s(%s) -> %s:\n", snakeName, strings.Join(sigParts, ", "), returnType))
	sb.WriteString(fmt.Sprintf("        \"\"\"%s %s\"\"\"\n", method, routePath))

	urlExpr := buildPySdkUrl(routePath, pathParams)
	if act.Query != "" {
		sb.WriteString("        qs = '?' + urlencode({k: v for k, v in (query or {}).items() if v is not None}) if query else ''\n")
		urlExpr = urlExpr + " + qs"
	}
	bodyArg := "None"
	if act.Input != "" {
		bodyArg = "input_data"
	}

	if act.Output == "" {
		sb.WriteString(fmt.Sprintf("        self._request(%q, %s, %s)\n\n", method, urlExpr, bodyArg))
	} else {
		sb.WriteString(fmt.Sprintf("        return self._request(%q, %s, %s)\n\n", method, urlExpr, bodyArg))
	}
}

// emitPySdkConstants writes constants from the consumed service into sdk/<name>/constants/.
func emitPySdkConstants(consumed emitter.ConsumedServiceInfo, dir string) error {
	if len(consumed.AST.Constants) == 0 {
		return nil
	}
	constDir := filepath.Join(dir, "constants")
	if err := os.MkdirAll(constDir, 0755); err != nil {
		return err
	}
	var groups []string
	for _, cg := range consumed.AST.Constants {
		fileName := emitter.ToSnakeCase(cg.Name)
		groups = append(groups, fileName)

		var sb strings.Builder
		sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		sb.WriteString(fmt.Sprintf("# Service SDK constants for: %s\n\n", consumed.Name))
		needsDecimal := false
		for _, f := range cg.Fields {
			if f.Type == "decimal" {
				needsDecimal = true
				break
			}
		}
		if needsDecimal {
			sb.WriteString("from decimal import Decimal\n\n")
		}
		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("# %s\n\n", cg.Description))
		}
		for _, f := range cg.Fields {
			pyType := pyConstType(f.Type)
			pyVal := pyConstValue(f)
			sb.WriteString(fmt.Sprintf("%s: %s = %s\n", f.Name, pyType, pyVal))
		}
		if err := os.WriteFile(filepath.Join(constDir, fileName+".py"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}
	var barrel strings.Builder
	barrel.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, g := range groups {
		barrel.WriteString(fmt.Sprintf("from .%s import *  # noqa: F401,F403\n", g))
	}
	return os.WriteFile(filepath.Join(constDir, "__init__.py"), []byte(barrel.String()), 0644)
}

func emitPySdkInit(consumed emitter.ConsumedServiceInfo, dir string) error {
	className := sdkhelpers.ServiceClassName(consumed.Name)
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("from .client import %s, VeldApiError  # noqa: F401\n", className))
	sb.WriteString("from .models import *  # noqa: F401,F403\n")
	if len(consumed.AST.Constants) > 0 {
		sb.WriteString("from .constants import *  # noqa: F401,F403\n")
	}
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(sb.String()), 0644)
}

func emitPySdkBarrel(consumed []emitter.ConsumedServiceInfo, outDir string) error {
	dir := filepath.Join(outDir, "sdk")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, c := range consumed {
		sb.WriteString(fmt.Sprintf("from .%s import %s  # noqa: F401\n", sdkhelpers.ServiceFileName(c.Name), sdkhelpers.ServiceClassName(c.Name)))
	}
	if len(consumed) > 0 {
		sb.WriteString(fmt.Sprintf("from .%s import VeldApiError  # noqa: F401\n", sdkhelpers.ServiceFileName(consumed[0].Name)))
	}
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(sb.String()), 0644)
}

func buildPySdkUrl(routePath string, pathParams []string) string {
	if len(pathParams) == 0 {
		return fmt.Sprintf("%q", routePath)
	}
	fstr := routePath
	for _, p := range pathParams {
		fstr = strings.ReplaceAll(fstr, ":"+p, "{"+emitter.ToSnakeCase(p)+"}")
	}
	return fmt.Sprintf("f%q", fstr)
}

func pySdkCollectTypes(a ast.AST) []string {
	seen := make(map[string]bool)
	var result []string
	// Collect types referenced by actions first.
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			if !seen[t] {
				seen[t] = true
				result = append(result, t)
			}
		}
	}
	// Always include every declared model and enum so services with no actions
	// (e.g. message-broker-only services) still have their types imported.
	for _, m := range a.Models {
		if !seen[m.Name] {
			seen[m.Name] = true
			result = append(result, m.Name)
		}
	}
	for _, en := range a.Enums {
		if !seen[en.Name] {
			seen[en.Name] = true
			result = append(result, en.Name)
		}
	}
	return result
}

// pyDefault returns the Python default-value literal for a field.
// If the field has an explicit default (via = value or @default), it is used;
// otherwise a type-based zero value is returned.
func pyDefault(f ast.Field) string {
	if f.Default != "" {
		val := f.Default
		// Quoted string → Python single-quote string: "hello" → 'hello'
		if strings.HasPrefix(val, "\"") && strings.HasSuffix(val, "\"") {
			inner := val[1 : len(val)-1]
			return "'" + inner + "'"
		}
		// Booleans → Python capitalised form
		if val == "true" {
			return "True"
		}
		if val == "false" {
			return "False"
		}
		// Numeric — pass through
		if f.Type == "int" || f.Type == "float" || f.Type == "decimal" {
			return val
		}
		// Identifier (enum value) → emit as string
		return "'" + val + "'"
	}
	if f.IsArray {
		return "[]"
	}
	if f.IsMap {
		return "{}"
	}
	switch f.Type {
	case "string", "date", "datetime", "uuid", "decimal":
		return "''"
	case "int":
		return "0"
	case "float":
		return "0.0"
	case "bool":
		return "False"
	default:
		return "None"
	}
}
