package python

// types.go — emits types/{module}.py + types/__init__.py barrel.
//
// Types are "owned" by the first module that references them. Later modules
// re-import shared types from the owning file (with noqa markers).

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *PythonEmitter) emitPerModuleTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "models")

	claimed := make(map[string]string) // typeName → owning module file

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceModule → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		needsList := false
		needsOptional := false
		needsLiteral := len(ownedEnums) > 0
		needsDict := false
		needsAny := false
		needsDecimal := false
		for _, m := range ownedModels {
			for _, f := range m.Fields {
				if f.IsArray {
					needsList = true
				}
				if f.Optional {
					needsOptional = true
				}
				if f.IsMap {
					needsDict = true
				}
				if f.Type == "any" || f.Type == "json" || f.MapValueType == "any" || f.MapValueType == "json" {
					needsAny = true
				}
				if f.Type == "decimal" || f.MapValueType == "decimal" {
					needsDecimal = true
				}
			}
		}

		var sb strings.Builder
		sb.WriteString("# AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
		sb.WriteString("from __future__ import annotations\n")

		if len(ownedModels) > 0 || len(ownedEnums) > 0 {
			typingImports := []string{}
			if needsAny {
				typingImports = append(typingImports, "Any")
			}
			if needsList {
				typingImports = append(typingImports, "List")
			}
			if needsOptional {
				typingImports = append(typingImports, "Optional")
			}
			if needsLiteral {
				typingImports = append(typingImports, "Literal")
			}
			if needsDict {
				typingImports = append(typingImports, "Dict")
			}
			if len(typingImports) > 0 {
				sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
			}
		}
		if needsDecimal {
			sb.WriteString("from decimal import Decimal\n")
		}

		for source, names := range reExports {
			sb.WriteString(fmt.Sprintf("from .%s import %s  # noqa: F401\n", source, strings.Join(names, ", ")))
		}
		sb.WriteString("\n")

		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
		}

		for _, m := range ownedModels {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("class %s(%s):\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("class %s:\n", m.Name))
			}
			// __init__
			initParams := []string{"self"}
			for _, f := range m.Fields {
				pyType := veldFieldToPy(f)
				snakeName := emitter.ToSnakeCase(f.Name)
				if f.Optional {
					initParams = append(initParams, fmt.Sprintf("%s: Optional[%s] = None", snakeName, pyType))
				} else {
					initParams = append(initParams, fmt.Sprintf("%s: %s = %s", snakeName, pyType, pyDefaultVal(f)))
				}
			}
			sb.WriteString(fmt.Sprintf("    def __init__(%s):\n", strings.Join(initParams, ", ")))
			if m.Extends != "" {
				sb.WriteString("        super().__init__()\n")
			}
			if len(m.Fields) == 0 {
				sb.WriteString("        pass\n")
			}
			for _, f := range m.Fields {
				snakeName := emitter.ToSnakeCase(f.Name)
				sb.WriteString(fmt.Sprintf("        self.%s = %s\n", snakeName, snakeName))
			}
			sb.WriteString("\n")
			// Getters and setters
			for _, f := range m.Fields {
				pyType := veldFieldToPy(f)
				snakeName := emitter.ToSnakeCase(f.Name)
				if f.Optional {
					sb.WriteString(fmt.Sprintf("    def get_%s(self) -> Optional[%s]:\n        return self.%s\n\n", snakeName, pyType, snakeName))
					sb.WriteString(fmt.Sprintf("    def set_%s(self, value: Optional[%s]) -> None:\n        self.%s = value\n\n", snakeName, pyType, snakeName))
				} else {
					sb.WriteString(fmt.Sprintf("    def get_%s(self) -> %s:\n        return self.%s\n\n", snakeName, pyType, snakeName))
					sb.WriteString(fmt.Sprintf("    def set_%s(self, value: %s) -> None:\n        self.%s = value\n\n", snakeName, pyType, snakeName))
				}
			}
			// to_dict / from_dict
			sb.WriteString("    def to_dict(self) -> dict:\n")
			sb.WriteString("        return {k: v for k, v in self.__dict__.items() if v is not None}\n\n")
			sb.WriteString(fmt.Sprintf("    @classmethod\n    def from_dict(cls, data: dict) -> '%s':\n", m.Name))
			sb.WriteString("        return cls(**{k: v for k, v in data.items()})\n\n")
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".py"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Emit unclaimed models/enums (e.g. from shared imports or no-module contracts)
	// into models/common.py — mirrors what tsshared does for common.ts.
	var unclaimedEnums []ast.Enum
	var unclaimedModels []ast.Model
	for _, en := range a.Enums {
		if _, taken := claimed[en.Name]; !taken {
			unclaimedEnums = append(unclaimedEnums, en)
		}
	}
	for _, m := range a.Models {
		if _, taken := claimed[m.Name]; !taken {
			unclaimedModels = append(unclaimedModels, m)
		}
	}
	hasCommon := len(unclaimedEnums) > 0 || len(unclaimedModels) > 0
	if hasCommon {
		// Determine typing imports needed.
		needsList := false
		needsOptional := false
		needsLiteral := len(unclaimedEnums) > 0
		needsDict := false
		needsAny := false
		needsDecimal := false
		for _, m := range unclaimedModels {
			for _, f := range m.Fields {
				if f.IsArray {
					needsList = true
				}
				if f.Optional {
					needsOptional = true
				}
				if f.IsMap {
					needsDict = true
				}
				if f.Type == "any" || f.Type == "json" || f.MapValueType == "any" || f.MapValueType == "json" {
					needsAny = true
				}
				if f.Type == "decimal" || f.MapValueType == "decimal" {
					needsDecimal = true
				}
			}
		}

		var csb strings.Builder
		csb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
		csb.WriteString("from __future__ import annotations\n")

		typingImports := []string{}
		if needsAny {
			typingImports = append(typingImports, "Any")
		}
		if needsList {
			typingImports = append(typingImports, "List")
		}
		if needsOptional {
			typingImports = append(typingImports, "Optional")
		}
		if needsLiteral {
			typingImports = append(typingImports, "Literal")
		}
		if needsDict {
			typingImports = append(typingImports, "Dict")
		}
		if len(typingImports) > 0 {
			csb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
		}
		if needsDecimal {
			csb.WriteString("from decimal import Decimal\n")
		}

		// Import types from module-owned files that unclaimed models reference
		// (via extends or field types).
		unclaimedNames := make(map[string]bool)
		for _, en := range unclaimedEnums {
			unclaimedNames[en.Name] = true
		}
		for _, m := range unclaimedModels {
			unclaimedNames[m.Name] = true
		}
		commonImports := make(map[string][]string) // sourceModule → []typeName
		for _, m := range unclaimedModels {
			checkRef := func(typeName string) {
				if typeName == "" || unclaimedNames[typeName] || emitter.IsPrimitive(typeName) {
					return
				}
				if owner, ok := claimed[typeName]; ok {
					commonImports[owner] = appendUniquePy(commonImports[owner], typeName)
				}
			}
			if m.Extends != "" {
				checkRef(m.Extends)
			}
			for _, f := range m.Fields {
				checkRef(f.Type)
				if f.IsMap {
					checkRef(f.MapValueType)
				}
				for _, ut := range f.UnionTypes {
					checkRef(ut)
				}
			}
		}
		sortedSources := make([]string, 0, len(commonImports))
		for source := range commonImports {
			sortedSources = append(sortedSources, source)
		}
		sort.Strings(sortedSources)
		for _, source := range sortedSources {
			names := commonImports[source]
			sort.Strings(names)
			csb.WriteString(fmt.Sprintf("from .%s import %s  # noqa: F401\n", source, strings.Join(names, ", ")))
		}
		csb.WriteString("\n")

		for _, en := range unclaimedEnums {
			if en.Description != "" {
				csb.WriteString(fmt.Sprintf("# %s\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			csb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
		}

		for _, m := range unclaimedModels {
			if m.Description != "" {
				csb.WriteString(fmt.Sprintf("# %s\n", m.Description))
			}
			if m.Extends != "" {
				csb.WriteString(fmt.Sprintf("class %s(%s):\n", m.Name, m.Extends))
			} else {
				csb.WriteString(fmt.Sprintf("class %s:\n", m.Name))
			}
			initParams := []string{"self"}
			for _, f := range m.Fields {
				pyType := veldFieldToPy(f)
				snakeName := emitter.ToSnakeCase(f.Name)
				if f.Optional {
					initParams = append(initParams, fmt.Sprintf("%s: Optional[%s] = None", snakeName, pyType))
				} else {
					initParams = append(initParams, fmt.Sprintf("%s: %s = %s", snakeName, pyType, pyDefaultVal(f)))
				}
			}
			csb.WriteString(fmt.Sprintf("    def __init__(%s):\n", strings.Join(initParams, ", ")))
			if m.Extends != "" {
				csb.WriteString("        super().__init__()\n")
			}
			if len(m.Fields) == 0 {
				csb.WriteString("        pass\n")
			}
			for _, f := range m.Fields {
				snakeName := emitter.ToSnakeCase(f.Name)
				csb.WriteString(fmt.Sprintf("        self.%s = %s\n", snakeName, snakeName))
			}
			csb.WriteString("\n")
			for _, f := range m.Fields {
				pyType := veldFieldToPy(f)
				snakeName := emitter.ToSnakeCase(f.Name)
				if f.Optional {
					csb.WriteString(fmt.Sprintf("    def get_%s(self) -> Optional[%s]:\n        return self.%s\n\n", snakeName, pyType, snakeName))
					csb.WriteString(fmt.Sprintf("    def set_%s(self, value: Optional[%s]) -> None:\n        self.%s = value\n\n", snakeName, pyType, snakeName))
				} else {
					csb.WriteString(fmt.Sprintf("    def get_%s(self) -> %s:\n        return self.%s\n\n", snakeName, pyType, snakeName))
					csb.WriteString(fmt.Sprintf("    def set_%s(self, value: %s) -> None:\n        self.%s = value\n\n", snakeName, pyType, snakeName))
				}
			}
			csb.WriteString("    def to_dict(self) -> dict:\n")
			csb.WriteString("        return {k: v for k, v in self.__dict__.items() if v is not None}\n\n")
			csb.WriteString(fmt.Sprintf("    @classmethod\n    def from_dict(cls, data: dict) -> '%s':\n", m.Name))
			csb.WriteString("        return cls(**{k: v for k, v in data.items()})\n\n")
		}

		if err := os.WriteFile(filepath.Join(dir, "common.py"), []byte(csb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: models/__init__.py re-exports everything from all module files.
	var barrel strings.Builder
	barrel.WriteString("# AUTO-GENERATED BY VELD\n")
	for _, mod := range a.Modules {
		barrel.WriteString(fmt.Sprintf("from .%s import *  # noqa: F401,F403\n", strings.ToLower(mod.Name)))
	}
	if hasCommon {
		barrel.WriteString("from .common import *  # noqa: F401,F403\n")
	}
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(barrel.String()), 0644)
}

// veldScalarToPy maps a Veld scalar type name to its Python type annotation.
func veldScalarToPy(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "decimal":
		return "Decimal"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "str"
	case "any", "json":
		return "Any"
	default:
		return t
	}
}

// veldFieldToPy returns the Python type annotation for a field (without Optional wrapper).
func veldFieldToPy(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("Dict[str, %s]", veldScalarToPy(f.MapValueType))
	}
	base := veldScalarToPy(f.Type)
	if f.IsArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}

// pyDefaultVal returns the Python default-value literal for a field.
// If the field has an explicit default (via = value or @default), it is used;
// otherwise a type-based zero value is returned.
func pyDefaultVal(f ast.Field) string {
	if f.Default != "" {
		val := f.Default
		// Quoted string → Python single-quote string: "hello" → 'hello'
		if strings.HasPrefix(val, "\"") && strings.HasSuffix(val, "\"") {
			inner := val[1 : len(val)-1]
			return "'" + inner + "'"
		}
		// Booleans → Python capitalised form
		if val == "true" {
			return "True"
		}
		if val == "false" {
			return "False"
		}
		// Numeric → pass through
		if _, err := strconv.ParseFloat(val, 64); err == nil {
			return val
		}
		// Identifier (enum value) → emit as string
		return "'" + val + "'"
	}
	if f.IsArray {
		return "[]"
	}
	if f.IsMap {
		return "{}"
	}
	switch f.Type {
	case "string", "date", "datetime", "uuid":
		return "''"
	case "int":
		return "0"
	case "float":
		return "0.0"
	case "decimal":
		return "Decimal('0')"
	case "bool":
		return "False"
	default:
		return "None"
	}
}

// appendUniquePy appends s to slice only if it is not already present.
func appendUniquePy(slice []string, s string) []string {
	for _, v := range slice {
		if v == s {
			return slice
		}
	}
	return append(slice, s)
}
