package python

// types.go — emits types/{module}.py + types/__init__.py barrel.
//
// Types are "owned" by the first module that references them. Later modules
// re-import shared types from the owning file (with noqa markers).

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func (e *PythonEmitter) emitPerModuleTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "models")

	claimed := make(map[string]string) // typeName → owning module file

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceModule → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		needsList := false
		needsOptional := false
		needsLiteral := len(ownedEnums) > 0
		needsDict := false
		needsAny := false
		for _, m := range ownedModels {
			for _, f := range m.Fields {
				if f.IsArray {
					needsList = true
				}
				if f.Optional {
					needsOptional = true
				}
				if f.IsMap {
					needsDict = true
				}
				if f.Type == "any" || f.Type == "json" || f.MapValueType == "any" || f.MapValueType == "json" {
					needsAny = true
				}
			}
		}

		var sb strings.Builder
		sb.WriteString("# AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
		sb.WriteString("from __future__ import annotations\n")

		if len(ownedModels) > 0 || len(ownedEnums) > 0 {
			typingImports := []string{"TypedDict"}
			if needsAny {
				typingImports = append(typingImports, "Any")
			}
			if needsList {
				typingImports = append(typingImports, "List")
			}
			if needsOptional {
				typingImports = append(typingImports, "Optional")
			}
			if needsLiteral {
				typingImports = append(typingImports, "Literal")
			}
			if needsDict {
				typingImports = append(typingImports, "Dict")
			}
			sb.WriteString(fmt.Sprintf("from typing import %s\n", strings.Join(typingImports, ", ")))
		}

		for source, names := range reExports {
			sb.WriteString(fmt.Sprintf("from .%s import %s  # noqa: F401\n", source, strings.Join(names, ", ")))
		}
		sb.WriteString("\n")

		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			sb.WriteString(fmt.Sprintf("%s = Literal[%s]\n\n", en.Name, strings.Join(quoted, ", ")))
		}

		for _, m := range ownedModels {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("class %s(%s, total=False):\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("class %s(TypedDict, total=False):\n", m.Name))
			}
			if len(m.Fields) == 0 {
				sb.WriteString("    pass\n")
			}
			for _, f := range m.Fields {
				pyType := veldFieldToPy(f)
				if f.Optional {
					pyType = fmt.Sprintf("Optional[%s]", pyType)
				}
				sb.WriteString(fmt.Sprintf("    %s: %s\n", emitter.ToSnakeCase(f.Name), pyType))
			}
			sb.WriteString("\n")
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".py"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: models/__init__.py re-exports everything from all module files.
	var barrel strings.Builder
	barrel.WriteString("# AUTO-GENERATED BY VELD\n")
	for _, mod := range a.Modules {
		barrel.WriteString(fmt.Sprintf("from .%s import *  # noqa: F401,F403\n", strings.ToLower(mod.Name)))
	}
	return os.WriteFile(filepath.Join(dir, "__init__.py"), []byte(barrel.String()), 0644)
}

// veldScalarToPy maps a Veld scalar type name to its Python type annotation.
func veldScalarToPy(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string", "date", "datetime", "uuid":
		return "str"
	case "any", "json":
		return "Any"
	default:
		return t
	}
}

// veldFieldToPy returns the Python type annotation for a field (without Optional wrapper).
func veldFieldToPy(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("Dict[str, %s]", veldScalarToPy(f.MapValueType))
	}
	base := veldScalarToPy(f.Type)
	if f.IsArray {
		return fmt.Sprintf("List[%s]", base)
	}
	return base
}
