package schema

import (
	"fmt"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// veldToPrisma maps Veld types to Prisma types.
func veldToPrisma(t string) string {
	switch t {
	case "string":
		return "String"
	case "int":
		return "Int"
	case "float":
		return "Float"
	case "bool":
		return "Boolean"
	case "datetime":
		return "DateTime"
	case "date":
		return "String"
	case "uuid":
		return "String"
	default:
		return "String"
	}
}

// BuildPrisma generates a Prisma schema string from the AST.
func BuildPrisma(a ast.AST) string {
	modelMap := make(map[string]ast.Model)
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	sb.WriteString("datasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\n")
	sb.WriteString("generator client {\n  provider = \"prisma-client-js\"\n}\n\n")

	for _, m := range a.Models {
		allFields := flattenFields(m, modelMap)
		sb.WriteString(fmt.Sprintf("model %s {\n", m.Name))

		for _, f := range allFields {
			prismaType := veldToPrisma(f.Type)

			var attrs []string

			// UUID id field gets special treatment
			if f.Name == "id" && f.Type == "uuid" {
				attrs = append(attrs, "@id @default(uuid())")
			}

			if f.Optional {
				prismaType += "?"
			}

			if f.IsArray {
				prismaType = prismaType + "[]"
			}

			if f.Default != "" && f.Name != "id" {
				attrs = append(attrs, fmt.Sprintf("@default(%s)", prismaDefault(f)))
			}

			if f.Unique {
				attrs = append(attrs, "@unique")
			}

			if f.Relation != "" {
				attrs = append(attrs, fmt.Sprintf("@relation(fields: [%sId], references: [id])", strings.ToLower(f.Relation)))
			}

			line := fmt.Sprintf("  %-15s %s", f.Name, prismaType)
			if len(attrs) > 0 {
				line += " " + strings.Join(attrs, " ")
			}
			sb.WriteString(line + "\n")
		}

		// Add @@index directives for @index annotated fields
		var indexedFields []string
		for _, f := range allFields {
			if f.Index {
				indexedFields = append(indexedFields, f.Name)
			}
		}
		for _, name := range indexedFields {
			sb.WriteString(fmt.Sprintf("\n  @@index([%s])", name))
		}
		if len(indexedFields) > 0 {
			sb.WriteString("\n")
		}

		sb.WriteString("}\n\n")
	}

	return sb.String()
}

func prismaDefault(f ast.Field) string {
	val := f.Default
	if strings.HasPrefix(val, "\"") {
		return val
	}
	if val == "true" || val == "false" {
		return val
	}
	return val
}

func flattenFields(m ast.Model, models map[string]ast.Model) []ast.Field {
	if m.Extends == "" {
		return m.Fields
	}
	parent, ok := models[m.Extends]
	if !ok {
		return m.Fields
	}
	return append(flattenFields(parent, models), m.Fields...)
}
