package schema

import (
	"fmt"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
)

// veldToSQL maps Veld types to SQL DDL types.
func veldToSQL(t string) string {
	switch t {
	case "string":
		return "VARCHAR(255)"
	case "int":
		return "INTEGER"
	case "float":
		return "REAL"
	case "decimal":
		return "DECIMAL(19,4)"
	case "bool":
		return "BOOLEAN"
	case "datetime":
		return "TIMESTAMP"
	case "date":
		return "DATE"
	case "long":
		return "BIGINT"
	case "uuid":
		return "UUID"
	case "bytes":
		return "BYTEA"
	case "time":
		return "TIME"
	case "any", "json":
		return "JSONB"
	default:
		return "VARCHAR(255)"
	}
}

// BuildSQL generates SQL DDL statements from the AST.
func BuildSQL(a ast.AST) string {
	modelMap := make(map[string]ast.Model)
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}

	var sb strings.Builder
	sb.WriteString("-- AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

	for _, m := range a.Models {
		allFields := flattenFields(m, modelMap)
		tableName := toSnakeCase(m.Name) + "s"
		sb.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", tableName))

		for i, f := range allFields {
			sqlType := veldToSQL(f.Type)

			var constraints []string

			if f.Name == "id" && f.Type == "uuid" {
				constraints = append(constraints, "PRIMARY KEY DEFAULT gen_random_uuid()")
			} else if f.Name == "id" {
				constraints = append(constraints, "PRIMARY KEY")
			}

			if !f.Optional && f.Name != "id" {
				constraints = append(constraints, "NOT NULL")
			}

			if f.Default != "" && f.Name != "id" {
				constraints = append(constraints, fmt.Sprintf("DEFAULT %s", sqlDefault(f)))
			}

			if f.Unique {
				constraints = append(constraints, "UNIQUE")
			}

			line := fmt.Sprintf("  %s %s", toSnakeCase(f.Name), sqlType)
			if len(constraints) > 0 {
				line += " " + strings.Join(constraints, " ")
			}

			if i < len(allFields)-1 {
				line += ","
			}
			sb.WriteString(line + "\n")
		}

		sb.WriteString(");\n")

		// Add indexes for @index annotated fields
		for _, f := range allFields {
			if f.Index {
				sb.WriteString(fmt.Sprintf("CREATE INDEX idx_%s_%s ON %s (%s);\n",
					tableName, toSnakeCase(f.Name), tableName, toSnakeCase(f.Name)))
			}
		}

		sb.WriteString("\n")
	}

	return sb.String()
}

func sqlDefault(f ast.Field) string {
	val := f.Default
	if strings.HasPrefix(val, "\"") {
		return "'" + strings.Trim(val, "\"") + "'"
	}
	if val == "true" {
		return "TRUE"
	}
	if val == "false" {
		return "FALSE"
	}
	return val
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
