package tsshared

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// EmitTSConstants writes typed constant files into constants/ for all
// TS-based emitters (TypeScript, React, Vue, Angular, Svelte, types-only).
func EmitTSConstants(a ast.AST, outDir string) error {
	if len(a.Constants) == 0 {
		return nil
	}
	dir := filepath.Join(outDir, "constants")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var barrelExports []string

	for _, cg := range a.Constants {
		fileName := emitter.ToSnakeCase(cg.Name)
		barrelExports = append(barrelExports, fileName)

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", cg.Description))
		}

		for _, f := range cg.Fields {
			tsType := tsConstType(f.Type)
			tsVal := tsConstValue(f)
			sb.WriteString(fmt.Sprintf("export const %s: %s = %s;\n", f.Name, tsType, tsVal))
		}

		if err := os.WriteFile(filepath.Join(dir, fileName+".ts"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel index.ts
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	for _, name := range barrelExports {
		barrel.WriteString(fmt.Sprintf("export * from './%s';\n", name))
	}
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(barrel.String()), 0644)
}

func tsConstType(veldType string) string {
	switch veldType {
	case "string", "uuid", "date", "datetime", "decimal":
		return "string"
	case "int", "float":
		return "number"
	case "bool":
		return "boolean"
	default:
		return "string"
	}
}

func tsConstValue(f ast.ConstantField) string {
	switch f.Type {
	case "string", "uuid", "date", "datetime", "decimal":
		return fmt.Sprintf("%q", f.Value)
	case "int", "float":
		return f.Value
	case "bool":
		return f.Value
	default:
		return fmt.Sprintf("%q", f.Value)
	}
}
