package tsshared

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// EmitTSConstants writes typed constant files into constants/ for all
// TS-based emitters (TypeScript, React, Vue, Angular, Svelte, types-only).
func EmitTSConstants(a ast.AST, outDir string) error {
	if len(a.Constants) == 0 {
		return nil
	}
	dir := filepath.Join(outDir, "constants")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var barrelExports []string

	for _, cg := range a.Constants {
		fileName := emitter.ToSnakeCase(cg.Name)
		barrelExports = append(barrelExports, fileName)

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")

		// Emit branded type aliases needed by this group's constants.
		sb.WriteString(tsConstScalarAliases(cg.Fields))

		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", cg.Description))
		}

		for _, f := range cg.Fields {
			tsType := tsConstType(f.Type)
			tsVal := tsConstValue(f)
			sb.WriteString(fmt.Sprintf("export const %s: %s = %s;\n", f.Name, tsType, tsVal))
		}

		if err := os.WriteFile(filepath.Join(dir, fileName+".ts"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel index.ts
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	for _, name := range barrelExports {
		barrel.WriteString(fmt.Sprintf("export * from './%s';\n", name))
	}
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(barrel.String()), 0644)
}

// tsConstScalarAliases emits branded type aliases needed by the constant fields,
// matching the same branded types used in normal model generation (tshelpers.ScalarAliasBlock).
func tsConstScalarAliases(fields []ast.ConstantField) string {
	needsUUID, needsDecimal, needsDate, needsDateTime := false, false, false, false
	for _, f := range fields {
		switch f.Type {
		case "uuid":
			needsUUID = true
		case "decimal":
			needsDecimal = true
		case "date":
			needsDate = true
		case "datetime":
			needsDateTime = true
		}
	}
	if !needsUUID && !needsDecimal && !needsDate && !needsDateTime {
		return ""
	}
	var sb strings.Builder
	sb.WriteString("// ── Branded scalar types ─────────────────────────────────────────────\n")
	if needsUUID {
		sb.WriteString("/** A UUID string (e.g. \"550e8400-e29b-41d4-a716-446655440000\"). */\n")
		sb.WriteString("type UUID = string & { readonly __brand: 'UUID' };\n")
	}
	if needsDecimal {
		sb.WriteString("/** A decimal value represented as a string for precision (e.g. \"12345.6789\"). */\n")
		sb.WriteString("type Decimal = string & { readonly __brand: 'Decimal' };\n")
	}
	if needsDate {
		sb.WriteString("/** An ISO 8601 date string (e.g. \"2024-01-15\"). */\n")
		sb.WriteString("type ISODate = string & { readonly __brand: 'ISODate' };\n")
	}
	if needsDateTime {
		sb.WriteString("/** An ISO 8601 datetime string (e.g. \"2024-01-15T09:30:00Z\"). */\n")
		sb.WriteString("type ISODateTime = string & { readonly __brand: 'ISODateTime' };\n")
	}
	sb.WriteString("\n")
	return sb.String()
}

// tsConstType maps Veld types to TypeScript types — matching VeldScalarToTS in tshelpers.
func tsConstType(veldType string) string {
	switch veldType {
	case "string":
		return "string"
	case "uuid":
		return "UUID"
	case "decimal":
		return "Decimal"
	case "date":
		return "ISODate"
	case "datetime":
		return "ISODateTime"
	case "int", "float":
		return "number"
	case "bool":
		return "boolean"
	default:
		return "string"
	}
}

// tsConstValue returns the TypeScript literal for a constant, using branded type assertions.
func tsConstValue(f ast.ConstantField) string {
	switch f.Type {
	case "string":
		return fmt.Sprintf("%q", f.Value)
	case "uuid":
		return fmt.Sprintf("%q as UUID", f.Value)
	case "decimal":
		return fmt.Sprintf("%q as Decimal", f.Value)
	case "date":
		return fmt.Sprintf("%q as ISODate", f.Value)
	case "datetime":
		return fmt.Sprintf("%q as ISODateTime", f.Value)
	case "int", "float":
		return f.Value
	case "bool":
		return f.Value
	default:
		return fmt.Sprintf("%q", f.Value)
	}
}
