package tsshared

// errors.go — emits errors/_base.ts, errors/{module}.errors.ts, errors/index.ts.
//
// Shared between the Node backend emitter and the TypeScript frontend emitter
// so the errors/ directory is always present when a TS frontend is generated,
// regardless of which backend (node, java, csharp, go, …) is chosen.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

// EmitTSErrors writes errors/_base.ts + errors/{module}.errors.ts + errors/index.ts
// into outDir. Does nothing if no module defines typed errors. Idempotent.
func EmitTSErrors(a ast.AST, outDir string) error {
	hasAny := false
	for _, mod := range a.Modules {
		if emitter.HasErrors(mod) {
			hasAny = true
			break
		}
	}
	if !hasAny {
		return nil
	}

	dir := filepath.Join(outDir, "errors")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	if err := emitErrorsBase(dir); err != nil {
		return err
	}
	for _, mod := range a.Modules {
		if err := emitModuleErrors(mod, dir); err != nil {
			return fmt.Errorf("errors %s: %w", mod.Name, err)
		}
	}
	return emitErrorsBarrel(a, dir)
}

func emitErrorsBase(dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("export class ApiError<Code extends string = string> extends Error {\n")
	sb.WriteString("  readonly code: Code;\n")
	sb.WriteString("  readonly status: number;\n\n")
	sb.WriteString("  constructor(code: Code, status: number, message?: string) {\n")
	sb.WriteString("    super(message ?? code);\n")
	sb.WriteString("    this.name = 'ApiError';\n")
	sb.WriteString("    this.code = code;\n")
	sb.WriteString("    this.status = status;\n")
	sb.WriteString("  }\n\n")
	sb.WriteString("  toJSON() {\n")
	sb.WriteString("    return { error: this.message, code: this.code };\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, "_base.ts"), []byte(sb.String()), 0644)
}

func emitModuleErrors(mod ast.Module, dir string) error {
	if !emitter.HasErrors(mod) {
		return nil
	}
	moduleLower := strings.ToLower(mod.Name)
	var sb strings.Builder

	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n\n")
	sb.WriteString("import { ApiError } from './_base';\n")
	sb.WriteString("export { ApiError } from './_base';\n\n")

	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		pascal := act.Name

		var codes []string
		for _, errName := range act.Errors {
			codes = append(codes, fmt.Sprintf("'%s'", emitter.ErrorCode(act.Name, errName)))
		}

		sb.WriteString(fmt.Sprintf("/** Error codes for %s */\n", pascal))
		sb.WriteString(fmt.Sprintf("export type %sErrorCode = %s;\n\n", pascal, strings.Join(codes, " | ")))

		sb.WriteString(fmt.Sprintf("/** Typed error for %s */\n", pascal))
		sb.WriteString(fmt.Sprintf("export type %sError = ApiError<%sErrorCode>;\n\n", pascal, pascal))

		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf("/** Error factories for %s — each factory also exposes .code and .status for frontend type guards. */\n", pascal))
		sb.WriteString(fmt.Sprintf("export const %sErrors = {\n", camelAction))
		for _, errName := range act.Errors {
			code := emitter.ErrorCode(act.Name, errName)
			status := emitter.ErrorHTTPStatus(errName)
			camelErr := emitter.ToCamelCase(errName)
			// Object.assign attaches .code/.status metadata to the factory function so
			// frontend can write: isErrorCode(err, usersErrors.getUser.notFound.code)
			// without magic strings, while the backend still calls: throw usersErrors.getUser.notFound('msg')
			sb.WriteString(fmt.Sprintf("  %s: Object.assign(\n", camelErr))
			sb.WriteString(fmt.Sprintf("    (message?: string): %sError => new ApiError('%s', %d, message ?? '%s'),\n", pascal, code, status, errName))
			sb.WriteString(fmt.Sprintf("    { code: '%s' as const, status: %d as const },\n", code, status))
			sb.WriteString("  ),\n")
		}
		sb.WriteString("} as const;\n\n")
	}

	sb.WriteString(fmt.Sprintf("export const %sErrors = {\n", moduleLower))
	for _, act := range mod.Actions {
		if len(act.Errors) == 0 {
			continue
		}
		camelAction := emitter.ToCamelCase(act.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sErrors,\n", camelAction, camelAction))
	}
	sb.WriteString("} as const;\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+".errors.ts"), []byte(sb.String()), 0644)
}

func emitErrorsBarrel(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
	sb.WriteString("export { ApiError } from './_base';\n")

	exported := map[string]bool{"ApiError": true}

	for _, mod := range a.Modules {
		if !emitter.HasErrors(mod) {
			continue
		}
		moduleLower := strings.ToLower(mod.Name)
		allNames := emitter.CollectErrorExports(mod)

		var unique []string
		for _, name := range allNames {
			if !exported[name] {
				exported[name] = true
				unique = append(unique, name)
			}
		}

		if len(unique) == len(allNames) {
			sb.WriteString(fmt.Sprintf("export * from './%s.errors';\n", moduleLower))
		} else if len(unique) > 0 {
			var typeNames, valueNames []string
			for _, name := range unique {
				if strings.HasSuffix(name, "ErrorCode") ||
					(strings.HasSuffix(name, "Error") && !strings.HasSuffix(name, "Errors")) {
					typeNames = append(typeNames, name)
				} else {
					valueNames = append(valueNames, name)
				}
			}
			if len(typeNames) > 0 {
				sb.WriteString(fmt.Sprintf("export type { %s } from './%s.errors';\n",
					strings.Join(typeNames, ", "), moduleLower))
			}
			if len(valueNames) > 0 {
				sb.WriteString(fmt.Sprintf("export { %s } from './%s.errors';\n",
					strings.Join(valueNames, ", "), moduleLower))
			}
		}
	}

	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(sb.String()), 0644)
}
