// Package tsshared provides TypeScript type generation shared between the Node
// backend emitter and the TypeScript/React/Vue/Angular/Svelte frontend emitters.
//
// This ensures the generated types/ directory is always available for the
// frontend SDK regardless of which backend (node, java, csharp, go, …) is used.
package tsshared

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

// EmitTSTypes writes types/{module}.ts + types/index.ts into outDir.
//
// Types are "owned" by the first module that references them. Later modules
// that also need the same type import+re-export it from the canonical file.
// A barrel types/index.ts re-exports everything for convenience.
//
// Call this from any emitter that needs a types/ directory in the output —
// the write is idempotent (deterministic output, same AST → identical files).
func EmitTSTypes(a ast.AST, outDir string) error {
	dir := filepath.Join(outDir, "types")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// claimed tracks which module file "owns" each type definition.
	claimed := make(map[string]string) // typeName → moduleLowerName

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)

		var ownedEnums []ast.Enum
		var ownedModels []ast.Model
		reExports := make(map[string][]string) // sourceFile → []typeName

		for _, en := range a.Enums {
			if !usedEnums[en.Name] {
				continue
			}
			if owner, taken := claimed[en.Name]; taken {
				reExports[owner] = append(reExports[owner], en.Name)
			} else {
				claimed[en.Name] = moduleLower
				ownedEnums = append(ownedEnums, en)
			}
		}
		for _, m := range a.Models {
			if !usedModels[m.Name] {
				continue
			}
			if owner, taken := claimed[m.Name]; taken {
				reExports[owner] = append(reExports[owner], m.Name)
			} else {
				claimed[m.Name] = moduleLower
				ownedModels = append(ownedModels, m)
			}
		}

		// Collect types referenced in owned model fields that are owned by another
		// module — they need a local import so they are in scope as field types.
		ownedNames := make(map[string]bool)
		for _, en := range ownedEnums {
			ownedNames[en.Name] = true
		}
		for _, m := range ownedModels {
			ownedNames[m.Name] = true
		}
		localImports := make(map[string][]string) // sourceFile → []typeName
		for _, m := range ownedModels {
			for _, f := range m.Fields {
				checkRef := func(typeName string) {
					if typeName == "" || ownedNames[typeName] {
						return
					}
					if owner, ok := claimed[typeName]; ok && owner != moduleLower {
						localImports[owner] = appendUnique(localImports[owner], typeName)
					}
				}
				checkRef(f.Type)
				if f.IsMap {
					checkRef(f.MapValueType)
				}
				for _, ut := range f.UnionTypes {
					checkRef(ut)
				}
			}
			if m.Extends != "" && !ownedNames[m.Extends] {
				if owner, ok := claimed[m.Extends]; ok && owner != moduleLower {
					localImports[owner] = appendUnique(localImports[owner], m.Extends)
				}
			}
		}

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")

		for source, names := range localImports {
			sb.WriteString(fmt.Sprintf("import type { %s } from './%s';\n", strings.Join(names, ", "), source))
		}
		for source, names := range reExports {
			sb.WriteString(fmt.Sprintf("export type { %s } from './%s';\n", strings.Join(names, ", "), source))
		}
		if (len(reExports) > 0 || len(localImports) > 0) && (len(ownedEnums) > 0 || len(ownedModels) > 0) {
			sb.WriteString("\n")
		}

		for _, en := range ownedEnums {
			if en.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", en.Name, strings.Join(quoted, " | ")))
		}

		for _, m := range ownedModels {
			if m.Description != "" {
				sb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			if m.Extends != "" {
				sb.WriteString(fmt.Sprintf("export interface %s extends %s {\n", m.Name, m.Extends))
			} else {
				sb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
			}
			for _, f := range m.Fields {
				if f.Deprecated != "" {
					sb.WriteString(fmt.Sprintf("  /** @deprecated %s */\n", f.Deprecated))
				}
				opt := ""
				if f.Optional {
					opt = "?"
				}
				sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, tshelpers.VeldFieldToTS(f)))
			}
			sb.WriteString("}\n\n")
		}

		if err := os.WriteFile(filepath.Join(dir, moduleLower+".ts"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Emit unclaimed models/enums (e.g. from shared imports) into types/common.ts.
	var unclaimedEnums []ast.Enum
	var unclaimedModels []ast.Model
	for _, en := range a.Enums {
		if _, taken := claimed[en.Name]; !taken {
			unclaimedEnums = append(unclaimedEnums, en)
		}
	}
	for _, m := range a.Models {
		if _, taken := claimed[m.Name]; !taken {
			unclaimedModels = append(unclaimedModels, m)
		}
	}
	hasCommon := len(unclaimedEnums) > 0 || len(unclaimedModels) > 0
	if hasCommon {
		var csb strings.Builder
		csb.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")
		for _, en := range unclaimedEnums {
			if en.Description != "" {
				csb.WriteString(fmt.Sprintf("/** %s */\n", en.Description))
			}
			quoted := make([]string, len(en.Values))
			for i, v := range en.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			csb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", en.Name, strings.Join(quoted, " | ")))
		}
		for _, m := range unclaimedModels {
			if m.Description != "" {
				csb.WriteString(fmt.Sprintf("/** %s */\n", m.Description))
			}
			if m.Extends != "" {
				csb.WriteString(fmt.Sprintf("export interface %s extends %s {\n", m.Name, m.Extends))
			} else {
				csb.WriteString(fmt.Sprintf("export interface %s {\n", m.Name))
			}
			for _, f := range m.Fields {
				if f.Deprecated != "" {
					csb.WriteString(fmt.Sprintf("  /** @deprecated %s */\n", f.Deprecated))
				}
				opt := ""
				if f.Optional {
					opt = "?"
				}
				csb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, tshelpers.VeldFieldToTS(f)))
			}
			csb.WriteString("}\n\n")
		}
		if err := os.WriteFile(filepath.Join(dir, "common.ts"), []byte(csb.String()), 0644); err != nil {
			return err
		}
	}

	// Barrel: types/index.ts re-exports everything.
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD \u2014 DO NOT EDIT\n")

	barrelExported := make(map[string]bool)
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)

		var moduleExports []string
		for typeName, owner := range claimed {
			if owner == moduleLower {
				moduleExports = append(moduleExports, typeName)
			}
		}
		usedModels := emitter.CollectTransitiveModels(a, mod)
		usedEnums := emitter.CollectUsedEnums(a, mod)
		for _, en := range a.Enums {
			if usedEnums[en.Name] && claimed[en.Name] != moduleLower {
				moduleExports = append(moduleExports, en.Name)
			}
		}
		for _, m := range a.Models {
			if usedModels[m.Name] && claimed[m.Name] != moduleLower {
				moduleExports = append(moduleExports, m.Name)
			}
		}

		var unique []string
		for _, name := range moduleExports {
			if !barrelExported[name] {
				barrelExported[name] = true
				unique = append(unique, name)
			}
		}

		if len(unique) == len(moduleExports) {
			barrel.WriteString(fmt.Sprintf("export * from './%s';\n", moduleLower))
		} else if len(unique) > 0 {
			barrel.WriteString(fmt.Sprintf("export type { %s } from './%s';\n",
				strings.Join(unique, ", "), moduleLower))
		}
	}
	if hasCommon {
		barrel.WriteString("export * from './common';\n")
	}
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(barrel.String()), 0644)
}

func appendUnique(slice []string, s string) []string {
	for _, v := range slice {
		if v == s {
			return slice
		}
	}
	return append(slice, s)
}
