// Package database generates database schema files (TypeORM, GORM, SQLAlchemy).
// Also exposes the existing Prisma and SQL DDL generators as a registered emitter.
package database

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/schema"
)

func init() {
	emitter.RegisterBackend("database", New())
}

type DatabaseEmitter struct{}

func New() *DatabaseEmitter         { return &DatabaseEmitter{} }
func (*DatabaseEmitter) IsBackend() {}

func (e *DatabaseEmitter) Summary(_ []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "database/", Files: "schema.prisma, schema.sql"},
		{Dir: "database/typeorm/", Files: "entities.ts"},
		{Dir: "database/gorm/", Files: "models.go"},
		{Dir: "database/sqlalchemy/", Files: "models.py"},
	}
}

func (e *DatabaseEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	dbDir := filepath.Join(outDir, "database")
	for _, sub := range []string{"", "typeorm", "gorm", "sqlalchemy"} {
		if err := os.MkdirAll(filepath.Join(dbDir, sub), 0755); err != nil {
			return err
		}
	}

	// Prisma
	prismaContent := schema.BuildPrisma(a)
	if err := os.WriteFile(filepath.Join(dbDir, "schema.prisma"), []byte(prismaContent), 0644); err != nil {
		return fmt.Errorf("prisma: %w", err)
	}

	// SQL DDL
	sqlContent := schema.BuildSQL(a)
	if err := os.WriteFile(filepath.Join(dbDir, "schema.sql"), []byte(sqlContent), 0644); err != nil {
		return fmt.Errorf("sql: %w", err)
	}

	// TypeORM entities
	if err := emitTypeORM(a, filepath.Join(dbDir, "typeorm")); err != nil {
		return fmt.Errorf("typeorm: %w", err)
	}

	// GORM models
	if err := emitGORM(a, filepath.Join(dbDir, "gorm")); err != nil {
		return fmt.Errorf("gorm: %w", err)
	}

	// SQLAlchemy models
	if err := emitSQLAlchemy(a, filepath.Join(dbDir, "sqlalchemy")); err != nil {
		return fmt.Errorf("sqlalchemy: %w", err)
	}

	return nil
}

// ── TypeORM ──────────────────────────────────────────────────────────

func emitTypeORM(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';\n\n")

	for _, m := range a.Models {
		sb.WriteString(fmt.Sprintf("@Entity('%s')\n", toSnakeCase(m.Name)+"s"))
		sb.WriteString(fmt.Sprintf("export class %sEntity {\n", m.Name))

		for _, f := range m.Fields {
			if f.Name == "id" {
				if f.Type == "uuid" {
					sb.WriteString("  @PrimaryGeneratedColumn('uuid')\n")
				} else {
					sb.WriteString("  @PrimaryGeneratedColumn()\n")
				}
			} else {
				colOpts := typeormColumnOpts(f)
				sb.WriteString(fmt.Sprintf("  @Column(%s)\n", colOpts))
			}
			tsType := typeormTSType(f)
			opt := ""
			if f.Optional {
				opt = "?"
			}
			sb.WriteString(fmt.Sprintf("  %s%s!: %s;\n\n", f.Name, opt, tsType))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "entities.ts"), []byte(sb.String()), 0644)
}

func typeormColumnOpts(f ast.Field) string {
	var opts []string
	switch f.Type {
	case "string", "uuid":
		// default
	case "int":
		opts = append(opts, "type: 'bigint'")
	case "float":
		opts = append(opts, "type: 'float'")
	case "bool":
		opts = append(opts, "type: 'boolean'")
	case "date":
		opts = append(opts, "type: 'date'")
	case "datetime":
		opts = append(opts, "type: 'timestamp'")
	}
	if f.Optional {
		opts = append(opts, "nullable: true")
	}
	if f.Default != "" && f.Default != "now()" {
		opts = append(opts, fmt.Sprintf("default: '%s'", f.Default))
	}
	if len(opts) == 0 {
		return ""
	}
	return "{ " + strings.Join(opts, ", ") + " }"
}

func typeormTSType(f ast.Field) string {
	if f.IsArray {
		return typeormScalar(f.Type) + "[]"
	}
	return typeormScalar(f.Type)
}

func typeormScalar(t string) string {
	switch t {
	case "string", "uuid", "date", "datetime":
		return "string"
	case "int", "float":
		return "number"
	case "bool":
		return "boolean"
	default:
		return t
	}
}

// ── GORM ─────────────────────────────────────────────────────────────

func emitGORM(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("package models\n\n")

	needsTime := false
	for _, m := range a.Models {
		for _, f := range m.Fields {
			if f.Type == "date" || f.Type == "datetime" {
				needsTime = true
			}
		}
	}

	sb.WriteString("import (\n")
	if needsTime {
		sb.WriteString("\t\"time\"\n")
	}
	sb.WriteString("\n\t\"gorm.io/gorm\"\n")
	sb.WriteString(")\n\n")

	for _, m := range a.Models {
		sb.WriteString(fmt.Sprintf("// %s is a GORM model.\n", m.Name))
		sb.WriteString(fmt.Sprintf("type %s struct {\n", m.Name))

		if m.Extends != "" {
			sb.WriteString(fmt.Sprintf("\t%s\n", m.Extends))
		}

		for _, f := range m.Fields {
			goType := gormGoType(f)
			fieldName := gormFieldName(f.Name)
			gormTag := gormTag(f)
			sb.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, goType, gormTag))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "models.go"), []byte(sb.String()), 0644)
}

func gormGoType(f ast.Field) string {
	if f.IsArray {
		return "[]" + gormScalar(f.Type)
	}
	if f.IsMap {
		return "map[string]" + gormScalar(f.MapValueType)
	}
	base := gormScalar(f.Type)
	if f.Optional {
		return "*" + base
	}
	return base
}

func gormScalar(t string) string {
	switch t {
	case "string", "uuid":
		return "string"
	case "int":
		return "int64"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	case "date", "datetime":
		return "time.Time"
	default:
		return t
	}
}

func gormFieldName(name string) string {
	parts := strings.Split(toSnakeCase(name), "_")
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return sb.String()
}

func gormTag(f ast.Field) string {
	var parts []string
	parts = append(parts, fmt.Sprintf("column:%s", toSnakeCase(f.Name)))
	if f.Name == "id" {
		parts = append(parts, "primaryKey")
		if f.Type == "uuid" {
			parts = append(parts, "type:uuid", "default:gen_random_uuid()")
		}
	}
	if !f.Optional && f.Name != "id" {
		parts = append(parts, "not null")
	}
	return fmt.Sprintf("`gorm:\"%s\" json:\"%s\"`", strings.Join(parts, ";"), f.Name)
}

// ── SQLAlchemy ───────────────────────────────────────────────────────

func emitSQLAlchemy(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("# AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, Date\n")
	sb.WriteString("from sqlalchemy.dialects.postgresql import UUID\n")
	sb.WriteString("from sqlalchemy.orm import DeclarativeBase\n")
	sb.WriteString("import uuid\n\n\n")

	sb.WriteString("class Base(DeclarativeBase):\n")
	sb.WriteString("    pass\n\n\n")

	for _, m := range a.Models {
		tableName := toSnakeCase(m.Name) + "s"
		sb.WriteString(fmt.Sprintf("class %s(Base):\n", m.Name))
		sb.WriteString(fmt.Sprintf("    __tablename__ = '%s'\n\n", tableName))

		for _, f := range m.Fields {
			colType := saColumnType(f)
			extras := ""
			if f.Name == "id" {
				extras = ", primary_key=True"
				if f.Type == "uuid" {
					extras += ", default=uuid.uuid4"
				}
			}
			if !f.Optional && f.Name != "id" {
				extras += ", nullable=False"
			} else if f.Optional {
				extras += ", nullable=True"
			}
			sb.WriteString(fmt.Sprintf("    %s = Column(%s%s)\n", toSnakeCase(f.Name), colType, extras))
		}
		sb.WriteString("\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "models.py"), []byte(sb.String()), 0644)
}

func saColumnType(f ast.Field) string {
	switch f.Type {
	case "string":
		return "String(255)"
	case "int":
		return "Integer"
	case "float":
		return "Float"
	case "bool":
		return "Boolean"
	case "date":
		return "Date"
	case "datetime":
		return "DateTime"
	case "uuid":
		return "UUID(as_uuid=True)"
	default:
		return "String(255)"
	}
}

// ── Helpers ──────────────────────────────────────────────────────────

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
