// Package golang implements the Veld service SDK emitter for Go.
//
// It generates typed, net/http-based HTTP client packages for consumed services,
// enabling type-safe inter-service communication. Each consumed service gets
// its own Go package under generated/sdk/<service>/ with:
//   - client.go — the typed Client struct (net/http + encoding/json only)
//   - types.go  — struct types used by that service's actions
//   - doc.go    — package documentation
//
// Self-registers under the name "go" (matching the backend emitter name).
package golang

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/sdkhelpers"
)

func init() {
	emitter.RegisterServiceSdk("go", New())
}

// Emitter generates Go service SDK clients.
type Emitter struct{}

func New() *Emitter            { return &Emitter{} }
func (*Emitter) IsServiceSdk() {}

// Summary returns a human-friendly breakdown of generated SDK files.
func (e *Emitter) Summary(modules []string) []emitter.SummaryLine {
	var lines []emitter.SummaryLine
	for _, m := range modules {
		name := sdkhelpers.ServiceFileName(m)
		lines = append(lines, emitter.SummaryLine{
			Dir:   fmt.Sprintf("sdk/%s/", name),
			Files: "client.go, types.go, doc.go",
		})
	}
	return lines
}

// Emit generates SDK client files for each consumed service.
func (e *Emitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	for _, consumed := range opts.ConsumedServices {
		if err := emitServiceSdk(consumed, outDir); err != nil {
			return fmt.Errorf("service sdk %s: %w", consumed.Name, err)
		}
	}

	return nil
}

func emitServiceSdk(consumed emitter.ConsumedServiceInfo, outDir string) error {
	name := sdkhelpers.ServiceFileName(consumed.Name)
	dir := filepath.Join(outDir, "sdk", name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	if err := emitSdkDoc(consumed, dir, name); err != nil {
		return fmt.Errorf("doc: %w", err)
	}
	if err := emitSdkTypes(consumed, dir, name); err != nil {
		return fmt.Errorf("types: %w", err)
	}
	if err := emitSdkClient(consumed, dir, name); err != nil {
		return fmt.Errorf("client: %w", err)
	}
	return nil
}

// ── doc.go ────────────────────────────────────────────────────────────────────

func emitSdkDoc(consumed emitter.ConsumedServiceInfo, dir, pkgName string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Service SDK: typed HTTP client for the %s service.\n", consumed.Name))
	sb.WriteString(fmt.Sprintf("package %s\n", pkgName))
	return os.WriteFile(filepath.Join(dir, "doc.go"), []byte(sb.String()), 0644)
}

// ── types.go ──────────────────────────────────────────────────────────────────

func emitSdkTypes(consumed emitter.ConsumedServiceInfo, dir, pkgName string) error {
	var sb strings.Builder
	a := consumed.AST

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	// Collect all models and enums used.
	usedModels := make(map[string]bool)
	usedEnums := make(map[string]bool)
	for _, mod := range a.Modules {
		for k, v := range emitter.CollectTransitiveModels(a, mod) {
			if v {
				usedModels[k] = true
			}
		}
		for k, v := range emitter.CollectUsedEnums(a, mod) {
			if v {
				usedEnums[k] = true
			}
		}
	}

	// Check if time import is needed.
	needsTime := false
	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		for _, f := range m.Fields {
			if f.Type == "date" || f.Type == "datetime" {
				needsTime = true
			}
		}
	}
	if needsTime {
		sb.WriteString("import \"time\"\n\n")
	}

	// Emit enums as string type aliases with constants.
	for _, en := range a.Enums {
		if !usedEnums[en.Name] {
			continue
		}
		sb.WriteString(fmt.Sprintf("// %s represents the %s enum.\n", en.Name, en.Name))
		sb.WriteString(fmt.Sprintf("type %s string\n\n", en.Name))
		sb.WriteString("const (\n")
		for _, v := range en.Values {
			constName := en.Name + capitalize(v)
			sb.WriteString(fmt.Sprintf("\t%s %s = %q\n", constName, en.Name, v))
		}
		sb.WriteString(")\n\n")
	}

	// Emit models as structs.
	modelMap := make(map[string]ast.Model, len(a.Models))
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}

	for _, m := range a.Models {
		if !usedModels[m.Name] {
			continue
		}
		if m.Description != "" {
			sb.WriteString(fmt.Sprintf("// %s — %s\n", m.Name, m.Description))
		} else {
			sb.WriteString(fmt.Sprintf("// %s is a generated model.\n", m.Name))
		}
		sb.WriteString(fmt.Sprintf("type %s struct {\n", m.Name))

		// If extends, include parent fields inline (Go doesn't have inheritance).
		allFields := collectFieldsWithInheritance(m, modelMap)
		for _, f := range allFields {
			goType := veldFieldToGo(f)
			if f.Optional {
				goType = "*" + goType
			}
			jsonTag := f.Name
			if f.Optional {
				jsonTag += ",omitempty"
			}
			sb.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", capitalize(f.Name), goType, jsonTag))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(dir, "types.go"), []byte(sb.String()), 0644)
}

// ── client.go ─────────────────────────────────────────────────────────────────

func emitSdkClient(consumed emitter.ConsumedServiceInfo, dir, pkgName string) error {
	var sb strings.Builder
	a := consumed.AST
	envVar := sdkhelpers.EnvVarName(consumed.Name)

	sb.WriteString("// Code generated by Veld — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	sb.WriteString("import (\n")
	sb.WriteString("\t\"bytes\"\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"io\"\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"net/url\"\n")
	sb.WriteString("\t\"os\"\n")
	sb.WriteString(")\n\n")

	// VeldApiError type.
	sb.WriteString("// VeldApiError represents an HTTP error from the service.\n")
	sb.WriteString("type VeldApiError struct {\n")
	sb.WriteString("\tStatus int\n")
	sb.WriteString("\tBody   string\n")
	sb.WriteString("}\n\n")
	sb.WriteString("func (e *VeldApiError) Error() string {\n")
	sb.WriteString("\treturn fmt.Sprintf(\"HTTP %d: %s\", e.Status, e.Body)\n")
	sb.WriteString("}\n\n")

	// Option type.
	sb.WriteString("// Option configures the Client.\n")
	sb.WriteString("type Option func(*Client)\n\n")

	sb.WriteString("// WithHTTPClient sets a custom http.Client.\n")
	sb.WriteString("func WithHTTPClient(c *http.Client) Option {\n")
	sb.WriteString("\treturn func(cl *Client) { cl.client = c }\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// WithHeaders sets default request headers.\n")
	sb.WriteString("func WithHeaders(h map[string]string) Option {\n")
	sb.WriteString("\treturn func(cl *Client) { cl.hdrs = h }\n")
	sb.WriteString("}\n\n")

	// Client struct.
	sb.WriteString(fmt.Sprintf("// Client communicates with the %s service.\n", consumed.Name))
	sb.WriteString("type Client struct {\n")
	sb.WriteString("\tbase   string\n")
	sb.WriteString("\tclient *http.Client\n")
	sb.WriteString("\thdrs   map[string]string\n")
	sb.WriteString("}\n\n")

	// NewClient constructor.
	sb.WriteString(fmt.Sprintf("// NewClient creates a %s service client.\n", consumed.Name))
	sb.WriteString(fmt.Sprintf("// baseURL defaults to %s env var", envVar))
	if consumed.BaseUrl != "" {
		sb.WriteString(fmt.Sprintf(", then %q.\n", consumed.BaseUrl))
	} else {
		sb.WriteString(".\n")
	}
	sb.WriteString("func NewClient(baseURL string, opts ...Option) *Client {\n")
	sb.WriteString("\tif baseURL == \"\" {\n")
	sb.WriteString(fmt.Sprintf("\t\tbaseURL = os.Getenv(%q)\n", envVar))
	sb.WriteString("\t}\n")
	if consumed.BaseUrl != "" {
		sb.WriteString("\tif baseURL == \"\" {\n")
		sb.WriteString(fmt.Sprintf("\t\tbaseURL = %q\n", consumed.BaseUrl))
		sb.WriteString("\t}\n")
	}
	sb.WriteString("\tc := &Client{base: baseURL, client: http.DefaultClient, hdrs: map[string]string{}}\n")
	sb.WriteString("\tfor _, o := range opts {\n")
	sb.WriteString("\t\to(c)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn c\n")
	sb.WriteString("}\n\n")

	// Private do method.
	sb.WriteString("func (c *Client) do(ctx context.Context, method, path string, body any) ([]byte, int, error) {\n")
	sb.WriteString("\tvar reader io.Reader\n")
	sb.WriteString("\tif body != nil {\n")
	sb.WriteString("\t\tb, err := json.Marshal(body)\n")
	sb.WriteString("\t\tif err != nil {\n")
	sb.WriteString("\t\t\treturn nil, 0, err\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t\treader = bytes.NewReader(b)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treq, err := http.NewRequestWithContext(ctx, method, c.base+path, reader)\n")
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\treturn nil, 0, err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	sb.WriteString("\tfor k, v := range c.hdrs {\n")
	sb.WriteString("\t\treq.Header.Set(k, v)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tresp, err := c.client.Do(req)\n")
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\treturn nil, 0, err\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\tdefer resp.Body.Close()\n")
	sb.WriteString("\tdata, _ := io.ReadAll(resp.Body)\n")
	sb.WriteString("\tif resp.StatusCode >= 400 {\n")
	sb.WriteString("\t\treturn nil, resp.StatusCode, &VeldApiError{Status: resp.StatusCode, Body: string(data)}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn data, resp.StatusCode, nil\n")
	sb.WriteString("}\n")

	// Per-module methods.
	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			if strings.ToUpper(act.Method) == "WS" {
				sb.WriteString(fmt.Sprintf("\n// WebSocket action %s.%s not supported in service SDK.\n", mod.Name, act.Name))
				continue
			}
			sb.WriteString("\n")
			writeGoActionMethod(&sb, mod, act)
		}
	}

	// Suppress unused import warnings.
	sb.WriteString("\nvar _ = url.Values{}\n")

	return os.WriteFile(filepath.Join(dir, "client.go"), []byte(sb.String()), 0644)
}

func writeGoActionMethod(sb *strings.Builder, mod ast.Module, act ast.Action) {
	routePath := mod.Prefix + act.Path
	method := strings.ToUpper(act.Method)
	funcName := capitalize(act.Name)
	pathParams := emitter.ExtractPathParams(routePath)

	// Return types.
	hasOutput := act.Output != ""
	goReturnType := ""
	if hasOutput {
		if act.OutputArray {
			goReturnType = fmt.Sprintf("[]%s", act.Output)
		} else {
			goReturnType = "*" + act.Output
		}
	}

	// Build doc comment.
	if act.Description != "" {
		sb.WriteString(fmt.Sprintf("// %s calls %s %s — %s\n", funcName, method, routePath, act.Description))
	} else {
		sb.WriteString(fmt.Sprintf("// %s calls %s %s.\n", funcName, method, routePath))
	}
	if act.Deprecated != "" {
		sb.WriteString(fmt.Sprintf("//\n// Deprecated: %s\n", act.Deprecated))
	}

	// Build signature.
	var params []string
	params = append(params, "ctx context.Context")
	for _, p := range pathParams {
		params = append(params, fmt.Sprintf("%s string", p))
	}
	if act.Input != "" {
		params = append(params, fmt.Sprintf("input %s", act.Input))
	}
	if act.Query != "" {
		params = append(params, fmt.Sprintf("query *%s", act.Query))
	}

	if hasOutput {
		sb.WriteString(fmt.Sprintf("func (c *Client) %s(%s) (%s, error) {\n", funcName, strings.Join(params, ", "), goReturnType))
	} else {
		sb.WriteString(fmt.Sprintf("func (c *Client) %s(%s) error {\n", funcName, strings.Join(params, ", ")))
	}

	// Build URL with path param interpolation.
	urlExpr := buildGoUrlExpr(routePath, pathParams)

	// Query string.
	if act.Query != "" {
		sb.WriteString(fmt.Sprintf("\tpath := %s\n", urlExpr))
		sb.WriteString("\tif query != nil {\n")
		sb.WriteString("\t\tqs := url.Values{}\n")
		sb.WriteString("\t\t// Query params would be added here based on the query model.\n")
		sb.WriteString("\t\tif encoded := qs.Encode(); encoded != \"\" {\n")
		sb.WriteString("\t\t\tpath += \"?\" + encoded\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t}\n")
		urlExpr = "path"
	}

	// Body arg.
	bodyArg := "nil"
	if act.Input != "" {
		bodyArg = "input"
	}

	if hasOutput {
		sb.WriteString(fmt.Sprintf("\tdata, _, err := c.do(ctx, %q, %s, %s)\n", method, urlExpr, bodyArg))
		sb.WriteString("\tif err != nil {\n")
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		if act.OutputArray {
			sb.WriteString(fmt.Sprintf("\tvar out []%s\n", act.Output))
		} else {
			sb.WriteString(fmt.Sprintf("\tvar out %s\n", act.Output))
		}
		sb.WriteString("\tif err := json.Unmarshal(data, &out); err != nil {\n")
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		if act.OutputArray {
			sb.WriteString("\treturn out, nil\n")
		} else {
			sb.WriteString("\treturn &out, nil\n")
		}
	} else {
		sb.WriteString(fmt.Sprintf("\t_, _, err := c.do(ctx, %q, %s, %s)\n", method, urlExpr, bodyArg))
		sb.WriteString("\treturn err\n")
	}

	sb.WriteString("}\n")
}

// ── helpers ───────────────────────────────────────────────────────────────────

func veldScalarToGo(t string) string {
	switch t {
	case "string", "uuid":
		return "string"
	case "int":
		return "int64"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	case "date", "datetime":
		return "time.Time"
	case "any", "json":
		return "interface{}"
	default:
		return t
	}
}

func veldFieldToGo(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("map[string]%s", veldScalarToGo(f.MapValueType))
	}
	base := veldScalarToGo(f.Type)
	if f.IsArray {
		return "[]" + base
	}
	return base
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func buildGoUrlExpr(routePath string, pathParams []string) string {
	if len(pathParams) == 0 {
		return fmt.Sprintf("%q", routePath)
	}
	// Convert :param to %s for fmt.Sprintf.
	fmtStr := routePath
	var args []string
	for _, p := range pathParams {
		fmtStr = strings.Replace(fmtStr, ":"+p, "%s", 1)
		args = append(args, p)
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", fmtStr, strings.Join(args, ", "))
}

// collectFieldsWithInheritance returns all fields for a model, including
// inherited fields from parent models. Go doesn't have struct inheritance,
// so we flatten the hierarchy.
func collectFieldsWithInheritance(m ast.Model, modelMap map[string]ast.Model) []ast.Field {
	var fields []ast.Field
	if m.Extends != "" {
		if parent, ok := modelMap[m.Extends]; ok {
			fields = append(fields, collectFieldsWithInheritance(parent, modelMap)...)
		}
	}
	fields = append(fields, m.Fields...)
	return fields
}
