package kotlin

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterFrontend("kotlin", New())
}

// KotlinEmitter generates the frontend Kotlin SDK (generated/client/ApiClient.kt).
type KotlinEmitter struct{}

func (*KotlinEmitter) IsFrontend() {}

// New returns a KotlinEmitter.
func New() *KotlinEmitter { return &KotlinEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *KotlinEmitter) Summary(modules []string) []emitter.SummaryLine {
	return []emitter.SummaryLine{
		{Dir: "client/", Files: "ApiClient.kt"},
	}
}

func veldTypeToKotlin(t string) string {
	switch t {
	case "int":
		return "Int"
	case "float":
		return "Double"
	case "bool":
		return "Boolean"
	case "string", "date", "datetime", "uuid":
		return "String"
	default:
		return t
	}
}

func kotlinFieldType(f ast.Field) string {
	if f.IsMap {
		return fmt.Sprintf("Map<String, %s>", veldTypeToKotlin(f.MapValueType))
	}
	base := veldTypeToKotlin(f.Type)
	if f.IsArray {
		return fmt.Sprintf("List<%s>", base)
	}
	return base
}

// Emit writes generated/client/ApiClient.kt into outDir.
func (e *KotlinEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}
	dir := filepath.Join(outDir, "client")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	allTypes := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, t := range emitter.CollectUsedTypes(a, mod) {
			allTypes[t] = true
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("package veld.generated.client\n\n")
	sb.WriteString("import java.net.URI\n")
	sb.WriteString("import java.net.http.HttpClient\n")
	sb.WriteString("import java.net.http.HttpRequest\n")
	sb.WriteString("import java.net.http.HttpResponse\n")
	sb.WriteString("import kotlinx.serialization.*\n")
	sb.WriteString("import kotlinx.serialization.json.*\n\n")

	// VeldApiError
	sb.WriteString("class VeldApiError(val status: Int, val body: String) : Exception(\"Veld API error $status: $body\")\n\n")

	// Json instance
	sb.WriteString("private val json = Json { ignoreUnknownKeys = true }\n\n")

	// Enums
	for _, en := range a.Enums {
		if !allTypes[en.Name] {
			continue
		}
		sb.WriteString("@Serializable\n")
		sb.WriteString(fmt.Sprintf("enum class %s {\n", en.Name))
		for i, v := range en.Values {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("    @SerialName(\"%s\") %s", v, strings.ToUpper(v)))
		}
		sb.WriteString("\n}\n\n")
	}

	// Data classes
	modelMap := make(map[string]ast.Model)
	for _, m := range a.Models {
		modelMap[m.Name] = m
	}
	for _, m := range a.Models {
		if !allTypes[m.Name] {
			continue
		}
		allFields := collectAllFields(m, modelMap)
		sb.WriteString("@Serializable\n")
		sb.WriteString(fmt.Sprintf("data class %s(\n", m.Name))
		for i, f := range allFields {
			ft := kotlinFieldType(f)
			if f.Optional {
				sb.WriteString(fmt.Sprintf("    val %s: %s? = null", f.Name, ft))
			} else {
				sb.WriteString(fmt.Sprintf("    val %s: %s", f.Name, ft))
			}
			if i < len(allFields)-1 {
				sb.WriteString(",")
			}
			sb.WriteString("\n")
		}
		sb.WriteString(")\n\n")
	}

	// VeldApi object
	baseUrlDefault := ""
	if opts.BaseUrl != "" {
		baseUrlDefault = opts.BaseUrl
	}
	sb.WriteString(fmt.Sprintf("object VeldApi {\n    private val client = HttpClient.newHttpClient()\n    var baseUrl: String = \"%s\"\n\n", baseUrlDefault))

	// Helper method
	sb.WriteString(`    private fun request(method: String, path: String, body: String? = null): String {
        val builder = HttpRequest.newBuilder()
            .uri(URI.create("$baseUrl$path"))
            .header("Content-Type", "application/json")
        when (method) {
            "GET" -> builder.GET()
            "DELETE" -> if (body != null) builder.method("DELETE", HttpRequest.BodyPublishers.ofString(body)) else builder.DELETE()
            else -> builder.method(method, HttpRequest.BodyPublishers.ofString(body ?: "{}"))
        }
        val response = client.send(builder.build(), HttpResponse.BodyHandlers.ofString())
        if (response.statusCode() >= 400) {
            throw VeldApiError(response.statusCode(), response.body())
        }
        return response.body()
    }

`)

	// Module objects
	for _, mod := range a.Modules {
		sb.WriteString(fmt.Sprintf("    object %s {\n", mod.Name))
		for _, act := range mod.Actions {
			routePath := act.Path
			if mod.Prefix != "" {
				routePath = mod.Prefix + act.Path
			}
			method := strings.ToUpper(act.Method)
			pathParams := emitter.ExtractPathParams(routePath)

			desc := act.Description
			if desc != "" {
				desc = " — " + desc
			}
			if method == "WS" {
				sb.WriteString(fmt.Sprintf("        /** WS %s%s */\n", routePath, desc))
			} else {
				sb.WriteString(fmt.Sprintf("        /** %s %s%s */\n", method, routePath, desc))
			}

			// Build return type
			outputType := "Unit"
			if act.Output != "" {
				base := veldTypeToKotlin(act.Output)
				if act.OutputArray {
					outputType = fmt.Sprintf("List<%s>", base)
				} else {
					outputType = base
				}
			}

			// Build params
			var sigParams []string
			for _, p := range pathParams {
				sigParams = append(sigParams, fmt.Sprintf("%s: String", p))
			}
			if act.Input != "" {
				sigParams = append(sigParams, fmt.Sprintf("input: %s", act.Input))
			}
			if act.Query != "" {
				sigParams = append(sigParams, fmt.Sprintf("query: %s? = null", act.Query))
			}
			sig := strings.Join(sigParams, ", ")

			// Build URL expression
			urlExpr := kotlinTemplateLiteral(routePath)

			sb.WriteString(fmt.Sprintf("        fun %s(%s): %s {\n", lcFirst(act.Name), sig, outputType))

			// Query string
			if act.Query != "" {
				sb.WriteString(fmt.Sprintf("            var url = \"%s\"\n", urlExpr))
				sb.WriteString("            // query params omitted for brevity\n")
			}

			bodyArg := "null"
			if act.Input != "" {
				bodyArg = "json.encodeToString(input)"
			}

			path := fmt.Sprintf("\"%s\"", urlExpr)
			if act.Query != "" {
				path = "url"
			}

			if method == "WS" {
				sb.WriteString(fmt.Sprintf("            // WebSocket: connect to $baseUrl%s\n", urlExpr))
				sb.WriteString("            throw UnsupportedOperationException(\"WebSocket not yet supported in JVM HTTP client\")\n")
			} else if act.Output == "" {
				sb.WriteString(fmt.Sprintf("            request(\"%s\", %s, %s)\n", method, path, bodyArg))
			} else {
				sb.WriteString(fmt.Sprintf("            val body = request(\"%s\", %s, %s)\n", method, path, bodyArg))
				if act.OutputArray {
					sb.WriteString(fmt.Sprintf("            return json.decodeFromString(body)\n"))
				} else if emitter.IsPrimitive(act.Output) {
					sb.WriteString("            return json.decodeFromString(body)\n")
				} else {
					sb.WriteString(fmt.Sprintf("            return json.decodeFromString(body)\n"))
				}
			}
			sb.WriteString("        }\n\n")
		}
		sb.WriteString("    }\n\n")
	}

	sb.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "ApiClient.kt"), []byte(sb.String()), 0644)
}

func collectAllFields(m ast.Model, models map[string]ast.Model) []ast.Field {
	if m.Extends == "" {
		return m.Fields
	}
	parent, ok := models[m.Extends]
	if !ok {
		return m.Fields
	}
	parentFields := collectAllFields(parent, models)
	return append(parentFields, m.Fields...)
}

func kotlinTemplateLiteral(path string) string {
	return emitter.ToTemplateLiteral(path)
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
