// Package react generates TanStack Query hooks wrapping the TypeScript API client.
package react

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	tsEmitter "github.com/Adhamzineldin/Veld/internal/emitter/frontend/typescript"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterFrontend("react", New())
}

// ReactEmitter generates TanStack Query hooks for React.
type ReactEmitter struct{}

func New() *ReactEmitter          { return &ReactEmitter{} }
func (*ReactEmitter) IsFrontend() {}

func (e *ReactEmitter) Summary(modules []string) []emitter.SummaryLine {
	clientFiles := []string{"_internal.ts", "api.ts", "package.json"}
	for _, m := range modules {
		clientFiles = append(clientFiles, strings.ToLower(m)+"Api.ts")
	}
	lines := []emitter.SummaryLine{
		{Dir: "client/", Files: strings.Join(clientFiles, ", ")},
	}
	hookFiles := make([]string, len(modules))
	for i, m := range modules {
		hookFiles[i] = "use" + m + ".ts"
	}
	lines = append(lines, emitter.SummaryLine{Dir: "hooks/", Files: strings.Join(hookFiles, ", ")})
	lines = append(lines, emitter.SummaryLine{Dir: "hooks/", Files: "index.ts, package.json"})
	return lines
}

func (e *ReactEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	// First emit the base TypeScript API client (per-module files)
	tsE := tsEmitter.New()
	if err := tsE.Emit(a, outDir, opts); err != nil {
		return fmt.Errorf("typescript base: %w", err)
	}

	hooksDir := filepath.Join(outDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return err
	}

	// Generate per-module hook files
	var barrelExports []string
	for _, mod := range a.Modules {
		if err := e.emitModuleHooks(a, mod, hooksDir); err != nil {
			return fmt.Errorf("hooks for %s: %w", mod.Name, err)
		}
		moduleLower := strings.ToLower(mod.Name)
		barrelExports = append(barrelExports, fmt.Sprintf("export { %sHooks } from './%sHooks';", moduleLower, moduleLower))
	}

	// Barrel index
	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, exp := range barrelExports {
		barrel.WriteString(exp + "\n")
	}
	if err := os.WriteFile(filepath.Join(hooksDir, "index.ts"), []byte(barrel.String()), 0644); err != nil {
		return err
	}

	// Write hooks/package.json with per-module exports
	return emitHooksPackageJSON(a, hooksDir)
}

func emitHooksPackageJSON(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString("  \"name\": \"@veld/hooks\",\n")
	sb.WriteString("  \"private\": true,\n")
	sb.WriteString("  \"types\": \"./index.ts\",\n")
	sb.WriteString("  \"exports\": {\n")
	sb.WriteString("    \".\": \"./index.ts\"")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf(",\n    \"./%sHooks\": \"./%sHooks.ts\"", moduleLower, moduleLower))
	}
	sb.WriteString("\n  },\n")
	sb.WriteString("  \"peerDependencies\": {\n")
	sb.WriteString("    \"@tanstack/react-query\": \">=5.0.0\"\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, "package.json"), []byte(sb.String()), 0644)
}

func (e *ReactEmitter) emitModuleHooks(a ast.AST, mod ast.Module, dir string) error {
	moduleLower := strings.ToLower(mod.Name)
	apiName := moduleLower + "Api"
	hooksName := moduleLower + "Hooks"

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';\n")
	sb.WriteString("import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';\n")
	sb.WriteString(fmt.Sprintf("import { %s } from '../client/%sApi';\n", apiName, moduleLower))

	// Collect types used
	usedTypes := emitter.CollectUsedTypes(a, mod)
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types';\n", strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	// Emit individual hook functions
	var hookNames []string
	for _, act := range mod.Actions {
		method := strings.ToUpper(act.Method)
		outputType := tshelpers.FormatOutputType(act)

		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)

		camelName := emitter.ToCamelCase(act.Name)
		hookName := "use" + act.Name

		if method == "GET" {
			// useQuery hook
			var paramTypes []string
			for _, p := range pathParams {
				paramTypes = append(paramTypes, p+": string")
			}
			if act.Query != "" {
				paramTypes = append(paramTypes, "query?: "+act.Query)
			}

			paramsStr := strings.Join(paramTypes, ", ")
			var argsList []string
			for _, p := range pathParams {
				argsList = append(argsList, p)
			}
			if act.Query != "" {
				argsList = append(argsList, "query")
			}
			argsStr := strings.Join(argsList, ", ")

			// Build query key
			keyParts := []string{fmt.Sprintf("'%s'", mod.Name), fmt.Sprintf("'%s'", camelName)}
			for _, p := range pathParams {
				keyParts = append(keyParts, p)
			}

			sb.WriteString(fmt.Sprintf("/**\n * %s\n */\n", act.Description))
			if len(paramTypes) > 0 {
				sb.WriteString(fmt.Sprintf("export function %s(%s, options?: Omit<UseQueryOptions<%s>, 'queryKey' | 'queryFn'>) {\n", hookName, paramsStr, outputType))
			} else {
				sb.WriteString(fmt.Sprintf("export function %s(options?: Omit<UseQueryOptions<%s>, 'queryKey' | 'queryFn'>) {\n", hookName, outputType))
			}
			sb.WriteString("  return useQuery({\n")
			sb.WriteString(fmt.Sprintf("    queryKey: [%s],\n", strings.Join(keyParts, ", ")))
			if argsStr != "" {
				sb.WriteString(fmt.Sprintf("    queryFn: () => %s.%s(%s),\n", apiName, camelName, argsStr))
			} else {
				sb.WriteString(fmt.Sprintf("    queryFn: () => %s.%s(),\n", apiName, camelName))
			}
			sb.WriteString("    ...options,\n")
			sb.WriteString("  });\n}\n\n")
			hookNames = append(hookNames, hookName)
		} else {
			// useMutation hook
			var inputType string
			var mutateParams []string

			if len(pathParams) > 0 || act.Input != "" {
				var fields []string
				for _, p := range pathParams {
					fields = append(fields, p+": string")
				}
				if act.Input != "" {
					fields = append(fields, "input: "+act.Input)
				}
				inputType = "{ " + strings.Join(fields, "; ") + " }"
				for _, p := range pathParams {
					mutateParams = append(mutateParams, "vars."+p)
				}
				if act.Input != "" {
					mutateParams = append(mutateParams, "vars.input")
				}
			} else {
				inputType = "void"
			}

			invalidateKey := fmt.Sprintf("['%s']", mod.Name)

			sb.WriteString(fmt.Sprintf("/**\n * %s\n */\n", act.Description))
			sb.WriteString(fmt.Sprintf("export function %s(options?: Omit<UseMutationOptions<%s, Error, %s>, 'mutationFn'>) {\n", hookName, outputType, inputType))
			sb.WriteString("  const queryClient = useQueryClient();\n")
			sb.WriteString("  return useMutation({\n")
			if inputType == "void" {
				sb.WriteString(fmt.Sprintf("    mutationFn: () => %s.%s(),\n", apiName, camelName))
			} else {
				sb.WriteString(fmt.Sprintf("    mutationFn: (vars: %s) => %s.%s(%s),\n", inputType, apiName, camelName, strings.Join(mutateParams, ", ")))
			}
			sb.WriteString("    onSuccess: () => {\n")
			sb.WriteString(fmt.Sprintf("      queryClient.invalidateQueries({ queryKey: %s });\n", invalidateKey))
			sb.WriteString("    },\n")
			sb.WriteString("    ...options,\n")
			sb.WriteString("  });\n}\n\n")
			hookNames = append(hookNames, hookName)
		}
	}

	// Export a module-level hooks object for convenient per-module imports.
	// import { usersHooks } from '@veld/hooks/usersHooks';
	sb.WriteString(fmt.Sprintf("export const %s = {\n", hooksName))
	for _, hn := range hookNames {
		sb.WriteString(fmt.Sprintf("  %s,\n", hn))
	}
	sb.WriteString("};\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+"Hooks.ts"), []byte(sb.String()), 0644)
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
