// Package react generates React hooks wrapping the TypeScript API client.
// Emits TanStack Query hooks (primary) plus zero-dependency core hooks as fallback.
package react

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	tsEmitter "github.com/Adhamzineldin/Veld/internal/emitter/frontend/typescript"
	"github.com/Adhamzineldin/Veld/internal/emitter/tshelpers"
)

func init() {
	emitter.RegisterFrontend("react", New())
}

// ReactEmitter generates TanStack Query hooks and zero-dependency core hooks.
type ReactEmitter struct{}

func New() *ReactEmitter          { return &ReactEmitter{} }
func (*ReactEmitter) IsFrontend() {}

func (e *ReactEmitter) Summary(modules []string) []emitter.SummaryLine {
	clientFiles := []string{"_internal.ts", "api.ts", "package.json"}
	for _, m := range modules {
		clientFiles = append(clientFiles, strings.ToLower(m)+"Api.ts")
	}
	lines := []emitter.SummaryLine{
		{Dir: "client/", Files: strings.Join(clientFiles, ", ")},
	}
	hookFiles := make([]string, len(modules))
	coreFiles := make([]string, len(modules))
	for i, m := range modules {
		hookFiles[i] = strings.ToLower(m) + "Hooks.ts"
		coreFiles[i] = strings.ToLower(m) + "Hooks.ts"
	}
	lines = append(lines, emitter.SummaryLine{Dir: "hooks/", Files: strings.Join(hookFiles, ", ")})
	lines = append(lines, emitter.SummaryLine{Dir: "hooks/", Files: "index.ts, package.json"})
	lines = append(lines, emitter.SummaryLine{Dir: "hooks/core/", Files: strings.Join(coreFiles, ", ")})
	return lines
}

func (e *ReactEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	tsE := tsEmitter.New()
	if err := tsE.Emit(a, outDir, opts); err != nil {
		return fmt.Errorf("typescript base: %w", err)
	}

	hooksDir := filepath.Join(outDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return err
	}

	// ── TanStack Query hooks (primary) ──────────────────────────────
	var barrelExports []string
	for _, mod := range a.Modules {
		if err := e.emitTanStackHooks(a, mod, hooksDir); err != nil {
			return fmt.Errorf("tanstack hooks for %s: %w", mod.Name, err)
		}
		moduleLower := strings.ToLower(mod.Name)
		barrelExports = append(barrelExports, fmt.Sprintf("export { %sHooks } from './%sHooks';", moduleLower, moduleLower))
	}

	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	for _, exp := range barrelExports {
		barrel.WriteString(exp + "\n")
	}
	barrel.WriteString("\n// Zero-dependency core hooks (no TanStack Query required):\n")
	barrel.WriteString("// import { usersHooks } from '@veld/hooks/core/usersHooks';\n")
	if err := os.WriteFile(filepath.Join(hooksDir, "index.ts"), []byte(barrel.String()), 0644); err != nil {
		return err
	}

	if err := emitHooksPackageJSON(a, hooksDir); err != nil {
		return err
	}

	// ── Zero-dependency core hooks (fallback) ───────────────────────
	coreDir := filepath.Join(hooksDir, "core")
	if err := os.MkdirAll(coreDir, 0755); err != nil {
		return err
	}

	var coreExports []string
	for _, mod := range a.Modules {
		if err := e.emitCoreHooks(a, mod, coreDir); err != nil {
			return fmt.Errorf("core hooks for %s: %w", mod.Name, err)
		}
		moduleLower := strings.ToLower(mod.Name)
		coreExports = append(coreExports, fmt.Sprintf("export { %sHooks } from './%sHooks';", moduleLower, moduleLower))
	}

	var coreBarrel strings.Builder
	coreBarrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	coreBarrel.WriteString("// Zero-dependency hooks — no TanStack Query required.\n")
	for _, exp := range coreExports {
		coreBarrel.WriteString(exp + "\n")
	}
	return os.WriteFile(filepath.Join(coreDir, "index.ts"), []byte(coreBarrel.String()), 0644)
}

func emitHooksPackageJSON(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString("  \"name\": \"@veld/hooks\",\n")
	sb.WriteString("  \"version\": \"0.0.0\",\n")
	sb.WriteString("  \"private\": true,\n")
	sb.WriteString("  \"types\": \"./index.ts\",\n")
	sb.WriteString("  \"exports\": {\n")
	sb.WriteString("    \".\": \"./index.ts\"")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf(",\n    \"./%sHooks\": \"./%sHooks.ts\"", moduleLower, moduleLower))
	}
	sb.WriteString(",\n    \"./core\": \"./core/index.ts\"")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf(",\n    \"./core/%sHooks\": \"./core/%sHooks.ts\"", moduleLower, moduleLower))
	}
	sb.WriteString("\n  },\n")
	sb.WriteString("  \"peerDependencies\": {\n")
	sb.WriteString("    \"@tanstack/react-query\": \">=5.0.0\"\n")
	sb.WriteString("  },\n")
	sb.WriteString("  \"peerDependenciesMeta\": {\n")
	sb.WriteString("    \"@tanstack/react-query\": { \"optional\": true }\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, "package.json"), []byte(sb.String()), 0644)
}

// ═══════════════════════════════════════════════════════════════════════════
// TanStack Query hooks (primary)
// ═══════════════════════════════════════════════════════════════════════════

func (e *ReactEmitter) emitTanStackHooks(a ast.AST, mod ast.Module, dir string) error {
	moduleLower := strings.ToLower(mod.Name)
	apiName := moduleLower + "Api"
	hooksName := moduleLower + "Hooks"

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';\n")
	sb.WriteString("import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';\n")
	sb.WriteString(fmt.Sprintf("import { %s } from '../client/%sApi';\n", apiName, moduleLower))
	sb.WriteString("import { VeldApiError } from '../client/_internal';\n")

	usedTypes := emitter.CollectUsedTypes(a, mod)
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../types';\n", strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	var hookNames []string
	for _, act := range mod.Actions {
		method := strings.ToUpper(act.Method)
		outputType := tshelpers.FormatOutputType(act)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)
		camelName := emitter.ToCamelCase(act.Name)
		hookName := "use" + act.Name

		if method == "GET" {
			writeTanStackQuery(&sb, hookName, apiName, camelName, outputType, mod.Name, pathParams, act)
		} else {
			writeTanStackMutation(&sb, hookName, apiName, camelName, outputType, mod.Name, pathParams, act)
		}
		hookNames = append(hookNames, hookName)
	}

	sb.WriteString(fmt.Sprintf("export const %s = {\n", hooksName))
	for _, hn := range hookNames {
		sb.WriteString(fmt.Sprintf("  %s,\n", hn))
	}
	sb.WriteString("};\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+"Hooks.ts"), []byte(sb.String()), 0644)
}

func writeTanStackQuery(sb *strings.Builder, hookName, apiName, camelName, outputType, modName string, pathParams []string, act ast.Action) {
	var paramTypes, argsList []string
	for _, p := range pathParams {
		paramTypes = append(paramTypes, p+": string")
		argsList = append(argsList, p)
	}
	if act.Query != "" {
		paramTypes = append(paramTypes, "query?: "+act.Query)
		argsList = append(argsList, "query")
	}
	paramsStr := strings.Join(paramTypes, ", ")
	argsStr := strings.Join(argsList, ", ")

	keyParts := []string{fmt.Sprintf("'%s'", modName), fmt.Sprintf("'%s'", camelName)}
	for _, p := range pathParams {
		keyParts = append(keyParts, p)
	}

	sb.WriteString(fmt.Sprintf("/** %s */\n", act.Description))
	if len(paramTypes) > 0 {
		sb.WriteString(fmt.Sprintf("export function %s(%s, options?: Omit<UseQueryOptions<%s, VeldApiError>, 'queryKey' | 'queryFn'>) {\n", hookName, paramsStr, outputType))
	} else {
		sb.WriteString(fmt.Sprintf("export function %s(options?: Omit<UseQueryOptions<%s, VeldApiError>, 'queryKey' | 'queryFn'>) {\n", hookName, outputType))
	}
	sb.WriteString("  return useQuery({\n")
	sb.WriteString(fmt.Sprintf("    queryKey: [%s],\n", strings.Join(keyParts, ", ")))
	if argsStr != "" {
		sb.WriteString(fmt.Sprintf("    queryFn: () => %s.%s(%s),\n", apiName, camelName, argsStr))
	} else {
		sb.WriteString(fmt.Sprintf("    queryFn: () => %s.%s(),\n", apiName, camelName))
	}
	sb.WriteString("    ...options,\n")
	sb.WriteString("  });\n}\n\n")
}

func writeTanStackMutation(sb *strings.Builder, hookName, apiName, camelName, outputType, modName string, pathParams []string, act ast.Action) {
	var inputFields, mutateParams []string
	for _, p := range pathParams {
		inputFields = append(inputFields, p+": string")
		mutateParams = append(mutateParams, "vars."+p)
	}
	if act.Input != "" {
		inputFields = append(inputFields, "input: "+act.Input)
		mutateParams = append(mutateParams, "vars.input")
	}
	inputType := "void"
	if len(inputFields) > 0 {
		inputType = "{ " + strings.Join(inputFields, "; ") + " }"
	}

	sb.WriteString(fmt.Sprintf("/** %s */\n", act.Description))
	sb.WriteString(fmt.Sprintf("export function %s(options?: Omit<UseMutationOptions<%s, VeldApiError, %s>, 'mutationFn'>) {\n", hookName, outputType, inputType))
	sb.WriteString("  const queryClient = useQueryClient();\n")
	sb.WriteString("  return useMutation({\n")
	if inputType == "void" {
		sb.WriteString(fmt.Sprintf("    mutationFn: () => %s.%s(),\n", apiName, camelName))
	} else {
		sb.WriteString(fmt.Sprintf("    mutationFn: (vars: %s) => %s.%s(%s),\n", inputType, apiName, camelName, strings.Join(mutateParams, ", ")))
	}
	sb.WriteString("    onSuccess: () => {\n")
	sb.WriteString(fmt.Sprintf("      queryClient.invalidateQueries({ queryKey: ['%s'] });\n", modName))
	sb.WriteString("    },\n")
	sb.WriteString("    ...options,\n")
	sb.WriteString("  });\n}\n\n")
}

// ═══════════════════════════════════════════════════════════════════════════
// Zero-dependency core hooks (fallback — no TanStack Query)
// ═══════════════════════════════════════════════════════════════════════════

func (e *ReactEmitter) emitCoreHooks(a ast.AST, mod ast.Module, dir string) error {
	moduleLower := strings.ToLower(mod.Name)
	apiName := moduleLower + "Api"
	hooksName := moduleLower + "Hooks"

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("// Zero-dependency hooks — no TanStack Query required.\n")
	sb.WriteString("import { useState, useEffect, useCallback } from 'react';\n")
	sb.WriteString(fmt.Sprintf("import { %s } from '../../client/%sApi';\n", apiName, moduleLower))

	usedTypes := emitter.CollectUsedTypes(a, mod)
	if len(usedTypes) > 0 {
		sb.WriteString(fmt.Sprintf("import type { %s } from '../../types';\n", strings.Join(usedTypes, ", ")))
	}
	sb.WriteString("\n")

	var hookNames []string
	for _, act := range mod.Actions {
		method := strings.ToUpper(act.Method)
		outputType := tshelpers.FormatOutputType(act)
		routePath := act.Path
		if mod.Prefix != "" {
			routePath = mod.Prefix + act.Path
		}
		pathParams := emitter.ExtractPathParams(routePath)
		camelName := emitter.ToCamelCase(act.Name)
		hookName := "use" + act.Name

		if method == "GET" {
			writeCoreQueryHook(&sb, hookName, apiName, camelName, outputType, pathParams, act)
		} else {
			writeCoreMutationHook(&sb, hookName, apiName, camelName, outputType, pathParams, act)
		}
		hookNames = append(hookNames, hookName)
	}

	sb.WriteString(fmt.Sprintf("export const %s = {\n", hooksName))
	for _, hn := range hookNames {
		sb.WriteString(fmt.Sprintf("  %s,\n", hn))
	}
	sb.WriteString("};\n")

	return os.WriteFile(filepath.Join(dir, moduleLower+"Hooks.ts"), []byte(sb.String()), 0644)
}

func writeCoreQueryHook(sb *strings.Builder, hookName, apiName, camelName, outputType string, pathParams []string, act ast.Action) {
	var paramTypes, argsList, deps []string
	for _, p := range pathParams {
		paramTypes = append(paramTypes, p+": string")
		argsList = append(argsList, p)
		deps = append(deps, p)
	}
	if act.Query != "" {
		paramTypes = append(paramTypes, "query?: "+act.Query)
		argsList = append(argsList, "query")
	}
	paramsStr := strings.Join(paramTypes, ", ")
	argsStr := strings.Join(argsList, ", ")

	sb.WriteString(fmt.Sprintf("/** %s */\n", act.Description))
	sb.WriteString(fmt.Sprintf("export function %s(%s) {\n", hookName, paramsStr))
	sb.WriteString(fmt.Sprintf("  const [data, setData] = useState<%s | null>(null);\n", outputType))
	sb.WriteString("  const [loading, setLoading] = useState(true);\n")
	sb.WriteString("  const [error, setError] = useState<Error | null>(null);\n\n")
	sb.WriteString("  const fetch = useCallback(() => {\n")
	sb.WriteString("    setLoading(true);\n")
	sb.WriteString("    setError(null);\n")
	if argsStr != "" {
		sb.WriteString(fmt.Sprintf("    %s.%s(%s)\n", apiName, camelName, argsStr))
	} else {
		sb.WriteString(fmt.Sprintf("    %s.%s()\n", apiName, camelName))
	}
	sb.WriteString("      .then(setData)\n")
	sb.WriteString("      .catch(setError)\n")
	sb.WriteString("      .finally(() => setLoading(false));\n")
	if len(deps) > 0 {
		sb.WriteString(fmt.Sprintf("  }, [%s]);\n\n", strings.Join(deps, ", ")))
	} else {
		sb.WriteString("  }, []);\n\n")
	}
	sb.WriteString("  useEffect(() => { fetch(); }, [fetch]);\n\n")
	sb.WriteString("  return { data, loading, error, refetch: fetch };\n")
	sb.WriteString("}\n\n")
}

func writeCoreMutationHook(sb *strings.Builder, hookName, apiName, camelName, outputType string, pathParams []string, act ast.Action) {
	var inputFields, callArgs []string
	for _, p := range pathParams {
		inputFields = append(inputFields, p+": string")
		callArgs = append(callArgs, "vars."+p)
	}
	if act.Input != "" {
		inputFields = append(inputFields, "input: "+act.Input)
		callArgs = append(callArgs, "vars.input")
	}
	inputType := "void"
	if len(inputFields) > 0 {
		inputType = "{ " + strings.Join(inputFields, "; ") + " }"
	}

	sb.WriteString(fmt.Sprintf("/** %s */\n", act.Description))
	sb.WriteString(fmt.Sprintf("export function %s() {\n", hookName))
	sb.WriteString(fmt.Sprintf("  const [data, setData] = useState<%s | null>(null);\n", outputType))
	sb.WriteString("  const [loading, setLoading] = useState(false);\n")
	sb.WriteString("  const [error, setError] = useState<Error | null>(null);\n\n")
	if inputType == "void" {
		sb.WriteString("  const mutate = useCallback(() => {\n")
	} else {
		sb.WriteString(fmt.Sprintf("  const mutate = useCallback((vars: %s) => {\n", inputType))
	}
	sb.WriteString("    setLoading(true);\n")
	sb.WriteString("    setError(null);\n")
	if inputType == "void" {
		sb.WriteString(fmt.Sprintf("    return %s.%s()\n", apiName, camelName))
	} else {
		sb.WriteString(fmt.Sprintf("    return %s.%s(%s)\n", apiName, camelName, strings.Join(callArgs, ", ")))
	}
	sb.WriteString("      .then((result) => { setData(result); return result; })\n")
	sb.WriteString("      .catch((err) => { setError(err); throw err; })\n")
	sb.WriteString("      .finally(() => setLoading(false));\n")
	sb.WriteString("  }, []);\n\n")
	sb.WriteString("  return { mutate, data, loading, error };\n")
	sb.WriteString("}\n\n")
}
