// AUTO-GENERATED BY VELD — DO NOT EDIT

use axum::{
    extract::{Json, Path, State},
    http::StatusCode,
    response::IntoResponse,
    routing::{delete, get, patch, post, put},
    Router,
};
use std::sync::Arc;

use crate::models::*;
use crate::services::AuthService;

/// Build the Axum sub-router for the Auth module.
pub fn router<S>() -> Router<S>
where
    S: AuthService + Clone + Send + Sync + 'static,
{
    Router::new()
        .route("/auth/login", post(login))
        .route("/auth/register", post(register))
        .route("/auth/current_user", get(me))
        .route("/auth/logout", post(logout))
}

/// Handle POST /auth/login.
pub async fn login(State(svc): State<Arc<dyn AuthService>>, Json(payload): Json<LoginInput>) -> Result<(StatusCode, Json<User>), (StatusCode, Json<serde_json::Value>)> {
    let err_response = |e: String| {
        (StatusCode::INTERNAL_SERVER_ERROR, Json(serde_json::json!({"error": e})))
    };

    let result = svc.login(payload).await.map_err(|e| err_response(e.to_string()))?;
    Ok((StatusCode::CREATED, Json(result)))
}

/// Handle POST /auth/register.
pub async fn register(State(svc): State<Arc<dyn AuthService>>, Json(payload): Json<RegisterInput>) -> Result<(StatusCode, Json<User>), (StatusCode, Json<serde_json::Value>)> {
    let err_response = |e: String| {
        (StatusCode::INTERNAL_SERVER_ERROR, Json(serde_json::json!({"error": e})))
    };

    let result = svc.register(payload).await.map_err(|e| err_response(e.to_string()))?;
    Ok((StatusCode::CREATED, Json(result)))
}

/// Handle GET /auth/current_user.
pub async fn me(State(svc): State<Arc<dyn AuthService>>) -> Result<(StatusCode, Json<User>), (StatusCode, Json<serde_json::Value>)> {
    let err_response = |e: String| {
        (StatusCode::INTERNAL_SERVER_ERROR, Json(serde_json::json!({"error": e})))
    };

    let result = svc.me().await.map_err(|e| err_response(e.to_string()))?;
    Ok((StatusCode::OK, Json(result)))
}

/// Handle POST /auth/logout.
pub async fn logout(State(svc): State<Arc<dyn AuthService>>) -> Result<(StatusCode, Json<SuccessResponse>), (StatusCode, Json<serde_json::Value>)> {
    let err_response = |e: String| {
        (StatusCode::INTERNAL_SERVER_ERROR, Json(serde_json::json!({"error": e})))
    };

    let result = svc.logout().await.map_err(|e| err_response(e.to_string()))?;
    Ok((StatusCode::CREATED, Json(result)))
}

