package javascript

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func emitJsConstants(a ast.AST, outDir string) error {
	if len(a.Constants) == 0 {
		return nil
	}
	dir := filepath.Join(outDir, "constants")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	var barrelExports []string

	for _, cg := range a.Constants {
		fileName := emitter.ToSnakeCase(cg.Name)
		barrelExports = append(barrelExports, fileName)

		var sb strings.Builder
		sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
		if cg.Description != "" {
			sb.WriteString(fmt.Sprintf("/** %s */\n", cg.Description))
		}
		for _, f := range cg.Fields {
			jsVal := jsConstVal(f)
			sb.WriteString(fmt.Sprintf("module.exports.%s = %s;\n", f.Name, jsVal))
		}
		if err := os.WriteFile(filepath.Join(dir, fileName+".js"), []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	var barrel strings.Builder
	barrel.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n\n")
	for _, name := range barrelExports {
		barrel.WriteString(fmt.Sprintf("Object.assign(module.exports, require('./%s'));\n", name))
	}
	return os.WriteFile(filepath.Join(dir, "index.js"), []byte(barrel.String()), 0644)
}

func jsConstVal(f ast.ConstantField) string {
	switch f.Type {
	case "string", "uuid", "date", "datetime", "decimal":
		return fmt.Sprintf("%q", f.Value)
	case "int", "float":
		return f.Value
	case "bool":
		return f.Value
	default:
		return fmt.Sprintf("%q", f.Value)
	}
}
