package javascript

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
)

func init() {
	emitter.RegisterFrontend("javascript", New())
}

// JSFrontendEmitter generates the frontend fetch SDK in plain JavaScript (generated/client/).
type JSFrontendEmitter struct{}

func (*JSFrontendEmitter) IsFrontend() {}
func New() *JSFrontendEmitter          { return &JSFrontendEmitter{} }

// Summary returns a human-friendly breakdown of generated files.
func (e *JSFrontendEmitter) Summary(modules []string) []emitter.SummaryLine {
	files := []string{"_internal.js", "api.js", "types.js", "errors.js", "package.json"}
	for _, m := range modules {
		files = append(files, strings.ToLower(m)+"Api.js")
	}
	return []emitter.SummaryLine{
		{Dir: "client/", Files: strings.Join(files, ", ")},
	}
}

// Emit writes generated/client/ into outDir.
func (e *JSFrontendEmitter) Emit(a ast.AST, outDir string, opts emitter.EmitOptions) error {
	if opts.DryRun {
		return nil
	}

	dir := filepath.Join(outDir, "client")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Collect which HTTP methods are used across all actions.
	methods := make(map[string]bool)
	for _, mod := range a.Modules {
		for _, act := range mod.Actions {
			methods[strings.ToUpper(act.Method)] = true
		}
	}

	// 1. _internal.js — shared error class, BASE URL, HTTP helpers.
	var internal strings.Builder
	internal.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	emitErrorClass(&internal)
	emitBaseURL(&internal, opts)
	emitHTTPHelpers(&internal, methods)
	if err := os.WriteFile(filepath.Join(dir, "_internal.js"), []byte(internal.String()), 0644); err != nil {
		return err
	}

	// 2. Per-module API files.
	for _, mod := range a.Modules {
		if err := emitModuleApi(a, mod, dir); err != nil {
			return fmt.Errorf("module api %s: %w", mod.Name, err)
		}
	}

	// 3. api.js barrel.
	if err := emitApiBarrel(a, dir); err != nil {
		return fmt.Errorf("api barrel: %w", err)
	}

	// 4. client/types.js barrel.
	if err := emitClientTypesBarrel(a, dir); err != nil {
		return fmt.Errorf("client types barrel: %w", err)
	}

	// 5. client/errors.js barrel.
	if err := emitClientErrorsBarrel(a, dir); err != nil {
		return fmt.Errorf("client errors barrel: %w", err)
	}

	// 6. client/package.json.
	return emitClientPackageJSON(a, dir)
}

// emitModuleApi writes client/{moduleLower}Api.js.
func emitModuleApi(a ast.AST, mod ast.Module, dir string) error {
	moduleLower := strings.ToLower(mod.Name)
	apiName := moduleLower + "Api"

	// Check if any action in this module uses query params.
	hasQuery := false
	for _, act := range mod.Actions {
		if act.Query != "" {
			hasQuery = true
			break
		}
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	if hasQuery {
		sb.WriteString("const { get, post, put, patch, del, buildQueryString } = require('./_internal');\n\n")
	} else {
		sb.WriteString("const { get, post, put, patch, del } = require('./_internal');\n\n")
	}

	sb.WriteString(fmt.Sprintf("const %s = {\n", apiName))
	for _, act := range mod.Actions {
		writeAction(&sb, mod, act)
	}

	// Emit typed error code constants if any actions define errors.
	if emitter.HasErrors(mod) {
		sb.WriteString("  errors: {\n")
		for _, act := range mod.Actions {
			if len(act.Errors) == 0 {
				continue
			}
			camelAction := emitter.ToCamelCase(act.Name)
			sb.WriteString(fmt.Sprintf("    %s: {\n", camelAction))
			for _, errName := range act.Errors {
				code := emitter.ErrorCode(act.Name, errName)
				camelErr := emitter.ToCamelCase(errName)
				sb.WriteString(fmt.Sprintf("      %s: '%s',\n", camelErr, code))
			}
			sb.WriteString("    },\n")
		}
		sb.WriteString("  },\n")
	}

	sb.WriteString("};\n\n")
	sb.WriteString(fmt.Sprintf("module.exports = { %s };\n", apiName))

	return os.WriteFile(filepath.Join(dir, moduleLower+"Api.js"), []byte(sb.String()), 0644)
}

// emitApiBarrel writes client/api.js.
func emitApiBarrel(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("const { VeldApiError, isApiError, isErrorCode } = require('./_internal');\n")

	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		apiName := moduleLower + "Api"
		sb.WriteString(fmt.Sprintf("const { %s } = require('./%sApi');\n", apiName, moduleLower))
	}

	sb.WriteString("\nconst api = {\n")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf("  %s: %sApi,\n", mod.Name, moduleLower))
	}
	sb.WriteString("};\n\n")

	sb.WriteString("module.exports = { VeldApiError, isApiError, isErrorCode, api")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf(", %sApi", moduleLower))
	}
	sb.WriteString(" };\n")

	return os.WriteFile(filepath.Join(dir, "api.js"), []byte(sb.String()), 0644)
}

// emitClientPackageJSON writes client/package.json.
func emitClientPackageJSON(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString("  \"name\": \"@veld/client\",\n")
	sb.WriteString("  \"version\": \"0.0.0\",\n")
	sb.WriteString("  \"private\": true,\n")
	sb.WriteString("  \"main\": \"./api.js\",\n")
	sb.WriteString("  \"exports\": {\n")
	sb.WriteString("    \".\": \"./api.js\",\n")
	sb.WriteString("    \"./types\": \"./types.js\",\n")
	sb.WriteString("    \"./errors\": \"./errors.js\"")
	for _, mod := range a.Modules {
		moduleLower := strings.ToLower(mod.Name)
		sb.WriteString(fmt.Sprintf(",\n    \"./%sApi\": \"./%sApi.js\"", moduleLower, moduleLower))
	}
	sb.WriteString("\n  }\n}\n")
	return os.WriteFile(filepath.Join(dir, "package.json"), []byte(sb.String()), 0644)
}

// emitClientTypesBarrel writes client/types.js.
func emitClientTypesBarrel(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("// Re-exports all types for frontend convenience.\n")
	sb.WriteString("// Types are defined as JSDoc @typedef in the types/ directory.\n")
	return os.WriteFile(filepath.Join(dir, "types.js"), []byte(sb.String()), 0644)
}

// emitClientErrorsBarrel writes client/errors.js.
func emitClientErrorsBarrel(a ast.AST, dir string) error {
	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED BY VELD — DO NOT EDIT\n")
	sb.WriteString("// Re-exports client-side error utilities.\n")
	sb.WriteString("const { VeldApiError, isApiError, isErrorCode } = require('./_internal');\n\n")

	// Also re-export backend error types if they exist.
	hasErrors := false
	for _, mod := range a.Modules {
		if emitter.HasErrors(mod) {
			hasErrors = true
			break
		}
	}

	if hasErrors {
		sb.WriteString("// Backend error types and factories:\n")
		for _, mod := range a.Modules {
			if !emitter.HasErrors(mod) {
				continue
			}
			moduleLower := strings.ToLower(mod.Name)
			sb.WriteString(fmt.Sprintf("const %sErrors = require('../errors/%s.errors');\n", moduleLower, moduleLower))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("module.exports = { VeldApiError, isApiError, isErrorCode")
	if hasErrors {
		for _, mod := range a.Modules {
			if !emitter.HasErrors(mod) {
				continue
			}
			moduleLower := strings.ToLower(mod.Name)
			sb.WriteString(fmt.Sprintf(", %sErrors", moduleLower))
		}
	}
	sb.WriteString(" };\n")

	return os.WriteFile(filepath.Join(dir, "errors.js"), []byte(sb.String()), 0644)
}
