package javascript_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Adhamzineldin/Veld/internal/ast"
	"github.com/Adhamzineldin/Veld/internal/emitter"
	"github.com/Adhamzineldin/Veld/internal/emitter/frontend/javascript"
	_ "github.com/Adhamzineldin/Veld/internal/emitter/frontend/javascript"
)

func minimalAST() ast.AST {
	return ast.AST{
		Models: []ast.Model{
			{
				Name: "LoginInput",
				Fields: []ast.Field{
					{Name: "email", Type: "string"},
					{Name: "password", Type: "string"},
				},
			},
			{
				Name: "User",
				Fields: []ast.Field{
					{Name: "id", Type: "uuid"},
					{Name: "email", Type: "string"},
				},
			},
		},
		Modules: []ast.Module{
			{
				Name:   "Auth",
				Prefix: "/api",
				Actions: []ast.Action{
					{
						Name:   "Login",
						Method: "POST",
						Path:   "/auth/login",
						Input:  "LoginInput",
						Output: "User",
					},
					{
						Name:   "Me",
						Method: "GET",
						Path:   "/auth/me",
						Output: "User",
					},
				},
			},
		},
	}
}

func TestJSFrontendEmitterEmit(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(outDir, "client", "_internal.js"),
		filepath.Join(outDir, "client", "api.js"),
		filepath.Join(outDir, "client", "types.js"),
		filepath.Join(outDir, "client", "errors.js"),
		filepath.Join(outDir, "client", "package.json"),
		filepath.Join(outDir, "client", "authApi.js"),
	}
	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}
}

func TestJSFrontendEmitterDryRun(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()

	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{DryRun: true}); err != nil {
		t.Fatalf("Emit(dry-run) error: %v", err)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run should write no files, but %d entries found", len(entries))
	}
}

func TestJSFrontendInternalContent(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "client", "_internal.js"))
	if err != nil {
		t.Fatalf("ReadFile _internal.js: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"error class", "class VeldApiError"},
		{"isApiError", "function isApiError"},
		{"isErrorCode", "function isErrorCode"},
		{"get helper", "async function get("},
		{"post helper", "async function post("},
		{"module.exports", "module.exports"},
		{"fetch call", "fetch(BASE + path"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("_internal.js missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}

	// Must NOT contain TypeScript syntax.
	tsChecks := []string{": Promise<", "export async"}
	for _, ts := range tsChecks {
		if strings.Contains(content, ts) {
			t.Errorf("_internal.js should not contain TypeScript syntax %q", ts)
		}
	}
}

func TestJSFrontendModuleApiContent(t *testing.T) {
	e := javascript.New()
	outDir := t.TempDir()
	if err := e.Emit(minimalAST(), outDir, emitter.EmitOptions{}); err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "client", "authApi.js"))
	if err != nil {
		t.Fatalf("ReadFile authApi.js: %v", err)
	}
	content := string(data)

	checks := []struct {
		desc   string
		needle string
	}{
		{"header", "AUTO-GENERATED BY VELD"},
		{"require _internal", "require('./_internal')"},
		{"api object", "const authApi = {"},
		{"login method", "login("},
		{"me method", "me("},
		{"module.exports", "module.exports"},
	}
	for _, c := range checks {
		if !strings.Contains(content, c.needle) {
			t.Errorf("authApi.js missing %s: want %q\ngot:\n%s", c.desc, c.needle, content)
		}
	}
}

func TestJSFrontendSummary(t *testing.T) {
	e := javascript.New()
	lines := e.Summary([]string{"Auth", "Users"})

	if len(lines) == 0 {
		t.Fatal("Summary() returned no lines")
	}
	if lines[0].Dir != "client/" {
		t.Errorf("Summary() first dir = %q, want client/", lines[0].Dir)
	}
}

func TestJSFrontendRegistered(t *testing.T) {
	if _, err := emitter.GetFrontend("javascript"); err != nil {
		t.Errorf("javascript frontend not registered: %v", err)
	}
}
